'use strict';
// 언락! 시나리오 — 입문 · 이스케이프 · 미스터리 · 시크릿 어드벤처 (원작 제목을 따온 오리지널 수수께끼)

module.exports = [
  // ───────────── 입문 ─────────────
  {
    id: 'tutorial', box: '입문', title: '첫 번째 방', orig: 'Tutorial', diff: 0, theme: '#6a8aa8',
    intro: '눈을 떠 보니 낯선 서재. 문은 잠겨 있다. 언락의 기본을 배워 봐요!',
    cards: [
      { key: 'room', type: 'place', start: true, title: '작은 서재', art: '📚🪑🕰️🚪', text: '책장과 낡은 의자, 멈춘 괘종시계. 장소 카드의 그림 속 물건을 눌러 살펴보세요. 이미 보이는 번호 카드는 바로 나와요.',
        shows: ['chest', 'clock'], spots: [{ label: '화분', emoji: '🪴', x: 20, y: 60, reveal: 'key' }, { label: '책장', emoji: '📚', x: 70, y: 35, text: '먼지 쌓인 요리책뿐이다.' }],
        hint: ['그림 속 물건(🪴 등)을 눌러 보세요. 숨은 번호가 있을 수 있어요.', '화분 속에 열쇠가 있어요.'] },
      { key: 'chest', type: 'red', title: '잠긴 나무 상자', art: '🧰', text: '작은 자물쇠가 달려 있다. 빨간 카드는 파란 카드와 합칠 수 있어요.', hint: ['빨간 카드와 파란 카드를 하나씩 골라 “합치기”를 눌러 보세요.', '상자 + 열쇠'] },
      { key: 'key', type: 'blue', title: '작은 열쇠', art: '🗝️', text: '녹슨 작은 열쇠.' },
      { key: 'note', type: 'item', from: ['chest', 'key'], title: '상자 속 쪽지', art: '📜', discard: ['chest', 'key'], shows: ['safe'], text: '“금고 비밀번호는 시계가 멈춘 시각.” 상자 바닥에 작은 금고 그림과 번호가 있다.' },
      { key: 'clock', type: 'item', title: '괘종시계', art: '🕰️', text: '시계는 9시 15분에 멈춰 있다.' },
      { key: 'safe', type: 'code', title: '벽 금고', art: '🔐', text: '숫자 4자리를 넣는 금고. (노란 카드는 코드를 입력해요)', code: '0915', result: 'panel', hint: ['쪽지와 시계를 함께 보세요.', '9시 15분 → 0915'] },
      { key: 'panel', type: 'machine', title: '문 패널', art: '🚪', text: '금고 안 메모: “무지개 순서로 색을 누르면 문이 열린다.” (초록 카드는 장치예요. 버튼을 차례로 눌러요)', buttons: ['🔵', '🟢', '🔴', '🟡'], solution: ['🔴', '🟡', '🟢', '🔵'], result: 'out', hint: ['무지개는 빨주노초파남보.', '🔴 🟡 🟢 🔵'] },
      { key: 'out', type: 'item', end: true, title: '문이 열렸다!', art: '🌅', text: '첫 번째 방 탈출 성공! 이제 진짜 모험을 떠나 볼까요?' },
    ],
  },

  // ───────────── 이스케이프 어드벤처 ─────────────
  {
    id: 'formula', box: '이스케이프 어드벤처', title: '포뮬러', orig: 'The Formula', diff: 1, theme: '#3a9a8a',
    intro: '천재 화학자 H 박사의 연구소에 갇혔다. 공기 중에 퍼진 신경가스! 해독제 공식을 완성하고 빠져나가야 한다.',
    cards: [
      { key: 'lab', type: 'place', start: true, title: '지하 실험실', art: '🧪🔬🧯🚪', text: '문은 전자 자물쇠로 잠겨 있다. 벽의 주기율표 일부: Fe 26 · Ni 28 · Cu 29 · Zn 30.',
        shows: ['cabinet'], spots: [{ label: '주기율표 뒤', emoji: '📋', x: 25, y: 30, reveal: 'keycard' }, { label: '서랍', emoji: '🗄️', x: 70, y: 70, reveal: 'injector' }, { label: '쓰레기통', emoji: '🗑️', x: 85, y: 75, text: '구겨진 영수증뿐이다.' }],
        hint: ['주기율표와 서랍을 살펴보세요.'] },
      { key: 'cabinet', type: 'red', title: '잠긴 약품장', art: '🗄️', text: '카드키 리더가 달린 유리 약품장.' },
      { key: 'keycard', type: 'blue', title: '연구원 카드키', art: '💳', text: '“Dr. H — 수석 연구원”' },
      { key: 'open', type: 'item', from: ['cabinet', 'keycard'], discard: ['cabinet', 'keycard'], shows: ['synth'], title: '열린 약품장', art: '🧴🧴🧴',
        text: '병 세 개: 붉은 병(Fe), 푸른 병(Cu), 초록 병(Ni). 박사의 메모: “공식 = 세 원소의 원자번호를 붉은 → 푸른 → 초록 순서로.”' },
      { key: 'synth', type: 'code', title: '합성 장치', art: '⚗️', text: '숫자 6자리를 넣으면 해독제를 합성한다.', code: '262928', result: 'antidote', hint: ['원자번호는 실험실 벽의 주기율표에 있어요.', 'Fe 26, Cu 29, Ni 28 → 262928'] },
      { key: 'antidote', type: 'red', title: '해독제 앰플', art: '💉', text: '푸르스름하게 빛나는 액체.' },
      { key: 'injector', type: 'blue', title: '빈 주사기', art: '🩹', text: '새것이다.' },
      { key: 'ready', type: 'item', from: ['antidote', 'injector'], discard: ['antidote', 'injector'], shows: ['door'], title: '해독제 주사', art: '😮‍💨',
        text: '정신이 맑아진다! 그제서야 문 패널의 글씨가 보인다: “원자번호 1, 2, 3 순서로.”' },
      { key: 'door', type: 'machine', title: '문 패널', art: '🚪', text: '원소 기호 버튼 네 개.', buttons: ['Li', 'He', 'Be', 'H'], solution: ['H', 'He', 'Li'], result: 'out', hint: ['수소 1, 헬륨 2, 리튬 3.', 'H → He → Li'] },
      { key: 'out', type: 'item', end: true, title: '탈출!', art: '🏃', text: '문이 열리고 맑은 공기가 쏟아진다. H 박사의 공식은 이제 당신 손에!' },
    ],
  },
  {
    id: 'squeek', box: '이스케이프 어드벤처', title: '찍찍이와 소시지', orig: 'Squeek & Sausage', diff: 2, theme: '#d88a3a',
    intro: '괴짜 발명가 노사이드 교수가 생쥐 로봇 찍찍이와 개 로봇 소시지로 도시를 어지럽히려 한다. 교수의 집에 숨어들어 계획을 막아라!',
    cards: [
      { key: 'hall', type: 'place', start: true, title: '교수의 현관', art: '🏠🎩🐀🐕', text: '신발장, 커다란 우산꽂이, 2층으로 가는 계단. 계단 문은 잠겨 있다.',
        shows: ['stairs'], spots: [{ label: '우산꽂이', emoji: '☂️', x: 20, y: 55, reveal: 'magnet' }, { label: '신발장', emoji: '👞', x: 65, y: 70, reveal: 'cheese' }],
        hint: ['우산꽂이와 신발장을 살펴보세요.'] },
      { key: 'stairs', type: 'red', title: '계단 문', art: '🚪', text: '문 아래 작은 구멍. 쥐 한 마리 지나갈 크기다. 구멍 안쪽에 걸쇠가 보인다.' },
      { key: 'magnet', type: 'blue', title: '말굽 자석', art: '🧲', text: '강력한 자석. 끈이 묶여 있다.' },
      { key: 'up', type: 'place', from: ['stairs', 'magnet'], discard: ['stairs', 'magnet', 'hall'], shows: ['squeek', 'board'], title: '2층 작업실', art: '🛠️🐀📋',
        text: '자석으로 걸쇠를 당겨 문을 열었다! 작업대 위에서 생쥐 로봇 찍찍이가 눈을 번쩍인다.',
        spots: [{ label: '작업대 서랍', emoji: '🗃️', x: 70, y: 65, reveal: 'remote' }] },
      { key: 'cheese', type: 'blue', title: '플라스틱 치즈', art: '🧀', text: '안에 작은 회로가 들었다. “찍찍이 유인용”' },
      { key: 'squeek', type: 'red', title: '생쥐 로봇 찍찍이', art: '🐀', text: '쉴 새 없이 돌아다닌다. 등에 전원 스위치가 있지만 잡을 수가 없다.' },
      { key: 'caught', type: 'item', from: ['squeek', 'cheese'], discard: ['squeek', 'cheese'], title: '멈춘 찍찍이', art: '🐁💤', shows: ['dogdoor'],
        text: '치즈에 홀린 찍찍이를 잡아 전원을 껐다. 배에 새겨진 글씨: “소시지 정지 코드 = 우리 집 개들의 다리 수를 모두 더한 수, 그 뒤에 쥐들의 꼬리 수.”' },
      { key: 'board', type: 'item', title: '작업 계획표', art: '📋', text: '“로봇 개 소시지 3마리, 로봇 생쥐 5마리 완성!” 그림 속 개들은 모두 다리가 4개다.' },
      { key: 'dogdoor', type: 'code', title: '소시지 제어반', art: '🐕‍🦺', text: '숫자를 넣으면 모든 소시지가 멈춘다.', code: '125', result: 'remote2', hint: ['계획표의 숫자를 보세요. 개 다리 수 + 쥐 꼬리 수.', '개 3마리 × 4 = 12, 쥐 5마리 꼬리 5 → 125'] },
      { key: 'remote', type: 'red', title: '고장 난 리모컨', art: '📟', text: '배터리 칸이 비어 있다.' },
      { key: 'remote2', type: 'blue', title: '소시지의 배터리', art: '🔋', text: '멈춘 소시지에게서 꺼낸 배터리.' },
      { key: 'final', type: 'machine', from: ['remote', 'remote2'], discard: ['remote', 'remote2'], title: '교수의 리모컨', art: '🎮',
        text: '리모컨이 켜졌다! 화면: “자폭 해제 — 동물 소리를 작은 동물부터 큰 동물 순서로.”', buttons: ['멍', '찍', '어흥', '음매'], solution: ['찍', '멍', '음매', '어흥'], result: 'out',
        hint: ['쥐 < 개 < 소 < 호랑이?', '찍 → 멍 → 음매 → 어흥'] },
      { key: 'out', type: 'item', end: true, title: '계획 저지!', art: '🎉', text: '모든 로봇이 멈췄다. 노사이드 교수는 다락방에서 투덜거리며 내려온다.' },
    ],
  },
  {
    id: 'goorse', box: '이스케이프 어드벤처', title: '구르스 박사의 섬', orig: 'The Island of Doctor Goorse', diff: 3, theme: '#3a8a3a',
    intro: '비행기가 수상한 섬에 불시착했다. 섬의 주인 구르스 박사는 위험한 실험을 하고 있다. 무전기를 찾아 구조를 요청하라!',
    cards: [
      { key: 'beach', type: 'place', start: true, title: '불시착한 해변', art: '🏝️✈️🌴🦀', text: '부서진 비행기, 야자수, 바위 틈. 숲으로 가는 길은 덩굴로 막혀 있다.',
        shows: ['vines', 'plane'], spots: [{ label: '바위 틈', emoji: '🪨', x: 75, y: 70, reveal: 'machete' }, { label: '야자수', emoji: '🌴', x: 30, y: 30, text: '코코넛이 높이 달려 있다.' }] },
      { key: 'plane', type: 'item', title: '비행기 잔해', art: '🛩️', text: '조종석 계기판에 마지막 좌표: “북위 12, 동경 47”. 무전기는 부서졌지만 주파수 다이얼은 멀쩡하다.' },
      { key: 'vines', type: 'red', title: '빽빽한 덩굴', art: '🌿' , text: '칼이 있으면 베어낼 수 있겠다.' },
      { key: 'machete', type: 'blue', title: '마체테', art: '🔪', text: '날이 잘 선 큰 칼.' },
      { key: 'jungle', type: 'place', from: ['vines', 'machete'], discard: ['vines'], shows: ['gate', 'totem'], title: '정글 속 연구소', art: '🌳🏚️🗿', text: '덩굴을 베고 나아가니 철조망 너머 연구소가 보인다.',
        spots: [{ label: '나무 위 둥지', emoji: '🪺', x: 20, y: 25, reveal: 'fuse' }] },
      { key: 'totem', type: 'item', title: '동물 토템', art: '🗿', text: '위에서부터 순서대로 새, 뱀, 원숭이, 거북이가 조각되어 있다.' },
      { key: 'gate', type: 'machine', title: '연구소 정문', art: '🚧', text: '동물 그림 버튼 네 개. 아래에 “토템이 길을 안다.”', buttons: ['🐢', '🐒', '🐍', '🦅'], solution: ['🦅', '🐍', '🐒', '🐢'], result: 'lab', hint: ['토템의 조각 순서대로.', '🦅 🐍 🐒 🐢'] },
      { key: 'lab', type: 'place', title: '구르스 박사의 연구실', art: '🧬🐊🧪📻', text: '수조 속 거대한 악어, 실험 기록, 구석의 전원이 꺼진 송신기.',
        shows: ['notes'], spots: [{ label: '수조 아래', emoji: '🐊', x: 30, y: 70, text: '악어가 이빨을 드러낸다. 손대지 말자!' }, { label: '책상', emoji: '🗂️', x: 75, y: 55, reveal: 'battery' }] },
      { key: 'notes', type: 'item', title: '실험 기록', art: '📓', text: '“실험체 12호 성공. 실험체 47호 탈출. 송신기 주파수는 좌표 숫자를 이어서.”' },
      { key: 'fuse', type: 'red', title: '반짝이는 퓨즈', art: '🔌', text: '새가 물어다 둥지에 둔 듯하다.' },
      { key: 'battery', type: 'blue', title: '대형 배터리', art: '🔋', text: '연구실 비상 배터리. 연결 단자가 빠져 있다.' },
      { key: 'trapmix', type: 'trap', from: ['fuse', 'machete'], title: '찌릿!', text: '칼로 퓨즈를 건드렸다가 감전됐다!', penalty: 1 },
      { key: 'power', type: 'item', from: ['fuse', 'battery'], discard: ['fuse', 'battery'], title: '전원 연결', art: '⚡', shows: ['radio'], text: '퓨즈를 끼우자 배터리가 살아났다. 이제 송신기를 켤 수 있다.' },
      { key: 'radio', type: 'code', title: '송신기', art: '📻', text: '전원이 들어온 송신기. 숫자 4자리 주파수를 맞추면 구조 신호가 나간다.', code: '1247', result: 'out',
        hint: ['실험 기록: 좌표 숫자를 이어서. 좌표는 비행기 계기판에.', '북위 12, 동경 47 → 1247'] },
      { key: 'out', type: 'item', end: true, title: '구조 헬기 도착!', art: '🚁', text: '신호를 받은 헬기가 섬 위를 맴돈다. 구르스 박사의 비밀도 세상에 알려질 것이다.' },
    ],
  },

  // ───────────── 미스터리 어드벤처 ─────────────
  {
    id: 'nautilus', box: '미스터리 어드벤처', title: '노틸러스호의 함정', orig: "The Nautilus' Traps", diff: 1, theme: '#2a6ab8',
    intro: '네모 선장의 잠수함 노틸러스호에 붙잡혔다. 산소가 떨어지기 전에 탈출 잠수정을 찾아라!',
    cards: [
      { key: 'cell', type: 'place', start: true, title: '선실', art: '🛏️🪟🐙', text: '둥근 창 밖으로 거대한 문어가 지나간다. 문에는 밸브식 잠금장치.',
        shows: ['valve'], spots: [{ label: '침대 밑', emoji: '🛏️', x: 30, y: 70, reveal: 'wheel' }, { label: '둥근 창', emoji: '🪟', x: 70, y: 30, text: '물고기 떼가 7마리씩 무리 지어 지나간다.' }] },
      { key: 'valve', type: 'red', title: '손잡이 빠진 밸브', art: '🔩', text: '밸브의 손잡이가 빠져 있다.' },
      { key: 'wheel', type: 'blue', title: '밸브 손잡이', art: '☸️', text: '바퀴 모양 손잡이.' },
      { key: 'corridor', type: 'place', from: ['valve', 'wheel'], discard: ['valve', 'wheel'], shows: ['organ', 'logbook'], title: '노틸러스호 복도', art: '⚓🎹📖', text: '밸브를 돌리자 문이 열렸다. 복도 끝에 선장의 파이프오르간과 항해일지가 놓여 있다.' },
      { key: 'logbook', type: 'item', title: '항해일지', art: '📖', text: '“잠수정 격납고는 오르간이 연다. 내 이름 NEMO의 글자를 오르간 건반에서 찾아 순서대로.”' },
      { key: 'organ', type: 'machine', title: '파이프오르간', art: '🎹', text: '건반마다 글자가 새겨져 있다.', buttons: ['E', 'O', 'A', 'M', 'N', 'S'], solution: ['N', 'E', 'M', 'O'], result: 'hangar', hint: ['항해일지에 선장의 이름이 있어요.', 'N → E → M → O'] },
      { key: 'hangar', type: 'place', title: '잠수정 격납고', art: '🚤🫧', text: '작은 잠수정! 조종석 계기판에 숫자 4자리 시동 코드를 넣어야 한다. 격납고 벽의 동판: “노틸러스호 — 진수 18□□년. 빈칸은 선실 창밖 물고기 떼의 마릿수를 두 번.”', shows: ['sub'] },
      { key: 'sub', type: 'code', title: '잠수정 시동 장치', art: '🔢', text: '숫자 4자리.', code: '1877', result: 'out', hint: ['선실의 둥근 창을 살펴봤나요? 물고기가 몇 마리씩 지나갔죠?', '7마리씩 → 18 + 7 + 7 → 1877'] },
      { key: 'out', type: 'item', end: true, title: '수면 위로!', art: '🌊', text: '잠수정이 노틸러스호를 떠나 빛이 비치는 수면으로 떠오른다.' },
    ],
  },
  {
    id: 'tonipal', box: '미스터리 어드벤처', title: '토니팔의 보물', orig: "The Tonipal's Treasure", diff: 2, theme: '#c8a030',
    intro: '전설의 해적 토니팔이 숨긴 보물이 이 섬 어딘가에 있다. 경쟁 해적보다 먼저 찾아라!',
    cards: [
      { key: 'cove', type: 'place', start: true, title: '해적의 만', art: '🏴‍☠️🏖️⛵💀', text: '난파선, 해골, 모래 언덕. 해골이 한쪽을 가리키고 있다.',
        shows: ['map'], spots: [{ label: '해골 입 속', emoji: '💀', x: 50, y: 60, reveal: 'lens' }, { label: '난파선', emoji: '⛵', x: 20, y: 40, reveal: 'shovel' }] },
      { key: 'map', type: 'red', title: '빛바랜 지도', art: '🗺️', text: '글씨가 너무 작아 읽을 수 없다.' },
      { key: 'lens', type: 'blue', title: '돋보기', art: '🔍', text: '해골이 물고 있던 돋보기.' },
      { key: 'mapread', type: 'item', from: ['map', 'lens'], discard: ['lens'], shows: ['cave'], title: '지도의 비밀', art: '🗺️🔍',
        text: '“야자수에서 북쪽으로 3걸음, 동쪽으로 5걸음, 남쪽으로 1걸음, 서쪽으로 2걸음. 보물상자의 숫자는 걸음 수를 차례로.”' },
      { key: 'cave', type: 'place', title: '해골 동굴', art: '🕳️🦇🪙', text: '동굴 바닥에 묻힌 무언가가 보인다. 벽에 나침반 모양 장치.',
        shows: ['compass'], spots: [{ label: '젖은 모래', emoji: '🏝️', x: 40, y: 75, reveal: 'chest' }] },
      { key: 'shovel', type: 'red', title: '삽', art: '⛏️', text: '' },
      { key: 'chest', type: 'blue', title: '흙 속의 상자 모서리', art: '📦', text: '파내야 한다.' },
      { key: 'dug', type: 'item', from: ['shovel', 'chest'], discard: ['shovel', 'chest'], shows: ['lock'], title: '파낸 보물상자', art: '🧰', text: '숫자 자물쇠가 달린 무거운 상자.' },
      { key: 'compass', type: 'machine', title: '나침반 장치', art: '🧭', text: '“지도의 걸음 방향 순서대로 돌려라.”', buttons: ['북', '동', '남', '서'], solution: ['북', '동', '남', '서'], result: 'gem', hint: ['지도에 적힌 방향 순서.', '북 → 동 → 남 → 서'] },
      { key: 'gem', type: 'item', title: '앵무새 보석', art: '🦜💎', text: '장치가 열리며 보석이 나왔다. 뒷면: “자물쇠는 4자리, 걸음 수.”' },
      { key: 'lock', type: 'code', title: '보물상자 자물쇠', art: '🔒', text: '숫자 4자리.', code: '3512', result: 'out', hint: ['지도의 걸음 수를 차례로.', '3, 5, 1, 2 → 3512'] },
      { key: 'out', type: 'item', end: true, title: '토니팔의 보물!', art: '💰👑', text: '금화와 보석이 가득! 경쟁 해적들의 배가 수평선에 나타날 즈음 당신은 이미 떠났다.' },
    ],
  },
  {
    id: 'househill', box: '미스터리 어드벤처', title: '언덕 위의 집', orig: 'The House on the Hill', diff: 3, theme: '#6a3a8a',
    intro: '마을 사람들이 피하는 언덕 위의 저택. 실종된 친구를 찾으러 들어갔더니 문이 저절로 닫혔다…',
    cards: [
      { key: 'foyer', type: 'place', start: true, title: '저택 현관', art: '🏚️🕯️🖼️👻', text: '초 4개가 켜진 촛대, 가족 초상화, 계단. 응접실 문은 잠겨 있다.',
        shows: ['portrait', 'parlor'], spots: [{ label: '촛대', emoji: '🕯️', x: 20, y: 40, reveal: 'candle' }, { label: '현관 매트', emoji: '🟫', x: 50, y: 85, text: '“WELCOME”… 아래 글자가 지워져 있다.' }] },
      { key: 'portrait', type: 'item', title: '가족 초상화', art: '🖼️', text: '네 사람: 아버지(1820년생), 어머니(1825년생), 딸 에밀리(1851년생), 아들 토마스(1853년생). 에밀리의 눈만 이쪽을 본다.' },
      { key: 'parlor', type: 'code', title: '응접실 문', art: '🚪', text: '숫자 4자리 자물쇠. 문에 새긴 글: “이쪽을 보는 아이가 태어난 해.”', code: '1851', result: 'room2', hint: ['초상화에서 이쪽을 보는 아이는?', '에밀리 1851'] },
      { key: 'room2', type: 'place', title: '응접실', art: '🎻🪞📕', text: '먼지 덮인 바이올린, 큰 거울, 펼쳐진 일기장. 거울에 무언가 비친다.',
        shows: ['diary', 'mirror'], spots: [{ label: '바이올린 케이스', emoji: '🎻', x: 25, y: 60, reveal: 'match' }] },
      { key: 'diary', type: 'item', title: '에밀리의 일기', art: '📕', text: '“지하실 문은 내 노래를 들어야 열린다. 도-미-솔-도. 오빠는 늘 거꾸로 불러서 문이 안 열렸지.”' },
      { key: 'mirror', type: 'item', title: '거울', art: '🪞', text: '거울 속 벽에 거꾸로 쓰인 글씨: “ƎᴚIℲ” — 불(FIRE)? 거울 속에는 촛불이 켜진 지하실 계단이 보인다.' },
      { key: 'candle', type: 'red', title: '꺼진 초', art: '🕯️', text: '심지가 길다.' },
      { key: 'match', type: 'blue', title: '성냥', art: '🔥', text: '바이올린 케이스 속 성냥갑.' },
      { key: 'lit', type: 'item', from: ['candle', 'match'], discard: ['candle', 'match'], shows: ['piano'], title: '켜진 초', art: '🕯️✨', text: '촛불을 비추자 벽 뒤에 숨은 낡은 피아노가 보인다.' },
      { key: 'piano', type: 'machine', title: '낡은 피아노', art: '🎹', text: '건반 다섯 개만 소리가 난다.', buttons: ['도', '레', '미', '파', '솔'], solution: ['도', '미', '솔', '도'], result: 'cellar', hint: ['일기장의 노래.', '도 → 미 → 솔 → 도 (거꾸로가 아니라 그대로!)'] },
      { key: 'cellar', type: 'place', title: '지하실', art: '⛓️🧸👧', text: '친구가 묶여 있다! 쇠사슬에는 다이얼 자물쇠. 바닥에 아이 장난감 블록이 흩어져 있다: 🧱 7개, 🧸 2개, 🪀 4개, 🎲 1개.',
        shows: ['chain'], spots: [{ label: '장난감 상자', emoji: '📦', x: 70, y: 70, text: '“장난감은 큰 것부터 세어라” — 블록·곰·요요·주사위 순서로 크다.' }] },
      { key: 'chain', type: 'code', title: '쇠사슬 자물쇠', art: '🔗', text: '숫자 4자리.', code: '7241', result: 'out', hint: ['장난감 상자의 쪽지: 큰 것부터 개수를.', '🧱7 🧸2 🪀4 🎲1 → 7241'] },
      { key: 'out', type: 'item', end: true, title: '저택 탈출!', art: '🌄', text: '친구를 구해 현관을 뛰쳐나오자 저택의 촛불이 일제히 꺼졌다.' },
    ],
  },

  // ───────────── 시크릿 어드벤처 ─────────────
  {
    id: 'nosidestory', box: '시크릿 어드벤처', title: '노사이드 스토리', orig: 'A Noside Story', diff: 1, theme: '#c84a8a',
    intro: '노사이드 교수가 시간 기계를 훔쳐 갔다! 교수의 아지트에서 기계를 되찾아라.',
    cards: [
      { key: 'den', type: 'place', start: true, title: '노사이드의 아지트', art: '🧔🕰️🧪🐈', text: '어지러운 실험대, 시계가 잔뜩 걸린 벽, 고양이 한 마리. 시간 기계는 유리 덮개 속에 있다.',
        shows: ['cover', 'clocks'], spots: [{ label: '고양이 목걸이', emoji: '🐈', x: 75, y: 70, reveal: 'pin' }] },
      { key: 'clocks', type: 'item', title: '시계 벽', art: '🕐🕒🕕🕘', text: '시계 네 개가 각각 1시, 3시, 6시, 9시를 가리킨다. 그 아래 쪽지: “덮개는 시계를 왼쪽부터 읽은 수.”' },
      { key: 'cover', type: 'code', title: '유리 덮개', art: '🔐', text: '숫자 4자리.', code: '1369', result: 'machine', hint: ['시계 벽의 시계를 왼쪽부터.', '1·3·6·9 → 1369'] },
      { key: 'machine', type: 'red', title: '시간 기계', art: '⏳', text: '핀 모양 열쇠 구멍이 있다.' },
      { key: 'pin', type: 'blue', title: '고양이의 핀', art: '📍', text: '목걸이에 달린 핀. “T-KEY”' },
      { key: 'on', type: 'machine', from: ['machine', 'pin'], discard: ['machine', 'pin'], title: '기계 제어판', art: '🎛️', text: '“과거 → 현재 → 미래 순으로 누르면 원래 주인에게 돌아간다.”', buttons: ['미래', '현재', '과거'], solution: ['과거', '현재', '미래'], result: 'out', hint: ['적힌 순서 그대로.', '과거 → 현재 → 미래'] },
      { key: 'out', type: 'item', end: true, title: '되찾았다!', art: '✨', text: '시간 기계가 반짝이며 사라졌다. 이번에도 노사이드 교수의 계획은 실패!' },
    ],
  },
  {
    id: 'tombstone', box: '시크릿 어드벤처', title: '툼스톤 익스프레스', orig: 'Tombstone Express', diff: 2, theme: '#a86a3a',
    intro: '1870년 서부. 툼스톤행 급행열차가 무법자들에게 점령당했다. 기관차까지 가서 열차를 멈춰라!',
    cards: [
      { key: 'car', type: 'place', start: true, title: '객차 3호', art: '🚃🤠💼', text: '승객들은 묶여 있고, 앞 칸 문은 잠겨 있다. 짐칸 위 가방들.',
        shows: ['door'], spots: [{ label: '짐칸 가방', emoji: '💼', x: 70, y: 25, reveal: 'hook' }, { label: '보안관 배지', emoji: '⭐', x: 30, y: 65, text: '“배지 번호 07” — 보안관은 기절해 있다.' }] },
      { key: 'door', type: 'red', title: '잠긴 연결 문', art: '🚪', text: '창문 너머로 걸쇠가 보인다.' },
      { key: 'hook', type: 'blue', title: '갈고리 지팡이', art: '🦯', text: '' },
      { key: 'mail', type: 'place', from: ['door', 'hook'], discard: ['door', 'hook', 'car'], shows: ['safe', 'telegram'], title: '우편 차량', art: '✉️💰🧨', text: '우편 자루와 금고. 무법자들이 금고를 노리고 있었다.',
        spots: [{ label: '우편 자루', emoji: '✉️', x: 25, y: 60, reveal: 'dynamite' }] },
      { key: 'telegram', type: 'item', title: '전보', art: '📨', text: '“금고 번호: 툼스톤 도착 시각(오후 4시 30분)을 24시간제로.”' },
      { key: 'safe', type: 'code', title: '우편 금고', art: '🔒', text: '숫자 4자리.', code: '1630', result: 'brake', hint: ['오후 4시 30분을 24시간으로.', '16:30 → 1630'] },
      { key: 'dynamite', type: 'red', title: '다이너마이트', art: '🧨', text: '절대 불을 붙이면 안 된다.' },
      { key: 'brake', type: 'blue', title: '제동 레버 손잡이', art: '🔧', text: '금고 속에 들어 있었다.' },
      { key: 'boom', type: 'trap', from: ['dynamite', 'brake'], title: '쾅!', text: '손잡이로 다이너마이트를 두드리다니! 다행히 불발이었지만 정신이 없다.', penalty: 1 },
      { key: 'engine', type: 'place', title: '기관차', art: '🚂🔥', text: '석탄이 활활. 기관사는 묶여 있고, 제동 레버는 손잡이가 빠졌다.', shows: ['lever'] },
      { key: 'lever', type: 'red', title: '빠진 제동 레버', art: '🕹️', text: '' },
      { key: 'stop', type: 'machine', from: ['lever', 'brake'], discard: ['lever', 'brake'], title: '제동 장치', art: '⚙️', text: '기관사가 외친다: “기적-증기-브레이크 순서야! 기적으로 경고부터!”', buttons: ['브레이크', '증기', '기적'], solution: ['기적', '증기', '브레이크'], result: 'out', hint: ['기관사의 말 그대로.', '기적 → 증기 → 브레이크'] },
      { key: 'safeopen', type: 'item', title: '금고 속 지도', art: '🗺️', text: '' },
      { key: 'out', type: 'item', end: true, title: '열차 정지!', art: '🌵', text: '열차가 멈추고 보안관이 깨어나 무법자들을 체포했다.' },
    ].map((c) => (c.key === 'mail' ? { ...c, shows: ['safe', 'telegram', 'engine'] } : c)).filter((c) => c.key !== 'safeopen'),
  },
  {
    id: 'oz', box: '시크릿 어드벤처', title: '오즈의 모험가들', orig: 'The Adventurers of Oz', diff: 3, theme: '#3ab858',
    intro: '회오리바람에 날려 오즈에 떨어졌다. 집으로 돌아가려면 에메랄드 시티의 마법사를 만나야 한다.',
    cards: [
      { key: 'road', type: 'place', start: true, title: '노란 벽돌 길', art: '🌪️🏡🟨🌻', text: '허수아비, 양철 나무꾼, 겁쟁이 사자가 길가에서 도움을 기다린다.',
        shows: ['scarecrow', 'tinman', 'lion'], spots: [{ label: '해바라기 밭', emoji: '🌻', x: 80, y: 60, reveal: 'oil' }, { label: '무너진 집', emoji: '🏡', x: 20, y: 40, reveal: 'shoes' }] },
      { key: 'scarecrow', type: 'item', title: '허수아비', art: '🧑‍🌾', text: '“나는 뇌가 없어… 하지만 숫자 하나는 알아. 첫 번째 숫자는 내 몸의 기둥 수, 1!”' },
      { key: 'tinman', type: 'red', title: '녹슨 양철 나무꾼', art: '🤖', text: '삐걱… 말을 할 수가 없다.' },
      { key: 'oil', type: 'blue', title: '기름통', art: '🛢️', text: '' },
      { key: 'tinok', type: 'item', from: ['tinman', 'oil'], discard: ['tinman', 'oil'], title: '움직이는 양철 나무꾼', art: '🤖❤️', text: '“고마워! 두 번째 숫자는 내 도끼의 날 수, 2. 그리고 사자는 용기가 필요해.”' },
      { key: 'lion', type: 'red', title: '겁쟁이 사자', art: '🦁', text: '덜덜 떨며 숨어 있다.' },
      { key: 'medal', type: 'blue', title: '용기 메달', art: '🏅', text: '' },
      { key: 'lionok', type: 'item', from: ['lion', 'medal'], discard: ['lion', 'medal'], title: '용감한 사자', art: '🦁🏅', text: '“어흥! 세 번째 숫자는 내 다리 수, 4. 네 번째는 우리 넷이 모두 모였다는 뜻의 4!”' },
      { key: 'shoes', type: 'item', title: '은 구두', art: '👠', text: '무너진 집 아래의 구두. 안쪽에 “에메랄드 성문 앞에서 뒤꿈치를 맞부딪쳐라”라고 적혀 있다. 구두 속에서 메달 하나가 떨어졌다.', shows: ['medal', 'city'] },
      { key: 'city', type: 'code', title: '에메랄드 시티 성문', art: '🏰', text: '숫자 4자리. “친구들이 알려 줄 것이다.”', code: '1244', result: 'wizard', hint: ['허수아비, 양철 나무꾼, 사자가 숫자를 하나씩 알려 줘요.', '1 · 2 · 4 · 4 → 1244'] },
      { key: 'wizard', type: 'machine', title: '마법사의 기구', art: '🎈', text: '마법사: “집에 가고 싶다면 구두에 적힌 대로 해 보거라.” 기구는 이미 떠났다…', buttons: ['👠 뒤꿈치 딱', '🙏 기도', '🏃 달리기'], solution: ['👠 뒤꿈치 딱', '👠 뒤꿈치 딱', '👠 뒤꿈치 딱'], result: 'out',
        hint: ['구두에 적힌 행동을 해 보세요. 몇 번일까요? “집만 한 곳은 없어” 하고 세 번!', '👠 뒤꿈치 딱 × 3'] },
      { key: 'out', type: 'item', end: true, title: '집만 한 곳은 없어', art: '🏡💫', text: '눈을 떠 보니 우리 집 침대. 꿈이었을까? 발밑에 은 구두가 반짝인다.' },
    ],
  },
];
