'use strict';
// 언락! 시나리오 — 엑조틱 · 히로익 · 에픽 · 미식 어드벤처

module.exports = [
  // ───────────── 엑조틱 어드벤처 ─────────────
  {
    id: 'boogeymen', box: '엑조틱 어드벤처', title: '부기맨들의 밤', orig: 'Night of the Boogeymen', diff: 1, theme: '#5a4a9a',
    intro: '아이 방 옷장에서 부기맨들이 쏟아져 나왔다! 날이 밝기 전에 잠든 아이의 악몽을 끝내자.',
    cards: [
      { key: 'room', type: 'place', start: true, title: '아이 방', art: '🛏️🧸🌙🚪', text: '아이는 곤히 잠들었고, 옷장 문이 덜컹거린다. 벽에 아이가 그린 그림 세 장이 붙어 있다.',
        shows: ['drawings', 'closet'], spots: [{ label: '침대 밑', emoji: '🛏️', x: 25, y: 70, reveal: 'torch' }, { label: '곰 인형', emoji: '🧸', x: 70, y: 65, text: '곰 인형 배에 “용감한 곰”이라고 수놓여 있다.' }] },
      { key: 'drawings', type: 'item', title: '아이의 그림', art: '🖍️', text: '그림 1: 별 3개. 그림 2: 달 1개. 그림 3: 구름 8개. 아래에 삐뚤삐뚤한 글씨: “밤하늘 순서대로 세면 무섭지 않아!”' },
      { key: 'closet', type: 'red', title: '덜컹거리는 옷장', art: '🚪👀', text: '틈새로 노란 눈이 번뜩인다. 너무 어두워서 안이 보이지 않는다.' },
      { key: 'torch', type: 'blue', title: '손전등', art: '🔦', text: '' },
      { key: 'inside', type: 'place', from: ['closet', 'torch'], discard: ['closet'], shows: ['music'], title: '옷장 속 부기맨 세계', art: '🌀👹🎠', text: '빛을 비추자 옷장 안이 끝없는 회전목마 세계로 이어진다! 부기맨 대장이 오르골 위에 앉아 있다.',
        spots: [{ label: '회전목마', emoji: '🎠', x: 70, y: 55, text: '목마 기둥에 “자장가를 들으면 부기맨은 잠든다.”' }] },
      { key: 'music', type: 'code', title: '오르골 자물쇠', art: '🎶', text: '숫자 3자리 자물쇠가 달린 오르골.', code: '318', result: 'lullaby', hint: ['아이의 그림을 그림 번호 순서대로 세어 보세요.', '별 3 · 달 1 · 구름 8 → 318'] },
      { key: 'lullaby', type: 'machine', title: '오르골 손잡이', art: '🎵', text: '태엽을 감는 방향이 그려져 있다. 오르골 뚜껑 안: “반짝반짝 작은 별 — 도도솔솔라라솔”', buttons: ['도', '레', '미', '솔', '라'], solution: ['도', '도', '솔', '솔', '라', '라', '솔'], result: 'out',
        hint: ['뚜껑 안의 계이름을 그대로.', '도 도 솔 솔 라 라 솔'] },
      { key: 'out', type: 'item', end: true, title: '부기맨들이 잠들었다', art: '😴🌅', text: '자장가에 부기맨들이 하나둘 하품하며 옷장 속으로 사라진다. 아침 햇살이 방을 비춘다.' },
    ],
  },
  {
    id: 'scheherazade', box: '엑조틱 어드벤처', title: '세헤라자드의 마지막 이야기', orig: "Scheherazade's Last Tale", diff: 2, theme: '#c87a2a',
    intro: '천 하룻밤째. 세헤라자드가 이야기를 잃어버렸다! 이야기 속으로 들어가 결말을 되찾아 술탄의 분노를 막자.',
    cards: [
      { key: 'palace', type: 'place', start: true, title: '술탄의 궁전', art: '🕌🪔📜🐫', text: '세헤라자드가 빈 두루마리를 들고 울고 있다. 램프, 양탄자, 보석함이 보인다.',
        shows: ['lamp', 'jewelbox'], spots: [{ label: '양탄자 아래', emoji: '🧶', x: 30, y: 75, reveal: 'cloth' }, { label: '창밖', emoji: '🌙', x: 75, y: 25, text: '초승달 아래 낙타 대상 4무리가 지나간다.' }] },
      { key: 'lamp', type: 'red', title: '먼지 낀 램프', art: '🪔', text: '문지르면 무슨 일이 생길 것 같다.' },
      { key: 'cloth', type: 'blue', title: '비단 천', art: '🧣', text: '' },
      { key: 'genie', type: 'item', from: ['lamp', 'cloth'], discard: ['cloth'], shows: ['door'], title: '램프의 요정', art: '🧞', text: '“세 가지 소원 대신 수수께끼 하나! 알리바바의 동굴 문을 열 주문을 알려 주마: 열려라, 그리고 깨(참깨)의 개수를 말해라. 깨는 낙타 무리 수의 열 배란다.”' },
      { key: 'door', type: 'code', title: '알리바바의 동굴 문', art: '🪨', text: '숫자 2자리.', code: '40', result: 'cave', hint: ['창밖의 낙타 무리 수 × 10.', '4 × 10 = 40'] },
      { key: 'cave', type: 'place', title: '보물 동굴', art: '💎🏺🪙', text: '보물 더미 속에 이야기의 마지막 장이 찢겨 있다. 항아리 40개 중 하나에 도둑이 숨어 있다!',
        shows: ['page'], spots: [{ label: '항아리 더미', emoji: '🏺', x: 60, y: 60, reveal: 'key' }] },
      { key: 'jewelbox', type: 'red', title: '보석함', art: '💍', text: '열쇠 구멍이 있다.' },
      { key: 'key', type: 'blue', title: '도둑의 열쇠', art: '🗝️', text: '항아리 속 도둑이 떨어뜨렸다.' },
      { key: 'gems', type: 'item', from: ['jewelbox', 'key'], discard: ['jewelbox', 'key'], title: '보석함 속 반지', art: '💍✨', text: '반지 안쪽에 새김: “이야기는 해-달-별에서 시작해 별-달-해로 끝난다.”' },
      { key: 'page', type: 'machine', title: '마지막 장의 문양', art: '📜', text: '찢긴 페이지의 문양 버튼. 맞는 순서로 누르면 이야기가 이어진다.', buttons: ['☀️', '🌙', '⭐'], solution: ['⭐', '🌙', '☀️'], result: 'out', hint: ['보석함 속 반지의 글을 보세요. “끝난다”는 쪽.', '⭐ 🌙 ☀️'] },
      { key: 'out', type: 'item', end: true, title: '이야기의 결말', art: '👑📖', text: '이야기가 끝나자 술탄은 감동해 눈물을 흘린다. 세헤라자드는 자유를 얻었다.' },
    ],
  },
  {
    id: 'challenger', box: '엑조틱 어드벤처', title: '탐험대: 챌린저', orig: 'Expedition: Challenger', diff: 3, theme: '#4a8a2a',
    intro: '챌린저 교수와 함께 아마존 고원에 올랐다. 공룡이 사는 잃어버린 세계! 다리가 무너져 내려갈 길이 없다.',
    cards: [
      { key: 'camp', type: 'place', start: true, title: '고원의 야영지', art: '⛺🌋🦕🌴', text: '무너진 밧줄 다리, 꺼진 모닥불, 교수의 일지. 저 멀리 화산이 연기를 뿜는다.',
        shows: ['journal', 'bridge'], spots: [{ label: '배낭', emoji: '🎒', x: 25, y: 70, reveal: 'rope' }, { label: '모닥불', emoji: '🔥', x: 55, y: 75, text: '재 속에 숯 덩어리 6개.' }] },
      { key: 'journal', type: 'item', title: '챌린저 교수의 일지', art: '📔', text: '“고원 탈출 경로: 프테라노돈 둥지 → 동굴 → 강. 동굴 입구는 원주민의 돌 자물쇠. 숫자는 공룡들의 발가락 수: 티라노 3, 트리케라톱스 5, 브론토 4, 랩터 3. 내가 만난 순서는 브론토, 랩터, 티라노, 트리케라톱스.”' },
      { key: 'bridge', type: 'red', title: '끊어진 다리', art: '🌉', text: '절벽 사이 줄이 끊어졌다.' },
      { key: 'rope', type: 'blue', title: '튼튼한 밧줄', art: '🪢', text: '' },
      { key: 'nest', type: 'place', from: ['bridge', 'rope'], discard: ['bridge', 'rope'], shows: ['egg', 'cavelock'], title: '프테라노돈 둥지', art: '🪺🦅🪨', text: '밧줄을 잇고 건너니 거대한 둥지! 어미 새는 사냥을 나갔다.',
        spots: [{ label: '둥지 가장자리', emoji: '🪶', x: 70, y: 40, reveal: 'feather' }] },
      { key: 'egg', type: 'item', title: '거대한 알', art: '🥚', text: '알 껍데기에 원주민 그림: 🌞 두 번, 🌧 한 번, 🌞 한 번. “비가 그친 뒤 해를 맞이하라.”' },
      { key: 'cavelock', type: 'code', title: '동굴 돌 자물쇠', art: '🗿', text: '숫자 4자리.', code: '4335', result: 'cave', hint: ['일지: 만난 순서대로 발가락 수.', '브론토 4, 랩터 3, 티라노 3, 트리케라톱스 5 → 4335'] },
      { key: 'cave', type: 'place', title: '어두운 동굴', art: '🕳️💧🦇', text: '동굴 끝에서 물소리. 벽에 해와 비 문양의 돌 버튼이 있다.', shows: ['sunrain'], spots: [{ label: '젖은 바위', emoji: '🪨', x: 30, y: 65, reveal: 'raft' }] },
      { key: 'sunrain', type: 'machine', title: '해와 비의 문', art: '🌞🌧', text: '돌 버튼 두 개.', buttons: ['🌞', '🌧'], solution: ['🌞', '🌞', '🌧', '🌞'], result: 'river', hint: ['알 껍데기의 그림 순서.', '🌞 🌞 🌧 🌞'] },
      { key: 'feather', type: 'red', title: '거대한 깃털', art: '🪶', text: '노처럼 넓적하다.' },
      { key: 'raft', type: 'blue', title: '통나무 뗏목', art: '🛶', text: '노가 없다.' },
      { key: 'river', type: 'place', title: '지하 강', art: '🌊🏞️', text: '빛이 들어오는 출구! 하지만 물살이 거세다. 뗏목을 저을 무언가가 필요하다.' },
      { key: 'out', type: 'item', from: ['feather', 'raft'], end: true, title: '고원 탈출!', art: '🛶🌅', text: '깃털 노로 뗏목을 저어 아마존 강으로! 챌린저 교수: “런던 학회가 놀라 자빠지겠군!”' },
    ],
  },

  // ───────────── 히로익 어드벤처 ─────────────
  {
    id: 'insertcoin', box: '히로익 어드벤처', title: '인서트 코인', orig: 'Insert Coin', diff: 1, theme: '#d83a8a',
    intro: '오락실 게임기 속으로 빨려 들어갔다! 마지막 스테이지를 깨야 현실로 돌아갈 수 있다.',
    cards: [
      { key: 'stage1', type: 'place', start: true, title: '스테이지 1: 버섯 왕국', art: '🍄👾🧱🪙', text: '점수판: HI-SCORE 0000. 벽돌 블록, 파이프, 깃대.',
        shows: ['pipe'], spots: [{ label: '? 블록', emoji: '🟨', x: 30, y: 30, reveal: 'coin' }, { label: '깃대', emoji: '🚩', x: 80, y: 40, text: '깃대에 숫자 1-1, 1-2, 1-3, 1-4 가 적혀 있다.' }] },
      { key: 'pipe', type: 'red', title: '초록 파이프', art: '🟩', text: '“코인을 넣으세요”라고 적힌 투입구.' },
      { key: 'coin', type: 'blue', title: '반짝이는 코인', art: '🪙', text: '' },
      { key: 'stage2', type: 'place', from: ['pipe', 'coin'], discard: ['pipe', 'coin'], shows: ['cheat', 'boss'], title: '스테이지 2: 보스의 성', art: '🏰🐉🔥', text: '파이프를 타고 내려오니 보스의 성! 보스는 무적 상태다.' },
      { key: 'cheat', type: 'item', title: '낡은 공략집', art: '📕', text: '“무적 해제 커맨드: 위 위 아래 아래 왼쪽 오른쪽 왼쪽 오른쪽.”' },
      { key: 'boss', type: 'machine', title: '조이스틱', art: '🕹️', text: '방향키를 입력하세요.', buttons: ['⬆️', '⬇️', '⬅️', '➡️'], solution: ['⬆️', '⬆️', '⬇️', '⬇️', '⬅️', '➡️', '⬅️', '➡️'], result: 'name', hint: ['공략집의 커맨드를 그대로.', '⬆️⬆️⬇️⬇️⬅️➡️⬅️➡️'] },
      { key: 'name', type: 'code', title: '최고 점수 등록', art: '🏆', text: '보스를 쓰러뜨렸다! “깃대에 적힌 스테이지 끝자리를 이어서 입력하면 현실로 돌아갑니다.”', code: '1234', result: 'out', hint: ['스테이지 1의 깃대.', '1-1, 1-2, 1-3, 1-4 의 끝자리 → 1234'] },
      { key: 'out', type: 'item', end: true, title: 'GAME CLEAR!', art: '🎮✨', text: '눈부신 빛과 함께 오락실 의자 위로 돌아왔다. 화면에는 당신의 이름이 1등!' },
    ],
  },
  {
    id: 'scarlet', box: '히로익 어드벤처', title: '셜록 홈즈: 주홍색 연구', orig: 'Sherlock Holmes: The Scarlet Thread of Murder', diff: 2, theme: '#8a2a2a',
    intro: '런던 브릭스턴 로드의 빈집에서 시신이 발견되었다. 벽에는 붉은 글씨. 홈즈와 함께 범인을 밝혀라.',
    cards: [
      { key: 'house', type: 'place', start: true, title: '로리스턴 가든 3번지', art: '🏚️🩸🕯️🎩', text: '벽에 핏빛 글씨 “RACHE”. 바닥에 결혼반지, 촛농, 마차 바퀴 자국.',
        shows: ['ring', 'wall'], spots: [{ label: '창틀', emoji: '🪟', x: 75, y: 30, reveal: 'lens' }, { label: '바닥 촛농', emoji: '🕯️', x: 35, y: 70, text: '붉은 촛농 — 범인은 불을 켜 두었다.' }] },
      { key: 'wall', type: 'item', title: '벽의 글씨', art: '🖋️', text: '“RACHE” — 레스트레이드: “레이첼이라는 여자 이름이야!” 홈즈: “독일어로 ‘복수’라는 뜻이지.”' },
      { key: 'ring', type: 'red', title: '여자 결혼반지', art: '💍', text: '안쪽에 무언가 아주 작게 새겨져 있다.' },
      { key: 'lens', type: 'blue', title: '홈즈의 돋보기', art: '🔍', text: '' },
      { key: 'engr', type: 'item', from: ['ring', 'lens'], discard: ['ring'], shows: ['telegram'], title: '반지의 새김', art: '💍🔍', text: '“J.H. ♥ L.F. — 솔트레이크, 1847”. 범인은 반지를 찾으러 돌아올 것이다.' },
      { key: 'telegram', type: 'code', title: '클리블랜드 경찰에 보낼 전보', art: '📨', text: '홈즈: “반지를 찾으러 올 사람은 반지에 새겨진 남자일세.” 전보 양식: 용의자 머리글자 두 개를 알파벳 순번(A=1 … Z=26)으로, 각각 두 자리씩.', code: '1008', result: 'reply',
        hint: ['반지에 새겨진 남자의 머리글자는 J.H.', 'J = 10, H = 08 → 1008'] },
      { key: 'reply', type: 'item', title: '답장 전보', art: '📩', text: '“제퍼슨 호프 — 마부로 일함. 마차 번호는 반지에 새겨진 해의 마지막 두 자리.”', shows: ['cab'] },
      { key: 'cab', type: 'code', title: '마차 승강장', art: '🐎', text: '수많은 마차. 번호 2자리를 부르면 그 마차가 온다.', code: '47', result: 'out', hint: ['반지에 새겨진 해.', '1847 → 47'] },
      { key: 'out', type: 'item', end: true, title: '수갑을 채우다', art: '🔗🎩', text: '홈즈가 짐을 옮겨 달라며 마부를 부르고, 순간 수갑을 채운다. “여러분, 제퍼슨 호프 씨를 소개하지.”' },
    ],
  },
  {
    id: 'whiterabbit', box: '히로익 어드벤처', title: '하얀 토끼를 쫓아서', orig: 'In Pursuit of the White Rabbit', diff: 3, theme: '#d85a9a',
    intro: '조끼 입은 하얀 토끼를 따라 굴에 떨어졌다. 이상한 나라에서 여왕의 재판이 시작되기 전에 집으로!',
    cards: [
      { key: 'hall', type: 'place', start: true, title: '문이 많은 복도', art: '🚪🚪🚪🔑', text: '아주 작은 문 하나와 유리 탁자. 탁자 위에 황금 열쇠와 “나를 마셔요” 병.',
        shows: ['door', 'drink'], spots: [{ label: '유리 탁자 밑', emoji: '🍰', x: 40, y: 75, reveal: 'cake' }, { label: '벽시계', emoji: '🕰️', x: 80, y: 25, text: '시계가 거꾸로 돈다. 6시에서 멈췄다 — 언제나 차 마실 시간!' }] },
      { key: 'door', type: 'red', title: '아주 작은 문', art: '🚪', text: '쥐구멍만 하다. 몸이 작아져야 지나갈 수 있다.' },
      { key: 'drink', type: 'blue', title: '“나를 마셔요” 병', art: '🧪', text: '마시면 작아진다.' },
      { key: 'cake', type: 'item', title: '“나를 먹어요” 케이크', art: '🍰', text: '먹으면 커진다. (지금은 필요 없어 보인다)' },
      { key: 'garden', type: 'place', from: ['door', 'drink'], discard: ['door', 'drink'], shows: ['party', 'cards'], title: '여왕의 정원', art: '🌹🃏🦩', text: '작아져서 문을 통과했다! 하얀 장미를 빨갛게 칠하는 카드 병정들, 그 옆 모자 장수의 다과회.' },
      { key: 'party', type: 'item', title: '미친 다과회', art: '🎩☕', text: '모자 장수: “까마귀와 책상이 닮은 이유를 알아? 몰라! 대신 내 모자 숫자를 알려 주지 — 10/6. 그리고 체셔 고양이는 정원 나무 위에 있어.”', spots: [{ label: '나무 위', emoji: '😺', x: 50, y: 30, reveal: 'cheshire' }] },
      { key: 'cards', type: 'item', title: '카드 병정들', art: '♠️♥️♦️♣️', text: '병정 넷이 일렬로 서 있다: 하트 7, 스페이드 2, 다이아 9, 클로버 4. “여왕님은 하트를 제일 좋아하고 클로버를 제일 싫어하시지. 좋아하는 순서대로 서야 해!” 여왕의 순서: ♥ ♦ ♠ ♣' },
      { key: 'cheshire', type: 'item', title: '체셔 고양이', art: '😼', shows: ['court'], text: '“재판장 문은 병정들을 여왕님 순서대로 세운 숫자야. 그리고 돌아가는 길은 시계를 거꾸로 돌리는 거지.” 고양이는 웃음만 남기고 사라졌다.' },
      { key: 'court', type: 'code', title: '재판장 문', art: '⚖️', text: '숫자 4자리.', code: '7924', result: 'trial', hint: ['카드 병정의 숫자를 여왕이 좋아하는 무늬 순서(♥ ♦ ♠ ♣)로.', '♥7 ♦9 ♠2 ♣4 → 7924'] },
      { key: 'trial', type: 'machine', title: '재판장의 큰 시계', art: '🕰️', text: '여왕: “목을 쳐라!” 시계 바늘을 돌려 도망쳐야 한다. 지금 시각은 9시.', buttons: ['⏩ 앞으로 1시간', '⏪ 뒤로 1시간'], solution: ['⏪ 뒤로 1시간', '⏪ 뒤로 1시간', '⏪ 뒤로 1시간'], result: 'out',
        hint: ['체셔 고양이: 거꾸로 돌려라. 어디까지? 복도의 멈춘 시계 — 6시.', '9시 → 6시: ⏪ 세 번'] },
      { key: 'out', type: 'item', end: true, title: '꿈에서 깨다', art: '🌳📖', text: '“앨리스, 일어나렴!” 강둑 나무 아래, 언니의 무릎 위에서 눈을 떴다.' },
    ],
  },

  // ───────────── 에픽 어드벤처 ─────────────
  {
    id: 'werewolf', box: '에픽 어드벤처', title: '늑대인간의 마지막 밤', orig: "The Werewolf's Final Night", diff: 1, theme: '#4a5a7a',
    intro: '보름달이 뜨는 밤, 마을 의사가 늑대인간으로 변하고 있다. 자정 전에 해독제를 만들어 저주를 풀자.',
    cards: [
      { key: 'clinic', type: 'place', start: true, title: '의사의 진료소', art: '🏥🌕🐺📚', text: '의사가 묶인 채 신음한다. 약장, 연구 노트, 은 쟁반.',
        shows: ['notes', 'cabinet'], spots: [{ label: '은 쟁반 밑', emoji: '🍽️', x: 30, y: 70, reveal: 'key' }, { label: '창밖 달', emoji: '🌕', x: 80, y: 20, text: '달이 점점 차오른다. 시계탑이 11번 울렸다.' }] },
      { key: 'notes', type: 'item', title: '연구 노트', art: '📓', text: '“저주를 푸는 약: 투구꽃, 은가루, 늑대 털. 넣는 순서가 중요하다 — 독 → 금속 → 짐승.”' },
      { key: 'cabinet', type: 'red', title: '잠긴 약장', art: '🗄️', text: '' },
      { key: 'key', type: 'blue', title: '약장 열쇠', art: '🗝️', text: '' },
      { key: 'herbs', type: 'machine', from: ['cabinet', 'key'], discard: ['cabinet', 'key'], title: '약 조제대', art: '⚗️', text: '약장 속 재료 세 개를 솥에 넣자.', buttons: ['🐺 늑대 털', '🌿 투구꽃', '🥈 은가루'], solution: ['🌿 투구꽃', '🥈 은가루', '🐺 늑대 털'], result: 'potion', hint: ['노트: 독 → 금속 → 짐승.', '투구꽃 → 은가루 → 늑대 털'] },
      { key: 'potion', type: 'code', title: '해독제 병 마개', art: '🧪', text: '병 마개에 숫자 2자리 자물쇠. “마지막으로 울린 종소리 수 + 1”', code: '12', result: 'out', hint: ['시계탑이 몇 번 울렸나요? 창밖 달을 살펴보세요.', '11 + 1 = 12'] },
      { key: 'out', type: 'item', end: true, title: '자정의 기적', art: '🌕🧑‍⚕️', text: '자정 종이 울리는 순간 해독제를 먹였다. 털이 빠지고, 의사가 사람의 얼굴로 돌아왔다.' },
    ],
  },
  {
    id: 'dragon7', box: '에픽 어드벤처', title: '용의 일곱 시험', orig: "The Dragon's Seven Tests", diff: 2, theme: '#b83a2a',
    intro: '왕국의 수호룡이 후계자를 고른다. 일곱 개의 시험 중 마지막 관문들을 통과해 용의 인정을 받아라.',
    cards: [
      { key: 'gate', type: 'place', start: true, title: '용의 산 입구', art: '🏔️🐉🔥🗿', text: '돌 석상 일곱 개가 늘어서 있고, 그중 다섯은 이미 금빛으로 빛난다 (지난 도전자들의 기록). 남은 두 석상: 지혜와 용기.',
        shows: ['wisdom'], spots: [{ label: '금빛 석상들', emoji: '🗿', x: 30, y: 50, text: '석상 받침에 차례로 I, II, III, IV, V. 남은 것은 VI과 VII.' }, { label: '바위 틈', emoji: '🪨', x: 75, y: 70, reveal: 'shield' }] },
      { key: 'wisdom', type: 'code', title: '여섯 번째 시험 — 지혜', art: '📜', text: '“나는 아침엔 네 발, 낮엔 두 발, 저녁엔 세 발. 세 시간대의 발 수를 이어 말하라.”', code: '423', result: 'courage', hint: ['스핑크스의 수수께끼예요. 답은 사람.', '아침 4 · 낮 2 · 저녁 3 → 423'] },
      { key: 'courage', type: 'place', title: '일곱 번째 시험 — 용기', art: '🔥🐉🌋', text: '용이 불을 뿜는 동굴. “불길을 지나 내 앞에 서라.” 동굴 벽에 용의 비늘 색 순서: 빨강, 금, 검정.',
        shows: ['flame'], spots: [{ label: '용의 둥지', emoji: '🥚', x: 70, y: 60, reveal: 'scales' }] },
      { key: 'flame', type: 'red', title: '불길의 벽', art: '🔥', text: '맨몸으로는 지날 수 없다.' },
      { key: 'shield', type: 'blue', title: '용 비늘 방패', art: '🛡️', text: '' },
      { key: 'pass', type: 'item', from: ['flame', 'shield'], discard: ['flame'], shows: ['scaleslock'], title: '불길을 지나', art: '🛡️🔥', text: '방패로 불을 막으며 용 앞에 섰다. 용: “마지막으로, 내 비늘의 순서를 맞춰라.”' },
      { key: 'scales', type: 'item', title: '떨어진 비늘들', art: '🔴🟡⚫', text: '빨강, 금, 검정 비늘이 섞여 있다.' },
      { key: 'scaleslock', type: 'machine', title: '용의 비늘 제단', art: '🐲', text: '비늘을 순서대로 올려라.', buttons: ['⚫', '🟡', '🔴'], solution: ['🔴', '🟡', '⚫'], result: 'out', hint: ['동굴 벽에 비늘 색 순서가 있어요.', '🔴 🟡 ⚫'] },
      { key: 'out', type: 'item', end: true, title: '용의 기사', art: '🐉👑', text: '용이 고개를 숙인다. “일곱 시험을 모두 마쳤구나. 이제 너는 용의 기사다.”' },
    ],
  },
  {
    id: 'mission07', box: '에픽 어드벤처', title: '미션 #07', orig: 'Mission #07', diff: 3, theme: '#2a4a6a',
    intro: '비밀 요원 07. 적국 대사관 금고에 있는 핵 발사 코드를 빼내고 들키지 않게 탈출하라. 이 메시지는 곧 자동 삭제된다.',
    cards: [
      { key: 'lobby', type: 'place', start: true, title: '대사관 로비', art: '🏛️🕴️🍸🎻', text: '파티가 한창이다. 경비원 둘, 피아노, 2층 계단. 초대장에는 “만찬 21시”.',
        shows: ['guard'], spots: [{ label: '꽃병', emoji: '💐', x: 25, y: 55, reveal: 'pen' }, { label: '피아노', emoji: '🎹', x: 75, y: 60, text: '피아니스트가 계속 같은 곡을 친다: 미-레-도-레-미-미-미.' }] },
      { key: 'guard', type: 'red', title: '2층 경비원', art: '💂', text: '“통행증을 보여 주시죠.”' },
      { key: 'pen', type: 'blue', title: '만년필형 수면가스', art: '🖊️', text: 'Q가 준 장비. 뚜껑을 돌리면 수면가스.' },
      { key: 'floor2', type: 'place', from: ['guard', 'pen'], discard: ['guard', 'pen'], shows: ['laser', 'portrait'], title: '2층 복도', art: '🚨🖼️🚪', text: '경비원이 쿨쿨 잠들었다. 대사 집무실 앞에 레이저 경보 장치.',
        spots: [{ label: '소화기', emoji: '🧯', x: 80, y: 70, reveal: 'mirror' }] },
      { key: 'portrait', type: 'item', title: '대사의 초상화', art: '🖼️', text: '대사가 훈장 4개를 달고 있다. 액자 밑: “1974년 부임”. 대사는 “메리 해드 어 리틀 램”을 좋아한다고 적혀 있다.' },
      { key: 'laser', type: 'red', title: '레이저 경보', art: '🔴〰️', text: '빛을 꺾을 수 있다면…' },
      { key: 'mirror', type: 'blue', title: '콤팩트 거울', art: '🪞', text: '' },
      { key: 'office', type: 'place', from: ['laser', 'mirror'], discard: ['laser', 'mirror'], shows: ['safe'], title: '대사 집무실', art: '🗄️💼🌐', text: '거울로 레이저를 비켜 들어왔다. 벽 금고는 음성 키패드 + 숫자 자물쇠 이중 잠금.' },
      { key: 'safe', type: 'machine', title: '금고 1단계: 음악 키패드', art: '🎼', text: '“대사가 좋아하는 노래의 첫 소절을 연주하시오.”', buttons: ['도', '레', '미', '파', '솔'], solution: ['미', '레', '도', '레', '미', '미', '미'], result: 'safe2',
        hint: ['로비의 피아노가 같은 곡을 치고 있었어요. (메리의 작은 양)', '미 레 도 레 미 미 미'] },
      { key: 'safe2', type: 'code', title: '금고 2단계: 숫자 자물쇠', art: '🔢', text: '“부임 연도의 뒤 두 자리 × 훈장 수.”', code: '296', result: 'out', hint: ['초상화를 보세요.', '74 × 4 = 296'] },
      { key: 'out', type: 'item', end: true, title: '임무 완수', art: '🕶️🚁', text: '코드를 손에 넣고 옥상 헬기로 탈출. 파티장은 아무것도 모른 채 춤을 춘다.' },
    ],
  },

  // ───────────── 미식 어드벤처 ─────────────
  {
    id: 'hades', box: '미식 어드벤처', title: '하데스의 손아귀에서', orig: 'In the Clutches of Hades', diff: 1, theme: '#4a2a6a',
    intro: '죽은 연인을 데려오려 지하 세계로 내려온 오르페우스. 하데스의 시험을 통과하고 지상으로 돌아가자.',
    cards: [
      { key: 'styx', type: 'place', start: true, title: '스틱스 강가', art: '🌊⛵💀🪙', text: '뱃사공 카론이 손을 내민다. “뱃삯을 내라.” 강가에 동전이 흩어져 있다.',
        shows: ['charon'], spots: [{ label: '강가 자갈', emoji: '🪨', x: 30, y: 75, reveal: 'obol' }, { label: '안개', emoji: '🌫️', x: 70, y: 30, text: '안개 속에서 머리 셋 달린 개가 짖는다 — 케르베로스!' }] },
      { key: 'charon', type: 'red', title: '뱃사공 카론', art: '🛶', text: '' },
      { key: 'obol', type: 'blue', title: '오볼로스 은화', art: '🪙', text: '' },
      { key: 'gate', type: 'place', from: ['charon', 'obol'], discard: ['charon', 'obol'], shows: ['lyre'], title: '하데스의 궁전 문', art: '🐕🐕🐕🏛️', text: '머리 셋 달린 케르베로스가 문을 지킨다. 각 머리 목걸이에 음표 하나씩: 첫째 머리 솔, 둘째 미, 셋째 도.' },
      { key: 'lyre', type: 'machine', title: '오르페우스의 리라', art: '🎼', text: '“케르베로스는 첫째 머리부터 노래를 들려주면 잠든다.”', buttons: ['도', '미', '솔'], solution: ['솔', '미', '도'], result: 'throne', hint: ['목걸이의 음표를 첫째 머리부터.', '솔 미 도'] },
      { key: 'throne', type: 'code', title: '하데스의 시험', art: '👑💀', text: '하데스: “석류 씨를 몇 개 먹었는지 맞혀라.” 페르세포네가 몰래 손가락 여섯 개를 편다.', code: '6', result: 'out', hint: ['페르세포네가 알려 줘요.', '6'] },
      { key: 'out', type: 'item', end: true, title: '지상으로', art: '☀️🎵', text: '하데스가 길을 열어 준다. 이번엔 뒤돌아보지 않고, 끝까지 앞만 보고 걸었다.' },
    ],
  },
  {
    id: 'animalomatic', box: '미식 어드벤처', title: '노사이드 교수의 애니멀-오-매틱', orig: "Professor Noside's Animal-O-Matic", diff: 2, theme: '#4ab878',
    intro: '노사이드 교수가 동물을 합체시키는 기계를 만들었다! 동물원 동물들이 뒤죽박죽. 기계를 되돌려라.',
    cards: [
      { key: 'zoo', type: 'place', start: true, title: '난장판 동물원', art: '🦁🐘🦒🐧', text: '사자 머리의 펭귄, 기린 목의 코끼리… 한가운데 거대한 기계 “애니멀-오-매틱”.',
        shows: ['machine', 'sign'], spots: [{ label: '먹이 통', emoji: '🪣', x: 25, y: 70, reveal: 'wrench' }, { label: '사육사 오두막', emoji: '🛖', x: 75, y: 55, reveal: 'manual' }] },
      { key: 'sign', type: 'item', title: '동물원 안내판', art: '🪧', text: '우리 번호: 🦁 사자 1, 🐧 펭귄 3, 🐘 코끼리 5, 🦒 기린 7.' },
      { key: 'machine', type: 'red', title: '애니멀-오-매틱', art: '🏭', text: '패널 나사가 꽉 조여 있다.' },
      { key: 'wrench', type: 'blue', title: '스패너', art: '🔧', text: '' },
      { key: 'panel', type: 'item', from: ['machine', 'wrench'], discard: ['wrench'], shows: ['reverse'], title: '열린 제어 패널', art: '🎛️', text: '패널 안 메모(노사이드 필체): “되돌리기 코드 = 합체된 동물 쌍의 우리 번호를 이어서. 사자+펭귄, 코끼리+기린.”' },
      { key: 'manual', type: 'item', title: '기계 설명서', art: '📘', text: '“코드를 넣은 뒤 레버를 당겨라: 빨강 → 파랑 → 빨강.”' },
      { key: 'reverse', type: 'code', title: '되돌리기 키패드', art: '🔢', text: '숫자 4자리.', code: '1357', result: 'lever', hint: ['안내판의 우리 번호를 쌍 순서대로.', '사자1 펭귄3 코끼리5 기린7 → 1357'] },
      { key: 'lever', type: 'machine', title: '레버 두 개', art: '🕹️', text: '빨간 레버와 파란 레버.', buttons: ['🔴 빨강', '🔵 파랑'], solution: ['🔴 빨강', '🔵 파랑', '🔴 빨강'], result: 'out', hint: ['사육사 오두막의 설명서.', '빨강 → 파랑 → 빨강'] },
      { key: 'out', type: 'item', end: true, title: '원래대로!', art: '🦁🐧🐘🦒', text: '펑! 동물들이 제 모습으로 돌아왔다. 노사이드 교수는 펭귄에게 쫓겨 도망간다.' },
    ],
  },
  {
    id: 'eighty', box: '미식 어드벤처', title: '80분간의 세계 일주', orig: 'Around the World in 80 Minutes', diff: 3, theme: '#3a7ab8',
    intro: '필리어스 포그처럼 내기를 걸었다 — 80분 만에 세계 일주! 런던을 떠나 다시 런던으로 돌아오자.',
    cards: [
      { key: 'london', type: 'place', start: true, title: '런던 리폼 클럽', art: '🎩🕰️🗺️☕', text: '빅벤이 20시 45분을 가리킨다. 탁자 위에 세계 지도와 여행 가방.',
        shows: ['suitcase', 'map'], spots: [{ label: '신문', emoji: '📰', x: 25, y: 65, reveal: 'ticketkey' }] },
      { key: 'map', type: 'item', title: '세계 지도', art: '🗺️', text: '경로: 런던 → 수에즈 → 봄베이 → 홍콩 → 요코하마 → 샌프란시스코 → 뉴욕 → 런던. 각 도시에 핀: 수에즈 🟢, 봄베이 🟡, 홍콩 🔴, 요코하마 ⚪.' },
      { key: 'suitcase', type: 'red', title: '잠긴 여행 가방', art: '🧳', text: '' },
      { key: 'ticketkey', type: 'blue', title: '가방 열쇠', art: '🔑', text: '신문 사이에 끼워져 있었다.' },
      { key: 'open', type: 'item', from: ['suitcase', 'ticketkey'], discard: ['suitcase', 'ticketkey'], shows: ['train'], title: '가방 속 여권', art: '🛂', text: '여권에 입국 도장 자리가 있다. 메모: “아시아 구간은 지도의 핀 색깔 순서로 기차를 갈아타라.”' },
      { key: 'train', type: 'machine', title: '아시아 횡단 기차 신호기', art: '🚂', text: '색깔 신호 버튼.', buttons: ['🔴', '🟡', '🟢', '⚪'], solution: ['🟢', '🟡', '🔴', '⚪'], result: 'ship', hint: ['지도의 핀을 경로 순서대로.', '수에즈🟢 봄베이🟡 홍콩🔴 요코하마⚪'] },
      { key: 'ship', type: 'place', title: '태평양 횡단 증기선', art: '🚢🌊🐳', text: '샌프란시스코로 가는 배. 선장: “석탄이 떨어졌소! 갑판 나무라도 태워야 하오.” 갑판에 도끼.',
        spots: [{ label: '구명보트', emoji: '🛟', x: 70, y: 60, reveal: 'axe' }], shows: ['deck'] },
      { key: 'deck', type: 'red', title: '나무 갑판', art: '🪵', text: '' },
      { key: 'axe', type: 'blue', title: '소방 도끼', art: '🪓', text: '' },
      { key: 'ny', type: 'item', from: ['deck', 'axe'], discard: ['deck', 'axe'], shows: ['bigben'], title: '뉴욕 도착', art: '🗽', text: '갑판을 태워 속력을 냈다! 대서양을 건너 런던으로. 그런데… 날짜 변경선을 넘으며 하루를 벌었다! 클럽에 도착하려면 빅벤 시계를 맞춰야 한다.' },
      { key: 'bigben', type: 'code', title: '빅벤 시계탑', art: '🕰️', text: '“출발한 시각에서 정확히 80분 뒤로 시계를 맞춰라 (24시간제 4자리).”', code: '2205', result: 'out', hint: ['출발 시각은 20시 45분.', '20:45 + 1:20 = 22:05 → 2205'] },
      { key: 'out', type: 'item', end: true, title: '내기에서 이겼다!', art: '🎩🏆', text: '마지막 종이 울리는 순간 클럽 문을 열었다. “신사 여러분, 제가 돌아왔습니다.”' },
    ],
  },
];
