'use strict';
// 언락! 시나리오 — 타임리스 · 레전더리 · 게임 · 엑스트라오디너리 어드벤처

module.exports = [
  // ───────────── 타임리스 어드벤처 ─────────────
  {
    id: 'nosideshow', box: '타임리스 어드벤처', title: '노사이드 쇼', orig: 'The Noside Show', diff: 1, theme: '#d84a4a',
    intro: '디오센 서커스가 마을에 왔다. 그런데 노사이드 교수가 공연을 망칠 장치를 숨겨 두었다! 막이 오르기 전에 찾아내자.',
    cards: [
      { key: 'tent', type: 'place', start: true, title: '서커스 천막', art: '🎪🤡🦁🎈', text: '광대, 사자 우리, 공중그네. 무대 아래에서 째깍째깍 소리가 난다.',
        shows: ['stage'], spots: [{ label: '광대의 모자', emoji: '🎩', x: 25, y: 35, reveal: 'crowbar' }, { label: '풍선 다발', emoji: '🎈', x: 75, y: 30, text: '풍선 색: 빨강 2개, 노랑 5개, 파랑 3개.' }] },
      { key: 'stage', type: 'red', title: '무대 바닥판', art: '🪵', text: '못으로 단단히 박혀 있다.' },
      { key: 'crowbar', type: 'blue', title: '쇠지렛대', art: '🔧', text: '' },
      { key: 'device', type: 'code', from: ['stage', 'crowbar'], discard: ['stage', 'crowbar'], title: '노사이드의 방해 장치', art: '💣🎈', text: '“해제 코드 = 풍선 색깔별 개수, 빨-노-파 순서로.” 이 교수는 왜 늘 힌트를 남길까?', code: '253', result: 'out',
        hint: ['천막의 풍선 다발을 살펴보세요.', '빨강 2 · 노랑 5 · 파랑 3 → 253'] },
      { key: 'out', type: 'item', end: true, title: '쇼는 계속된다!', art: '🎪✨', text: '장치는 작은 꽃가루만 뿜고 멈췄다. 관객들은 그게 공연인 줄 알고 박수를 친다.' },
    ].map((c) => (c.key === 'device' ? { ...c, type: 'code' } : c)),
  },
  {
    id: 'lupin', box: '타임리스 어드벤처', title: '아르센 뤼팽과 거대한 흰 다이아몬드', orig: 'Arsène Lupin and the Great White Diamond', diff: 2, theme: '#2a2a4a',
    intro: '1910년 파리. 괴도 뤼팽이 “오늘 밤 자정, 흰 다이아몬드를 가져가겠다”는 예고장을 보냈다. 뤼팽보다 먼저 보석을 지켜라 — 아니면 먼저 훔쳐라?',
    cards: [
      { key: 'museum', type: 'place', start: true, title: '루브르 특별 전시실', art: '🏛️💎🎩🕯️', text: '진열장 속 다이아몬드는 가짜다! 바닥에 뤼팽의 카드가 떨어져 있다.',
        shows: ['card'], spots: [{ label: '경비원 의자', emoji: '🪑', x: 25, y: 70, reveal: 'uv' }, { label: '창문', emoji: '🪟', x: 75, y: 25, text: '창밖으로 센 강과 노트르담 성당이 보인다.' }] },
      { key: 'card', type: 'red', title: '뤼팽의 카드', art: '🃏', text: '“A.L.” 이라는 서명뿐. 무언가 보이지 않는 잉크로 쓰인 듯하다.' },
      { key: 'uv', type: 'blue', title: '자외선 등', art: '🔦', text: '' },
      { key: 'msg', type: 'item', from: ['card', 'uv'], discard: ['card', 'uv'], shows: ['bookshop'], title: '보이지 않는 글씨', art: '🃏✨', text: '“다이아몬드는 센 강변 고서점에. 서점 금고는 노트르담의 탑 수와 종 수(10)를 이어서.” 노트르담의 탑은 둘이다.' },
      { key: 'bookshop', type: 'place', title: '센 강변 고서점', art: '📚🕰️🐈‍⬛', text: '서점 주인은 사라졌다. 금고와 오래된 지도책.', shows: ['safe', 'atlas'] },
      { key: 'safe', type: 'code', title: '서점 금고', art: '🔐', text: '숫자 3자리.', code: '210', result: 'box', hint: ['노트르담의 탑 수 + 종 수.', '2와 10 → 210'] },
      { key: 'atlas', type: 'item', title: '지도책', art: '🗺️', text: '책갈피에 “에트르타의 바늘바위 — 나의 은신처”라는 메모. 지도에 화살표: 북→서→북→동.' },
      { key: 'box', type: 'machine', title: '비밀 상자', art: '📦', text: '금고 속 상자. 나침반 다이얼이 달렸다.', buttons: ['북', '동', '남', '서'], solution: ['북', '서', '북', '동'], result: 'out', hint: ['지도책의 화살표.', '북 → 서 → 북 → 동'] },
      { key: 'out', type: 'item', end: true, title: '흰 다이아몬드', art: '💎🎩', text: '상자 속엔 진짜 다이아몬드와 쪽지: “축하하오. 다음엔 내가 이기겠지. — A.L.”' },
    ],
  },
  {
    id: 'timewarp', box: '타임리스 어드벤처', title: '시간의 틈에 갇히다!', orig: 'Lost in the Timewarp!', diff: 3, theme: '#3a6ad8',
    intro: '알키비아데스 템푸스 교수의 시간 기계가 고장 나 역사가 뒤죽박죽! 공룡이 로마에, 기사가 우주선에… 시간선을 원래대로 돌려놓자.',
    cards: [
      { key: 'lab', type: 'place', start: true, title: '템푸스 교수의 연구실', art: '⏳🌀🦖🏛️', text: '시간 기계가 불꽃을 튀긴다. 교수는 시간의 틈에 반쯤 걸려 있다! “부품 셋이 다른 시대로 날아갔어!”',
        shows: ['timemachine', 'board'], spots: [{ label: '공구함', emoji: '🧰', x: 25, y: 70, reveal: 'magnet' }] },
      { key: 'board', type: 'item', title: '시대 표지판', art: '📅', text: '기계의 시대 버튼: 🦖 백악기, 🏛️ 고대 로마, 🏰 중세, 🚀 미래. 교수: “부품은 시간 순서대로 되찾아야 해!”' },
      { key: 'timemachine', type: 'machine', title: '시간 기계 행선지', art: '🌀', text: '시대 버튼을 차례로 눌러 부품을 모으자. (한 번에 모든 시대를 돈다)', buttons: ['🚀', '🏰', '🏛️', '🦖'], solution: ['🦖', '🏛️', '🏰', '🚀'], result: 'trip', discardSelf: false,
        hint: ['시대 표지판: 시간 순서대로.', '🦖 → 🏛️ → 🏰 → 🚀'] },
      { key: 'trip', type: 'place', title: '시간 여행', art: '🦖🏛️🏰🚀', text: '네 시대를 휙휙 지나며 부품을 찾는다! 공룡 둥지, 콜로세움, 성의 탑, 우주 정거장.',
        spots: [{ label: '공룡 둥지', emoji: '🥚', x: 15, y: 60, reveal: 'gear' }, { label: '콜로세움', emoji: '🏟️', x: 40, y: 40, text: '검투사의 방패에 로마 숫자 XII.' }, { label: '성의 탑', emoji: '🏰', x: 65, y: 35, reveal: 'crystal' }, { label: '우주 정거장', emoji: '🛰️', x: 88, y: 55, text: '“시간 좌표 확인: 연도 2150”' }] },
      { key: 'gear', type: 'red', title: '시간 톱니바퀴', art: '⚙️', text: '자석에 붙는 쇠 톱니. 원래 자리에 끼우려면 끌어당겨야 한다.' },
      { key: 'magnet', type: 'blue', title: '강력 자석', art: '🧲', text: '' },
      { key: 'gearok', type: 'item', from: ['gear', 'magnet'], discard: ['gear', 'magnet'], title: '톱니 장착', art: '⚙️✅', text: '톱니가 기계에 철컥 붙었다. 교수: “다음은 크리스털!”' },
      { key: 'crystal', type: 'red', title: '시간 크리스털', art: '🔮', text: '받침대가 필요하다.' },
      { key: 'holder', type: 'blue', title: '크리스털 받침대', art: '🏺', text: '톱니를 붙이자 기계 옆 서랍이 열리며 나왔다.' },
      { key: 'crok', type: 'item', from: ['crystal', 'holder'], discard: ['crystal', 'holder'], shows: ['final'], title: '크리스털 장착', art: '🔮✅', text: '기계가 웅웅 울린다. 마지막으로 원래 시간 좌표를 입력해야 한다: “검투사 방패의 숫자를 아라비아 숫자로, 그리고 그 앞에 지금 연도의 앞 두 자리(20).”' },
      { key: 'final', type: 'code', title: '시간 좌표 입력', art: '⌨️', text: '숫자 4자리.', code: '2012', result: 'out', hint: ['콜로세움의 방패: XII = 12.', '20 + 12 → 2012'] },
      { key: 'out', type: 'item', end: true, title: '시간선 복구!', art: '⏳✨', text: '번쩍! 공룡은 백악기로, 기사는 중세로. 교수가 틈에서 빠져나와 안경을 고쳐 쓴다. “자, 차 한잔할까?”' },
    ].map((c) => (c.key === 'gearok' ? { ...c, shows: ['holder'] } : c)),
  },

  // ───────────── 레전더리 어드벤처 ─────────────
  {
    id: 'actionstory', box: '레전더리 어드벤처', title: '액션 스토리', orig: 'Action Story', diff: 1, theme: '#e86a2a',
    intro: '전설의 도둑 스텔라가 세계에서 가장 비싼 보석 “태양의 눈”을 훔쳤다. 영화처럼 추격해 되찾아라!',
    cards: [
      { key: 'roof', type: 'place', start: true, title: '고층 빌딩 옥상', art: '🏙️🚁💼🌃', text: '스텔라가 헬기로 도망쳤다! 남은 건 서류 가방 하나와 무전기.',
        shows: ['case'], spots: [{ label: '환풍구', emoji: '🌀', x: 30, y: 70, reveal: 'code1' }, { label: '헬기 착륙장', emoji: '🅷', x: 70, y: 50, text: '헬기 꼬리 번호를 기억해 두었다: S-84.' }] },
      { key: 'case', type: 'code', title: '스텔라의 서류 가방', art: '💼', text: '숫자 4자리 자물쇠.', code: '0084', result: 'gps', hint: ['헬기 꼬리 번호… 그리고 환풍구 쪽지를 보세요.', '0084'] },
      { key: 'code1', type: 'item', title: '환풍구 속 쪽지', art: '📄', text: '“가방 비밀번호는 헬기 번호 앞에 0을 두 개.”' },
      { key: 'gps', type: 'machine', title: '위치 추적기', art: '📡', text: '가방 속 추적기. “헬기는 3번 구역 → 1번 구역 → 2번 구역으로 이동 중.”', buttons: ['1', '2', '3'], solution: ['3', '1', '2'], result: 'out', hint: ['화면의 이동 순서.', '3 → 1 → 2'] },
      { key: 'out', type: 'item', end: true, title: '추격 성공!', art: '💎🏍️', text: '오토바이로 헬기를 따라잡아 착륙장에서 스텔라를 붙잡았다. “태양의 눈”은 무사하다!' },
    ],
  },
  {
    id: 'robinhood', box: '레전더리 어드벤처', title: '로빈 후드: 생사불문', orig: 'Robin Hood: Dead or Alive', diff: 2, theme: '#3a7a2a',
    intro: '로빈 후드가 노팅엄 영주에게 붙잡혔다! 내일 아침 교수형. 셔우드 숲의 친구들과 함께 로빈을 구하자.',
    cards: [
      { key: 'forest', type: 'place', start: true, title: '셔우드 숲', art: '🌳🏹🦌🔥', text: '리틀 존과 수도사 턱이 걱정스레 모닥불 앞에 앉아 있다. 숲 너머 노팅엄 성이 보인다.',
        shows: ['john', 'castle'], spots: [{ label: '속 빈 나무', emoji: '🌳', x: 20, y: 40, reveal: 'robe' }, { label: '과녁', emoji: '🎯', x: 80, y: 45, text: '과녁에 화살 3개가 꽂혀 있다: 정중앙 2개, 바깥 1개.' }] },
      { key: 'john', type: 'item', title: '리틀 존', art: '🧔', text: '“성문 파수꾼은 수도사에게는 문을 열어 줘. 감옥 열쇠는 영주의 방에 있고, 영주 방 자물쇠는 셋째 탑의 종 번호야.”' },
      { key: 'castle', type: 'red', title: '노팅엄 성문', art: '🏰', text: '파수꾼: “수상한 자는 못 들어간다!”' },
      { key: 'robe', type: 'blue', title: '수도사 옷', art: '🥻', text: '' },
      { key: 'inside', type: 'place', from: ['castle', 'robe'], discard: ['castle', 'robe'], shows: ['lordroom'], title: '노팅엄 성 안뜰', art: '🏰🔔🔔🔔', text: '변장하고 들어왔다! 탑 세 개에 종이 걸려 있다. 첫째 탑 종에 “7”, 둘째 “3”, 셋째 “9”.' },
      { key: 'lordroom', type: 'code', title: '영주의 방 문', art: '🚪', text: '숫자 1자리.', code: '9', result: 'room', hint: ['리틀 존: 셋째 탑의 종 번호.', '9'] },
      { key: 'room', type: 'place', title: '영주의 방', art: '🍗🗝️🐕', text: '영주는 연회 중. 큰 사냥개가 열쇠 고리 옆에 잠들어 있다.', spots: [{ label: '연회 식탁', emoji: '🍗', x: 30, y: 60, reveal: 'meat' }], shows: ['dog'] },
      { key: 'dog', type: 'red', title: '잠든 사냥개', art: '🐕', text: '깨면 짖어 댈 것이다. 개 옆에 감옥 열쇠.' },
      { key: 'meat', type: 'blue', title: '닭다리', art: '🍗', text: '' },
      { key: 'keys', type: 'item', from: ['dog', 'meat'], discard: ['dog', 'meat'], shows: ['cell'], title: '감옥 열쇠', art: '🗝️', text: '개가 닭다리에 정신이 팔린 사이 열쇠를 챙겼다.' },
      { key: 'cell', type: 'machine', title: '감옥 쇠창살', art: '⛓️', text: '로빈: “열쇠를 넣고, 신호로 휘파람을 불어! 과녁의 화살처럼 — 짧게, 짧게, 길게.”', buttons: ['짧게 🎵', '길게 🎶'], solution: ['짧게 🎵', '짧게 🎵', '길게 🎶'], result: 'out',
        hint: ['로빈이 직접 알려 줘요 (과녁: 정중앙 2개, 바깥 1개).', '짧게 → 짧게 → 길게'] },
      { key: 'out', type: 'item', end: true, title: '셔우드로!', art: '🏹🌳', text: '로빈과 함께 성벽을 넘어 숲으로. 영주의 고함이 메아리친다.' },
    ],
  },
  {
    id: 'burntangels', box: '레전더리 어드벤처', title: '셜록 홈즈: 불탄 천사들 사건', orig: 'Sherlock Holmes: The Case of the Burnt Angels', diff: 3, theme: '#6a3a2a',
    intro: '런던의 성당에서 천사상 세 개가 불탄 채 발견되었다. 그리고 한 신부가 사라졌다. 홈즈와 왓슨이 되어 사건을 풀자.',
    cards: [
      { key: 'church', type: 'place', start: true, title: '세인트 미카엘 성당', art: '⛪👼🔥🕯️', text: '불탄 천사상 셋: 각각 날개, 나팔, 책을 들고 있었다. 제단 위에 촛대, 신부의 기도서.',
        shows: ['angels', 'prayer'], spots: [{ label: '고해실', emoji: '🚪', x: 20, y: 55, reveal: 'ash' }, { label: '스테인드글라스', emoji: '🪟', x: 70, y: 25, text: '창의 성인 넷: 마태(I), 마가(II), 누가(III), 요한(IV).' }] },
      { key: 'angels', type: 'item', title: '불탄 천사상', art: '👼👼👼', text: '받침대 번호: 날개 천사 III, 나팔 천사 I, 책 천사 IV. 모두 오른쪽부터 불탔다.' },
      { key: 'prayer', type: 'red', title: '신부의 기도서', art: '📖', text: '어떤 페이지가 재로 얼룩져 읽을 수 없다.' },
      { key: 'ash', type: 'blue', title: '고해실의 재', art: '🧪', text: '홈즈: “이 재는 담배가 아니라 인화성 약품이야.” 왓슨이 붓을 꺼낸다.' },
      { key: 'page', type: 'item', from: ['prayer', 'ash'], discard: ['prayer', 'ash'], shows: ['crypt'], title: '드러난 페이지', art: '📖🔍', text: '재를 털어 내자 신부의 필체: “천사들이 불탄 순서대로 성인의 이름을 부르면 지하 묘지가 열린다.” 홈즈: “불탄 순서는 오른쪽부터, 즉 받침대 번호가 큰 것부터.”' },
      { key: 'crypt', type: 'machine', title: '지하 묘지 석판', art: '⚰️', text: '성인 이름이 새겨진 석판 버튼.', buttons: ['마태', '마가', '누가', '요한'], solution: ['요한', '누가', '마태'], result: 'tomb',
        hint: ['받침대 번호 IV, III, I 순서 — 스테인드글라스에서 번호에 맞는 성인을.', '요한(IV) → 누가(III) → 마태(I)'] },
      { key: 'tomb', type: 'place', title: '지하 묘지', art: '💀🕯️⛓️', text: '사라진 신부가 묶여 있다! 쇠사슬엔 숫자 자물쇠, 벽에 범인의 낙서: “나는 세 천사의 날을 기억한다 — 3월 1일, 4월 3일.”',
        shows: ['chains'], spots: [{ label: '관 뚜껑', emoji: '⚰️', x: 70, y: 60, text: '관 안에 마차 승차권: “범인: 성당 오르간 연주자 그레이브스”' }] },
      { key: 'chains', type: 'code', title: '쇠사슬 자물쇠', art: '🔗', text: '숫자 4자리. “두 날짜를 월일 순서로, 한 자리씩.”', code: '3143', result: 'out', hint: ['낙서의 날짜: 3월 1일, 4월 3일.', '3·1·4·3 → 3143'] },
      { key: 'out', type: 'item', end: true, title: '사건 해결', art: '🎩🔍', text: '신부를 구하고, 오르간 연주자 그레이브스를 체포했다. 홈즈: “간단하지, 왓슨.”' },
    ],
  },

  // ───────────── 게임 어드벤처 ─────────────
  {
    id: 'mysterium', box: '게임 어드벤처', title: '미스테리움: 유령 저택의 꿈', orig: 'Mysterium', diff: 1, theme: '#5a3a8a',
    intro: '워윅 저택의 유령이 꿈으로 단서를 보낸다. 유령이 보여 주는 환영을 읽고, 잠든 영혼을 풀어 주자.',
    cards: [
      { key: 'parlor', type: 'place', start: true, title: '워윅 저택 응접실', art: '🏚️🔮🕯️👻', text: '수정 구슬 주위에 꿈의 카드 세 장이 놓여 있다. 유령이 시계를 가리킨다.',
        shows: ['visions', 'clock'], spots: [{ label: '수정 구슬', emoji: '🔮', x: 50, y: 50, text: '구슬 속에서 열쇠 모양 그림자가 흔들린다… 피아노 쪽으로?' }, { label: '피아노 뚜껑 속', emoji: '🎹', x: 80, y: 65, reveal: 'key' }] },
      { key: 'visions', type: 'item', title: '꿈의 카드들', art: '🃏🃏🃏', text: '1: 정원사의 가위. 2: 서재의 촛대. 3: 다락방의 밧줄. “범인은 정원사, 장소는 서재, 흉기는 밧줄.”' },
      { key: 'clock', type: 'red', title: '괘종시계 문', art: '🕰️', text: '시계 몸통에 작은 문과 열쇠 구멍.' },
      { key: 'key', type: 'blue', title: '은 열쇠', art: '🗝️', text: '' },
      { key: 'inside', type: 'machine', from: ['clock', 'key'], discard: ['clock', 'key'], title: '시계 속 영혼 상자', art: '📦👻', text: '상자에 그림 버튼: 가위, 촛대, 밧줄, 정원, 서재, 다락. “누가, 어디서, 무엇으로 — 그 순서로 누르면 영혼이 풀려난다.”', buttons: ['✂️ 가위', '🕯️ 촛대', '🪢 밧줄', '🌷 정원', '📚 서재', '🏠 다락'], solution: ['✂️ 가위', '📚 서재', '🪢 밧줄'], result: 'out',
        hint: ['꿈의 카드: 범인(정원사 → 가위), 장소(서재), 흉기(밧줄).', '✂️ 가위 → 📚 서재 → 🪢 밧줄'] },
      { key: 'out', type: 'item', end: true, title: '영혼의 안식', art: '👻✨', text: '유령이 미소 지으며 빛 속으로 사라진다. 저택에 처음으로 고요한 아침이 온다.' },
    ],
  },
  {
    id: 'tickettoride', box: '게임 어드벤처', title: '티켓 투 라이드: 대륙 횡단 열차', orig: 'Ticket to Ride', diff: 2, theme: '#c83a3a',
    intro: '1900년 대륙 횡단 열차 경주! 기차표를 모아 노선을 완성하고, 경쟁자보다 먼저 종착역에 도착하자.',
    cards: [
      { key: 'station', type: 'place', start: true, title: '출발역', art: '🚉🚂🎫🗺️', text: '노선도: 시애틀 → 덴버(초록 노선 4칸) → 시카고(노랑 3칸) → 뉴욕(빨강 5칸). 매표소는 닫혀 있다.',
        shows: ['ticket'], spots: [{ label: '벤치 위 가방', emoji: '👜', x: 25, y: 65, reveal: 'coin' }, { label: '노선도', emoji: '🗺️', x: 70, y: 35, text: '각 노선 칸마다 기관차 칸을 놓아야 한다. 색깔 기차 카드가 필요!' }] },
      { key: 'ticket', type: 'red', title: '매표소 창구', art: '🎫', text: '“표 한 장에 금화 한 닢.”' },
      { key: 'coin', type: 'blue', title: '금화', art: '🪙', text: '' },
      { key: 'train', type: 'place', from: ['ticket', 'coin'], discard: ['ticket', 'coin'], shows: ['route', 'conductor'], title: '대륙 횡단 열차', art: '🚂🚃🚃', text: '표를 사서 올라탔다. 차장이 다가온다.' },
      { key: 'conductor', type: 'item', title: '차장', art: '👨‍✈️', text: '“노선 스위치는 색깔 순서대로! 그리고 종착역 승강장 번호는 모든 노선 칸 수의 합이오.”' },
      { key: 'route', type: 'machine', title: '노선 스위치', art: '🎚️', text: '색깔 레버.', buttons: ['🔴', '🟡', '🟢', '🔵'], solution: ['🟢', '🟡', '🔴'], result: 'platform', hint: ['노선도: 시애틀부터 순서대로 노선 색.', '🟢 → 🟡 → 🔴'] },
      { key: 'platform', type: 'code', title: '뉴욕 종착역 승강장', art: '🗽', text: '승강장 번호 2자리를 입력하면 기차가 들어간다.', code: '12', result: 'out', hint: ['칸 수: 4 + 3 + 5.', '12'] },
      { key: 'out', type: 'item', end: true, title: '1등 도착!', art: '🏆🚂', text: '경적을 울리며 뉴욕역에 1등으로 들어왔다. 가장 긴 노선 보너스까지!' },
    ],
  },
  {
    id: 'pandemic', box: '게임 어드벤처', title: '팬데믹: 백신 연구소', orig: 'Pandemic', diff: 3, theme: '#2a8ab8',
    intro: '네 가지 질병이 세계로 퍼지고 있다. 질병통제센터 연구원이 되어 마지막 치료제를 완성하고 연구소 봉쇄를 풀자.',
    cards: [
      { key: 'cdc', type: 'place', start: true, title: '애틀랜타 질병통제센터', art: '🏥🦠🌍🧫', text: '세계 지도에 큐브가 가득. 치료제 세 개는 완성, 노란 질병(🟡)만 남았다. 연구실 문은 봉쇄 중.',
        shows: ['map', 'lockdown'], spots: [{ label: '연구원 사물함', emoji: '🗄️', x: 20, y: 65, reveal: 'badge' }, { label: '화이트보드', emoji: '📋', x: 75, y: 30, text: '“발병 마커: 3 / 감염률: 2 / 남은 연구 카드: 5장 필요”' }] },
      { key: 'map', type: 'item', title: '세계 감염 지도', art: '🗺️', text: '노란 질병 도시: 라고스(큐브 3), 보고타(큐브 1), 상파울루(큐브 2), 킨샤사(큐브 3). “치료제 코드 = 도시들의 큐브 수, 알파벳 이름순(Bogota, Kinshasa, Lagos, Sao Paulo).”' },
      { key: 'lockdown', type: 'red', title: '봉쇄된 연구실 문', art: '🚫', text: '출입증 리더기.' },
      { key: 'badge', type: 'blue', title: '연구원 출입증', art: '🪪', text: '' },
      { key: 'lab', type: 'place', from: ['lockdown', 'badge'], discard: ['lockdown', 'badge'], shows: ['cure', 'samples'], title: '연구실', art: '🔬🧪🧫', text: '노란 질병 샘플 다섯 개와 합성기.' },
      { key: 'samples', type: 'item', title: '샘플 선반', art: '🧪', text: '샘플 라벨: A, B, C, D, E. 메모: “감염률(2)의 배수가 아닌 순서 번호의 샘플만 합성기에 — 1번째(A), 3번째(C), 5번째(E).”' },
      { key: 'cure', type: 'machine', title: '샘플 투입구', art: '⚗️', text: '샘플을 순서대로 넣는다.', buttons: ['A', 'B', 'C', 'D', 'E'], solution: ['A', 'C', 'E'], result: 'synth', hint: ['샘플 선반의 메모.', 'A → C → E'] },
      { key: 'synth', type: 'code', title: '치료제 합성 코드', art: '💉', text: '숫자 4자리.', code: '1332', result: 'out', hint: ['감염 지도의 도시를 알파벳 순으로: Bogota, Kinshasa, Lagos, Sao Paulo.', '보고타1 킨샤사3 라고스3 상파울루2 → 1332'] },
      { key: 'out', type: 'item', end: true, title: '네 번째 치료제!', art: '🌍💉', text: '마지막 치료제가 완성됐다. 전 세계 병원으로 백신이 날아간다. 인류의 승리!' },
    ],
  },

  // ───────────── 엑스트라오디너리 어드벤처 ─────────────
  {
    id: 'restart', box: '엑스트라오디너리 어드벤처', title: '리스타트', orig: 'Restart', diff: 1, theme: '#5ab8d8',
    intro: '같은 하루가 계속 반복된다. 아침 7시, 알람이 울리면 다시 처음부터. 시간의 고리를 끊을 방법을 찾자.',
    cards: [
      { key: 'bedroom', type: 'place', start: true, title: '내 방, 오전 7시', art: '⏰🛏️☕📺', text: '알람 시계가 7:00. 텔레비전 뉴스: “오늘은 3월 14일…” 어제도 3월 14일이었다.',
        shows: ['alarm'], spots: [{ label: '책상 서랍', emoji: '🗃️', x: 25, y: 65, reveal: 'diary' }, { label: '달력', emoji: '📆', x: 75, y: 30, text: '3월 14일에 동그라미가 7번 그려져 있다 — 내가 반복한 횟수?' }] },
      { key: 'diary', type: 'item', title: '내 일기', art: '📔', text: '내 글씨다. “루프를 끊으려면 알람을 반복한 횟수와 날짜(월·일)로 맞춰라. 순서: 월, 일, 횟수.”' },
      { key: 'alarm', type: 'code', title: '알람 시계 설정', art: '⏰', text: '숫자 4자리.', code: '3147', result: 'out', hint: ['달력과 일기를 함께.', '3월 · 14일 · 7번 → 3147'] },
      { key: 'out', type: 'item', end: true, title: '3월 15일', art: '🌅📅', text: '알람이 울리지 않았다. 창밖 신문 배달부가 외친다. “3월 15일 조간이오!”' },
    ],
  },
  {
    id: 'hollywood', box: '엑스트라오디너리 어드벤처', title: '할리우드 컨피덴셜', orig: 'Hollywood Confidential', diff: 2, theme: '#c8a03a',
    intro: '1950년대 할리우드. 영화 시사회 직전 필름 원본이 도난당했다. 사립 탐정이 되어 범인을 찾고 필름을 되찾자.',
    cards: [
      { key: 'studio', type: 'place', start: true, title: '촬영 스튜디오', art: '🎬🎥💄🕶️', text: '비어 있는 필름 금고. 배우 대기실, 감독의 의자, 조명 장치.',
        shows: ['vault', 'suspects'], spots: [{ label: '감독의 의자', emoji: '🪑', x: 25, y: 60, reveal: 'lighter' }, { label: '대기실 거울', emoji: '💄', x: 75, y: 40, text: '립스틱으로 쓴 숫자: 5 · 2 · 8' }, { label: '경비원 책상', emoji: '👮', x: 50, y: 75, reveal: 'locker' }] },
      { key: 'suspects', type: 'item', title: '용의자 명단', art: '📋', text: '1. 여배우 비비안(립스틱). 2. 감독 오슨(시가). 3. 조명기사 잭(라이터). 경비원: “어젯밤 금고 근처에서 라이터 불빛을 봤소.”' },
      { key: 'vault', type: 'item', title: '빈 필름 금고', art: '🗄️', text: '금고 바닥에 라이터 기름 자국.' },
      { key: 'lighter', type: 'red', title: '금장 라이터', art: '🪔', text: '“J” 이니셜. 잠금 장치가 달린 특이한 라이터.' },
      { key: 'locker', type: 'blue', title: '조명기사 사물함 열쇠', art: '🔑', text: '경비원이 빌려준 마스터키.' },
      { key: 'jack', type: 'place', from: ['lighter', 'locker'], discard: ['lighter', 'locker'], shows: ['reel'], title: '조명기사 잭의 사물함', art: '🧰🎞️', text: '라이터 이니셜과 같은 J! 사물함 속에 필름 통이 잠겨 있다. 쪽지: “여배우가 거울에 남긴 숫자를 거꾸로.”' },
      { key: 'reel', type: 'code', title: '필름 통 자물쇠', art: '🎞️', text: '숫자 3자리.', code: '825', result: 'proj', hint: ['대기실 거울의 숫자를 거꾸로.', '5·2·8 → 825'] },
      { key: 'proj', type: 'machine', title: '영사기', art: '📽️', text: '필름을 확인하자. 영사기 버튼: “감기 → 초점 → 재생” 순서로 누르라고 적혀 있다.', buttons: ['▶ 재생', '🔍 초점', '🔄 감기'], solution: ['🔄 감기', '🔍 초점', '▶ 재생'], result: 'out', hint: ['영사기에 적힌 순서.', '감기 → 초점 → 재생'] },
      { key: 'out', type: 'item', end: true, title: '시사회 대성공', art: '🎬🌟', text: '필름은 무사했고, 잭은 경쟁 스튜디오의 사주를 자백했다. 레드 카펫 위로 플래시가 터진다.' },
    ],
  },
  {
    id: 'waff', box: '엑스트라오디너리 어드벤처', title: 'W.A.F.F. 오디세이', orig: 'The W.A.F.F. Odyssey', diff: 3, theme: '#3a3ab8',
    intro: '우주견 연맹(W.A.F.F.) 소속 강아지 우주비행사가 되어, 고장 난 우주선을 고치고 지구로 귀환하자. 멍!',
    cards: [
      { key: 'bridge', type: 'place', start: true, title: '우주선 조종실', art: '🚀🐕🌌🛰️', text: '경보가 울린다! “산소 재생기 고장. 항법 컴퓨터 오프라인.” 함장 비글이 짖는다.',
        shows: ['oxygen'], spots: [{ label: '사료 그릇', emoji: '🥣', x: 25, y: 70, reveal: 'bone' }, { label: '창밖', emoji: '🪐', x: 75, y: 25, text: '창밖 행성들: 화성(4번째), 목성(5번째), 토성(6번째).' }] },
      { key: 'oxygen', type: 'red', title: '산소 재생기', art: '🫧', text: '뼈다귀 모양 부품 칸이 비어 있다. (강아지 우주선답다)' },
      { key: 'bone', type: 'blue', title: '뼈다귀 부품', art: '🦴', text: '' },
      { key: 'air', type: 'item', from: ['oxygen', 'bone'], discard: ['oxygen', 'bone'], shows: ['engine'], title: '산소 복구', art: '🫧✅', text: '숨쉬기 편해졌다! 이제 엔진실 문이 열린다.' },
      { key: 'engine', type: 'place', title: '엔진실', art: '⚙️🔥🐾', text: '엔진 패널에 발바닥 버튼 네 개 (🐾 크기별). 벽의 안내문: “작은 발 → 큰 발 순서로 눌러 점화.”',
        shows: ['ignite'], spots: [{ label: '공구 벽', emoji: '🔧', x: 70, y: 60, text: '렌치 위 낙서: “항법 좌표 = 지구는 3번째 행성! 지구-화성-목성 순서로 행성 번호.”' }] },
      { key: 'ignite', type: 'machine', title: '점화 패널', art: '🐾', text: '발바닥 버튼.', buttons: ['🐾 큰 발', '🐾 아주 작은 발', '🐾 중간 발', '🐾 작은 발'], solution: ['🐾 아주 작은 발', '🐾 작은 발', '🐾 중간 발', '🐾 큰 발'], result: 'fire', hint: ['안내문: 작은 발부터 큰 발까지.', '아주 작은 → 작은 → 중간 → 큰'] },
      { key: 'fire', type: 'item', title: '엔진 점화!', art: '🔥🚀', shows: ['nav'], text: '엔진이 우렁차게 깨어났다. 조종실의 항법 컴퓨터가 켜졌다!' },
      { key: 'nav', type: 'code', title: '항법 컴퓨터', art: '🧭', text: '숫자 3자리. (엔진이 켜져야 동작한다는 경고문이 붙어 있지만, 일단 입력은 된다)', code: '345', result: 'out', hint: ['엔진실 공구 벽 낙서와 조종실 창밖 행성 번호.', '지구3 · 화성4 · 목성5 → 345'] },
      { key: 'out', type: 'item', end: true, title: '지구 귀환', art: '🌍🐶', text: '우주선이 대기권을 뚫고 바다에 착수! 강아지 우주비행사들이 꼬리를 흔들며 손을 흔든다.' },
    ].map((c) => (c.key === 'nav' ? { ...c, text: '숫자 3자리 항법 좌표.' } : c)),
  },
];
