'use strict';
// 언락! 시나리오 — 슈퍼내추럴 · 리스키 · 인챈티드 · 스타워즈 어드벤처

module.exports = [
  // ───────────── 슈퍼내추럴 어드벤처 ─────────────
  {
    id: 'novacity', box: '슈퍼내추럴 어드벤처', title: '위기의 노바 시티', orig: 'Nova City under Threat', diff: 1, theme: '#2a8ad8',
    intro: '초능력 영웅들의 도시 노바 시티. 악당 닥터 볼트가 도시 전력망을 장악했다! 영웅 본부를 되살려 반격하자.',
    cards: [
      { key: 'hq', type: 'place', start: true, title: '영웅 본부', art: '🦸🏙️⚡🖥️', text: '정전된 본부. 비상 발전기와 영웅 명단 스크린이 꺼져 있다.',
        shows: ['generator', 'roster'], spots: [{ label: '망토 걸이', emoji: '🧥', x: 25, y: 45, reveal: 'fuse' }] },
      { key: 'roster', type: 'item', title: '영웅 명단', art: '📋', text: '번개맨(번호 2), 강철소녀(번호 9), 그림자(번호 4). “출동 코드 = 영웅 번호를 이름 글자 수가 적은 순서로.”' },
      { key: 'generator', type: 'red', title: '비상 발전기', art: '🔋', text: '퓨즈가 끊어졌다.' },
      { key: 'fuse', type: 'blue', title: '예비 퓨즈', art: '🔌', text: '' },
      { key: 'power', type: 'code', from: ['generator', 'fuse'], discard: ['generator', 'fuse'], title: '출동 콘솔', art: '🖥️', text: '불이 들어왔다! 숫자 3자리 출동 코드를 입력하세요.', code: '249', result: 'out',
        hint: ['이름 글자 수: 그림자 3, 번개맨 3, 강철소녀 4… 같으면? 명단 순서대로.', '번개맨(3자) 2, 그림자(3자) 4, 강철소녀(4자) 9 → 249'] },
      { key: 'out', type: 'item', end: true, title: '영웅 출동!', art: '🦸‍♀️⚡', text: '영웅들이 하늘로 날아올라 닥터 볼트의 타워를 무너뜨린다. 노바 시티에 불이 켜졌다!' },
    ],
  },
  {
    id: 'muertos', box: '슈퍼내추럴 어드벤처', title: '죽은 자들의 날', orig: 'Día de los Muertos', diff: 2, theme: '#e85aa8',
    intro: '멕시코의 축제 날, 할머니의 영혼이 저승에서 길을 잃었다. 제단을 완성해 할머니가 가족에게 돌아오도록 길을 밝히자.',
    cards: [
      { key: 'altar', type: 'place', start: true, title: '가족 제단 (오프렌다)', art: '💀🌼🕯️🖼️', text: '할머니 사진, 설탕 해골, 메리골드 꽃잎. 촛불 네 개 중 하나만 켜져 있다. 제단은 세 칸.',
        shows: ['photo', 'candles'], spots: [{ label: '부엌', emoji: '🫓', x: 20, y: 65, reveal: 'pan' }, { label: '꽃바구니', emoji: '🌼', x: 75, y: 70, reveal: 'petals' }] },
      { key: 'photo', type: 'item', title: '할머니 사진', art: '👵', text: '사진 뒤: “내가 좋아하던 것: 노래(맨 아래 칸), 빵(가운데 칸), 꽃(맨 윗칸).” 제단은 아래 칸부터 채운다.' },
      { key: 'candles', type: 'red', title: '꺼진 초 세 자루', art: '🕯️', text: '' },
      { key: 'pan', type: 'item', title: '죽은 자의 빵', art: '🍞', text: '갓 구운 빵. 제단에 올릴 수 있다.' },
      { key: 'petals', type: 'blue', title: '메리골드와 성냥', art: '🌼🔥', text: '꽃잎 사이에 성냥갑이 있다.' },
      { key: 'lit', type: 'machine', from: ['candles', 'petals'], discard: ['candles'], title: '제단 꾸미기', art: '🪔', text: '촛불이 모두 켜졌다! 이제 제단 칸에 할머니가 좋아하던 것을 올리자 (아래 칸부터).', buttons: ['🌼 꽃', '🍞 빵', '🎸 노래'], solution: ['🎸 노래', '🍞 빵', '🌼 꽃'], result: 'bridge',
        hint: ['사진 뒷면을 보세요. 아래 칸 → 위 칸.', '🎸 노래 → 🍞 빵 → 🌼 꽃'] },
      { key: 'bridge', type: 'code', title: '꽃잎 다리', art: '🌉🌼', text: '저승과 이승을 잇는 꽃잎 다리가 나타났다. 다리 문에 숫자 자물쇠: “켜진 촛불 수와 제단 칸 수.”', code: '43', result: 'out', hint: ['촛불은 모두 몇 개? 제단은 몇 칸?', '촛불 4, 제단 3 → 43'] },
      { key: 'out', type: 'item', end: true, title: '할머니가 돌아왔다', art: '👵💐', text: '꽃잎 다리를 건너 할머니의 영혼이 웃으며 가족 곁에 앉는다. 마리아치 음악이 울려 퍼진다.' },
    ],
  },
  {
    id: 'ragnarok', box: '슈퍼내추럴 어드벤처', title: '라그나로크', orig: 'Ragnarök', diff: 3, theme: '#6a8ab8',
    intro: '신들의 황혼이 다가온다. 늑대 펜리르가 사슬을 끊으려 한다! 아스가르드의 룬을 모아 운명을 바꾸자.',
    cards: [
      { key: 'bifrost', type: 'place', start: true, title: '비프로스트 무지개 다리', art: '🌈⚔️🐺❄️', text: '파수꾼 헤임달이 뿔피리를 들고 있다. 다리 끝에 아홉 세계를 가리키는 표지판.',
        shows: ['heimdall', 'worlds'], spots: [{ label: '무지개 아래', emoji: '🌈', x: 30, y: 70, reveal: 'rune1' }, { label: '얼음 바위', emoji: '🧊', x: 75, y: 60, text: '얼음 속에 룬 문자 ᚠ(F)가 비친다.' }] },
      { key: 'heimdall', type: 'item', title: '헤임달', art: '🛡️📯', text: '“펜리르의 사슬 글레이프니르는 여섯 가지로 만들어졌지: 고양이 발소리, 여자의 수염, 산의 뿌리, 곰의 힘줄, 물고기의 숨, 새의 침. 사슬을 다시 묶으려면 그 순서대로!”' },
      { key: 'worlds', type: 'item', title: '아홉 세계 표지판', art: '🪧', text: '아스가르드 1, 미드가르드 2, 요툰헤임 3, … 헬헤임 9. 펜리르는 요툰헤임에서 아스가르드로 오고 있다.' },
      { key: 'rune1', type: 'red', title: '부서진 룬석', art: '🪨', text: '반쪽만 남았다.' },
      { key: 'rune2', type: 'blue', title: '룬석의 나머지 반쪽', art: '🪨', text: '' },
      { key: 'forge', type: 'place', title: '드워프의 대장간', art: '⚒️🔥💎', text: '드워프 형제가 망치를 두드린다. “룬석을 맞추면 사슬을 만들어 주지!”', spots: [{ label: '모루 아래', emoji: '🔨', x: 60, y: 65, reveal: 'rune2' }] },
      { key: 'chain', type: 'machine', from: ['rune1', 'rune2'], discard: ['rune1', 'rune2'], title: '글레이프니르 제작', art: '⛓️✨', text: '여섯 재료 버튼.', buttons: ['🐟 물고기의 숨', '🐻 곰의 힘줄', '🐈 고양이 발소리', '🐦 새의 침', '⛰️ 산의 뿌리', '🧔‍♀️ 여자의 수염'], solution: ['🐈 고양이 발소리', '🧔‍♀️ 여자의 수염', '⛰️ 산의 뿌리', '🐻 곰의 힘줄', '🐟 물고기의 숨', '🐦 새의 침'], result: 'fenrir',
        hint: ['헤임달이 말한 순서.', '고양이 → 수염 → 산 → 곰 → 물고기 → 새'] },
      { key: 'fenrir', type: 'code', title: '펜리르를 묶을 바위', art: '🐺⛓️', text: '사슬이 완성됐다! 바위의 룬 자물쇠: “늑대가 지나온 세계의 번호와 가려는 세계의 번호, 그리고 얼음 속 룬 글자의 알파벳 순번.”', code: '316', result: 'out',
        hint: ['요툰헤임(3) → 아스가르드(1). 얼음 속 룬 ᚠ = F.', '3 · 1 · F(6) → 316'] },
      { key: 'out', type: 'item', end: true, title: '황혼은 오지 않는다', art: '🌅🛡️', text: '펜리르가 다시 묶였다. 라그나로크는 먼 미래로 미뤄졌다. 아스가르드에 축배가 오른다!' },
    ].map((c) => (c.key === 'bifrost' ? { ...c, shows: ['heimdall', 'worlds', 'forge'] } : c)),
  },

  // ───────────── 리스키 어드벤처 ─────────────
  {
    id: 'altipia', box: '리스키 어드벤처', title: '알티피아의 왕관', orig: "La couronne d'Altipia", diff: 1, theme: '#d8a83a',
    intro: '알티피아 왕국의 대관식 날, 왕관이 사라졌다! 대관식 종이 울리기 전에 왕관을 찾아라.',
    cards: [
      { key: 'throne', type: 'place', start: true, title: '왕좌의 방', art: '👑🏰🦚🎺', text: '빈 왕관 받침대. 공작새 한 마리가 무언가를 쪼고 있다. 창문 밖 종탑.',
        shows: ['peacock'], spots: [{ label: '커튼 뒤', emoji: '🎭', x: 25, y: 45, reveal: 'seed' }, { label: '종탑', emoji: '🔔', x: 80, y: 25, text: '종탑의 시계: 10시 50분. 대관식은 11시!' }] },
      { key: 'peacock', type: 'red', title: '공작새', art: '🦚', text: '꼬리 깃털 사이에 무언가 반짝인다. 다가가면 날개를 퍼덕인다.' },
      { key: 'seed', type: 'blue', title: '해바라기 씨', art: '🌻', text: '' },
      { key: 'box', type: 'code', from: ['peacock', 'seed'], discard: ['peacock', 'seed'], title: '깃털 속 보석함', art: '💎', text: '공작새가 씨를 먹는 사이 작은 보석함을 꺼냈다. 숫자 4자리: “대관식 시각.”', code: '1100', result: 'out',
        hint: ['종탑: 대관식은 11시.', '11:00 → 1100'] },
      { key: 'out', type: 'item', end: true, title: '대관식', art: '👑🎺', text: '왕관을 받침대에 올리는 순간 종이 울린다. 새 여왕이 미소 짓는다.' },
    ],
  },
  {
    id: 'rendezvous', box: '리스키 어드벤처', title: '깜짝 랑데부', orig: 'Rendez-vous surprise', diff: 2, theme: '#e85a7a',
    intro: '오늘은 연인과의 기념일! 깜짝 파티를 준비했는데, 상대가 30분 뒤 도착한다. 엉망이 된 준비를 마무리하자.',
    cards: [
      { key: 'apt', type: 'place', start: true, title: '우리 집 거실', art: '🏠🎂🎈🎁', text: '케이크는 냉장고에, 선물은 잠긴 서랍에, 풍선은 바람이 빠졌다. 휴대폰에 메시지 알림.',
        shows: ['phone', 'drawer'], spots: [{ label: '소파 쿠션', emoji: '🛋️', x: 25, y: 65, reveal: 'pump' }, { label: '냉장고', emoji: '🧊', x: 80, y: 50, text: '냉장고 자석: “우리가 처음 만난 날 ♥ 5월 20일”' }] },
      { key: 'phone', type: 'item', title: '휴대폰 메시지', art: '📱', text: '친구: “선물 서랍 비번은 너희 처음 만난 날(월일 4자리)! 그리고 풍선은 꼭 하트 모양으로 불어 ㅋㅋ”' },
      { key: 'drawer', type: 'code', title: '선물 서랍', art: '🗃️', text: '숫자 4자리.', code: '0520', result: 'gift', hint: ['냉장고 자석을 보세요.', '5월 20일 → 0520'] },
      { key: 'gift', type: 'item', title: '선물 상자', art: '🎁', text: '포장 완료! 이제 풍선만 남았다.' },
      { key: 'balloon', type: 'red', title: '바람 빠진 풍선', art: '🎈', text: '' },
      { key: 'pump', type: 'blue', title: '풍선 펌프', art: '🪠', text: '' },
      { key: 'shape', type: 'machine', from: ['balloon', 'pump'], discard: ['balloon', 'pump'], title: '풍선 아트', art: '🎈✨', text: '풍선을 꼬아 모양을 만들자. 버튼: 비틀기 방향.', buttons: ['↩ 왼쪽', '↪ 오른쪽', '⬆ 위로'], solution: ['↩ 왼쪽', '↪ 오른쪽', '⬆ 위로'], result: 'out',
        hint: ['하트는 왼쪽 반, 오른쪽 반, 그리고 위로 묶기!', '↩ → ↪ → ⬆'] },
      { key: 'out', type: 'item', end: true, title: '서프라이즈!', art: '💝🥂', text: '문이 열리는 순간 “서프라이즈!” 연인의 눈이 동그래진다. 완벽한 기념일!' },
    ].map((c) => (c.key === 'apt' ? { ...c, shows: ['phone', 'drawer', 'balloon'] } : c)),
  },
  {
    id: 'littleitaly', box: '리스키 어드벤처', title: '리틀 이탈리아의 잠입자', orig: "L'infiltré de Little Italy", diff: 3, theme: '#3a2a2a',
    intro: '1930년대 뉴욕. 마피아 패밀리에 잠입한 FBI 요원이다. 정체가 들통나기 전에 장부를 빼내라.',
    cards: [
      { key: 'restaurant', type: 'place', start: true, title: '루이지의 식당', art: '🍝🍷🎻🕴️', text: '패밀리의 아지트. 주방 뒤 사무실은 잠겨 있다. 바이올린 연주자가 같은 곡만 연주한다.',
        shows: ['menu', 'office'], spots: [{ label: '와인 저장고', emoji: '🍷', x: 25, y: 65, reveal: 'corkscrew' }, { label: '바이올린 케이스', emoji: '🎻', x: 75, y: 55, text: '악보 표지: “대부의 왈츠 — 솔 · 도 · 미 · 레”' }] },
      { key: 'menu', type: 'item', title: '오늘의 메뉴', art: '📜', text: '“카르보나라 7달러, 라자냐 3달러, 리조또 9달러, 티라미수 1달러.” 메뉴판 귀퉁이에 연필로: “사무실 = 디저트-파스타-밥 순서 가격”' },
      { key: 'office', type: 'code', title: '사무실 문', art: '🚪', text: '숫자 3자리.', code: '179', result: 'den', hint: ['메뉴판 귀퉁이: 디저트(티라미수), 파스타(카르보나라), 밥(리조또).', '1 · 7 · 9 → 179'] },
      { key: 'den', type: 'place', title: '보스의 사무실', art: '💼🗄️📞', text: '책상 위 와인 병, 벽에 걸린 대부의 초상. 장부는 축음기 금고 속에 있다.', shows: ['bottle', 'gramophone'] },
      { key: 'bottle', type: 'red', title: '코르크로 막힌 와인 병', art: '🍾', text: '병 안에 돌돌 말린 쪽지가 보인다.' },
      { key: 'corkscrew', type: 'blue', title: '코르크 따개', art: '🌀', text: '' },
      { key: 'note', type: 'item', from: ['bottle', 'corkscrew'], discard: ['bottle', 'corkscrew'], title: '병 속 쪽지', art: '📃', text: '“축음기 금고는 대부의 왈츠를 연주하면 열린다. 단, 거꾸로.”' },
      { key: 'gramophone', type: 'machine', title: '축음기 금고', art: '📻', text: '음 버튼.', buttons: ['도', '레', '미', '파', '솔'], solution: ['레', '미', '도', '솔'], result: 'out', hint: ['악보: 솔 도 미 레 — 쪽지대로 거꾸로.', '레 → 미 → 도 → 솔'] },
      { key: 'out', type: 'item', end: true, title: '장부 확보', art: '📒🚓', text: '장부를 코트 속에 숨기고 뒷문으로. 골목 끝에 FBI 차량이 기다린다.' },
    ],
  },

  // ───────────── 인챈티드 어드벤처 ─────────────
  {
    id: 'kilea', box: '인챈티드 어드벤처', title: '킬레아의 분노', orig: "Kilea's Wrath", diff: 1, theme: '#3ab8a8',
    intro: '숲의 여신 킬레아가 분노해 마을의 샘을 말려 버렸다. 여신의 분노를 달랠 제물을 바치자.',
    cards: [
      { key: 'grove', type: 'place', start: true, title: '신성한 숲', art: '🌳🦌💧🗿', text: '말라 버린 샘과 여신의 석상. 석상 받침에 작은 그릇 세 개.',
        shows: ['statue'], spots: [{ label: '고목 구멍', emoji: '🌳', x: 25, y: 45, reveal: 'flute' }, { label: '사슴 발자국', emoji: '🦌', x: 70, y: 70, text: '사슴들이 남긴 꽃 세 송이: 흰 꽃, 붉은 꽃, 푸른 꽃.' }] },
      { key: 'statue', type: 'machine', title: '여신의 석상', art: '🗿', text: '받침의 글: “내가 사랑하는 것은 새벽의 흰빛, 노을의 붉은빛, 밤의 푸른빛.” 꽃을 그릇에 담자.', buttons: ['🔵 푸른 꽃', '⚪ 흰 꽃', '🔴 붉은 꽃'], solution: ['⚪ 흰 꽃', '🔴 붉은 꽃', '🔵 푸른 꽃'], result: 'spring',
        hint: ['새벽 → 노을 → 밤.', '⚪ → 🔴 → 🔵'] },
      { key: 'spring', type: 'red', title: '꿈틀대는 샘', art: '💧', text: '물이 나올 듯 말 듯. 여신이 노래를 원한다.' },
      { key: 'flute', type: 'blue', title: '나무 피리', art: '🪈', text: '' },
      { key: 'out', type: 'item', from: ['spring', 'flute'], end: true, title: '샘이 다시 흐른다', art: '💧🌸', text: '피리 소리에 여신이 미소 짓자 샘이 솟구친다. 숲에 꽃이 피어난다.' },
    ],
  },
  {
    id: 'amusement', box: '인챈티드 어드벤처', title: '놀이공원 대소동', orig: 'Frenzy at the Amusement Park', diff: 2, theme: '#e8a83a',
    intro: '폐장 시간, 놀이기구들이 마법에 걸려 제멋대로 움직인다! 관리실에 가서 마법을 멈추자.',
    cards: [
      { key: 'gate', type: 'place', start: true, title: '놀이공원 광장', art: '🎡🎢🎠🍿', text: '대관람차가 거꾸로 돌고, 회전목마의 말들이 뛰어다닌다. 관리실은 롤러코스터 너머.',
        shows: ['coaster', 'map'], spots: [{ label: '팝콘 수레', emoji: '🍿', x: 25, y: 65, reveal: 'token' }, { label: '대관람차', emoji: '🎡', x: 75, y: 35, text: '칸 번호가 거꾸로 지나간다: 8, 6, 4, 2…' }] },
      { key: 'map', type: 'item', title: '공원 지도', art: '🗺️', text: '관리실 비상 정지 코드: “대관람차 칸 번호를 올바른 순서로(작은 수부터).”' },
      { key: 'coaster', type: 'red', title: '롤러코스터 탑승구', art: '🎢', text: '“토큰을 넣으세요.”' },
      { key: 'token', type: 'blue', title: '탑승 토큰', art: '🪙', text: '' },
      { key: 'ride', type: 'place', from: ['coaster', 'token'], discard: ['coaster', 'token'], shows: ['booth'], title: '관리실', art: '🎛️🧙', text: '코스터를 타고 관리실 앞에 도착! 안에서 장난꾸러기 마법사 인형이 키득거린다.',
        spots: [{ label: '마법사 인형', emoji: '🧙', x: 70, y: 55, text: '“정지 코드 뒤에 내 주문도 외워야 해! 아브라 → 카 → 다브라!”' }] },
      { key: 'booth', type: 'code', title: '비상 정지 패널', art: '🛑', text: '숫자 4자리.', code: '2468', result: 'spell', hint: ['지도와 대관람차를 함께.', '2 · 4 · 6 · 8 → 2468'] },
      { key: 'spell', type: 'machine', title: '마법 해제 버튼', art: '✨', text: '주문 버튼.', buttons: ['다브라', '아브라', '카'], solution: ['아브라', '카', '다브라'], result: 'out', hint: ['마법사 인형의 말.', '아브라 → 카 → 다브라'] },
      { key: 'out', type: 'item', end: true, title: '평화로운 밤', art: '🎡🌙', text: '놀이기구들이 스르르 멈추고 불빛이 고요해진다. 마법사 인형은 하품하며 잠들었다.' },
    ],
  },
  {
    id: 'camelot', box: '인챈티드 어드벤처', title: '카멜롯의 저주', orig: 'The Curse on Camelot', diff: 3, theme: '#5a5ab8',
    intro: '마녀 모르가나의 저주로 카멜롯의 기사들이 돌이 되었다. 마법사 멀린의 탑에서 저주를 풀 방법을 찾자.',
    cards: [
      { key: 'hall', type: 'place', start: true, title: '원탁의 방', art: '🛡️🗿🗿🗡️', text: '원탁에 둘러앉은 채 돌이 된 기사들. 아서 왕의 자리만 비어 있다. 탁자 위 기사 이름표.',
        shows: ['names', 'tower'], spots: [{ label: '아서 왕의 의자', emoji: '🪑', x: 50, y: 60, reveal: 'scabbard' }, { label: '벽 태피스트리', emoji: '🧵', x: 80, y: 30, text: '수놓인 그림: 엑스칼리버가 호수에서 떠오르고, 칼집에 별 셋.' }] },
      { key: 'names', type: 'item', title: '기사 이름표', art: '📛', text: '랜슬롯, 가웨인, 퍼시벌, 갤러해드 — 탁자 시계 방향 순서. 이름표 뒷면: “성배를 찾은 기사는 맨 끝에 앉는다.”' },
      { key: 'tower', type: 'red', title: '멀린의 탑 문', art: '🗼', text: '“칼집을 가진 자만 들어오라.”' },
      { key: 'scabbard', type: 'blue', title: '엑스칼리버의 칼집', art: '🗡️', text: '별 세 개가 박혀 있다.' },
      { key: 'merlin', type: 'place', from: ['tower', 'scabbard'], discard: ['tower'], shows: ['book', 'cauldron'], title: '멀린의 탑', art: '🧙‍♂️📚🦉', text: '멀린은 없고 부엉이만 있다. 마법서와 끓는 솥.' },
      { key: 'book', type: 'item', title: '멀린의 마법서', art: '📖', text: '“돌의 저주를 푸는 물약: 기사들의 이름 첫 글자를 원탁 순서대로 솥에 외치고, 칼집의 별 수만큼 저어라.”' },
      { key: 'cauldron', type: 'machine', title: '마법의 솥', art: '🫕', text: '글자 버튼.', buttons: ['가', '갤', '랜', '퍼'], solution: ['랜', '가', '퍼', '갤'], result: 'stir', hint: ['이름표의 원탁 순서, 첫 글자만.', '랜 → 가 → 퍼 → 갤'] },
      { key: 'stir', type: 'code', title: '솥 젓개 다이얼', art: '🥄', text: '“몇 번 저을까?” 숫자 1자리.', code: '3', result: 'out', hint: ['칼집의 별 수.', '3'] },
      { key: 'out', type: 'item', end: true, title: '기사들의 부활', art: '⚔️👑', text: '물약 연기가 원탁을 감싸자 기사들이 기지개를 켠다. 아서 왕이 엑스칼리버를 높이 든다!' },
    ],
  },

  // ───────────── 스타워즈 ─────────────
  {
    id: 'sw-delay', box: '스타워즈', title: '예상치 못한 지연', orig: 'An Unforeseen Delay', diff: 1, theme: '#3a3a5a',
    intro: '먼 옛날 은하계 저편. 밀수선이 제국 순찰대에 붙잡혀 정비 행성에 묶였다. 하이퍼드라이브를 고쳐 탈출하자!',
    cards: [
      { key: 'hangar', type: 'place', start: true, title: '정비 격납고', art: '🛸🔧🤖⭐', text: '고장 난 하이퍼드라이브, 수다쟁이 정비 드로이드, 제국 경비 순찰 시간표.',
        shows: ['droid', 'drive'], spots: [{ label: '부품 상자', emoji: '📦', x: 25, y: 65, reveal: 'coil' }] },
      { key: 'droid', type: 'item', title: '정비 드로이드', art: '🤖', text: '“삐빅! 하이퍼드라이브 재가동 순서: 냉각 → 충전 → 점프. 확률은 3720분의 1이지만요!”' },
      { key: 'drive', type: 'red', title: '하이퍼드라이브', art: '⚙️', text: '동력 코일이 타 버렸다.' },
      { key: 'coil', type: 'blue', title: '새 동력 코일', art: '🌀', text: '' },
      { key: 'fixed', type: 'machine', from: ['drive', 'coil'], discard: ['drive', 'coil'], title: '하이퍼드라이브 제어판', art: '🎛️', text: '세 개의 레버.', buttons: ['🚀 점프', '❄️ 냉각', '⚡ 충전'], solution: ['❄️ 냉각', '⚡ 충전', '🚀 점프'], result: 'out', hint: ['드로이드의 말.', '냉각 → 충전 → 점프'] },
      { key: 'out', type: 'item', end: true, title: '광속 점프!', art: '✨🚀', text: '별빛이 선으로 늘어나며 우주선이 하이퍼스페이스로 사라진다. 순찰대는 허탕!' },
    ],
  },
  {
    id: 'sw-hoth', box: '스타워즈', title: '얼음 행성 탈출', orig: 'Escape From Hoth', diff: 2, theme: '#a8c8e8',
    intro: '얼음 행성의 반란군 기지가 공격받는다! 거대한 4족 보행 병기가 다가온다. 마지막 수송선을 띄워 탈출하라.',
    cards: [
      { key: 'base', type: 'place', start: true, title: '얼음 기지 지휘실', art: '❄️🛰️🚨🧊', text: '경보! 방어막 발생기가 꺼졌다. 격납고 문은 얼어붙었다.',
        shows: ['shield', 'hangardoor'], spots: [{ label: '난방 장치', emoji: '♨️', x: 25, y: 70, reveal: 'heater' }, { label: '레이더', emoji: '📡', x: 75, y: 35, text: '레이더: 적 보행 병기 5기가 북쪽 2시 방향에서 접근 중.' }] },
      { key: 'shield', type: 'code', title: '방어막 발생기', art: '🛡️', text: '“재가동 코드 = 접근 중인 적 병기 수와 방향 시각.”', code: '52', result: 'shieldon', hint: ['레이더를 보세요.', '5기, 2시 → 52'] },
      { key: 'shieldon', type: 'item', title: '방어막 가동', art: '🛡️✨', text: '포격이 방어막에 막힌다! 시간을 벌었다.' },
      { key: 'hangardoor', type: 'red', title: '얼어붙은 격납고 문', art: '🧊🚪', text: '' },
      { key: 'heater', type: 'blue', title: '휴대용 히터', art: '♨️', text: '' },
      { key: 'hangar', type: 'place', from: ['hangardoor', 'heater'], discard: ['hangardoor', 'heater'], shows: ['transport'], title: '격납고', art: '🚀❄️', text: '문이 녹아 열렸다! 마지막 수송선이 대기 중. 조종사: “발사 순서는 엔진-방어막-이륙!”' },
      { key: 'transport', type: 'machine', title: '수송선 발사 패널', art: '🕹️', text: '세 버튼.', buttons: ['🛫 이륙', '🔥 엔진', '🛡️ 방어막'], solution: ['🔥 엔진', '🛡️ 방어막', '🛫 이륙'], result: 'out', hint: ['조종사의 말.', '엔진 → 방어막 → 이륙'] },
      { key: 'out', type: 'item', end: true, title: '탈출 성공', art: '🚀🌌', text: '수송선이 얼음 행성을 벗어난다. 반란군은 다음 기지에서 다시 모일 것이다.' },
    ],
  },
  {
    id: 'sw-jedha', box: '스타워즈', title: '제다의 비밀 임무', orig: 'Secret Mission on Jedha', diff: 3, theme: '#c8a878',
    intro: '사막의 성지 도시에 제국의 비밀 무기 정보가 숨겨져 있다. 반란군 첩보원이 되어 데이터 카드를 손에 넣어라.',
    cards: [
      { key: 'market', type: 'place', start: true, title: '성지 도시 시장', art: '🏜️🛕🛒👁️', text: '제국 순찰병이 거리를 누빈다. 눈먼 수도승이 사원 앞에서 기도문을 외운다.',
        shows: ['monk', 'temple'], spots: [{ label: '과일 가게', emoji: '🍈', x: 25, y: 65, reveal: 'robe' }, { label: '순찰병', emoji: '🪖', x: 75, y: 45, text: '순찰병 둘이 투덜거린다: “사원 비밀 금고 번호가 기도문의 행 수래.”' }] },
      { key: 'monk', type: 'item', title: '눈먼 수도승', art: '🧘', text: '“나는 포스와 하나, 포스는 나와 함께.” 수도승이 같은 기도문을 네 줄로 반복한다. 그의 염주 구슬 색: 초록, 파랑, 초록, 보라.' },
      { key: 'temple', type: 'red', title: '사원 입구', art: '🛕', text: '경비병: “순례자만 들어갈 수 있다.”' },
      { key: 'robe', type: 'blue', title: '순례자 망토', art: '🧥', text: '' },
      { key: 'inside', type: 'place', from: ['temple', 'robe'], discard: ['temple', 'robe'], shows: ['crystals', 'vault'], title: '사원 내부', art: '💎🕯️📜', text: '빛나는 크리스털이 박힌 제단과 비밀 금고.' },
      { key: 'crystals', type: 'machine', title: '크리스털 제단', art: '💎', text: '크리스털을 순서대로 만지면 제단이 열린다.', buttons: ['🟢', '🔵', '🟣', '🔴'], solution: ['🟢', '🔵', '🟢', '🟣'], result: 'datacard', hint: ['수도승의 염주 구슬 색.', '🟢 🔵 🟢 🟣'] },
      { key: 'datacard', type: 'item', title: '제단 속 홀로그램', art: '📽️', text: '홀로그램: “데이터 카드는 금고에. 금고 번호 = 기도문의 줄 수와 글자 수(띄어쓰기 빼고 첫 줄).”' },
      { key: 'vault', type: 'code', title: '비밀 금고', art: '🔐', text: '숫자 3자리.', code: '414', result: 'out', hint: ['기도문은 4줄. “나는포스와하나포스는나와함께”는 몇 글자?', '4 · 14 → 414'] },
      { key: 'out', type: 'item', end: true, title: '희망을 손에', art: '💾✨', text: '데이터 카드를 품고 도시를 빠져나왔다. 이 정보가 은하계의 희망이 될 것이다.' },
    ],
  },
];
