'use strict';
// 언락! — 인챈티드 어드벤처 (2025, 원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '인챈티드 어드벤처';
module.exports = [
  {
    id: 'kilea', box: B, title: '킬레아의 분노', orig: "Kilea's Wrath", diff: 1, theme: '#e8603a',
    intro: '낙원 같은 섬의 화산이 우르릉거린다. 불의 신 킬레아가 분노했다! 화산이 폭발해 섬을 삼키기 전에 신의 분노를 달래자.',
    cards: [
      { key: 'village', type: 'place', start: true, title: '해변 마을', art: '🏝️🌋🛖🌺', text: '화산에서 연기가 솟는다. 마을 장로가 외친다. “킬레아께 바칠 세 가지 제물이 필요하다 — 불의 꽃, 바다의 진주, 노래!” 마을 토템에 그림이 새겨져 있다.',
        shows: ['elder', 'totem'], spots: [{ label: '야자수 꼭대기', x: 80, y: 24, reveal: 'flower' }, { label: '조개 바구니', x: 24, y: 74, reveal: 'pearl' }] },
      { key: 'elder', type: 'item', title: '마을 장로', art: '👴', text: '“제물은 분화구 제단에 꽃 → 진주 → 노래 순서로 바쳐야 한다. 노래의 북장단은 토템에 새겨져 있지.”' },
      { key: 'totem', type: 'item', title: '마을 토템', art: '🗿', text: '토템의 북 그림: 둥 · 둥 · 탁 · 둥' },
      { key: 'flower', type: 'item', title: '불의 꽃', art: '🌺', text: '붉게 타오르는 꽃.' },
      { key: 'pearl', type: 'item', title: '바다의 진주', art: '🦪', text: '' },
      { key: 'path', type: 'place', title: '화산 오르는 길', art: '🌋🪨🔥', text: '용암이 흐르는 길. 끊어진 돌다리 앞에서 멈췄다.', shows: ['bridge'], spots: [{ label: '흑요석 바위', x: 70, y: 70, reveal: 'plank' }] },
      { key: 'bridge', type: 'red', title: '끊어진 돌다리', art: '🌉', text: '' },
      { key: 'plank', type: 'blue', title: '흑요석 판자', art: '⬛', text: '용암에도 타지 않는다.' },
      { key: 'crater', type: 'place', from: ['bridge', 'plank'], discard: ['bridge', 'plank'], shows: ['offering'], title: '분화구 제단', art: '🔥🗿🌋', text: '판자를 놓고 건넜다! 분화구 가장자리에 불의 신 킬레아의 석상과 제단.' },
      { key: 'offering', type: 'machine', title: '킬레아의 제단', art: '🔥', text: '제물을 바치고 북을 쳐라.', buttons: ['🌺 불의 꽃', '🦪 진주', '🥁 둥', '🪘 탁'], solution: ['🌺 불의 꽃', '🦪 진주', '🥁 둥', '🥁 둥', '🪘 탁', '🥁 둥'], result: 'out', hint: ['장로: 꽃 → 진주 → 노래. 노래는 토템의 북장단.', '🌺 → 🦪 → 둥 둥 탁 둥'] },
      { key: 'out', type: 'item', end: true, title: '불의 신이 잠들다', art: '🌋💤🌺', text: '북소리에 화산이 잠잠해지고, 분화구에서 무지개가 피어오른다. 킬레아가 미소 짓는 듯하다.' },
    ].map((c) => (c.key === 'elder' ? { ...c, shows: ['path'] } : c)),
  },
  {
    id: 'amusement', box: B, title: '놀이공원 대소동', orig: 'Frenzy at the Amusement Park', diff: 2, theme: '#e8a83a',
    intro: '마법 놀이공원의 최고 상품 “소원 트로피”를 차지하라! 그런데 놀이기구들이 마법에 걸려 제멋대로 움직인다. 미션 카드 세 장을 모두 깨고 트로피를 손에 넣자.',
    cards: [
      { key: 'plaza', type: 'place', start: true, title: '놀이공원 광장', art: '🎡🎢🎠🍿', text: '대관람차가 거꾸로 돌고, 회전목마 말들이 뛰어다닌다. 상품 부스에 반짝이는 트로피. 부스 직원이 미션 카드를 건넨다.',
        shows: ['mission', 'coaster', 'booth'], spots: [{ label: '팝콘 수레', x: 24, y: 66, reveal: 'token' }, { label: '대관람차', emoji: '🎡', x: 76, y: 32, text: '칸 번호가 거꾸로 지나간다: 8, 6, 4, 2…' }] },
      { key: 'mission', type: 'item', title: '미션 카드', art: '🎫', text: '“① 롤러코스터 완주 ② 사격장 만점 ③ 대관람차 정지 — 셋 다 깨면 트로피 부스 금고 비밀번호를 드려요!”' },
      { key: 'booth', type: 'item', title: '상품 부스', art: '🏆', text: '금고 속 소원 트로피. 금고 비밀번호는 미션을 깨면 알려 준다고.' },
      { key: 'coaster', type: 'red', title: '롤러코스터 탑승구', art: '🎢', text: '“토큰을 넣으세요.”' },
      { key: 'token', type: 'blue', title: '탑승 토큰', art: '🪙', text: '' },
      { key: 'ride', type: 'item', from: ['coaster', 'token'], discard: ['coaster', 'token'], shows: ['shooting'], title: '미션 ① 완료!', art: '🎢✅', text: '으아아아! 완주했다. 내리면서 탑승 사진 번호를 받았다: 사진 속 당신 옆 좌석 번호 “3”. 코스터 끝에 사격장이 있다.' },
      { key: 'shooting', type: 'place', title: '사격장', art: '🎯🔫🧸', text: '움직이는 오리 과녁. 사격장 주인: “노란 오리 → 파란 오리 → 빨간 오리 순서로 맞혀야 만점!” 그런데 장난감 총에 코르크 총알이 없다.',
        shows: ['gun'], spots: [{ label: '곰인형 선반', x: 72, y: 36, reveal: 'cork' }] },
      { key: 'gun', type: 'red', title: '장난감 총', art: '🔫', text: '' },
      { key: 'cork', type: 'blue', title: '코르크 총알', art: '🍾', text: '' },
      { key: 'shoot', type: 'machine', from: ['gun', 'cork'], discard: ['gun', 'cork'], title: '사격', art: '🎯', text: '과녁을 순서대로!', buttons: ['🔴 빨간 오리', '🟡 노란 오리', '🔵 파란 오리'], solution: ['🟡 노란 오리', '🔵 파란 오리', '🔴 빨간 오리'], result: 'shot', hint: ['사격장 주인이 말한 순서.', '노랑 → 파랑 → 빨강'] },
      { key: 'shot', type: 'item', title: '미션 ② 만점!', art: '🎯✅', shows: ['wheel'], text: '만점! 상품으로 받은 곰인형 배에 숫자 “7”이 수놓여 있다. 이제 대관람차를 세우자.' },
      { key: 'wheel', type: 'code', title: '대관람차 정지 레버', art: '🎡', text: '관리 상자: “비상 정지 코드 = 칸 번호를 올바른 순서로(작은 수부터).”', code: '2468', result: 'stopped', hint: ['광장에서 본 대관람차 칸 번호.', '2 · 4 · 6 · 8 → 2468'] },
      { key: 'stopped', type: 'item', title: '미션 ③ 완료!', art: '🎡✅', shows: ['safe'], text: '대관람차가 멈췄다! 부스 직원: “축하해요! 금고 비밀번호는 미션에서 받은 숫자 둘을 이어서, 그리고 미션 수(3)를 붙여요.”' },
      { key: 'safe', type: 'code', title: '트로피 금고', art: '🔐', text: '숫자 3자리.', code: '373', result: 'out', hint: ['코스터 사진의 좌석 번호, 곰인형의 숫자, 그리고 미션 수.', '3 · 7 · 3 → 373'] },
      { key: 'trap1', type: 'trap', from: ['gun', 'token'], title: '총이 막혔다', text: '토큰을 총에 넣었다가 꽉 끼어 버렸다. 빼느라 한참 걸렸다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '소원 트로피!', art: '🏆✨', text: '트로피를 높이 들자 폭죽이 터지고, 마법에 걸린 놀이기구들이 얌전해진다. 무슨 소원을 빌까?' },
    ],
  },
  {
    id: 'camelot', box: B, title: '카멜롯의 저주', orig: 'The Curse on Camelot', diff: 3, theme: '#5a5ab8',
    intro: '마녀 모르가나의 저주로 펜드래건 왕국이 시들었다. 기사들은 돌이 되고, 엑스칼리버는 사라졌다. 장대한 모험을 떠나 카멜롯의 영광을 되찾자!',
    cards: [
      { key: 'hall', type: 'place', start: true, title: '원탁의 방', art: '🛡️🗿🗿🗡️', text: '돌이 된 기사들. 아서 왕의 자리만 비어 있다. 탁자 위 기사 이름표, 벽에 태피스트리.',
        shows: ['names', 'tower'], spots: [{ label: '아서 왕의 의자', x: 50, y: 62, reveal: 'scabbard' }, { label: '벽 태피스트리', emoji: '🧵', x: 80, y: 28, text: '엑스칼리버가 호수에서 떠오르는 그림. 칼집에 별 셋.' }] },
      { key: 'names', type: 'item', title: '기사 이름표', art: '📛', text: '시계 방향 순서: 랜슬롯, 가웨인, 퍼시벌, 갤러해드.' },
      { key: 'tower', type: 'red', title: '멀린의 탑 문', art: '🗼', text: '“칼집을 가진 자만 들어오라.”' },
      { key: 'scabbard', type: 'blue', title: '엑스칼리버의 칼집', art: '🗡️', text: '칼은 없고 칼집만. 별 세 개가 박혀 있다.' },
      { key: 'merlin', type: 'place', from: ['tower', 'scabbard'], discard: ['tower'], shows: ['book', 'cauldron'], title: '멀린의 탑', art: '🧙‍♂️📚🦉', text: '멀린은 없고 부엉이만 있다. 마법서와 끓는 솥.' },
      { key: 'book', type: 'item', title: '멀린의 마법서', art: '📖', text: '“돌의 저주를 푸는 물약: 기사들의 이름 첫 글자를 원탁 순서대로 솥에 외치고, 칼집의 별 수만큼 저어라. 엑스칼리버는 호수의 여인에게 — 호수로 가는 길은 기사들이 안다.”' },
      { key: 'cauldron', type: 'machine', title: '마법의 솥', art: '🫕', text: '글자 버튼.', buttons: ['가', '갤', '랜', '퍼'], solution: ['랜', '가', '퍼', '갤'], result: 'stir', hint: ['이름표의 원탁 순서, 첫 글자만.', '랜 → 가 → 퍼 → 갤'] },
      { key: 'stir', type: 'code', title: '솥 젓개 다이얼', art: '🥄', text: '“몇 번 저을까?” 숫자 1자리.', code: '3', result: 'knights', hint: ['칼집의 별 수.', '3'] },
      { key: 'knights', type: 'item', title: '깨어난 기사들', art: '⚔️🛡️', shows: ['lake'], text: '물약 연기에 기사들이 깨어났다! 퍼시벌: “호수의 여인은 안개 낀 아발론 호수에 계시오. 배를 타려면 성배의 문양을 보여야 하지.”' },
      { key: 'lake', type: 'place', title: '아발론 호수', art: '🌫️🌊🛶', text: '짙은 안개 속 작은 배. 배에 문양 자물쇠: 성배, 검, 왕관, 장미. 뱃머리에 새겨진 시: “왕관 아래 검, 검 아래 장미, 성배는 모든 것 위에.”',
        shows: ['boatlock'], spots: [{ label: '갈대숲', x: 24, y: 70, reveal: 'grail' }] },
      { key: 'grail', type: 'item', title: '성배 그림 방패', art: '🏆🛡️', text: '갈대 사이에 걸린 방패. 성배 그림이 그려져 있다.' },
      { key: 'boatlock', type: 'machine', title: '배의 문양 자물쇠', art: '🛶', text: '위에서부터 문양을 차례로.', buttons: ['🌹 장미', '⚔️ 검', '👑 왕관', '🏆 성배'], solution: ['🏆 성배', '👑 왕관', '⚔️ 검', '🌹 장미'], result: 'lady', hint: ['성배가 가장 위, 그 아래 왕관, 검, 장미.', '🏆 → 👑 → ⚔️ → 🌹'] },
      { key: 'lady', type: 'place', title: '호수의 여인', art: '🧝‍♀️🗡️🌊', text: '물속에서 손이 솟아 엑스칼리버를 든다. 여인: “칼집을 가져온 자에게만 칼을 돌려주겠다.”', shows: ['sword'] },
      { key: 'sword', type: 'red', title: '호수 위의 엑스칼리버', art: '🗡️✨', text: '' },
      { key: 'out', type: 'item', from: ['sword', 'scabbard'], end: true, title: '카멜롯의 영광', art: '⚔️👑', text: '엑스칼리버가 칼집에 꽂히는 순간, 모르가나의 저주가 산산이 흩어진다. 펜드래건 왕국에 다시 꽃이 핀다!' },
      { key: 'trap1', type: 'trap', from: ['tower', 'scabbard'], title: '', text: '', penalty: 1 },
    ].filter((c) => c.key !== 'trap1'),
  },
];
