'use strict';
// 언락! — 에픽 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '에픽 어드벤처';
module.exports = [
  {
    id: 'werewolf', box: B, title: '일곱 번째 상영 — 늑대인간의 마지막 밤', orig: 'The Seventh Screening', diff: 1, theme: '#4a5a7a',
    intro: '낡은 극장에서 흑백 공포 영화 「늑대인간의 마지막 밤」 시사회가 열린다. 일곱 번째 상영이 시작되자 스크린 속으로 빨려 들어갔다! 영화의 결말을 바꿔야 극장으로 돌아올 수 있다.',
    cards: [
      { key: 'lobby', type: 'place', start: true, title: '극장 로비', art: '🎞️🍿🎟️🚪', text: '빛바랜 영화 포스터, 팝콘 기계, “관계자 외 출입 금지” 영사실 문.',
        shows: ['poster', 'projdoor'], spots: [{ label: '팝콘 기계 아래', x: 70, y: 78, reveal: 'stub' }] },
      { key: 'poster', type: 'item', title: '영화 포스터', art: '🐺🌕', text: '「늑대인간의 마지막 밤」 — 저택을 공포에 떨게 하는 유령의 정체는? 오늘 상영: 1회 13시 … 7회 23시 15분 (마지막!)' },
      { key: 'stub', type: 'item', title: '찢어진 입장권', art: '🎟️', text: '“7회 상영 — 영사실 비밀번호는 상영 시각 4자리” 라고 영사기사가 뒤에 휘갈겨 썼다.' },
      { key: 'projdoor', type: 'code', title: '영사실 문', art: '🔢', text: '숫자 4자리.', code: '2315', result: 'booth', hint: ['포스터와 입장권 메모를 함께.', '7회 23시 15분 → 2315'] },
      { key: 'booth', type: 'place', title: '영사실', art: '📽️🎞️🕸️', text: '먼지 쌓인 영사기. 필름 통 하나가 비어 있다.', shows: ['projector'], spots: [{ label: '필름 선반', x: 24, y: 40, reveal: 'reel' }] },
      { key: 'projector', type: 'red', title: '영사기', art: '📽️', text: '' },
      { key: 'reel', type: 'blue', title: '7번 필름 릴', art: '🎞️', text: '“일곱 번째 상영 전용 — 절대 틀지 말 것”' },
      { key: 'manor', type: 'place', from: ['projector', 'reel'], discard: ['projector', 'reel'], shows: ['notes', 'cabinet'], title: '흑백 영화 속 저택', art: '🏰🌕🐺⚗️', text: '필름을 거는 순간 세상이 흑백으로! 영화 속 저택의 의사가 늑대인간으로 변해 가고 있다. 자정까지 해독제를 만들어야 영화가 해피 엔딩이 된다.',
        spots: [{ label: '은 쟁반', x: 26, y: 70, reveal: 'key' }, { label: '창밖 달', emoji: '🌕', x: 80, y: 20, text: '시계탑이 11번 울렸다.' }] },
      { key: 'notes', type: 'item', title: '의사의 연구 노트', art: '📓', text: '“저주를 푸는 약: 투구꽃, 은가루, 늑대 털. 넣는 순서가 중요하다 — 독 → 금속 → 짐승.”' },
      { key: 'cabinet', type: 'red', title: '잠긴 약장', art: '🗄️', text: '' },
      { key: 'key', type: 'blue', title: '약장 열쇠', art: '🗝️', text: '' },
      { key: 'brew', type: 'machine', from: ['cabinet', 'key'], discard: ['cabinet', 'key'], title: '조제대', art: '⚗️', text: '약장 속 재료 셋을 솥에 넣자.', buttons: ['🐺 늑대 털', '🌿 투구꽃', '🥈 은가루'], solution: ['🌿 투구꽃', '🥈 은가루', '🐺 늑대 털'], result: 'potion', hint: ['노트: 독 → 금속 → 짐승.', '투구꽃 → 은가루 → 늑대 털'] },
      { key: 'potion', type: 'code', title: '해독제 병 마개', art: '🧪', text: '마개에 숫자 2자리 자물쇠: “마지막으로 울린 종소리 수 + 1”', code: '12', result: 'out', hint: ['창밖 시계탑이 몇 번 울렸죠?', '11 + 1 = 12'] },
      { key: 'trap1', type: 'trap', from: ['cabinet', 'reel'], title: '필름이 엉켰다', text: '필름 릴로 약장을 비틀다 필름이 줄줄 풀려 버렸다. 감느라 시간이 흘렀다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: 'THE END', art: '🎬🌅', text: '자정 종과 함께 의사가 사람으로 돌아왔다. 화면에 “THE END”가 떠오르고, 정신을 차려 보니 극장 의자. 관객들의 박수가 쏟아진다.' },
    ],
  },
  {
    id: 'dragon7', box: B, title: '용의 일곱 시험', orig: "The Dragon's Seven Tests", diff: 2, theme: '#b83a2a',
    intro: '7년에 한 번, 리 사부가 황금 용의 사원 문을 연다. 제자가 되려면 하루 안에 일곱 가지 시험을 모두 통과해야 한다!',
    cards: [
      { key: 'gate', type: 'place', start: true, title: '황금 용의 사원 정문', art: '⛩️🐉🏮🏮', text: '붉은 등 일곱 개가 걸린 정문. 리 사부: “첫 번째 시험 — 문을 열어라.” 문에 숫자 자물쇠. 등마다 한자 숫자가 쓰여 있다: 一, 七, 四, 九 (나머지는 꺼져 있다).',
        shows: ['gatelock', 'scroll'], spots: [{ label: '돌사자 입', x: 18, y: 66, reveal: 'brush' }] },
      { key: 'scroll', type: 'item', title: '사부의 두루마리', art: '📜', text: '“일곱 시험: 문, 붓, 차, 저울, 수수께끼, 잉어, 용의 불. 첫 시험의 답은 켜진 등의 숫자를 큰 순서대로.”' },
      { key: 'gatelock', type: 'code', title: '첫째 시험: 정문', art: '🔢', text: '숫자 4자리.', code: '9741', result: 'court', hint: ['켜진 등: 一 七 四 九. 큰 순서대로!', '9 · 7 · 4 · 1 → 9741'] },
      { key: 'court', type: 'place', title: '사원 안뜰', art: '🏯🖌️🍵⚖️', text: '서예 탁자, 차 도구, 커다란 저울이 놓여 있다. 제자들이 지켜본다.',
        shows: ['paper', 'kettle', 'scale'], spots: [{ label: '차 상자', x: 50, y: 74, reveal: 'leaves' }] },
      { key: 'brush', type: 'blue', title: '용 수염 붓', art: '🖌️', text: '' },
      { key: 'paper', type: 'red', title: '둘째 시험: 빈 화선지', art: '📄', text: '“마음을 담아 한 획을 그어라.”' },
      { key: 'callig', type: 'item', from: ['paper', 'brush'], discard: ['paper', 'brush'], title: '한 획의 글씨', art: '🖋️', text: '붓을 대자 화선지에 저절로 글씨가 떠오른다: “저울은 무거운 것부터 내려놓아라. 쇠 > 돌 > 나무 > 깃털.” 둘째 시험 통과!' },
      { key: 'kettle', type: 'red', title: '셋째 시험: 끓는 주전자', art: '🫖', text: '“차 한 잔으로 마음을 보여라.”' },
      { key: 'leaves', type: 'blue', title: '용정차 잎', art: '🍃', text: '' },
      { key: 'tea', type: 'item', from: ['kettle', 'leaves'], discard: ['kettle', 'leaves'], title: '향긋한 차', art: '🍵', text: '사부가 차를 마시고 고개를 끄덕인다. “셋째 시험 통과. 찻잔 바닥을 보아라.” — 바닥에 새겨진 글: “아침엔 네 발, 낮엔 두 발, 저녁엔 세 발.”' },
      { key: 'scale', type: 'machine', title: '넷째 시험: 저울', art: '⚖️', text: '추 네 개를 순서대로 내려놓아 저울을 맞춰라.', buttons: ['🪶 깃털', '🪵 나무', '🪨 돌', '⚙️ 쇠'], solution: ['⚙️ 쇠', '🪨 돌', '🪵 나무', '🪶 깃털'], result: 'riddle', hint: ['둘째 시험(서예)의 글씨가 알려 줘요.', '쇠 → 돌 → 나무 → 깃털'] },
      { key: 'riddle', type: 'code', title: '다섯째 시험: 수수께끼', art: '❓', text: '“찻잔 바닥의 존재는 무엇인가? 대답 대신 세 때의 발 수를 이어 말하라.”', code: '423', result: 'pond', hint: ['답은 사람(아기 → 어른 → 지팡이 짚은 노인).', '4 · 2 · 3 → 423'] },
      { key: 'pond', type: 'place', title: '잉어 연못', art: '🎏🌊🪷', text: '여섯째 시험. 연못의 잉어들이 용문을 향해 뛰어오를 순서를 기다린다. 연못가 비석: “가장 붉은 것이 먼저, 가장 흰 것이 마지막. 금빛은 검은 것보다 먼저.”',
        shows: ['koi'], spots: [{ label: '연잎 아래', x: 72, y: 70, reveal: 'shield' }] },
      { key: 'koi', type: 'machine', title: '여섯째 시험: 잉어의 용문', art: '🐟', text: '잉어를 순서대로 뛰어오르게 하라.', buttons: ['⚪ 흰 잉어', '⚫ 검은 잉어', '🔴 붉은 잉어', '🟡 금빛 잉어'], solution: ['🔴 붉은 잉어', '🟡 금빛 잉어', '⚫ 검은 잉어', '⚪ 흰 잉어'], result: 'cave', hint: ['비석: 붉은 것 먼저, 흰 것 마지막, 금빛이 검은 것보다 먼저.', '🔴 → 🟡 → ⚫ → ⚪'] },
      { key: 'cave', type: 'place', title: '일곱째 시험: 용의 동굴', art: '🐉🔥🌋', text: '황금 용이 불을 뿜는다. “불길을 지나 내 앞에 서라.”', shows: ['flame'] },
      { key: 'flame', type: 'red', title: '용의 불길', art: '🔥', text: '맨몸으로는 지날 수 없다.' },
      { key: 'shield', type: 'blue', title: '용비늘 방패', art: '🛡️', text: '' },
      { key: 'out', type: 'item', from: ['flame', 'shield'], end: true, title: '리 사부의 제자', art: '🐉👑', text: '방패로 불길을 가르고 용 앞에 섰다. 용이 고개를 숙이고, 리 사부가 미소 짓는다. “일곱 시험을 모두 마쳤구나. 오늘부터 너는 나의 제자다.”' },
      { key: 'trap1', type: 'trap', from: ['kettle', 'brush'], title: '먹물 차?', text: '붓을 주전자에 담갔더니 차가 새까매졌다. 다시 끓이느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['flame', 'leaves'], title: '활활!', text: '찻잎이 불에 타올라 연기만 자욱해졌다.', penalty: 1 },
    ],
  },
  {
    id: 'mission07', box: B, title: '미션 #07', orig: 'Mission #07', diff: 3, theme: '#2a4a6a',
    intro: '1965년 홍콩. 비밀 요원 07이 되어 국제 범죄 조직 “흑룡”의 보스가 숨긴 마이크로필름을 빼내라. 이 메시지는 5초 후 자동 삭제된다.',
    cards: [
      { key: 'hotel', type: 'place', start: true, title: '페닌슐라 호텔 객실', art: '🏨🕶️💼🌃', text: '본부에서 보낸 서류 가방이 도착했다. 창밖 항구에 흑룡의 정크선 카지노 “골든 로터스”가 떠 있다.',
        shows: ['briefcase', 'briefing'], spots: [{ label: '꽃병', x: 22, y: 60, reveal: 'pen' }] },
      { key: 'briefing', type: 'item', title: '작전 지령서', art: '📄', text: '“목표: 골든 로터스 3층 보스 집무실 금고 속 마이크로필름. 서류 가방 비밀번호는 너의 요원 번호 앞에 0을 두 개.”' },
      { key: 'briefcase', type: 'code', title: '서류 가방', art: '💼', text: '숫자 4자리.', code: '0007', result: 'gadgets', hint: ['지령서: 요원 번호 07 앞에 0 두 개.', '0007'] },
      { key: 'gadgets', type: 'item', title: '본부의 장비', art: '⌚🪞📸', shows: ['mirror', 'invite'], text: '레이저 시계(배터리 없음 — 가방에 넣어 둠), 콤팩트 거울, 초소형 카메라, 그리고 카지노 초대장.' },
      { key: 'pen', type: 'blue', title: '만년필형 수면가스', art: '🖊️', text: '뚜껑을 돌리면 수면가스가 나온다.' },
      { key: 'invite', type: 'item', title: '카지노 초대장', art: '✉️', shows: ['casino'], text: '“골든 로터스 — 오늘 밤 9시. 드레스 코드: 검정.”' },
      { key: 'casino', type: 'place', title: '골든 로터스 카지노 (1층)', art: '🎰🎲🍸🎻', text: '룰렛, 마작 테이블, 재즈 밴드. 2층 계단을 덩치 큰 경비원이 막고 있다. 피아니스트는 같은 곡만 친다: 미-레-도-레-미-미-미.',
        shows: ['guard', 'roulette'], spots: [{ label: '마작 테이블', x: 30, y: 70, reveal: 'chip' }] },
      { key: 'roulette', type: 'item', title: '룰렛 테이블', art: '🎡', text: '딜러가 속삭인다: “보스는 늘 같은 숫자에만 걸지. 빨강 9, 검정 4.”' },
      { key: 'guard', type: 'red', title: '2층 경비원', art: '💂', text: '“VIP만 올라갈 수 있습니다.”' },
      { key: 'floor2', type: 'place', from: ['guard', 'pen'], discard: ['guard', 'pen'], shows: ['laser', 'portrait'], title: '2층 복도', art: '🚨🖼️🚪', text: '경비원이 쿨쿨 잠들었다. 3층 계단 앞에 레이저 경보 장치. 벽에 보스의 초상화.',
        spots: [{ label: '소화기 상자', x: 82, y: 72, reveal: 'battery' }] },
      { key: 'portrait', type: 'item', title: '보스의 초상화', art: '🖼️', text: '흑룡 보스가 훈장 4개를 달고 있다. 액자 아래: “1958년 조직 창설”. 보스는 “메리의 작은 양” 노래를 좋아한다고 한다.' },
      { key: 'laser', type: 'red', title: '레이저 경보', art: '🔴〰️', text: '빛줄기를 꺾을 수 있다면…' },
      { key: 'mirror', type: 'blue', title: '콤팩트 거울', art: '🪞', text: '' },
      { key: 'floor3', type: 'place', from: ['laser', 'mirror'], discard: ['laser', 'mirror'], shows: ['safe1'], title: '3층 보스 집무실', art: '🗄️🐉📞', text: '거울로 레이저를 비켜 들어왔다. 벽 금고는 음악 키패드 + 숫자 다이얼 이중 잠금.' },
      { key: 'watch', type: 'red', title: '레이저 시계', art: '⌚', text: '배터리 칸이 비어 있다.' },
      { key: 'battery', type: 'blue', title: '소형 배터리', art: '🔋', text: '' },
      { key: 'chip', type: 'item', title: 'VIP 칩', art: '🪙', text: '보스의 VIP 칩. 용 문양이 새겨져 있다. 쓸모는 없어 보이지만 기념으로 챙겼다.' },
      { key: 'safe1', type: 'machine', title: '금고 1단계: 음악 키패드', art: '🎼', text: '“보스가 좋아하는 노래의 첫 소절을 연주하시오.”', buttons: ['도', '레', '미', '파', '솔'], solution: ['미', '레', '도', '레', '미', '미', '미'], result: 'safe2', hint: ['1층 피아니스트가 같은 곡을 치고 있었어요.', '미 레 도 레 미 미 미'] },
      { key: 'safe2', type: 'code', title: '금고 2단계: 숫자 다이얼', art: '🔢', text: '“조직 창설 연도의 뒤 두 자리 × 훈장 수.”', code: '232', result: 'film', hint: ['초상화를 보세요.', '58 × 4 = 232'] },
      { key: 'film', type: 'item', title: '마이크로필름', art: '🎞️', text: '금고 속 마이크로필름 확보! 그 순간 경보가 울리고 집무실 문이 쇠창살로 잠긴다. 창밖은 항구 — 탈출할 길은 창뿐인데 방탄유리다.' },
      { key: 'cutter', type: 'machine', from: ['watch', 'battery'], discard: ['watch', 'battery'], title: '충전된 레이저 시계', art: '⌚🔴', text: '레이저로 유리에 원을 그려 잘라 내자. 시계 다이얼 방향을 순서대로: 룰렛 딜러가 말한 보스의 숫자를 시계 방향 위치로!', buttons: ['12시', '3시', '6시', '9시', '4시'], solution: ['9시', '4시'], result: 'out', hint: ['룰렛 딜러: 빨강 9, 검정 4.', '9시 → 4시'] },
      { key: 'trap1', type: 'trap', from: ['laser', 'battery'], title: '경보 직전!', text: '배터리를 레이저에 대자 불꽃이 튀었다. 경보가 울리기 직전 손을 뗐다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['watch', 'mirror'], title: '눈부셔!', text: '거울에 시계 불빛이 반사돼 눈이 멀 뻔했다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '임무 완수', art: '🕶️🚤', text: '유리창을 잘라 항구로 뛰어내리자 본부의 쾌속정이 기다리고 있었다. 미션 #07 — 완료.' },
    ].map((c) => (c.key === 'film' ? { ...c, shows: ['watch'], text: c.text + ' 가방 속 레이저 시계를 꺼냈다 — 배터리만 있으면!' } : c)),
  },
];
