'use strict';
// 언락! — 입문 + 이스케이프 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)
// 카드 키 이름으로 쓰고 번호는 build.js 가 자동으로 붙인다.
// spots: reveal 이 있으면 그림 속 숨은 번호(작은 숫자), click:true 면 눌러서 찾는 지점.

module.exports = [
  {
    id: 'tutorial', box: '입문', title: '첫 번째 방', orig: 'Tutorial', diff: 0, theme: '#6a8aa8', limit: 20, decoys: 1,
    intro: '눈을 떠 보니 낯선 서재. 문은 잠겨 있다. 언락의 기본을 배워 봐요!',
    cards: [
      { key: 'room', type: 'place', start: true, title: '작은 서재', art: '📚🪑🕰️🚪', text: '책장과 낡은 의자, 멈춘 괘종시계. 장소 카드에 보이는 번호의 카드는 바로 나와요. 🔍 동그라미는 눌러서 살펴보고, 그림 속에 작게 숨은 숫자는 오른쪽 위 칸에 입력해서 가져와요!',
        shows: ['chest'], spots: [{ label: '화분', emoji: '🪴', x: 18, y: 62, reveal: 'key', click: true }, { label: '책장', emoji: '📚', x: 72, y: 30, text: '먼지 쌓인 요리책뿐이다.' }, { label: '시계 아래', x: 56, y: 82, reveal: 'clock' }],
        hint: ['🪴 동그라미를 눌러 보세요. 그리고 시계 아래쪽을 아주 자세히 보세요 — 작은 숫자가 있어요.', '시계 아래 숨은 숫자를 “번호로 카드 가져오기”에 입력하세요.'] },
      { key: 'chest', type: 'red', title: '잠긴 나무 상자', art: '🧰', text: '작은 자물쇠가 달려 있다. 빨간 번호는 파란 번호와 합칠 수 있어요 — 두 번호의 합이 새 카드!' },
      { key: 'key', type: 'blue', title: '작은 열쇠', art: '🗝️', text: '녹슨 작은 열쇠.' },
      { key: 'note', type: 'item', from: ['chest', 'key'], title: '상자 속 쪽지', art: '📜', discard: ['chest', 'key'], shows: ['safe'], text: '“금고 비밀번호는 시계가 멈춘 시각.” 상자 바닥에 금고 그림이 있다. (다 쓴 카드는 이렇게 버려져요)' },
      { key: 'clock', type: 'item', title: '괘종시계', art: '🕰️', text: '그림 속 숨은 번호를 찾았군요! 시계는 9시 15분에 멈춰 있다.' },
      { key: 'safe', type: 'code', title: '벽 금고', art: '🔐', text: '숫자 4자리 금고. 노란 카드는 코드를 입력해요. (틀리면 벌점 3분!)', code: '0915', result: 'panel', hint: ['쪽지와 시계를 함께 보세요.', '9시 15분 → 0915'] },
      { key: 'panel', type: 'machine', title: '문 패널', art: '🚪', text: '금고 안 메모: “무지개 순서로 색을 누르면 문이 열린다.” 초록 카드는 장치 — 버튼을 차례로 누르고 작동!', buttons: ['🔵', '🟢', '🔴', '🟡'], solution: ['🔴', '🟡', '🟢', '🔵'], result: 'out', hint: ['무지개는 빨주노초파남보.', '🔴 🟡 🟢 🔵'] },
      { key: 'out', type: 'item', end: true, title: '문이 열렸다!', art: '🌅', text: '첫 번째 방 탈출 성공! 이제 진짜 모험을 떠나 볼까요?' },
    ],
  },


  // ───────────── 이스케이프 어드벤처 ─────────────
  {
    id: 'formula', box: '이스케이프 어드벤처', title: '포뮬러', orig: 'The Formula', diff: 2, theme: '#3a9a8a',
    intro: '실종된 H 박사가 비밀 연구소에 숨긴 만능 혈청 “포뮬러”. 경쟁 조직보다 먼저 연구소에 잠입해 혈청을 손에 넣고 빠져나와라!',
    cards: [
      { key: 'corridor', type: 'place', start: true, title: '연구소 지하 복도', art: '🚪🧯📋🪴', text: '정면에 실험실 보안문, 왼쪽에 경비실 문, 고장 난 엘리베이터. 벽에 소화기 점검표.',
        shows: ['guarddoor', 'extinguisher', 'secdoor', 'elevator'], spots: [{ label: '화분 그늘', x: 84, y: 70, reveal: 'bolt' }, { label: '안내도', emoji: '🗺️', x: 40, y: 28, text: '지하 1층: 복도 → 실험실 → 저온 보관실. 박사의 서재는 실험실 안쪽. 비상계단은 주차장으로.' }, { label: '쓰레기통', emoji: '🗑️', x: 62, y: 80, text: '빈 커피 컵과 구겨진 출입 기록지뿐.' }] },
      { key: 'elevator', type: 'item', title: '고장 난 엘리베이터', art: '🛗', text: '“점검 중 — 비상시 비상계단 이용”. 비상계단 문은 실험실 봉쇄와 연동돼 있다고 적혀 있다.' },
      { key: 'guarddoor', type: 'red', title: '경비실 문', art: '🚪', text: '체인 자물쇠가 걸려 있다.' },
      { key: 'bolt', type: 'blue', title: '볼트 커터', art: '✂️', text: '화분 뒤에 누가 숨겨 두었다.' },
      { key: 'extinguisher', type: 'item', title: '소화기 점검표', art: '🧯', text: '점검 기록: 9월 2일 ✔ · 10월 15일 ✔ · 11월 24일 ✔ (최근)' },
      { key: 'guardroom', type: 'place', from: ['guarddoor', 'bolt'], discard: ['guarddoor'], shows: ['locker', 'monitor', 'logbook'], title: '경비실', art: '📺🗄️☕🔦', text: '체인을 끊고 들어왔다. CCTV 모니터, 경비 사물함, 근무 일지. 식은 커피가 놓여 있다.',
        spots: [{ label: '책상 서랍', x: 22, y: 74, reveal: 'lockerkey' }, { label: '충전기 거치대', x: 80, y: 30, reveal: 'flashlight' }] },
      { key: 'logbook', type: 'item', title: '근무 일지', art: '📔', text: '“보안문 비밀번호는 매주 바뀐다: 이번 주 = 소화기 최근 점검일(월·일). 카메라: 복도 CAM1 · 보관실 CAM2 · 실험실 CAM3 · 서재 CAM4. 순찰은 복도 → 보관실 → 실험실 순서.”' },
      { key: 'monitor', type: 'machine', title: 'CCTV 모니터', art: '📺', text: '카메라 버튼 넷. 순찰 순서대로 화면을 돌려 보자.', buttons: ['CAM1', 'CAM2', 'CAM3', 'CAM4'], solution: ['CAM1', 'CAM2', 'CAM3'], result: 'cctv', hint: ['근무 일지에 카메라 배치와 순찰 순서가 있어요.', 'CAM1 → CAM2 → CAM3'] },
      { key: 'cctv', type: 'item', title: 'CCTV 녹화', art: '🎞️', text: '실험실 화면: 경쟁 조직 요원 둘이 환기구로 빠져나가며 무언가를 터뜨렸다 — 실험실에 노란 가스가 가득! 보관실 화면엔 냉동고 온도 표시가 비친다: 1번 -18 · 2번 -25 · 3번 -40 · 4번 -86.' },
      { key: 'locker', type: 'red', title: '경비 사물함', art: '🔒', text: '' },
      { key: 'lockerkey', type: 'blue', title: '사물함 열쇠', art: '🗝️', text: '' },
      { key: 'flashlight', type: 'blue', title: '손전등', art: '🔦', text: '배터리는 충분하다.' },
      { key: 'lockerOpen', type: 'item', from: ['locker', 'lockerkey'], discard: ['locker', 'lockerkey'], shows: ['badge', 'gasmask'], title: '열린 사물함', art: '🗄️', text: '방독면 하나와 박사의 신분증이 들어 있다.' },
      { key: 'badge', type: 'item', title: 'H 박사 신분증', art: '🪪', text: 'Dr. H. 하르트만 — 수석 연구원. 생년월일 1958. 07. 21' },
      { key: 'gasmask', type: 'blue', title: '방독면', art: '😷', text: '' },
      { key: 'secdoor', type: 'code', title: '실험실 보안문', art: '🔢', text: '숫자 4자리 키패드.', code: '1124', result: 'lab', hint: ['경비실 근무 일지가 규칙을 알려 줘요.', '가장 최근 점검일 11월 24일 → 1124'] },
      { key: 'lab', type: 'place', title: '실험실', art: '🧪🔬🖥️⚗️', text: '문이 열리자 노란 신경가스가 밀려 나온다! 숨을 참은 채로는 오래 버틸 수 없다.', shows: ['gascloud'] },
      { key: 'gascloud', type: 'red', title: '신경가스', art: '🌫️', text: '방독면 없이는 한 걸음도 들어갈 수 없다.' },
      { key: 'masked', type: 'item', from: ['gascloud', 'gasmask'], discard: ['gascloud'], shows: ['whiteboard', 'centrifuge', 'computer', 'studydoor', 'cabinet'], title: '실험실 안으로', art: '😷🧪', text: '방독면을 쓰고 들어갔다. 실험대, 원심분리기, 컴퓨터, 잠긴 시약장. 안쪽에 “서재” 문.', spots: [{ label: '실험대 아래', x: 70, y: 70, reveal: 'cabinetkey' }] },
      { key: 'whiteboard', type: 'item', title: '화이트보드', art: '📋', text: '“시약을 원심분리 → 층이 나뉜다. 저온 보관실 문은 아래층 색부터 차례로!” 구석에: “컴퓨터 암호 = 내 생일(월일)”' },
      { key: 'cabinet', type: 'red', title: '잠긴 시약장', art: '🗄️', text: '작은 열쇠 구멍.' },
      { key: 'cabinetkey', type: 'blue', title: '시약장 열쇠', art: '🔑', text: '' },
      { key: 'reagents', type: 'item', from: ['cabinet', 'cabinetkey'], discard: ['cabinet', 'cabinetkey'], shows: ['vial'], title: '시약장 안', art: '🧴', text: '라벨이 붙은 시약 병들. “포뮬러 원료 — 원심분리 필수” 시험관 하나.' },
      { key: 'centrifuge', type: 'red', title: '원심분리기', art: '🌀', text: '시험관 칸이 비어 있다.' },
      { key: 'vial', type: 'blue', title: '원료 시험관', art: '🧪', text: '탁한 액체.' },
      { key: 'spun', type: 'item', from: ['centrifuge', 'vial'], discard: ['centrifuge', 'vial'], shows: ['cryodoor'], title: '분리된 시약', art: '🟨🟩🟪', text: '시약이 세 층으로 나뉘었다. 위에서부터 노랑, 초록, 보라.' },
      { key: 'cryodoor', type: 'machine', title: '저온 보관실 문 패널', art: '❄️🚪', text: '색 버튼 넷.', buttons: ['🟨', '🟩', '🟪', '🟥'], solution: ['🟪', '🟩', '🟨'], result: 'cryo', hint: ['화이트보드: 아래층 색부터.', '보라 → 초록 → 노랑'] },
      { key: 'computer', type: 'code', title: '박사의 컴퓨터', art: '🖥️', text: '로그인 암호 4자리.', code: '0721', result: 'email', hint: ['화이트보드 구석의 메모와 신분증.', '7월 21일 → 0721'] },
      { key: 'email', type: 'item', title: '박사의 메일', art: '📧', text: '“포뮬러 원액은 4번 냉동고 케이스에. 케이스 비밀번호 = 냉동고 네 대의 온도 끝자리를 1번부터. 원액은 반드시 안정제와 섞을 것. 안정제는 서재 금고 — 우리 결혼기념일.”' },
      { key: 'studydoor', type: 'red', title: '서재 문', art: '🚪', text: '카드키 리더기.' },
      { key: 'cryo', type: 'place', title: '저온 보관실', art: '❄️🧊🗄️🧬', text: '성에 낀 냉동고 네 대. 표시창은 성에에 가려 보이지 않는다.',
        shows: ['freezer'], spots: [{ label: '선반 위 상자', x: 78, y: 30, reveal: 'gloves' }, { label: '바닥 성에', x: 30, y: 84, reveal: 'keycard' }] },
      { key: 'freezer', type: 'red', title: '4번 초저온 냉동고', art: '🧊', text: '손잡이가 너무 차가워 맨손으로는 열 수 없다.' },
      { key: 'gloves', type: 'blue', title: '방한 장갑', art: '🧤', text: '' },
      { key: 'keycard', type: 'blue', title: '얼어붙은 카드키', art: '💳', text: '“H — 서재”' },
      { key: 'serumcase', type: 'code', from: ['freezer', 'gloves'], title: '혈청 케이스', art: '🧳', text: '냉동고 안에서 케이스를 꺼냈다. 숫자 4자리 자물쇠.', code: '8506', result: 'serum', hint: ['메일: 온도 끝자리를 1번부터. 온도는 CCTV 녹화에 보였어요.', '-18, -25, -40, -86 → 8506'] },
      { key: 'serum', type: 'red', title: '포뮬러 원액', art: '🧫', text: '불안정하다. 이대로는 몇 분 안에 분해될 것이다.' },
      { key: 'study', type: 'place', from: ['studydoor', 'keycard'], discard: ['studydoor', 'keycard'], shows: ['notes', 'photo', 'studysafe'], title: '박사의 서재', art: '📚🕯️🖼️🖋️', text: '책상 위 연구 노트, 결혼식 사진 액자, 벽 금고.' },
      { key: 'notes', type: 'item', title: '연구 노트', art: '📓', text: '“연구소 봉쇄 해제 순서 — 생명의 네 원소를 원자번호 순서대로. H 1 · C 6 · N 7 · O 8”' },
      { key: 'photo', type: 'item', title: '결혼식 사진', art: '🖼️', text: '사진 아래 금박 글씨: “1985년 6월 14일, 하르트만 ♥ 마리”' },
      { key: 'studysafe', type: 'code', title: '서재 금고', art: '🔐', text: '숫자 4자리.', code: '0614', result: 'stabilizer', hint: ['메일: 결혼기념일. 사진을 보세요.', '6월 14일 → 0614'] },
      { key: 'stabilizer', type: 'blue', title: '안정제', art: '💧', text: '' },
      { key: 'formula', type: 'item', from: ['serum', 'stabilizer'], discard: ['serum', 'stabilizer'], shows: ['lockdown'], title: '포뮬러 완성', art: '✨🧪', text: '혈청이 맑은 푸른빛으로 안정되었다! 그 순간 사이렌. “침입자 감지 — 연구소 봉쇄.” 모든 문이 닫힌다.' },
      { key: 'lockdown', type: 'machine', title: '봉쇄 해제 패널', art: '🚨', text: '원소 기호 버튼.', buttons: ['O', 'N', 'He', 'C', 'H'], solution: ['H', 'C', 'N', 'O'], result: 'stairs', hint: ['서재의 연구 노트.', 'H → C → N → O'] },
      { key: 'stairs', type: 'place', title: '비상계단', art: '🪜⬛🚪', text: '봉쇄가 풀리고 비상계단 문이 열렸다. 정전이라 계단이 칠흑같이 어둡다.', shows: ['dark'] },
      { key: 'dark', type: 'red', title: '어두운 계단', art: '⬛', text: '' },
      { key: 'garage', type: 'place', from: ['dark', 'flashlight'], discard: ['dark'], shows: ['car'], title: '지하 주차장', art: '🚗🅿️💨', text: '손전등을 비추며 내려왔다. 연구소 차량 한 대. 저 멀리 경쟁 조직의 차가 헤드라이트를 켠다!',
        spots: [{ label: '차량 선바이저', x: 60, y: 30, reveal: 'carkey' }] },
      { key: 'car', type: 'red', title: '연구소 차량', art: '🚗', text: '' },
      { key: 'carkey', type: 'blue', title: '자동차 열쇠', art: '🔑', text: '' },
      { key: 'out', type: 'item', from: ['car', 'carkey'], end: true, title: '탈출 성공!', art: '🚗💨', text: '시동이 걸리자마자 출구 차단기를 뚫고 나왔다. 포뮬러는 안전하게 당신의 손에!' },
      { key: 'trap1', type: 'trap', from: ['serum', 'gloves'], title: '원액이 증발할 뻔!', text: '장갑으로 원액을 감싸 봤지만 온도가 올라가 버렸다. 서둘러 다시 식혔다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['freezer', 'vial'], title: '꽁꽁 얼었다', text: '시험관을 냉동고에 넣었다가 얼어붙었다. 녹이느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['gascloud', 'flashlight'], title: '불꽃 조심!', text: '가스 속에서 손전등을 켜자 스파크가 튀었다! 급히 물러났다.', penalty: 1 },
      { key: 'trap4', type: 'trap', from: ['locker', 'bolt'], title: '손을 다쳤다', text: '볼트 커터로 사물함 자물쇠를 자르려다 미끄러져 손을 다쳤다.', penalty: 1 },
    ],
  },
  {
    id: 'squeek', box: '이스케이프 어드벤처', title: '찍찍이와 소시지', orig: 'Squeek & Sausage', diff: 2, theme: '#d88a3a',
    intro: '괴짜 악당 노사이드 교수가 로봇 생쥐 찍찍이와 로봇 개 소시지로 세상을 정복하려 한다! 교수의 저택에 숨어들어 로켓 발사를 막아라.',
    cards: [
      { key: 'garden', type: 'place', start: true, title: '노사이드 저택 정원', art: '🏡🌳⛲📮', text: '대문 앞에서 로봇 개 소시지가 으르렁댄다. 분수대, 우체통, 정원 창고. 대문 기둥의 번지 표지판 숫자가 떨어져 거꾸로 붙어 있다: 2 · 1 · 7',
        shows: ['sausage', 'mailbox', 'shed'], spots: [{ label: '덤불', x: 16, y: 72, reveal: 'bone' }, { label: '분수대', emoji: '⛲', x: 62, y: 60, text: '동전이 잔뜩. “세계 정복”이라고 적힌 소원 쪽지가 떠 있다.' }] },
      { key: 'sausage', type: 'red', title: '로봇 개 소시지', art: '🐕‍🦺', text: '“멍! 침입자! 멍!” 대문을 지나갈 수 없다.' },
      { key: 'bone', type: 'blue', title: '강철 뼈다귀', art: '🦴', text: '로봇 개 전용 간식.' },
      { key: 'gate', type: 'item', from: ['sausage', 'bone'], discard: ['bone'], shows: ['hall'], title: '정신 팔린 소시지', art: '🐕‍🦺🦴', text: '소시지가 뼈다귀를 씹느라 정신이 없다. 대문을 살금살금 통과!' },
      { key: 'mailbox', type: 'code', title: '우체통', art: '📮', text: '숫자 3자리 자물쇠. “번지수를 넣으세요.”', code: '712', result: 'letter', hint: ['대문 기둥 표지판은 거꾸로 붙어 있어요.', '2·1·7 을 바로 읽으면 712'] },
      { key: 'letter', type: 'item', title: '배송 확인서', art: '✉️', shows: ['shedkey'], text: '“노사이드 교수님께 — 로봇 부품 배송 완료: 큰 상자 3, 중간 상자 4, 작은 상자 9.” 교수의 낙서: “기지 중지 코드는 작은 것부터 세고, 끝에 내 로봇 수를 붙인다!” 봉투에 창고 열쇠가 들어 있다.' },
      { key: 'shed', type: 'red', title: '정원 창고', art: '🛖', text: '' },
      { key: 'shedkey', type: 'blue', title: '창고 열쇠', art: '🔑', text: '' },
      { key: 'shedOpen', type: 'item', from: ['shed', 'shedkey'], discard: ['shed', 'shedkey'], shows: ['ladder'], title: '창고 안', art: '🧰🪜', text: '잡동사니 사이에 접이식 사다리.' },
      { key: 'ladder', type: 'blue', title: '접이식 사다리', art: '🪜', text: '' },
      { key: 'hall', type: 'place', title: '현관 홀', art: '🎩🪞🕰️🪟', text: '모자걸이, 커다란 거울, 괘종시계. 실험실 문은 걸쇠가 안쪽에 걸려 있다. 2층 다락 창문이 높이 열려 있다.',
        shows: ['labdoor', 'mirror', 'portrait', 'clock', 'window'], spots: [{ label: '코트 주머니', x: 28, y: 50, reveal: 'magnet' }] },
      { key: 'mirror', type: 'item', title: '커다란 거울', art: '🪞', text: '거울에 비친 벽 글씨: “ᴎOIƧƧIM — 부하들아, 내 로봇은 둘뿐이니 소중히 다뤄라! 비밀 칸은 자정 5분 전에 열린다.”' },
      { key: 'portrait', type: 'item', title: '교수의 초상화', art: '🖼️', text: '젊은 노사이드와 햄스터 “찍찍이 1호”. 액자 아래: “나의 첫 발명품”.' },
      { key: 'clock', type: 'code', title: '괘종시계', art: '🕰️', text: '바늘을 맞출 수 있다. 시각 4자리(시·분).', code: '1155', result: 'compartment', hint: ['거울의 글씨: 자정 5분 전.', '11시 55분 → 1155'] },
      { key: 'compartment', type: 'item', title: '시계 속 비밀 칸', art: '🗃️', shows: ['battery'], text: '시계추 뒤에서 작은 칸이 열렸다. 리모컨용 배터리!' },
      { key: 'battery', type: 'blue', title: '리모컨 배터리', art: '🔋', text: '' },
      { key: 'window', type: 'red', title: '높은 다락 창문', art: '🪟', text: '손이 닿지 않는다.' },
      { key: 'attic', type: 'place', from: ['window', 'ladder'], discard: ['window', 'ladder'], shows: ['diary'], title: '다락방', art: '📦🕸️📓', text: '사다리를 타고 다락으로! 먼지 쌓인 상자들 사이에 교수의 일기장.',
        spots: [{ label: '공구 상자', x: 76, y: 70, reveal: 'screwdriver' }] },
      { key: 'diary', type: 'item', title: '교수의 일기', art: '📓', text: '“로켓 제어반 배선: 초록선은 자폭선! 절대 자르지 말 것. 발사를 멈추려면 빨강선 → 파랑선 순서로.”' },
      { key: 'screwdriver', type: 'blue', title: '드라이버', art: '🪛', text: '' },
      { key: 'labdoor', type: 'red', title: '실험실 문', art: '🚪', text: '문틈으로 쇠 걸쇠가 보인다.' },
      { key: 'magnet', type: 'blue', title: '말굽 자석', art: '🧲', text: '끈이 매달려 있다.' },
      { key: 'lab', type: 'place', from: ['labdoor', 'magnet'], discard: ['labdoor'], shows: ['squeek', 'remote', 'blueprint'], title: '노사이드의 실험실', art: '🛠️🐀📐🔋', text: '자석으로 걸쇠를 당겨 열었다! 작업대 위를 로봇 생쥐 찍찍이가 쌩쌩 달린다.',
        spots: [{ label: '작업대 아래 쥐덫', x: 76, y: 78, reveal: 'cheese' }] },
      { key: 'blueprint', type: 'item', title: '비밀 기지 설계도', art: '📐', text: '“기지 엘리베이터 호출: ▲ ▲ ▼ ●”' },
      { key: 'squeek', type: 'red', title: '로봇 생쥐 찍찍이', art: '🐀', text: '너무 빨라서 잡을 수가 없다!' },
      { key: 'cheese', type: 'blue', title: '플라스틱 치즈', art: '🧀', text: '“찍찍이 유인용 — 효과 100%”' },
      { key: 'caught', type: 'item', from: ['squeek', 'cheese'], discard: ['squeek', 'cheese'], plus: 7, plusColor: 'blue', title: '멈춘 찍찍이', art: '🐁💤', text: '치즈에 홀린 찍찍이의 전원을 껐다. 등 뒤 회로판에 파란 숫자 +7 이 새겨져 있다: “리모컨 연결용”.' },
      { key: 'remote', type: 'red', title: '교수의 리모컨', art: '📟', text: '배터리 칸이 비어 있다.' },
      { key: 'remoteP', type: 'red', from: ['remote', 'battery'], discard: ['remote', 'battery'], title: '켜진 리모컨', art: '📟✨', text: '화면: “연결할 로봇을 찾는 중…”' },
      { key: 'remoteOn', type: 'machine', from: ['remoteP', 'caught'], title: '연결된 리모컨', art: '🎮', text: '화면: “기지 엘리베이터를 호출하시겠습니까?”', buttons: ['▲', '▼', '●', '■'], solution: ['▲', '▲', '▼', '●'], result: 'base', hint: ['설계도에 호출 순서가 있어요.', '▲ ▲ ▼ ●'] },
      { key: 'base', type: 'place', title: '지하 비밀 기지', art: '🚀🐀🐕‍🦺⏳', text: '로봇 군단을 실은 로켓이 카운트다운 중! 노사이드 교수: “늦었다!” 발사 제어반 덮개는 나사로 잠겨 있다.', shows: ['control'] },
      { key: 'control', type: 'red', title: '발사 제어반 덮개', art: '🎛️', text: '' },
      { key: 'wires', type: 'machine', from: ['control', 'screwdriver'], discard: ['control', 'screwdriver'], title: '제어반 배선', art: '🔌', text: '덮개를 열자 선 세 가닥.', buttons: ['🔴 빨강선', '🟢 초록선', '🔵 파랑선'], solution: ['🔴 빨강선', '🔵 파랑선'], result: 'rocket', hint: ['다락방의 교수 일기.', '빨강 → 파랑 (초록은 절대 안 돼요!)'] },
      { key: 'rocket', type: 'code', title: '발사 중지 패널', art: '🛑', text: '배선을 끊자 수동 중지 패널이 열렸다. 숫자 4자리.', code: '9432', result: 'out', hint: ['배송 확인서의 상자 수를 작은 것부터. 거울: 교수의 로봇은 둘뿐.', '작은 9 · 중간 4 · 큰 3 · 로봇 2 → 9432'] },
      { key: 'trap1', type: 'trap', from: ['squeek', 'magnet'], title: '빙글빙글!', text: '자석에 찍찍이가 달라붙어 미친 듯이 회전했다. 간신히 떼어냈다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['squeek', 'bone'], title: '앗, 손가락!', text: '찍찍이는 뼈다귀엔 관심 없다. 대신 손가락을 깨물었다!', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['remote', 'magnet'], title: '지지직', text: '자석을 리모컨에 대자 화면이 지지직거렸다. 다시 켜질 때까지 한참 기다렸다.', penalty: 1 },
      { key: 'trap4', type: 'trap', from: ['sausage', 'magnet'], title: '덜컹!', text: '자석에 소시지가 철컥 달라붙었다! 소시지가 화가 나서 짖어 댄다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '계획 저지!', art: '🎉', text: '로켓이 멈추고 로봇들이 잠들었다. 노사이드 교수는 “다음엔 꼭!”을 외치며 굴뚝으로 도망쳤다.' },
    ],
  },
  {
    id: 'goorse', box: '이스케이프 어드벤처', title: '구르스 박사의 섬', orig: 'The Island of Doctor Goorse', diff: 3, theme: '#3a8a3a',
    intro: '괴짜 억만장자 구르스 박사의 섬으로 가던 비행기가 추락했다. 일행은 해변과 절벽 두 곳으로 흩어졌다! 각자 길을 찾아 다시 합류하고, 실종된 조종사를 구해 섬을 탈출하자.',
    cards: [
      { key: 'beach', type: 'place', start: true, title: '해변 (첫째 무리)', art: '🏝️✈️🦀🌴', text: '부서진 비행기 꼬리, 떠밀려 온 나무 상자. 블랙박스가 모래에 반쯤 묻혀 있다. 조종사가 보이지 않는다!',
        shows: ['crate', 'blackbox'], spots: [{ label: '야자수 밑동', x: 82, y: 66, reveal: 'crowbar' }, { label: '모래 위 발자국', emoji: '👣', x: 46, y: 82, text: '조종사의 발자국이 정글로 이어지다… 커다란 짐승 발자국과 섞여 사라졌다.' }] },
      { key: 'cliff', type: 'place', start: true, title: '절벽 (둘째 무리)', art: '⛰️🌿🦜🪂', text: '낙하산이 나무에 걸렸다. 정글로 이어지는 길은 덩굴로 막혀 있다.',
        shows: ['vines'], spots: [{ label: '낙하산 가방', x: 70, y: 32, reveal: 'machete' }, { label: '앵무새', emoji: '🦜', x: 30, y: 30, text: '“구르스! 구르스! 지도 반쪽! 반쪽!”' }] },
      { key: 'blackbox', type: 'item', title: '블랙박스', art: '📦', text: '마지막 기록 좌표: 북위 12°, 동경 47°.' },
      { key: 'crate', type: 'red', title: '못 박힌 나무 상자', art: '📦', text: '“구르스 산업 — 보급품”' },
      { key: 'crowbar', type: 'blue', title: '쇠지렛대', art: '🔧', text: '' },
      { key: 'supplies', type: 'item', from: ['crate', 'crowbar'], discard: ['crate', 'crowbar'], shows: ['mapL', 'flare', 'firstaid'], title: '보급품', art: '🎒', text: '구급상자, 신호탄, 그리고 찢어진 지도의 왼쪽 반쪽.' },
      { key: 'firstaid', type: 'item', title: '구급상자', art: '🩹', text: '붕대와 진통제. 상자 안쪽에 구르스 박사의 낙서: “실험체들은 바나나를 좋아하지.”' },
      { key: 'mapL', type: 'red', title: '지도 왼쪽 반쪽', art: '🗺️', text: '해변과 강이 그려져 있다.' },
      { key: 'flare', type: 'blue', title: '신호탄', art: '🧨', text: '불을 붙이면 환하게 타오른다.' },
      { key: 'vines', type: 'red', title: '빽빽한 덩굴', art: '🌿', text: '' },
      { key: 'machete', type: 'blue', title: '마체테', art: '🔪', text: '' },
      { key: 'jungle', type: 'place', from: ['vines', 'machete'], discard: ['vines'], shows: ['totem', 'monkey'], title: '정글 공터', art: '🌳🗿🐒', text: '덩굴을 헤치니 공터. 동물 토템과, 망원경을 목에 건 원숭이(꼬리가 둘!). 원숭이가 지도 조각을 깔고 앉아 있다.',
        spots: [{ label: '바나나 나무', x: 80, y: 30, reveal: 'banana' }] },
      { key: 'totem', type: 'item', title: '동물 토템', art: '🗿', text: '토템에 동물과 숫자: 🦅 3 · 🐍 1 · 🐒 4 · 🐢 2' },
      { key: 'monkey', type: 'red', title: '꼬리 둘 달린 원숭이', art: '🐒', text: '“끽끽!” 지도 조각과 망원경을 꽉 쥐고 있다.' },
      { key: 'banana', type: 'blue', title: '잘 익은 바나나', art: '🍌', text: '' },
      { key: 'monkeyGift', type: 'item', from: ['monkey', 'banana'], discard: ['monkey', 'banana'], shows: ['mapR', 'binoculars'], title: '원숭이의 선물', art: '🐒🍌', text: '바나나를 받은 원숭이가 지도 조각과 망원경을 내놓았다.' },
      { key: 'binoculars', type: 'item', title: '망원경', art: '🔭', text: '망원경으로 보니 강에 악어 5마리, 화산 기슭에 저택과 송신탑. 저택 지하 창문으로 조종사가 갇힌 모습이 보인다!' },
      { key: 'mapR', type: 'blue', title: '지도 오른쪽 반쪽', art: '🗺️', text: '동굴과 화산 기슭의 저택이 그려져 있다.' },
      { key: 'map', type: 'item', from: ['mapL', 'mapR'], discard: ['mapL', 'mapR'], shows: ['river'], title: '섬 전체 지도', art: '🗺️✨', text: '두 무리가 다시 만났다! 지도: 강을 건너 → 동굴 → 구르스 박사의 저택.' },
      { key: 'river', type: 'place', title: '악어 강', art: '🌊🐊🌳', text: '악어가 우글거린다. 강가에 큰 나무 한 그루.', shows: ['tree'], spots: [{ label: '물가 바위', x: 22, y: 76, reveal: 'rope' }] },
      { key: 'tree', type: 'red', title: '강가의 큰 나무', art: '🌳', text: '가지가 강 건너까지 뻗어 있다.' },
      { key: 'rope', type: 'blue', title: '밧줄', art: '🪢', text: '' },
      { key: 'crossing', type: 'item', from: ['tree', 'rope'], discard: ['tree', 'rope'], shows: ['cave'], title: '밧줄 다리', art: '🪢🌊', text: '가지에 밧줄을 묶어 강을 건넜다. 악어들이 아쉬운 듯 입맛을 다신다.' },
      { key: 'cave', type: 'place', title: '어두운 동굴', art: '🕳️🦇💧', text: '칠흑같이 어둡다. 손으로 더듬으니 벽에 그림이 새겨진 느낌.', shows: ['dark'] },
      { key: 'dark', type: 'red', title: '어둠', art: '⬛', text: '아무것도 보이지 않는다.' },
      { key: 'paintings', type: 'item', from: ['dark', 'flare'], discard: ['dark', 'flare'], shows: ['gate'], title: '동굴 벽화', art: '🦅🐍🐒🐢', text: '신호탄 불빛에 벽화가 드러났다: 왼쪽부터 독수리, 뱀, 원숭이, 거북. 출구 쪽에 같은 동물 버튼이 달린 철문.' },
      { key: 'gate', type: 'machine', title: '저택 뒷문', art: '🚧', text: '동물 버튼 네 개.', buttons: ['🐢', '🐒', '🐍', '🦅'], solution: ['🦅', '🐍', '🐒', '🐢'], result: 'mansion', hint: ['동굴 벽화의 순서.', '🦅 🐍 🐒 🐢'] },
      { key: 'mansion', type: 'place', title: '구르스 박사의 저택', art: '🏰🧬🐊📡', text: '수조 속 변이 악어, 제어실 문, 지하 실험실 계단, 꺼진 송신탑. 박사는 사라졌다. 제어실 문에 동물 그림: 원숭이, 독수리, 거북, 뱀. 실험실 문에는 “강의 수호자 수 × 토템의 거북”.',
        shows: ['ctrldoor', 'labdoor'], spots: [{ label: '박사의 책상', x: 74, y: 62, reveal: 'battery' }] },
      { key: 'ctrldoor', type: 'code', title: '제어실 문', art: '🔢', text: '숫자 4자리. 그림 아래: “토템이 숫자를 안다.”', code: '4321', result: 'log', hint: ['문에 그려진 동물 순서대로, 토템의 숫자를.', '원숭이4 · 독수리3 · 거북2 · 뱀1 → 4321'] },
      { key: 'log', type: 'item', title: '제어실 기록', art: '📓', text: '“송신 주파수는 섬의 좌표를 이어서. 송신기는 비상 전원(퓨즈 + 배터리)이 있어야 켜진다. 퓨즈는 실험실 공구함에.”' },
      { key: 'labdoor', type: 'code', title: '지하 실험실 문', art: '🔢', text: '숫자 2자리.', code: '10', result: 'lab', hint: ['강의 수호자는 악어(망원경으로 셌죠), 토템의 거북 숫자는?', '악어 5 × 거북 2 = 10'] },
      { key: 'lab', type: 'place', title: '지하 실험실', art: '🧪🐊⛓️', text: '변이 동물들의 우리. 맨 끝 우리에 조종사가 갇혀 있다! 공구함이 보인다.', shows: ['cage'], spots: [{ label: '공구함', x: 26, y: 70, reveal: 'fuse' }, { label: '열쇠 걸이', x: 80, y: 30, reveal: 'cagekey' }] },
      { key: 'cage', type: 'red', title: '조종사가 갇힌 우리', art: '⛓️', text: '' },
      { key: 'cagekey', type: 'blue', title: '우리 열쇠', art: '🗝️', text: '' },
      { key: 'pilot', type: 'item', from: ['cage', 'cagekey'], discard: ['cage', 'cagekey'], title: '구출된 조종사', art: '👨‍✈️', text: '“살았다! 구르스는 잠수정으로 도망쳤소. 송신기만 켜면 해안 경비대가 올 거요.”' },
      { key: 'fuse', type: 'red', title: '퓨즈', art: '🔌', text: '' },
      { key: 'battery', type: 'blue', title: '비상 배터리', art: '🔋', text: '' },
      { key: 'power', type: 'item', from: ['fuse', 'battery'], discard: ['fuse', 'battery'], shows: ['radio'], title: '비상 전원', art: '⚡', text: '송신탑에 불이 들어왔다!' },
      { key: 'radio', type: 'code', title: '송신기', art: '📻', text: '숫자 4자리 주파수.', code: '1247', result: 'out', hint: ['섬의 좌표는 해변의 블랙박스에.', '12°, 47° → 1247'] },
      { key: 'trap1', type: 'trap', from: ['fuse', 'machete'], title: '찌릿!', text: '칼로 퓨즈를 건드렸다가 감전됐다!', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['tree', 'machete'], title: '나무가 떠내려갔다', text: '나무를 베어 다리를 만들려다 강물에 휩쓸려 보냈다. 한참 걸려 다른 방법을 찾았다.', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['monkey', 'machete'], title: '원숭이의 반격', text: '칼을 휘두르자 원숭이가 망원경으로 머리를 때리고 나무 위로 도망쳤다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '구조 헬기 도착!', art: '🚁', text: '신호를 받은 해안 경비대 헬기가 섬 위를 맴돈다. 조종사와 함께 섬을 떠난다. 구르스 박사의 위험한 실험도 세상에 알려질 것이다.' },
    ],
  },
];
