'use strict';
// 언락! — 입문 + 이스케이프 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)
// 카드 키 이름으로 쓰고 번호는 build.js 가 자동으로 붙인다.
// spots: reveal 이 있으면 그림 속 숨은 번호(작은 숫자), click:true 면 눌러서 찾는 지점.

module.exports = [
  {
    id: 'tutorial', box: '입문', title: '첫 번째 방', orig: 'Tutorial', diff: 0, theme: '#6a8aa8', limit: 20, decoys: 1,
    intro: '눈을 떠 보니 낯선 서재. 문은 잠겨 있다. 언락의 기본을 배워 봐요!',
    cards: [
      { key: 'room', type: 'place', start: true, title: '작은 서재', art: '📚🪑🕰️🚪', text: '책장과 낡은 의자, 멈춘 괘종시계. 장소 카드에 보이는 번호의 카드는 바로 나와요. 🔍 동그라미는 눌러서 살펴보고, 그림 속에 작게 숨은 숫자는 오른쪽 위 칸에 입력해서 가져와요!',
        shows: ['chest'], spots: [{ label: '화분', emoji: '🪴', x: 18, y: 62, reveal: 'key', click: true }, { label: '책장', emoji: '📚', x: 72, y: 30, text: '먼지 쌓인 요리책뿐이다.' }, { label: '시계 아래', x: 56, y: 82, reveal: 'clock' }],
        hint: ['🪴 동그라미를 눌러 보세요. 그리고 시계 아래쪽을 아주 자세히 보세요 — 작은 숫자가 있어요.', '시계 아래 숨은 숫자를 “번호로 카드 가져오기”에 입력하세요.'] },
      { key: 'chest', type: 'red', title: '잠긴 나무 상자', art: '🧰', text: '작은 자물쇠가 달려 있다. 빨간 번호는 파란 번호와 합칠 수 있어요 — 두 번호의 합이 새 카드!' },
      { key: 'key', type: 'blue', title: '작은 열쇠', art: '🗝️', text: '녹슨 작은 열쇠.' },
      { key: 'note', type: 'item', from: ['chest', 'key'], title: '상자 속 쪽지', art: '📜', discard: ['chest', 'key'], shows: ['safe'], text: '“금고 비밀번호는 시계가 멈춘 시각.” 상자 바닥에 금고 그림이 있다. (다 쓴 카드는 이렇게 버려져요)' },
      { key: 'clock', type: 'item', title: '괘종시계', art: '🕰️', text: '그림 속 숨은 번호를 찾았군요! 시계는 9시 15분에 멈춰 있다.' },
      { key: 'safe', type: 'code', title: '벽 금고', art: '🔐', text: '숫자 4자리 금고. 노란 카드는 코드를 입력해요. (틀리면 벌점 3분!)', code: '0915', result: 'panel', hint: ['쪽지와 시계를 함께 보세요.', '9시 15분 → 0915'] },
      { key: 'panel', type: 'machine', title: '문 패널', art: '🚪', text: '금고 안 메모: “무지개 순서로 색을 누르면 문이 열린다.” 초록 카드는 장치 — 버튼을 차례로 누르고 작동!', buttons: ['🔵', '🟢', '🔴', '🟡'], solution: ['🔴', '🟡', '🟢', '🔵'], result: 'out', hint: ['무지개는 빨주노초파남보.', '🔴 🟡 🟢 🔵'] },
      { key: 'out', type: 'item', end: true, title: '문이 열렸다!', art: '🌅', text: '첫 번째 방 탈출 성공! 이제 진짜 모험을 떠나 볼까요?' },
    ],
  },

  // ───────────── 이스케이프 어드벤처 ─────────────
  {
    id: 'formula', box: '이스케이프 어드벤처', title: '포뮬러', orig: 'The Formula', diff: 2, theme: '#3a9a8a',
    intro: '실종된 H 박사가 비밀 연구소에 숨긴 만능 혈청 “포뮬러”. 경쟁 조직보다 먼저 연구소에 잠입해 혈청을 손에 넣어라!',
    cards: [
      { key: 'corridor', type: 'place', start: true, title: '연구소 지하 복도', art: '🚪🧯📋🪴', text: '정면에 실험실 보안문, 옆에 경비실 사물함. 벽에 소화기 점검표가 붙어 있다.',
        shows: ['locker', 'extinguisher', 'secdoor'], spots: [{ label: '화분 그늘', x: 84, y: 70, reveal: 'bolt' }, { label: '안내도', emoji: '🗺️', x: 40, y: 28, text: '지하 1층: 복도 → 실험실 → 저온 보관실. 박사의 서재는 실험실 안쪽.' }] },
      { key: 'locker', type: 'red', title: '경비실 사물함', art: '🔒', text: '맹꽁이 자물쇠가 단단히 걸려 있다.' },
      { key: 'bolt', type: 'blue', title: '볼트 커터', art: '✂️', text: '화분 뒤에 누가 숨겨 두었다.' },
      { key: 'lockerOpen', type: 'item', from: ['locker', 'bolt'], discard: ['locker'], shows: ['badge'], title: '열린 사물함', art: '🗄️', text: '경비 일지: “보안문 비밀번호는 매주 바뀐다. 이번 주 = 소화기 점검일(월·일 4자리).” 사물함 구석에 박사의 신분증이 떨어져 있다.' },
      { key: 'extinguisher', type: 'item', title: '소화기 점검표', art: '🧯', text: '점검 기록: 9월 2일 ✔ · 10월 15일 ✔ · 11월 24일 ✔ (최근)' },
      { key: 'badge', type: 'item', title: 'H 박사 신분증', art: '🪪', text: 'Dr. H. 하르트만 — 수석 연구원. 생년월일 1958. 07. 21' },
      { key: 'secdoor', type: 'code', title: '실험실 보안문', art: '🔢', text: '숫자 4자리 키패드.', code: '1124', result: 'lab', hint: ['경비 일지가 비밀번호 규칙을 알려 줘요. 사물함을 열어야 해요.', '가장 최근 점검일 11월 24일 → 1124'] },
      { key: 'lab', type: 'place', title: '실험실', art: '🧪🔬🖥️⚗️', text: '실험대, 원심분리기, 박사의 컴퓨터. 안쪽에 “서재” 팻말이 붙은 문. 화이트보드에 메모가 가득.',
        shows: ['whiteboard', 'centrifuge', 'computer', 'studydoor'], spots: [{ label: '실험대 시험관 꽂이', x: 22, y: 74, reveal: 'vial' }] },
      { key: 'whiteboard', type: 'item', title: '화이트보드', art: '📋', text: '“시약을 원심분리 → 층이 나뉜다. 저온 보관실 문은 아래층 색부터 차례로!” 구석에: “컴퓨터 암호 = 내 생일(월일)”' },
      { key: 'centrifuge', type: 'red', title: '원심분리기', art: '🌀', text: '시험관을 꽂는 칸이 비어 있다.' },
      { key: 'vial', type: 'blue', title: '시약 시험관', art: '🧪', text: '탁한 액체가 들어 있다.' },
      { key: 'spun', type: 'item', from: ['centrifuge', 'vial'], discard: ['centrifuge', 'vial'], shows: ['cryodoor'], title: '분리된 시약', art: '🟨🟩🟪', text: '시약이 세 층으로 나뉘었다. 위에서부터 노랑, 초록, 보라.' },
      { key: 'cryodoor', type: 'machine', title: '저온 보관실 문 패널', art: '❄️🚪', text: '색 버튼 네 개.', buttons: ['🟨', '🟩', '🟪', '🟥'], solution: ['🟪', '🟩', '🟨'], result: 'cryo', hint: ['화이트보드: 아래층 색부터.', '보라 → 초록 → 노랑'] },
      { key: 'computer', type: 'code', title: '박사의 컴퓨터', art: '🖥️', text: '로그인 암호 4자리.', code: '0721', result: 'email', hint: ['화이트보드 구석의 메모와 신분증.', '7월 21일 → 0721'] },
      { key: 'email', type: 'item', title: '박사의 메일', art: '📧', text: '“포뮬러 원액은 저온 보관실 케이스에. 케이스 비밀번호 = 냉동고 네 대의 온도 끝자리를 1번부터. 원액은 반드시 안정제와 섞을 것.”' },
      { key: 'studydoor', type: 'red', title: '서재 문', art: '🚪', text: '카드키 리더가 달려 있다.' },
      { key: 'cryo', type: 'place', title: '저온 보관실', art: '❄️🧊🗄️🧬', text: '성에 낀 냉동고 네 대. 표시창: 1번 -18℃ · 2번 -25℃ · 3번 -40℃ · 4번 -86℃.',
        shows: ['freezer'], spots: [{ label: '선반 위 상자', x: 78, y: 30, reveal: 'gloves' }, { label: '바닥 성에', x: 30, y: 84, reveal: 'keycard' }] },
      { key: 'freezer', type: 'red', title: '4번 초저온 냉동고', art: '🧊', text: '손잡이가 너무 차가워 맨손으로는 열 수 없다.' },
      { key: 'gloves', type: 'blue', title: '방한 장갑', art: '🧤', text: '' },
      { key: 'keycard', type: 'blue', title: '얼어붙은 카드키', art: '💳', text: '“H — 서재”' },
      { key: 'serumcase', type: 'code', from: ['freezer', 'gloves'], title: '혈청 케이스', art: '🧳', text: '냉동고 안에서 케이스를 꺼냈다. 숫자 4자리 자물쇠.', code: '8506', result: 'serum', hint: ['박사의 메일: 냉동고 온도 끝자리를 1번부터.', '-18, -25, -40, -86 → 8506'] },
      { key: 'serum', type: 'red', title: '포뮬러 원액', art: '🧫', text: '불안정하다. 이대로는 몇 분 안에 분해될 것이다.' },
      { key: 'study', type: 'place', from: ['studydoor', 'keycard'], discard: ['studydoor', 'keycard'], shows: ['notes'], title: '박사의 서재', art: '📚🕯️🧬🖋️', text: '책상 위 연구 노트, 그리고 벽장 속 작은 약병들.',
        spots: [{ label: '벽장 약병', x: 80, y: 55, reveal: 'stabilizer' }] },
      { key: 'notes', type: 'item', title: '연구 노트', art: '📓', text: '“연구소 봉쇄 해제 순서 — 생명의 네 원소를 원자번호 순서대로. H 1 · C 6 · N 7 · O 8”' },
      { key: 'stabilizer', type: 'blue', title: '안정제', art: '💧', text: '' },
      { key: 'formula', type: 'item', from: ['serum', 'stabilizer'], discard: ['serum', 'stabilizer'], shows: ['lockdown'], title: '포뮬러 완성', art: '✨🧪', text: '혈청이 맑은 푸른빛으로 안정되었다! 그 순간 사이렌이 울린다. “침입자 감지 — 연구소 봉쇄.”' },
      { key: 'lockdown', type: 'machine', title: '봉쇄 해제 패널', art: '🚨', text: '원소 기호 버튼.', buttons: ['O', 'N', 'He', 'C', 'H'], solution: ['H', 'C', 'N', 'O'], result: 'out', hint: ['서재의 연구 노트.', 'H → C → N → O'] },
      { key: 'trap1', type: 'trap', from: ['serum', 'gloves'], title: '원액이 증발할 뻔!', text: '장갑으로 원액을 감싸 봤지만 온도가 올라가 버렸다. 서둘러 다시 식혔다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['freezer', 'vial'], title: '꽁꽁 얼었다', text: '시약을 냉동고에 넣었다가 얼어붙었다. 녹이느라 시간이 흘렀다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '탈출 성공!', art: '🏃‍♂️💨', text: '봉쇄가 풀리고 복도를 내달린다. 포뮬러는 안전하게 당신의 손에!' },
    ],
  },
  {
    id: 'squeek', box: '이스케이프 어드벤처', title: '찍찍이와 소시지', orig: 'Squeek & Sausage', diff: 2, theme: '#d88a3a',
    intro: '괴짜 악당 노사이드 교수가 로봇 생쥐 찍찍이와 로봇 개 소시지로 세상을 정복하려 한다! 교수의 저택에 숨어들어 계획을 막아라.',
    cards: [
      { key: 'garden', type: 'place', start: true, title: '노사이드 저택 정원', art: '🏡🌳⛲📮', text: '대문 앞에서 로봇 개 소시지가 으르렁댄다. 분수대, 우체통. 대문 기둥의 번지 표지판 숫자가 떨어져 거꾸로 붙어 있다: 2 · 1 · 7',
        shows: ['sausage', 'mailbox'], spots: [{ label: '덤불', x: 16, y: 72, reveal: 'bone' }, { label: '분수대', emoji: '⛲', x: 62, y: 60, text: '동전이 잔뜩. 소원은 “세계 정복”이라고 적힌 쪽지가 떠 있다.' }] },
      { key: 'sausage', type: 'red', title: '로봇 개 소시지', art: '🐕‍🦺', text: '“멍! 침입자! 멍!” 대문을 지나갈 수 없다.' },
      { key: 'bone', type: 'blue', title: '강철 뼈다귀', art: '🦴', text: '로봇 개 전용 간식.' },
      { key: 'gate', type: 'item', from: ['sausage', 'bone'], discard: ['bone'], shows: ['hall'], title: '정신 팔린 소시지', art: '🐕‍🦺🦴', text: '소시지가 뼈다귀를 씹느라 정신이 없다. 대문을 살금살금 통과!' },
      { key: 'mailbox', type: 'code', title: '우체통', art: '📮', text: '숫자 3자리 자물쇠. “번지수를 넣으세요.”', code: '712', result: 'letter', hint: ['대문 기둥 표지판은 거꾸로 붙어 있어요.', '2·1·7 을 바로 읽으면 712'] },
      { key: 'letter', type: 'item', title: '배송 확인서', art: '✉️', text: '“노사이드 교수님께 — 로봇 부품 배송 완료: 큰 상자 3, 중간 상자 4, 작은 상자 9.” 교수의 낙서: “기지 중지 코드는 작은 것부터 세고, 끝에 내 로봇 수를 붙인다!”' },
      { key: 'hall', type: 'place', title: '현관 홀', art: '🎩🪞🧥🪜', text: '모자걸이, 커다란 거울, 2층 계단. 실험실 문은 걸쇠가 안쪽에 걸려 있다.',
        shows: ['labdoor', 'mirror'], spots: [{ label: '코트 주머니', x: 28, y: 50, reveal: 'magnet' }] },
      { key: 'mirror', type: 'item', title: '커다란 거울', art: '🪞', text: '거울에 비친 벽 글씨: “ᴎOIƧƧIM — 부하들아, 내 로봇은 둘뿐이니 소중히 다뤄라!”' },
      { key: 'labdoor', type: 'red', title: '실험실 문', art: '🚪', text: '문틈으로 쇠 걸쇠가 보인다.' },
      { key: 'magnet', type: 'blue', title: '말굽 자석', art: '🧲', text: '끈이 매달려 있다.' },
      { key: 'lab', type: 'place', from: ['labdoor', 'magnet'], discard: ['labdoor'], shows: ['squeek', 'remote', 'blueprint'], title: '노사이드의 실험실', art: '🛠️🐀📐🔋', text: '자석으로 걸쇠를 당겨 열었다! 작업대 위를 로봇 생쥐 찍찍이가 쌩쌩 달린다.',
        spots: [{ label: '작업대 아래 쥐덫', x: 76, y: 78, reveal: 'cheese' }] },
      { key: 'blueprint', type: 'item', title: '비밀 기지 설계도', art: '📐', text: '“기지 엘리베이터 호출: ▲ ▲ ▼ ●”' },
      { key: 'squeek', type: 'red', title: '로봇 생쥐 찍찍이', art: '🐀', text: '너무 빨라서 잡을 수가 없다!' },
      { key: 'cheese', type: 'blue', title: '플라스틱 치즈', art: '🧀', text: '“찍찍이 유인용 — 효과 100%”' },
      { key: 'caught', type: 'item', from: ['squeek', 'cheese'], discard: ['squeek', 'cheese'], plus: 7, plusColor: 'blue', title: '멈춘 찍찍이', art: '🐁💤', text: '치즈에 홀린 찍찍이의 전원을 껐다. 등 뒤 회로판에 파란 숫자 +7 이 새겨져 있다: “리모컨 연결용”.' },
      { key: 'remote', type: 'red', title: '교수의 리모컨', art: '📟', text: '전원은 들어오는데 연결된 로봇이 없다.' },
      { key: 'remoteOn', type: 'machine', from: ['remote', 'caught'], title: '연결된 리모컨', art: '🎮', text: '화면: “기지 엘리베이터를 호출하시겠습니까?”', buttons: ['▲', '▼', '●', '■'], solution: ['▲', '▲', '▼', '●'], result: 'base', hint: ['설계도에 호출 순서가 있어요.', '▲ ▲ ▼ ●'] },
      { key: 'base', type: 'place', title: '지하 비밀 기지', art: '🚀🐀🐕‍🦺⏳', text: '로봇 군단을 실은 로켓이 카운트다운 중! 발사대 옆에 중지 코드 패널. 노사이드 교수가 외친다. “늦었다!”', shows: ['rocket'] },
      { key: 'rocket', type: 'code', title: '발사 중지 패널', art: '🛑', text: '숫자 4자리.', code: '9432', result: 'out', hint: ['배송 확인서의 상자 수를 작은 것부터. 거울: 교수의 로봇은 둘뿐.', '작은 9 · 중간 4 · 큰 3 · 로봇 2 → 9432'] },
      { key: 'trap1', type: 'trap', from: ['squeek', 'magnet'], title: '빙글빙글!', text: '자석에 찍찍이가 달라붙어 미친 듯이 회전했다. 간신히 떼어냈다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['squeek', 'bone'], title: '앗, 손가락!', text: '찍찍이는 뼈다귀엔 관심 없다. 대신 손가락을 깨물었다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '계획 저지!', art: '🎉', text: '로켓이 멈추고 로봇들이 잠들었다. 노사이드 교수는 “다음엔 꼭!”을 외치며 굴뚝으로 도망쳤다.' },
    ],
  },
  {
    id: 'goorse', box: '이스케이프 어드벤처', title: '구르스 박사의 섬', orig: 'The Island of Doctor Goorse', diff: 3, theme: '#3a8a3a',
    intro: '괴짜 억만장자 구르스 박사의 섬으로 가던 비행기가 추락했다. 일행은 해변과 절벽 두 곳으로 흩어졌다! 각자 길을 찾아 다시 합류하고, 섬을 탈출하자.',
    cards: [
      { key: 'beach', type: 'place', start: true, title: '해변 (첫째 무리)', art: '🏝️✈️🦀🌴', text: '부서진 비행기 꼬리, 떠밀려 온 나무 상자. 블랙박스가 모래에 반쯤 묻혀 있다.',
        shows: ['crate', 'blackbox'], spots: [{ label: '야자수 밑동', x: 82, y: 66, reveal: 'crowbar' }] },
      { key: 'cliff', type: 'place', start: true, title: '절벽 (둘째 무리)', art: '⛰️🌿🦜🪂', text: '낙하산이 나무에 걸렸다. 정글로 이어지는 길은 덩굴로 막혀 있다.',
        shows: ['vines'], spots: [{ label: '낙하산 가방', x: 70, y: 32, reveal: 'machete' }, { label: '앵무새', emoji: '🦜', x: 30, y: 30, text: '“구르스! 구르스! 지도 반쪽! 반쪽!”' }] },
      { key: 'blackbox', type: 'item', title: '블랙박스', art: '📦', text: '마지막 기록 좌표: 북위 12°, 동경 47°.' },
      { key: 'crate', type: 'red', title: '못 박힌 나무 상자', art: '📦', text: '“구르스 산업 — 보급품”' },
      { key: 'crowbar', type: 'blue', title: '쇠지렛대', art: '🔧', text: '' },
      { key: 'supplies', type: 'item', from: ['crate', 'crowbar'], discard: ['crate', 'crowbar'], shows: ['mapL', 'flare'], title: '보급품', art: '🎒', text: '구급상자, 신호탄, 그리고 찢어진 지도의 왼쪽 반쪽.' },
      { key: 'mapL', type: 'red', title: '지도 왼쪽 반쪽', art: '🗺️', text: '해변과 강이 그려져 있다.' },
      { key: 'flare', type: 'blue', title: '신호탄', art: '🧨', text: '불을 붙이면 환하게 타오른다.' },
      { key: 'vines', type: 'red', title: '빽빽한 덩굴', art: '🌿', text: '' },
      { key: 'machete', type: 'blue', title: '마체테', art: '🔪', text: '' },
      { key: 'jungle', type: 'place', from: ['vines', 'machete'], discard: ['vines'], shows: ['mapR', 'totem'], title: '정글 공터', art: '🌳🗿🐍', text: '덩굴을 헤치니 공터. 동물 토템 옆에 지도의 오른쪽 반쪽이 박혀 있다.' },
      { key: 'totem', type: 'item', title: '동물 토템', art: '🗿', text: '토템에 동물과 숫자: 🦅 3 · 🐍 1 · 🐒 4 · 🐢 2' },
      { key: 'mapR', type: 'blue', title: '지도 오른쪽 반쪽', art: '🗺️', text: '동굴과 화산 기슭의 저택이 그려져 있다.' },
      { key: 'map', type: 'item', from: ['mapL', 'mapR'], discard: ['mapL', 'mapR'], shows: ['river'], title: '섬 전체 지도', art: '🗺️✨', text: '두 무리가 다시 만났다! 지도: 강을 건너 → 동굴 → 구르스 박사의 저택.' },
      { key: 'river', type: 'place', title: '악어 강', art: '🌊🐊🌳', text: '악어가 우글거린다. 강가에 큰 나무 한 그루.', shows: ['tree'], spots: [{ label: '물가 바위', x: 22, y: 76, reveal: 'rope' }] },
      { key: 'tree', type: 'red', title: '강가의 큰 나무', art: '🌳', text: '가지가 강 건너까지 뻗어 있다.' },
      { key: 'rope', type: 'blue', title: '밧줄', art: '🪢', text: '' },
      { key: 'crossing', type: 'item', from: ['tree', 'rope'], discard: ['tree', 'rope'], shows: ['cave'], title: '밧줄 다리', art: '🪢🌊', text: '가지에 밧줄을 묶어 강을 건넜다. 악어들이 아쉬운 듯 입맛을 다신다.' },
      { key: 'cave', type: 'place', title: '어두운 동굴', art: '🕳️🦇💧', text: '칠흑같이 어둡다. 손으로 더듬으니 벽에 그림이 새겨진 느낌.', shows: ['dark'] },
      { key: 'dark', type: 'red', title: '어둠', art: '⬛', text: '아무것도 보이지 않는다.' },
      { key: 'paintings', type: 'item', from: ['dark', 'flare'], discard: ['dark', 'flare'], shows: ['gate'], title: '동굴 벽화', art: '🦅🐍🐒🐢', text: '신호탄 불빛에 벽화가 드러났다: 왼쪽부터 독수리, 뱀, 원숭이, 거북. 출구 쪽에 같은 동물 버튼이 달린 철문.' },
      { key: 'gate', type: 'machine', title: '저택 뒷문', art: '🚧', text: '동물 버튼 네 개.', buttons: ['🐢', '🐒', '🐍', '🦅'], solution: ['🦅', '🐍', '🐒', '🐢'], result: 'mansion', hint: ['동굴 벽화의 순서.', '🦅 🐍 🐒 🐢'] },
      { key: 'mansion', type: 'place', title: '구르스 박사의 저택', art: '🏰🧬🐊📡', text: '수조 속 변이 악어, 제어실 문, 꺼진 송신탑. 박사는 실험체들을 풀어놓고 사라졌다. 제어실 문에 동물 그림: 원숭이, 독수리, 거북, 뱀.',
        shows: ['ctrldoor'], spots: [{ label: '수조 옆 공구함', x: 26, y: 70, reveal: 'fuse' }, { label: '박사의 책상', x: 74, y: 62, reveal: 'battery' }] },
      { key: 'ctrldoor', type: 'code', title: '제어실 문', art: '🔢', text: '숫자 4자리. 그림 아래: “토템이 숫자를 안다.”', code: '4321', result: 'log', hint: ['문에 그려진 동물 순서대로, 토템의 숫자를.', '원숭이4 · 독수리3 · 거북2 · 뱀1 → 4321'] },
      { key: 'log', type: 'item', title: '제어실 기록', art: '📓', text: '“송신 주파수는 섬의 좌표를 이어서. 송신기는 비상 전원이 있어야 켜진다.”' },
      { key: 'fuse', type: 'red', title: '퓨즈', art: '🔌', text: '' },
      { key: 'battery', type: 'blue', title: '비상 배터리', art: '🔋', text: '' },
      { key: 'power', type: 'item', from: ['fuse', 'battery'], discard: ['fuse', 'battery'], shows: ['radio'], title: '비상 전원', art: '⚡', text: '송신탑에 불이 들어왔다!' },
      { key: 'radio', type: 'code', title: '송신기', art: '📻', text: '숫자 4자리 주파수.', code: '1247', result: 'out', hint: ['섬의 좌표는 해변의 블랙박스에.', '12°, 47° → 1247'] },
      { key: 'trap1', type: 'trap', from: ['fuse', 'machete'], title: '찌릿!', text: '칼로 퓨즈를 건드렸다가 감전됐다!', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['tree', 'machete'], title: '나무가 떠내려갔다', text: '나무를 베어 다리를 만들려다 강물에 휩쓸려 보냈다. 한참 걸려 다른 방법을 찾았다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '구조 헬기 도착!', art: '🚁', text: '신호를 받은 헬기가 섬 위를 맴돈다. 구르스 박사의 위험한 실험도 세상에 알려질 것이다.' },
    ],
  },
];
