'use strict';
// 언락! — 엑조틱 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '엑조틱 어드벤처';
module.exports = [
  {
    id: 'boogeymen', box: B, title: '부기맨들의 밤', orig: 'The Night of the Boogeymen', diff: 1, theme: '#5a4a9a',
    intro: '부기맨들이 어린 윌리엄의 꿈속에 쳐들어왔다! 꿈속으로 들어가 부기맨들을 쫓아내고 윌리엄을 편히 재워 주자.',
    cards: [
      { key: 'room', type: 'place', start: true, title: '윌리엄의 방', art: '🛏️🧸🌙🖍️', text: '윌리엄이 식은땀을 흘리며 뒤척인다. 벽에 윌리엄이 그린 그림, 창가의 오르골.',
        shows: ['drawings', 'william'], spots: [{ label: '장난감 상자', x: 78, y: 72, reveal: 'teddy' }] },
      { key: 'drawings', type: 'item', title: '윌리엄의 그림', art: '🖍️', text: '그림 1: 별 3개 · 그림 2: 달 1개 · 그림 3: 구름 8개. 삐뚤빼뚤한 글씨: “무서울 땐 그림 순서대로 세면 돼!”' },
      { key: 'william', type: 'red', title: '악몽을 꾸는 윌리엄', art: '😣', text: '“싫어… 오지 마…” 잠꼬대를 한다.' },
      { key: 'teddy', type: 'blue', title: '꿈의 곰인형', art: '🧸', text: '“꼭 안고 자면 꿈속으로 갈 수 있어.” — 곰인형 배에 수놓인 글.' },
      { key: 'dream', type: 'place', from: ['william', 'teddy'], discard: ['teddy'], shows: ['closetman', 'bedman', 'musicbox'], title: '윌리엄의 꿈속', art: '🌀👹🎠🌙', text: '곰인형을 안기자 방이 빙글 돌며 꿈속으로! 옷장 부기맨과 침대 밑 부기맨이 회전목마 위에서 낄낄댄다. 한가운데 커다란 오르골.',
        spots: [{ label: '회전목마 말 안장', x: 24, y: 64, reveal: 'torch' }, { label: '구름 사이', x: 78, y: 22, reveal: 'feather' }] },
      { key: 'closetman', type: 'red', title: '옷장 부기맨', art: '👹', text: '어둠 속에서만 힘이 세다고 한다.' },
      { key: 'torch', type: 'blue', title: '꿈의 손전등', art: '🔦', text: '' },
      { key: 'bye1', type: 'item', from: ['closetman', 'torch'], discard: ['closetman'], title: '도망간 옷장 부기맨', art: '💨', text: '빛을 비추자 “으악, 눈부셔!” 하고 달아났다. 남긴 쪽지: “자장가 첫 소절 — 도 도 솔 솔”' },
      { key: 'bedman', type: 'red', title: '침대 밑 부기맨', art: '👺', text: '간지럼을 엄청 탄다는 소문.' },
      { key: 'feather', type: 'blue', title: '구름 깃털', art: '🪶', text: '' },
      { key: 'bye2', type: 'item', from: ['bedman', 'feather'], discard: ['bedman', 'feather'], title: '도망간 침대 밑 부기맨', art: '🤣💨', text: '간질간질! 깔깔 웃다가 굴러서 달아났다. 남긴 쪽지: “자장가 둘째 소절 — 라 라 솔”' },
      { key: 'musicbox', type: 'code', title: '꿈의 오르골', art: '🎶', text: '숫자 3자리 자물쇠. 부기맨 대장이 그 위에 앉아 있다.', code: '318', result: 'lullaby', hint: ['윌리엄의 그림을 순서대로 세어 보세요.', '별 3 · 달 1 · 구름 8 → 318'] },
      { key: 'lullaby', type: 'machine', title: '오르골 건반', art: '🎵', text: '부기맨 대장: “자장가 따위로 날 재울 수 있을 것 같아?”', buttons: ['도', '레', '미', '솔', '라'], solution: ['도', '도', '솔', '솔', '라', '라', '솔'], result: 'out', hint: ['두 부기맨이 남긴 쪽지를 이어서.', '도 도 솔 솔 라 라 솔'] },
      { key: 'trap1', type: 'trap', from: ['bedman', 'torch'], title: '더 커졌다!', text: '침대 밑 부기맨은 빛을 먹고 더 커졌다! 숨어 있느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['closetman', 'feather'], title: '깜짝이야!', text: '옷장 부기맨은 간지럼을 안 탄다. 대신 “왁!” 하고 놀래켰다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '쌔근쌔근', art: '😴🌅', text: '자장가에 부기맨 대장이 하품하며 잠들었다. 윌리엄의 얼굴에 미소가 번진다. 창밖이 밝아 온다.' },
    ],
  },
  {
    id: 'scheherazade', box: B, title: '세헤라자드의 마지막 이야기', orig: "Scheherazade's Last Tale", diff: 2, theme: '#c87a2a',
    intro: '천 하룻밤의 마지막 밤. 이야기의 결말을 잃어버린 세헤라자드에게 술탄이 사형을 선고했다! 하늘을 날아 그녀를 구하고 이야기를 끝맺자.',
    cards: [
      { key: 'bazaar', type: 'place', start: true, title: '바그다드 시장', art: '🕌🧞🪔🧶', text: '향신료 냄새 가득한 시장. 양탄자 상인이 하품을 하고, 진열대에 먼지 낀 램프가 있다.',
        shows: ['merchant', 'lamp', 'carpet'], spots: [{ label: '비단 가게', x: 22, y: 62, reveal: 'cloth' }, { label: '하늘', emoji: '🌙', x: 80, y: 18, text: '초승달 아래 궁전 첨탑이 보인다. 바람이 동쪽에서 분다.' }] },
      { key: 'merchant', type: 'item', title: '양탄자 상인', art: '🧔', text: '“이 양탄자는 날 수 있지만, 바람의 주문을 아는 자만 태우지. 주문은… 요정만 알걸?”' },
      { key: 'lamp', type: 'red', title: '먼지 낀 램프', art: '🪔', text: '문지르면 무슨 일이 생길 것 같다.' },
      { key: 'cloth', type: 'blue', title: '비단 천', art: '🧣', text: '' },
      { key: 'genie', type: 'item', from: ['lamp', 'cloth'], discard: ['cloth'], title: '램프의 요정', art: '🧞', text: '“펑! 소원 대신 바람의 주문을 알려 주마: 동쪽, 서쪽, 다시 동쪽!”' },
      { key: 'carpet', type: 'machine', title: '하늘을 나는 양탄자', art: '🧶', text: '양탄자 술에 방향 매듭 네 개.', buttons: ['동', '서', '남', '북'], solution: ['동', '서', '동'], result: 'roof', hint: ['요정이 주문을 알려 줘요.', '동 → 서 → 동'] },
      { key: 'roof', type: 'place', title: '궁전 지붕', art: '🏯🌙💂', text: '양탄자를 타고 궁전 지붕에 내렸다! 경비병의 교대 일지가 바람에 날린다. 탑 감옥 문은 숫자 자물쇠.',
        shows: ['schedule', 'prison'], spots: [{ label: '물항아리', x: 26, y: 72, reveal: 'key' }] },
      { key: 'schedule', type: 'item', title: '경비 교대 일지', art: '📜', text: '“교대는 매시 정각과 30분. 감옥 문 비밀번호 = 다음 교대 시각(4자리). 지금 시각 10시 15분.”' },
      { key: 'prison', type: 'code', title: '탑 감옥 문', art: '🚪', text: '숫자 4자리.', code: '1030', result: 'tower', hint: ['일지: 지금 10시 15분, 다음 교대는?', '10시 30분 → 1030'] },
      { key: 'tower', type: 'place', title: '감옥 탑', art: '👸⛓️💍', text: '세헤라자드! “결말이 생각나지 않아요… 어머니의 보석함 속 반지에 순서가 새겨져 있었는데.”', shows: ['jewelbox'] },
      { key: 'jewelbox', type: 'red', title: '보석함', art: '💎', text: '작은 열쇠 구멍.' },
      { key: 'key', type: 'blue', title: '작은 금 열쇠', art: '🗝️', text: '' },
      { key: 'ring', type: 'item', from: ['jewelbox', 'key'], discard: ['jewelbox', 'key'], shows: ['ending'], title: '어머니의 반지', art: '💍', text: '반지 안쪽: “이야기는 해-달-별로 시작해, 별-달-해로 끝난다.”' },
      { key: 'ending', type: 'machine', title: '마지막 이야기', art: '📖', text: '술탄 앞에서 세헤라자드가 이야기를 시작한다. 결말의 문양을 순서대로!', buttons: ['☀️', '🌙', '⭐'], solution: ['⭐', '🌙', '☀️'], result: 'out', hint: ['반지에 새겨진 “끝난다” 쪽.', '⭐ 🌙 ☀️'] },
      { key: 'trap1', type: 'trap', from: ['lamp', 'key'], title: '요정이 화났다', text: '열쇠로 램프를 긁자 요정이 “아야!” 하며 화를 냈다. 달래느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['jewelbox', 'cloth'], title: '안 열린다', text: '비단으로 보석함을 문질러 봤자 반짝이기만 했다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '이야기의 결말', art: '👑📖', text: '이야기가 끝나자 술탄은 감동해 눈물을 흘린다. 세헤라자드는 자유를 얻고, 천 하룻밤의 이야기는 전설이 되었다.' },
    ],
  },
  {
    id: 'challenger', box: B, title: '탐험대: 챌린저', orig: 'Expedition: Challenger', diff: 3, theme: '#4a8a2a',
    intro: '공룡이 사는 아마존의 잃어버린 고원. 챌린저 교수의 탐험대원들이 뿔뿔이 흩어졌다! 지도를 보며 원하는 순서대로 대원들을 구하고, 함께 고원을 탈출하자.',
    cards: [
      { key: 'camp', type: 'place', start: true, title: '고원 야영지', art: '⛺🌋🦕🌴', text: '무너진 텐트, 챌린저 교수의 일지, 고원 지도. 교수: “대원 셋이 사라졌네! 서머리, 맬런, 록스턴 경…”',
        shows: ['journal', 'map'], spots: [{ label: '식량 상자', x: 76, y: 72, reveal: 'meat' }] },
      { key: 'journal', type: 'item', title: '챌린저 교수의 일지', art: '📔', text: '“원주민의 돌문은 공룡 발가락 수로 연다. 티라노 3 · 트리케라톱스 5 · 브론토사우루스 4 · 랩터 3. 내가 고원에서 만난 순서: 브론토, 랩터, 티라노, 트리케라톱스.”' },
      { key: 'map', type: 'item', title: '고원 지도', art: '🗺️', shows: ['nest', 'swamp'], text: '표시된 곳: 프테라노돈 둥지, 티라노 늪, 원주민 동굴(늪 너머). 어디부터 가도 좋다.' },
      { key: 'nest', type: 'place', title: '프테라노돈 둥지', art: '🪺🦅🪨', text: '절벽 위 거대한 둥지에 서머리 교수가 갇혀 있다! 둥지에는 그림이 그려진 거대한 알.',
        shows: ['summerlee', 'egg'], spots: [{ label: '절벽 아래 덤불', x: 20, y: 78, reveal: 'rope' }] },
      { key: 'egg', type: 'item', title: '거대한 알', art: '🥚', text: '알 껍데기에 원주민의 그림: 구름이 동쪽으로, 다시 동쪽으로, 그리고 북쪽으로 흘러간다. “하늘의 길”' },
      { key: 'summerlee', type: 'red', title: '둥지 위 서머리 교수', art: '🧓', text: '“이보게! 여기서 좀 내려 주게!”' },
      { key: 'rope', type: 'blue', title: '덩굴 밧줄', art: '🪢', text: '' },
      { key: 'sumFree', type: 'item', from: ['summerlee', 'rope'], discard: ['summerlee', 'rope'], shows: ['basket'], title: '구출된 서머리', art: '🧓😮‍💨', text: '“고맙네! 탈출용 열기구를 만들 수 있겠어. 바구니는 여기 있고, 가스 주머니는 늪에서 봤네. 불도 필요하지.”' },
      { key: 'swamp', type: 'place', title: '티라노 늪', art: '🦖🌫️🪵', text: '맬런 기자가 쓰러진 통나무 위에서 꼼짝 못 한다. 바로 아래 티라노사우루스가 으르렁거린다!',
        shows: ['trex'], spots: [{ label: '늪 가장자리', x: 76, y: 76, reveal: 'gasbag' }] },
      { key: 'trex', type: 'red', title: '티라노사우루스', art: '🦖', text: '배가 고파 보인다.' },
      { key: 'meat', type: 'blue', title: '말린 고기', art: '🍖', text: '' },
      { key: 'malone', type: 'item', from: ['trex', 'meat'], discard: ['trex', 'meat'], shows: ['cave'], title: '구출된 맬런', art: '📰😅', text: '고기를 멀리 던지자 티라노가 쫓아갔다! 맬런: “록스턴 경은 늪 너머 원주민 동굴에 갇혔어!”' },
      { key: 'gasbag', type: 'blue', title: '가스 주머니', art: '🎈', text: '늪 가스를 가득 머금은 거대한 주머니.' },
      { key: 'cave', type: 'place', title: '원주민 동굴', art: '🗿🔥🕳️', text: '돌문 너머에서 록스턴 경의 목소리가 들린다. 문에 공룡 그림 네 개와 숫자 다이얼.', shows: ['cavelock'] },
      { key: 'cavelock', type: 'code', title: '원주민의 돌문', art: '🗿', text: '숫자 4자리.', code: '4335', result: 'roxton', hint: ['교수의 일지: 만난 순서대로 발가락 수.', '브론토4 · 랩터3 · 티라노3 · 트리케라톱스5 → 4335'] },
      { key: 'roxton', type: 'item', title: '구출된 록스턴 경', art: '🎩🔥', shows: ['torch'], text: '“고맙소! 소총 탄약은 떨어졌지만 원주민의 횃불은 챙겼지.”' },
      { key: 'torch', type: 'blue', title: '원주민의 횃불', art: '🔥', text: '' },
      { key: 'basket', type: 'red', title: '열기구 바구니', art: '🧺', text: '' },
      { key: 'envelope', type: 'red', from: ['basket', 'gasbag'], discard: ['basket', 'gasbag'], title: '열기구', art: '🎈🧺', text: '가스 주머니를 바구니에 매달았다. 이제 불만 붙이면!' },
      { key: 'launch', type: 'machine', from: ['envelope', 'torch'], discard: ['envelope', 'torch'], title: '열기구 조종', art: '🎈🔥', text: '대원 모두가 바구니에 올랐다! 바람을 타야 고원을 벗어날 수 있다.', buttons: ['동', '서', '남', '북'], solution: ['동', '동', '북'], result: 'out', hint: ['둥지의 알 껍데기에 “하늘의 길”이 있어요.', '동 → 동 → 북'] },
      { key: 'trap1', type: 'trap', from: ['trex', 'torch'], title: '화난 티라노', text: '횃불을 휘두르자 티라노가 더 화가 나서 쫓아왔다! 겨우 숨었다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['summerlee', 'meat'], title: '프테라노돈 습격', text: '고기 냄새에 프테라노돈 떼가 몰려왔다! 혼쭐이 났다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '고원 탈출!', art: '🎈🌅', text: '열기구가 고원을 넘어 아마존 강으로 내려간다. 챌린저 교수: “런던 학회가 놀라 자빠지겠군!”' },
    ],
  },
];
