'use strict';
// 언락! — 엑스트라오디너리 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '엑스트라오디너리 어드벤처';
module.exports = [
  {
    id: 'restart', box: B, title: '리스타트', orig: 'Restart', diff: 1, theme: '#5ab8d8',
    intro: '90년대 게임 「크레아리아」 속 왕국이 엉망이 됐다! 게임 속으로 들어가 납치된 왕과 왕비를 구하고 픽셀 왕국에 평화를 되찾자.',
    cards: [
      { key: 'village', type: 'place', start: true, title: '레벨 1: 픽셀 마을', art: '🏘️👾🗡️💾', text: '“PRESS START”. 마을 사람들이 외친다. “마왕이 왕과 왕비를 성에 가뒀어요!” 대장간과 세이브 포인트가 보인다.',
        shows: ['smith', 'savepoint'], spots: [{ label: '항아리', x: 24, y: 72, reveal: 'coin' }] },
      { key: 'savepoint', type: 'item', title: '세이브 포인트', art: '💾', text: '“성문 비밀번호는 마을 집 수와 나무 수를 이어서.” 마을에는 집 3채, 나무 7그루가 있다.' },
      { key: 'smith', type: 'red', title: '대장장이', art: '⚒️', text: '“검을 원하나? 코인 한 개!”' },
      { key: 'coin', type: 'blue', title: '픽셀 코인', art: '🪙', text: '' },
      { key: 'sword', type: 'item', from: ['smith', 'coin'], discard: ['coin'], shows: ['gate'], title: '픽셀 검 획득!', art: '🗡️✨', text: '“용사여, 마왕성은 북쪽이다!” 레벨 업!' },
      { key: 'gate', type: 'code', title: '레벨 2: 마왕성 성문', art: '🏰', text: '숫자 2자리.', code: '37', result: 'castle', hint: ['세이브 포인트의 메시지.', '집 3, 나무 7 → 37'] },
      { key: 'castle', type: 'place', title: '레벨 3: 마왕의 방', art: '😈👑👸🔥', text: '마왕이 왕과 왕비를 새장에 가뒀다! 벽에 패턴 힌트: “↑ ↑ → ← 로 공격을 피해라.”', shows: ['boss'] },
      { key: 'boss', type: 'machine', title: '마왕 전투', art: '🕹️', text: '공격을 피할 방향을 입력!', buttons: ['⬆️', '⬇️', '⬅️', '➡️'], solution: ['⬆️', '⬆️', '➡️', '⬅️'], result: 'out', hint: ['마왕의 방 벽에 패턴이 있어요.', '⬆️ ⬆️ ➡️ ⬅️'] },
      { key: 'trap1', type: 'trap', from: ['smith', 'savepoint'], title: '???', text: '세이브는 합칠 수 없다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: 'CONGRATULATIONS!', art: '👑👸🎉', text: '마왕이 픽셀 조각으로 흩어지고, 왕과 왕비가 풀려났다. 엔딩 크레딧이 올라간다… THE END?' },
    ].filter((c) => c.key !== 'trap1'),
  },
  {
    id: 'hollywood', box: B, title: '할리우드 컨피덴셜', orig: 'Hollywood Confidential', diff: 2, theme: '#c8a03a',
    intro: '1950년대 할리우드. 당신의 보스, 사립 탐정 잭 말로우가 납치됐다! 영화 촬영장 뒤편을 수사해 보스를 구해 내자.',
    cards: [
      { key: 'office', type: 'place', start: true, title: '말로우 탐정 사무소', art: '🕵️🗄️☕🌆', text: '뒤집힌 책상, 식은 커피, 벽에 붙은 수사 메모들. 전화기에 잭의 마지막 메모가 끼워져 있다.',
        shows: ['memo', 'cabinet'], spots: [{ label: '모자걸이', x: 80, y: 30, reveal: 'key' }] },
      { key: 'memo', type: 'item', title: '잭의 마지막 메모', art: '📝', text: '“스타라이트 스튜디오 필름 도난 사건 — 용의자: 여배우 비비안, 감독 오슨, 조명기사 잭슨. 증거는 내 서류함에.”' },
      { key: 'cabinet', type: 'red', title: '잠긴 서류함', art: '🗄️', text: '' },
      { key: 'key', type: 'blue', title: '서류함 열쇠', art: '🔑', text: '' },
      { key: 'file', type: 'item', from: ['cabinet', 'key'], discard: ['cabinet', 'key'], shows: ['studio'], title: '수사 파일', art: '📂', text: '사진 속 필름 금고 앞에 라이터 불빛. 메모: “스튜디오 경비원이 라이터를 가진 자를 봤다.”' },
      { key: 'studio', type: 'place', title: '스타라이트 스튜디오', art: '🎬🎥💄🕶️', text: '빈 필름 금고, 배우 대기실, 감독 의자, 조명 장치. 대기실 거울에 립스틱 숫자가 남아 있다.',
        shows: ['suspects', 'vault'], spots: [{ label: '감독의 의자', x: 24, y: 60, reveal: 'lighter' }, { label: '대기실 거울', emoji: '💄', x: 76, y: 40, text: '립스틱으로 쓴 숫자: 5 · 2 · 8' }, { label: '경비원 책상', x: 50, y: 76, reveal: 'locker' }] },
      { key: 'suspects', type: 'item', title: '용의자 명단', art: '📋', text: '1. 여배우 비비안(립스틱) · 2. 감독 오슨(시가) · 3. 조명기사 잭슨(금장 라이터). 경비원: “어젯밤 금고 근처에서 라이터 불빛을 봤소.”' },
      { key: 'vault', type: 'item', title: '빈 필름 금고', art: '🗄️', text: '금고 바닥에 라이터 기름 자국. 그리고 “J”가 새겨진 커프스 단추.' },
      { key: 'lighter', type: 'red', title: '금장 라이터', art: '🪔', text: '“J” 이니셜.' },
      { key: 'locker', type: 'blue', title: '조명기사 사물함 열쇠', art: '🔑', text: '경비원이 빌려준 마스터키.' },
      { key: 'jackson', type: 'place', from: ['lighter', 'locker'], discard: ['lighter', 'locker'], shows: ['reel'], title: '조명기사 잭슨의 사물함', art: '🧰🎞️', text: '라이터와 같은 J! 사물함 속 필름 통과 쪽지: “여배우가 거울에 남긴 숫자를 거꾸로. 잭 말로우는 B 스테이지 소품 창고에.”' },
      { key: 'reel', type: 'code', title: '필름 통 자물쇠', art: '🎞️', text: '숫자 3자리.', code: '825', result: 'stage', hint: ['대기실 거울의 숫자를 거꾸로.', '5·2·8 → 825'] },
      { key: 'stage', type: 'place', title: 'B 스테이지 소품 창고', art: '🎭🪑📽️', text: '밧줄에 묶인 잭 말로우! “이 영사기를 켜면 놈들이 숨긴 진짜 필름이 돌아가며 증거가 남을 거야. 감기 → 초점 → 재생 순서로!”', shows: ['proj'] },
      { key: 'proj', type: 'machine', title: '영사기', art: '📽️', text: '세 버튼.', buttons: ['▶ 재생', '🔍 초점', '🔄 감기'], solution: ['🔄 감기', '🔍 초점', '▶ 재생'], result: 'out', hint: ['잭이 순서를 알려 줘요.', '감기 → 초점 → 재생'] },
      { key: 'trap1', type: 'trap', from: ['cabinet', 'locker'], title: '열쇠가 안 맞아', text: '스튜디오 마스터키로 사무소 서류함을 열려다 열쇠가 끼어 버렸다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '사건 종결', art: '🎬🌟', text: '영사기에 잭슨이 경쟁 스튜디오와 거래하는 장면이 찍혀 있었다! 잭 말로우가 모자를 고쳐 쓴다. “좋은 수사였어, 파트너.”' },
    ],
  },
  {
    id: 'waff', box: B, title: 'W.A.F.F. 오디세이', orig: "The W.A.F.F.'s Odyssey", diff: 3, theme: '#3a3ab8',
    intro: '먼 행성에서 신호가 왔다 — 이상한 생명체가 있을지도 모른다! 우주견 연맹(W.A.F.F.)의 강아지 우주비행사가 되어 행성을 탐사하고 무사히 지구로 귀환하자. 멍!',
    cards: [
      { key: 'bridge', type: 'place', start: true, title: '우주선 조종실', art: '🚀🐕🌌📡', text: '신호 수신기가 삐빅거린다. 함장 비글이 짖는다. “착륙선을 내리자! 그런데 산소 재생기가 고장이다!”',
        shows: ['oxygen', 'signal'], spots: [{ label: '사료 그릇', x: 24, y: 72, reveal: 'bone' }, { label: '창밖', emoji: '🪐', x: 78, y: 24, text: '창밖 행성 번호: 화성 4, 목성 5, 토성 6. 목표 행성은 토성의 위성.' }] },
      { key: 'signal', type: 'item', title: '수신된 신호', art: '📡', text: '반복 패턴: 🟣 🟢 🟣 🟡. “생명체의 언어일지도 모른다.”' },
      { key: 'oxygen', type: 'red', title: '산소 재생기', art: '🫧', text: '뼈다귀 모양 부품 칸이 비었다.' },
      { key: 'bone', type: 'blue', title: '뼈다귀 부품', art: '🦴', text: '' },
      { key: 'air', type: 'item', from: ['oxygen', 'bone'], discard: ['oxygen', 'bone'], shows: ['lander'], title: '산소 복구', art: '🫧✅', text: '숨쉬기 편해졌다! 착륙선 격납고 문이 열린다.' },
      { key: 'lander', type: 'place', title: '착륙선 → 외계 행성', art: '🛸🌋👽', text: '보랏빛 하늘, 수정 나무. 젤리처럼 말랑한 외계 생명체들이 다가온다. 그들의 몸이 색깔로 깜빡인다.',
        shows: ['aliens'], spots: [{ label: '수정 나무 아래', x: 76, y: 66, reveal: 'crystal' }] },
      { key: 'aliens', type: 'machine', title: '색깔 대화', art: '👽💬', text: '착륙선의 색깔 신호등으로 인사하자. 같은 신호를 돌려주면 친구가 될 수 있을지도.', buttons: ['🟢', '🟡', '🟣', '🔴'], solution: ['🟣', '🟢', '🟣', '🟡'], result: 'friends', hint: ['조종실에서 받은 신호 패턴.', '🟣 🟢 🟣 🟡'] },
      { key: 'friends', type: 'item', title: '외계 친구들', art: '👽🐶', text: '외계인들이 기뻐하며 꼬리(?)를 흔든다. 선물로 반짝이는 연료 수정을 가리킨다. “엔진에 넣으면 집에 갈 수 있어!” (몸짓으로)' },
      { key: 'crystal', type: 'blue', title: '연료 수정', art: '💎', text: '' },
      { key: 'engine', type: 'place', title: '귀환: 엔진실', art: '⚙️🔥🐾', text: '우주선으로 돌아왔다. 엔진 연료 칸이 비었다. 벽 안내문: “점화 버튼은 작은 발 → 큰 발 순서로.” 렌치 위 낙서: “항법 좌표 = 지구는 3번째 행성! 지구-화성-목성 순서로 행성 번호.”',
        shows: ['tank'] },
      { key: 'tank', type: 'red', title: '빈 연료 칸', art: '⛽', text: '' },
      { key: 'ignite', type: 'machine', from: ['tank', 'crystal'], discard: ['tank', 'crystal'], title: '점화 패널', art: '🐾', text: '수정을 넣자 패널에 불이 들어왔다. 발바닥 버튼.', buttons: ['🐾 큰 발', '🐾 아주 작은 발', '🐾 중간 발', '🐾 작은 발'], solution: ['🐾 아주 작은 발', '🐾 작은 발', '🐾 중간 발', '🐾 큰 발'], result: 'fire', hint: ['안내문: 작은 발부터.', '아주 작은 → 작은 → 중간 → 큰'] },
      { key: 'fire', type: 'item', title: '엔진 점화!', art: '🔥🚀', shows: ['nav'], text: '엔진이 우렁차게 깨어났다. 조종실의 항법 컴퓨터가 켜졌다!' },
      { key: 'nav', type: 'code', title: '항법 컴퓨터', art: '🧭', text: '숫자 3자리 항법 좌표.', code: '345', result: 'out', hint: ['엔진실 낙서와 조종실 창밖 행성 번호.', '지구3 · 화성4 · 목성5 → 345'] },
      { key: 'trap1', type: 'trap', from: ['oxygen', 'crystal'], title: '산소가 보라색으로!', text: '수정을 산소 재생기에 넣었더니 공기가 보라색으로 변했다! 모두 콜록콜록.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '지구 귀환', art: '🌍🐶', text: '우주선이 대기권을 뚫고 바다에 착수! 강아지 우주비행사들이 꼬리를 흔든다. 외계 친구들의 사진은 W.A.F.F. 명예의 전당에 걸렸다.' },
    ].map((c) => (c.key === 'friends' ? { ...c, shows: ['engine'] } : c)),
  },
];
