'use strict';
// 언락! — 게임 어드벤처 (다른 보드게임을 테마로 한 원작 박스의 분위기를 따른 오리지널 수수께끼)

const B = '게임 어드벤처';
module.exports = [
  {
    id: 'tickettoride', box: B, title: '티켓 투 라이드: 대륙 횡단 열차', orig: 'Ticket to Ride', diff: 1, theme: '#c83a3a',
    intro: '1900년, 철도 사업가가 되어 대륙 횡단 노선 경쟁에 뛰어들었다! 기차표를 모아 노선을 잇고, 경쟁자보다 먼저 종착역에 도착하자.',
    cards: [
      { key: 'station', type: 'place', start: true, title: '시애틀 출발역', art: '🚉🚂🎫🗺️', text: '노선도: 시애틀 → 덴버(초록 노선 4칸) → 시카고(노랑 3칸) → 뉴욕(빨강 5칸). 매표소 창구 앞에 줄이 길다.',
        shows: ['ticket', 'routemap'], spots: [{ label: '벤치 위 가방', x: 24, y: 66, reveal: 'coin' }] },
      { key: 'routemap', type: 'item', title: '노선도', art: '🗺️', text: '노선마다 색깔 기차 칸을 놓아야 한다. 경쟁자 “밴더빌트 철도”가 이미 시카고까지 놓았다는 소문!' },
      { key: 'ticket', type: 'red', title: '매표소 창구', art: '🎫', text: '“목적지 티켓 한 장에 금화 한 닢.”' },
      { key: 'coin', type: 'blue', title: '금화', art: '🪙', text: '' },
      { key: 'train', type: 'place', from: ['ticket', 'coin'], discard: ['ticket', 'coin'], shows: ['route', 'conductor'], title: '대륙 횡단 열차', art: '🚂🚃🚃', text: '목적지 티켓 “시애틀 → 뉴욕”을 사서 올라탔다. 차장이 다가온다.' },
      { key: 'conductor', type: 'item', title: '차장', art: '👨‍✈️', text: '“노선 스위치는 시애틀부터 노선 색깔 순서대로! 그리고 종착역 승강장 번호는 모든 노선 칸 수의 합이오.”' },
      { key: 'route', type: 'machine', title: '노선 스위치', art: '🎚️', text: '색깔 레버.', buttons: ['🔴', '🟡', '🟢', '🔵'], solution: ['🟢', '🟡', '🔴'], result: 'platform', hint: ['노선도: 시애틀부터 노선 색.', '🟢 → 🟡 → 🔴'] },
      { key: 'platform', type: 'code', title: '뉴욕 종착역 승강장', art: '🗽', text: '승강장 번호 2자리를 입력하면 기차가 들어간다.', code: '12', result: 'out', hint: ['칸 수: 4 + 3 + 5.', '12'] },
      { key: 'out', type: 'item', end: true, title: '1등 도착!', art: '🏆🚂', text: '경적을 울리며 뉴욕역에 1등으로 들어왔다. 가장 긴 노선 보너스까지!' },
    ],
  },
  {
    id: 'mysterium', box: B, title: '미스테리움: 유령 저택의 꿈', orig: 'Mysterium', diff: 2, theme: '#5a3a8a',
    intro: '워윅 저택에 사는 유령이 살해당한 진실을 알려 달라며 꿈으로 환영을 보낸다. 모호한 그림 속 단서를 읽고 범인, 장소, 흉기를 밝혀 영혼을 풀어 주자.',
    cards: [
      { key: 'parlor', type: 'place', start: true, title: '워윅 저택 응접실', art: '🏚️🔮🕯️👻', text: '강령회 탁자. 수정 구슬 주위로 유령이 보낸 꿈의 카드들. 유령이 괘종시계를 가리킨다.',
        shows: ['dream1', 'clock'], spots: [{ label: '피아노 뚜껑 속', x: 80, y: 64, reveal: 'key' }, { label: '수정 구슬', emoji: '🔮', x: 50, y: 50, text: '구슬 속에 열쇠 모양 그림자가 피아노 쪽으로 흔들린다.' }] },
      { key: 'dream1', type: 'item', title: '첫 번째 꿈 — 누가?', art: '🌹✂️🌿', text: '장미 덤불, 날카로운 가위, 진흙 묻은 장화. (용의자: 정원사 · 요리사 · 집사)' },
      { key: 'clock', type: 'red', title: '괘종시계 문', art: '🕰️', text: '시계 몸통에 작은 문과 열쇠 구멍.' },
      { key: 'key', type: 'blue', title: '은 열쇠', art: '🗝️', text: '' },
      { key: 'inclock', type: 'item', from: ['clock', 'key'], discard: ['clock', 'key'], shows: ['dream2', 'library'], title: '시계 속 두 번째 꿈', art: '📚🕯️', text: '시계 속에 꿈의 카드가 숨겨져 있었다.' },
      { key: 'dream2', type: 'item', title: '두 번째 꿈 — 어디서?', art: '📚🦉🕯️', text: '먼지 쌓인 책장, 부엉이 박제, 꺼진 촛대. (장소: 정원 · 서재 · 다락방)' },
      { key: 'library', type: 'place', title: '서재', art: '📚🦉🪜', text: '꿈에서 본 그대로의 서재! 부엉이 박제가 사다리 위 책장을 응시한다. 책장 맨 위 칸에 낡은 상자.', shows: ['ladder'], spots: [{ label: '부엉이 박제 받침', x: 30, y: 40, reveal: 'chain' }] },
      { key: 'ladder', type: 'red', title: '흔들리는 사다리', art: '🪜', text: '고정 고리가 빠졌다.' },
      { key: 'chain', type: 'blue', title: '고정 사슬', art: '⛓️', text: '' },
      { key: 'topbox', type: 'item', from: ['ladder', 'chain'], discard: ['ladder', 'chain'], shows: ['dream3', 'spiritbox'], title: '책장 위 상자', art: '📦', text: '사다리를 고정하고 올라가 상자를 꺼냈다. 마지막 꿈의 카드와, 그림 버튼이 달린 영혼 상자.' },
      { key: 'dream3', type: 'item', title: '세 번째 꿈 — 무엇으로?', art: '🪢🌙⚓', text: '꼬인 밧줄, 뱃사람의 매듭, 달빛. (흉기: 촛대 · 밧줄 · 독약)' },
      { key: 'spiritbox', type: 'machine', title: '영혼 상자', art: '📦👻', text: '그림 버튼: 가위, 촛대, 밧줄, 정원, 서재, 다락. “누가 — 어디서 — 무엇으로, 그 순서로 누르면 영혼이 풀려난다.”', buttons: ['✂️ 가위', '🕯️ 촛대', '🪢 밧줄', '🌷 정원', '📚 서재', '🏠 다락'], solution: ['✂️ 가위', '📚 서재', '🪢 밧줄'], result: 'out',
        hint: ['꿈 1: 정원사(→ 가위), 꿈 2: 서재, 꿈 3: 밧줄.', '✂️ 가위 → 📚 서재 → 🪢 밧줄'] },
      { key: 'trap1', type: 'trap', from: ['ladder', 'key'], title: '쿵!', text: '열쇠로 사다리를 고정하려다 사다리가 쓰러졌다. 유령이 깜짝 놀라 촛불을 꺼 버렸다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '영혼의 안식', art: '👻✨', text: '“정원사가 서재에서 밧줄로…” 진실이 밝혀지자 유령이 미소 지으며 빛 속으로 사라진다.' },
    ],
  },
  {
    id: 'pandemic', box: B, title: '팬데믹: 백신 연구소', orig: 'Pandemic', diff: 3, theme: '#2a8ab8', limit: 70,
    intro: '세 가지 질병이 세계로 퍼지고 있다. 질병통제센터 연구팀이 되어 70분 안에 세 치료제를 모두 개발하자! (원작처럼 70분)',
    cards: [
      { key: 'cdc', type: 'place', start: true, title: '애틀랜타 질병통제센터', art: '🏥🦠🌍🧫', text: '세계 지도에 질병 큐브가 가득하다: 🔵 파랑, 🟡 노랑, 🔴 빨강. 연구실 세 곳은 모두 봉쇄 중. 화이트보드에 상황판.',
        shows: ['board', 'map', 'bluelab'], spots: [{ label: '연구원 사물함', x: 20, y: 66, reveal: 'badge' }] },
      { key: 'board', type: 'item', title: '상황판', art: '📋', text: '“발병 마커 3 · 감염률 2. 연구실 출입증은 사물함에. 치료제 코드는 각 질병 도시들의 큐브 수를 도시 이름의 가나다순으로.”' },
      { key: 'map', type: 'item', title: '세계 감염 지도', art: '🗺️', text: '🔵 파랑: 런던 2 · 파리 3 · 뉴욕 1. 🟡 노랑: 라고스 3 · 보고타 1 · 상파울루 2. 🔴 빨강: 서울 3 · 도쿄 2 · 베이징 1 · 홍콩 2.' },
      { key: 'bluelab', type: 'red', title: '파랑 연구실 문', art: '🚫🔵', text: '출입증 리더기.' },
      { key: 'badge', type: 'blue', title: '연구원 출입증', art: '🪪', text: '' },
      { key: 'lab1', type: 'place', from: ['bluelab', 'badge'], discard: ['bluelab'], shows: ['bluecure'], title: '파랑 질병 연구실', art: '🔬🧪🔵', text: '샘플 합성기가 기다린다. 화면: “파랑 치료제 코드 3자리.”' },
      { key: 'bluecure', type: 'code', title: '파랑 치료제 합성', art: '💉🔵', text: '숫자 3자리.', code: '123', result: 'blueok', hint: ['파랑 도시를 가나다순: 뉴욕, 런던, 파리.', '뉴욕1 · 런던2 · 파리3 → 123'] },
      { key: 'blueok', type: 'item', title: '파랑 치료제 완성', art: '✅🔵', shows: ['yellowlab'], text: '첫 번째 치료제! 노랑 연구실의 봉쇄가 풀리려면 출입증을 다시 찍어야 한다.' },
      { key: 'yellowlab', type: 'red', title: '노랑 연구실 문', art: '🚫🟡', text: '' },
      { key: 'lab2', type: 'place', from: ['yellowlab', 'badge'], discard: ['yellowlab'], shows: ['samples'], title: '노랑 질병 연구실', art: '🔬🧫🟡', text: '샘플 다섯 개(A~E)와 투입구. 메모: “감염률(2)의 배수 순번은 오염 샘플! 나머지만 넣을 것.”' },
      { key: 'samples', type: 'machine', title: '샘플 투입구', art: '⚗️', text: '샘플을 순서대로 넣는다.', buttons: ['A', 'B', 'C', 'D', 'E'], solution: ['A', 'C', 'E'], result: 'yellowcure', hint: ['B(2번째), D(4번째)는 2의 배수 — 오염!', 'A → C → E'] },
      { key: 'yellowcure', type: 'code', title: '노랑 치료제 합성', art: '💉🟡', text: '숫자 3자리.', code: '312', result: 'yellowok', hint: ['노랑 도시를 가나다순으로: 라고스, 보고타, 상파울루.', '라고스3 · 보고타1 · 상파울루2 → 312'] },
      { key: 'yellowok', type: 'item', title: '노랑 치료제 완성', art: '✅🟡', shows: ['redlab', 'director'], text: '두 번째 치료제! 빨강 연구실은 출입증만으로는 안 열린다. 연구소장의 지문이 필요하다.' },
      { key: 'redlab', type: 'red', title: '빨강 연구실 문', art: '🚫🔴', text: '지문 인식기.' },
      { key: 'director', type: 'place', title: '연구소장실', art: '🧑‍⚕️☕📂', text: '연구소장이 과로로 쓰러져 잠들었다. 책상 위 커피잔에 선명한 지문.', spots: [{ label: '커피잔', x: 50, y: 60, reveal: 'print' }] },
      { key: 'print', type: 'blue', title: '소장의 지문 테이프', art: '🫆', text: '' },
      { key: 'lab3', type: 'place', from: ['redlab', 'print'], discard: ['redlab', 'print'], shows: ['redcure'], title: '빨강 질병 연구실', art: '🔬🧬🔴', text: '마지막 합성기. 화면: “빨강 치료제 코드 4자리 — 감염 도시가 넷이다.”' },
      { key: 'redcure', type: 'code', title: '빨강 치료제 합성', art: '💉🔴', text: '숫자 4자리.', code: '2132', result: 'out', hint: ['빨강 도시 가나다순: 도쿄, 베이징, 서울, 홍콩.', '도쿄2 · 베이징1 · 서울3 · 홍콩2 → 2132'] },
      { key: 'trap1', type: 'trap', from: ['bluelab', 'print'], title: '지문 오류', text: '파랑 연구실은 출입증 리더기다. 지문을 대자 경보가 울렸다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '인류의 승리', art: '🌍💉', text: '세 치료제가 모두 완성됐다! 전 세계 병원으로 치료제가 날아간다.' },
    ],
  },
];
