'use strict';
// 언락! — 히로익 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '히로익 어드벤처';
module.exports = [
  {
    id: 'insertcoin', box: B, title: '인서트 코인', orig: 'Insert Coin', diff: 1, theme: '#d83a8a',
    intro: '낡은 오락실 게임기에 동전을 넣는 순간 화면 속으로 빨려 들어갔다! 고전 게임을 닮은 스테이지들을 깨고 최종 보스를 쓰러뜨려야 현실로 돌아갈 수 있다.',
    cards: [
      { key: 'stage1', type: 'place', start: true, title: '스테이지 1: 버섯 왕국', art: '🍄🧱🟩🚩', text: '점프! 벽돌 블록, 초록 파이프, 결승 깃대. 화면 위 점수판: HI-SCORE 0000.',
        shows: ['pipe', 'flag'], spots: [{ label: '? 블록', x: 30, y: 26, reveal: 'coin' }] },
      { key: 'flag', type: 'item', title: '결승 깃대', art: '🚩', text: '깃대에 스테이지 번호: 1-1 · 1-2 · 1-3 · 1-4' },
      { key: 'pipe', type: 'red', title: '초록 파이프', art: '🟩', text: '“INSERT COIN” 투입구가 달려 있다.' },
      { key: 'coin', type: 'blue', title: '반짝이는 코인', art: '🪙', text: '' },
      { key: 'stage2', type: 'place', from: ['pipe', 'coin'], discard: ['pipe', 'coin', 'stage1'], shows: ['maze'], title: '스테이지 2: 유령 미로', art: '🟡👻🍒⬛', text: '파이프를 타고 내려오니 점이 가득한 미로! 유령 넷이 쫓아온다. 출구를 찾아야 한다.',
        spots: [{ label: '체리', x: 70, y: 30, reveal: 'mazemap' }] },
      { key: 'mazemap', type: 'item', title: '체리 속 지도', art: '🍒🗺️', text: '체리 씨에 새겨진 출구 경로: ⬆️ ➡️ ➡️ ⬇️ ➡️' },
      { key: 'maze', type: 'machine', title: '조이스틱', art: '🕹️', text: '방향을 입력하세요.', buttons: ['⬆️', '⬇️', '⬅️', '➡️'], solution: ['⬆️', '➡️', '➡️', '⬇️', '➡️'], result: 'stage3', hint: ['미로 속 체리를 자세히 보세요.', '⬆️ ➡️ ➡️ ⬇️ ➡️'] },
      { key: 'stage3', type: 'place', title: '스테이지 3: 우주 침공', art: '🚀👾👾👾', text: '외계인 편대가 내려온다! 우주선의 레이저는 탄약이 바닥났다.',
        shows: ['ship'], spots: [{ label: '떨어지는 별', x: 80, y: 22, reveal: 'powerup' }, { label: '격추된 외계인 잔해', x: 30, y: 70, reveal: 'cheat' }] },
      { key: 'ship', type: 'red', title: '레이저 우주선', art: '🚀', text: '' },
      { key: 'powerup', type: 'blue', title: '파워 업 캡슐', art: '⭐', text: '' },
      { key: 'cheat', type: 'item', title: '비밀 공략 쪽지', art: '📜', text: '“보스의 무적 해제 커맨드: 위 위 아래 아래 왼쪽 오른쪽 왼쪽 오른쪽”' },
      { key: 'blast', type: 'item', from: ['ship', 'powerup'], discard: ['ship', 'powerup'], shows: ['blocks'], title: '편대 격추!', art: '💥👾', text: '파워 업! 외계인 편대가 모두 터졌다. 화면이 바뀌며 블록이 쏟아진다.' },
      { key: 'blocks', type: 'code', title: '스테이지 4: 블록 쌓기', art: '🟦🟨🟥🟩', text: '블록이 4줄 쌓였다. 각 줄의 빈칸 위치(왼쪽부터): 맨 위 줄 3번째, 둘째 줄 1번째, 셋째 줄 4번째, 맨 아래 줄 2번째. 빈칸 위치를 위에서부터 입력해 모든 줄을 지우자!', code: '3142', result: 'boss', hint: ['빈칸 위치를 맨 위 줄부터 차례로.', '3 · 1 · 4 · 2 → 3142'] },
      { key: 'boss', type: 'machine', title: '최종 보스: 메가 드래곤', art: '🐉🔥', text: '보스가 무적 상태로 불을 뿜는다! 커맨드를 입력하세요.', buttons: ['⬆️', '⬇️', '⬅️', '➡️'], solution: ['⬆️', '⬆️', '⬇️', '⬇️', '⬅️', '➡️', '⬅️', '➡️'], result: 'score', hint: ['우주 스테이지에서 찾은 공략 쪽지.', '⬆️⬆️⬇️⬇️⬅️➡️⬅️➡️'] },
      { key: 'score', type: 'code', title: '최고 점수 등록', art: '🏆', text: '보스 격파! “스테이지 1의 깃대에 적힌 번호의 끝자리를 이어서 입력하면 현실로 돌아갑니다.”', code: '1234', result: 'out', hint: ['스테이지 1의 결승 깃대.', '1-1, 1-2, 1-3, 1-4 → 1234'] },
      { key: 'trap1', type: 'trap', from: ['ship', 'coin'], title: 'GAME OVER?', text: '우주선에 코인을 넣자 “CONTINUE? 10… 9…” 겨우 이어서 했다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: 'GAME CLEAR!', art: '🎮✨', text: '눈부신 빛과 함께 오락실 의자로 돌아왔다. 화면 속 랭킹 1위에 당신의 이름이 반짝인다.' },
    ],
  },
  {
    id: 'scarlet', box: B, title: '셜록 홈즈: 주홍색 연구', orig: 'Sherlock Holmes: The Scarlet Thread of Murder', diff: 2, theme: '#8a2a2a',
    intro: '런던 브릭스턴 로드의 빈집에서 미국인 드레버의 시신이 발견됐다. 벽에는 붉은 글씨 “RACHE”. 홈즈와 함께 세 용의자를 찾아 사건의 순서를 맞추고, 범인과 동기를 밝혀라.',
    cards: [
      { key: 'house', type: 'place', start: true, title: '로리스턴 가든 3번지', art: '🏚️🩸🕯️🎩', text: '시신 곁에 여자 결혼반지. 벽에 핏빛 글씨. 레스트레이드 경감이 수첩을 들고 서 있다.',
        shows: ['wall', 'ring', 'body'], spots: [{ label: '창틀', x: 80, y: 26, reveal: 'lens' }, { label: '바닥', emoji: '👣', x: 40, y: 82, text: '진흙 발자국 두 쌍 — 하나는 드레버의 에나멜 구두, 하나는 큰 장화. 마차 바퀴 자국이 문 앞까지.' }] },
      { key: 'wall', type: 'item', title: '벽의 글씨', art: '🖋️', text: '“RACHE” — 레스트레이드: “레이첼이라는 여자를 찾아야 해!” 홈즈: “독일어로 ‘복수’라는 뜻이지, 경감.”' },
      { key: 'body', type: 'item', title: '드레버의 시신', art: '⚰️', shows: ['boarding'], text: '외상은 없다. 입술에서 쓴 아몬드 냄새 — 독이다. 주머니에 샤르팡티에 하숙집 영수증.' },
      { key: 'ring', type: 'red', title: '여자 결혼반지', art: '💍', text: '안쪽에 아주 작게 무언가 새겨져 있다.' },
      { key: 'lens', type: 'blue', title: '홈즈의 돋보기', art: '🔍', text: '' },
      { key: 'engr', type: 'item', from: ['ring', 'lens'], discard: ['ring'], shows: ['telegram'], title: '반지의 새김', art: '💍🔍', text: '“J.H. ♥ L.F. — 솔트레이크, 1847”. 홈즈: “반지를 찾으러 올 사람은 반지에 새겨진 남자일세.”' },
      { key: 'telegram', type: 'code', title: '클리블랜드 경찰에 보낼 전보', art: '📨', text: '전보 양식: 용의자 머리글자 두 개를 알파벳 순번(A=1 … Z=26)으로, 각각 두 자리씩.', code: '1008', result: 'reply', hint: ['반지에 새겨진 남자의 머리글자는 J.H.', 'J = 10, H = 08 → 1008'] },
      { key: 'reply', type: 'item', title: '답장 전보', art: '📩', text: '“J.H. = 제퍼슨 호프. 약혼녀 루시 페리어는 드레버에게 강제로 결혼당한 뒤 숨졌다. 호프는 지금 런던에서 마부로 일한다. 마차 번호는 그가 루시와 약혼한 해의 끝 두 자리.”' },
      { key: 'boarding', type: 'place', title: '샤르팡티에 하숙집', art: '🏠🫖👩‍🦳', text: '하숙집 주인 샤르팡티에 부인과 아들 아서 중위. 부인은 무언가 숨기는 눈치다.',
        shows: ['landlady', 'arthur'], spots: [{ label: '드레버의 방 서랍', x: 76, y: 60, reveal: 'pills' }] },
      { key: 'landlady', type: 'item', title: '샤르팡티에 부인의 증언', art: '👩‍🦳', text: '“드레버는 밤 8시에 짐을 싸서 나갔어요. 그런데 딸을 희롱하러 다시 돌아와서… 아들이 몽둥이를 들고 8시 10분에 쫓아 나갔죠.”' },
      { key: 'arthur', type: 'item', title: '아서 중위의 증언', art: '💂', text: '“쫓아가긴 했지만 골목에서 놓쳤소. 그 자는 8시 30분쯤 지나가던 이륜마차를 잡아탔지. 나는 집에 돌아왔소.”' },
      { key: 'pills', type: 'red', title: '알약 상자', art: '💊', text: '똑같이 생긴 알약 두 개가 들어 있다.' },
      { key: 'bakerst', type: 'place', title: '베이커가 221B', art: '🎻🧪📚🐕', text: '홈즈의 하숙방. 화학 실험대, 바이올린, 허드슨 부인이 맡긴 늙고 병든 테리어 한 마리.', spots: [{ label: '테리어 바구니', x: 76, y: 70, reveal: 'dog' }] },
      { key: 'dog', type: 'blue', title: '늙은 테리어', art: '🐕', text: '아파서 오래 살지 못할 것이라고 한다.' },
      { key: 'test', type: 'item', from: ['pills', 'dog'], discard: ['pills'], shows: ['timeline'], title: '알약 실험', art: '🧪', text: '첫 알약을 녹여 주자 개는 멀쩡했다. 둘째 알약 — 개는 즉시 쓰러졌다. 홈즈: “범인은 피해자에게 독과 무해한 알약 중 하나를 고르게 했군. 새벽 1시, 빈집에서. ‘신의 심판’이라며.”' },
      { key: 'timeline', type: 'machine', title: '사건 재구성', art: '🧩', text: '홈즈: “사건을 일어난 순서대로 맞춰 보게, 왓슨.”', buttons: ['🐎 마차를 탐', '💊 빈집에서 독 알약', '🫖 하숙집을 나감', '🏃 아서가 쫓아감'], solution: ['🫖 하숙집을 나감', '🏃 아서가 쫓아감', '🐎 마차를 탐', '💊 빈집에서 독 알약'], result: 'deduce', hint: ['8시, 8시 10분, 8시 30분, 새벽 1시.', '나감 → 쫓아감 → 마차 → 독 알약'] },
      { key: 'deduce', type: 'item', title: '홈즈의 결론', art: '🎩💡', shows: ['cabrank'], text: '“드레버를 태운 마차의 마부가 범인일세. 장화 발자국, 마차 바퀴 자국, 반지, 그리고 복수(RACHE). 마부를 부르게!”' },
      { key: 'cabrank', type: 'code', title: '마차 승강장', art: '🐎', text: '수많은 이륜마차. 번호 2자리를 부르면 그 마차가 온다.', code: '47', result: 'out', hint: ['답장 전보: 약혼한 해의 끝 두 자리. 반지에 새겨진 해.', '1847 → 47'] },
      { key: 'trap1', type: 'trap', from: ['pills', 'lens'], title: '위험해!', text: '돋보기로 알약을 들여다보다 냄새를 맡을 뻔했다. 홈즈가 낚아챘다. “함부로 만지지 말게!”', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '수갑을 채우다', art: '🔗🎩', text: '홈즈가 짐 옮기는 걸 도와 달라며 마부를 부르고, 순간 수갑을 채운다. “여러분, 제퍼슨 호프 씨를 소개하지.” 복수는 그렇게 끝났다.' },
    ].map((c) => (c.key === 'reply' ? { ...c, shows: ['bakerst'] } : c)),
  },
  {
    id: 'whiterabbit', box: B, title: '하얀 토끼를 쫓아서', orig: 'In Pursuit of the White Rabbit', diff: 3, theme: '#d85a9a',
    intro: '작가 루이스 캐럴이 「이상한 나라의 앨리스」의 결말을 쓰지 못하고 있다. 그때 원고 속에서 하얀 토끼가 뛰쳐나왔다! 앨리스와 함께 이상한 나라를 여행하며 이야기의 끝을 찾아 주자.',
    cards: [
      { key: 'study', type: 'place', start: true, title: '캐럴의 서재', art: '🖋️📜🐇🕰️', text: '책상 위 미완성 원고. 조끼 입은 하얀 토끼가 “늦었다, 늦었어!” 외치며 방을 뛰어다닌다. 바닥에 무언가 떨어져 있다.',
        shows: ['manuscript', 'rabbit'], spots: [{ label: '카펫 위', x: 46, y: 80, reveal: 'watch' }] },
      { key: 'manuscript', type: 'item', title: '미완성 원고', art: '📜', text: '“…그리고 앨리스는 —” 여기서 끊겼다. 여백 메모: “출판일은 앨리스와 보트를 탄 날, 7월 4일로 하자.”' },
      { key: 'rabbit', type: 'red', title: '허둥대는 하얀 토끼', art: '🐇', text: '“내 시계! 내 시계 못 봤어?”' },
      { key: 'watch', type: 'blue', title: '토끼의 회중시계', art: '⏱️', text: '' },
      { key: 'hall', type: 'place', from: ['rabbit', 'watch'], discard: ['rabbit', 'watch'], shows: ['door', 'drink'], title: '문이 많은 복도', art: '🚪🚪🔑🍰', text: '시계를 돌려주자 토끼가 굴로 뛰어들었고, 정신을 차려 보니 앨리스와 함께 문이 많은 복도에! 아주 작은 문과 “나를 마셔요” 병.' },
      { key: 'door', type: 'red', title: '아주 작은 문', art: '🚪', text: '쥐구멍만 하다.' },
      { key: 'drink', type: 'blue', title: '“나를 마셔요”', art: '🧪', text: '마시면 작아진다.' },
      { key: 'forest', type: 'place', from: ['door', 'drink'], discard: ['door', 'drink'], shows: ['caterpillar'], title: '버섯 숲', art: '🍄🐛💨', text: '작아져서 문을 통과! 거대한 버섯 위에서 애벌레가 물담배를 피운다.' },
      { key: 'caterpillar', type: 'code', title: '애벌레의 질문', art: '🐛', text: '“너는 누구니? …대답 대신 내 다리 수를 맞혀 봐. 앞다리 6개, 배다리 10개. 합쳐서 말해 봐.”', code: '16', result: 'mushroom', hint: ['애벌레가 다 알려 줬어요.', '6 + 10 = 16'] },
      { key: 'mushroom', type: 'item', title: '양쪽 버섯', art: '🍄', shows: ['party'], text: '“한쪽은 커지고 한쪽은 작아지지.” 버섯 조각을 먹고 원래 크기가 되어 숲을 빠져나왔다.' },
      { key: 'party', type: 'place', title: '미친 다과회', art: '🎩🐰☕🫖', text: '모자 장수와 3월 토끼의 끝없는 다과회. “언제나 6시라서 차를 마셔야 해!” 찻주전자 속에서 코 고는 소리.',
        shows: ['teapot'], spots: [{ label: '찻잔 받침', x: 24, y: 76, reveal: 'spoon' }] },
      { key: 'teapot', type: 'red', title: '찻주전자', art: '🫖', text: '뚜껑이 꽉 끼어 있다.' },
      { key: 'spoon', type: 'blue', title: '은 찻숟가락', art: '🥄', text: '' },
      { key: 'dormouse', type: 'item', from: ['teapot', 'spoon'], discard: ['teapot', 'spoon'], shows: ['croquet'], title: '잠꾸러기 겨울잠쥐', art: '🐭💤', text: '뚜껑을 열자 겨울잠쥐가 하품한다. “여왕님 크로케 경기장… 여기서 아주 가까워… 쿨…”' },
      { key: 'croquet', type: 'place', title: '여왕의 크로케 경기장', art: '🌹🦩🦔🃏', text: '홍학을 방망이로, 고슴도치를 공으로 쓰는 엉망진창 경기. 카드 병정들이 하얀 장미를 빨갛게 칠한다.',
        shows: ['flamingo', 'soldiers'], spots: [{ label: '장미 덤불', x: 80, y: 60, reveal: 'hedgehog' }] },
      { key: 'soldiers', type: 'item', title: '카드 병정들', art: '♥️♦️♠️♣️', text: '병정 넷: 하트 7, 스페이드 2, 다이아 9, 클로버 4. “여왕님은 하트를 가장 좋아하시고, 다이아, 스페이드, 클로버 순이지. 재판장 문은 그 순서대로 선 우리 숫자야!”' },
      { key: 'flamingo', type: 'red', title: '홍학 방망이', art: '🦩', text: '' },
      { key: 'hedgehog', type: 'blue', title: '고슴도치 공', art: '🦔', text: '' },
      { key: 'shot', type: 'item', from: ['flamingo', 'hedgehog'], discard: ['flamingo', 'hedgehog'], shows: ['courtdoor'], title: '멋진 한 방!', art: '🏏✨', text: '고슴도치가 아치를 통과하자 여왕이 깔깔 웃는다. “재판에 참석하도록 허락하노라!”' },
      { key: 'courtdoor', type: 'code', title: '재판장 문', art: '⚖️', text: '숫자 4자리.', code: '7924', result: 'court', hint: ['카드 병정의 숫자를 여왕이 좋아하는 무늬 순서로.', '♥7 ♦9 ♠2 ♣4 → 7924'] },
      { key: 'court', type: 'place', title: '여왕의 재판장', art: '👑⚖️🃏', text: '“목을 쳐라!” 여왕이 외치자 카드들이 날아든다! 재판장 큰 시계가 9시를 가리킨다. 앨리스: “모자 장수 다과회 시각으로 돌아가면 깨어날 수 있을지도!”', shows: ['clock'] },
      { key: 'clock', type: 'machine', title: '재판장의 큰 시계', art: '🕰️', text: '바늘을 돌리자.', buttons: ['⏩ 앞으로 1시간', '⏪ 뒤로 1시간'], solution: ['⏪ 뒤로 1시간', '⏪ 뒤로 1시간', '⏪ 뒤로 1시간'], result: 'back', hint: ['다과회는 언제나 몇 시였죠?', '9시 → 6시: ⏪ 세 번'] },
      { key: 'back', type: 'item', title: '서재로 돌아오다', art: '🖋️✨', shows: ['publish'], text: '눈을 떠 보니 캐럴의 서재. 캐럴이 펜을 들었다. “…그리고 앨리스는 언니의 무릎 위에서 깨어났다.” 결말이 완성됐다! 이제 출판사에 원고를 보내자.' },
      { key: 'publish', type: 'code', title: '출판사 우편 봉투', art: '✉️', text: '봉투에 출판 날짜(월일 4자리)를 적으면 완성.', code: '0704', result: 'out', hint: ['미완성 원고의 여백 메모.', '7월 4일 → 0704'] },
      { key: 'trap1', type: 'trap', from: ['rabbit', 'drink'], title: '토끼가 작아졌다!', text: '토끼에게 물약을 먹이자 콩알만 해져서 찾느라 한참 걸렸다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['flamingo', 'spoon'], title: '홍학이 화났다', text: '숟가락으로 홍학을 툭 쳤더니 날개를 퍼덕이며 도망갔다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '이야기의 끝', art: '📖🐇', text: '「이상한 나라의 앨리스」가 세상에 나왔다. 서재 창밖으로 하얀 토끼가 손을 흔들며 사라진다.' },
    ],
  },
];
