'use strict';
// 언락! — 미스터리 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '미스터리 어드벤처';
module.exports = [
  {
    id: 'househill', box: B, title: '언덕 위의 집', orig: 'The House on the Hill', diff: 1, theme: '#6a3a8a',
    intro: '마을 아이들이 언덕 위 빈집에서 “사자의 서” 한 구절을 소리 내어 읽은 뒤로, 그 집에서 이상한 일들이 벌어진다. 초자연 현상 조사대가 되어 원인을 밝히고 책을 봉인하자.',
    cards: [
      { key: 'foyer', type: 'place', start: true, title: '빈집 현관', art: '🏚️🕯️🖼️👻', text: '먼지 쌓인 현관. 가족 초상화, 꺼진 촛대, 아이들이 떨어뜨리고 간 쪽지. 응접실 문은 숫자 자물쇠로 잠겨 있다.',
        shows: ['kidsnote', 'portrait', 'parlordoor', 'candles'], spots: [{ label: '현관 매트 밑', x: 46, y: 86, reveal: 'matches' }, { label: '거울', emoji: '🪞', x: 82, y: 30, text: '거울에 입김으로 쓴 글씨가 떠오른다: “내 생일에 문을 열어 줘…”' }] },
      { key: 'kidsnote', type: 'item', title: '아이들의 쪽지', art: '📝', text: '“우리 셋이 그 이상한 책 147쪽을 같이 읽었어. 그 뒤로 노래 소리가 들려…”' },
      { key: 'portrait', type: 'item', title: '가족 초상화', art: '🖼️', text: '아버지(1820년생), 어머니(1825년생), 딸 에밀리(1851년생), 아들 토마스(1853년생). 에밀리의 눈만 이쪽을 따라온다.' },
      { key: 'parlordoor', type: 'code', title: '응접실 문', art: '🚪', text: '숫자 4자리.', code: '1851', result: 'parlor', hint: ['거울의 글씨: “내 생일”. 누가 이쪽을 보고 있죠?', '에밀리의 출생 연도 1851'] },
      { key: 'candles', type: 'red', title: '꺼진 촛대', art: '🕯️', text: '' },
      { key: 'matches', type: 'blue', title: '성냥갑', art: '🔥', text: '' },
      { key: 'lit', type: 'item', from: ['candles', 'matches'], discard: ['candles'], title: '흔들리는 촛불', art: '🕯️✨', text: '촛불이 켜지자 어디선가 아이 목소리가 노래한다. “도… 미… 솔… 도…”' },
      { key: 'parlor', type: 'place', title: '응접실', art: '📕🎼🛋️🕸️', text: '탁자 위에 펼쳐진 낡은 책 — “사자의 서”. 한 장이 찢겨 있다. 구석에 오래된 축음기.',
        shows: ['book', 'gramophone'], spots: [{ label: '소파 쿠션 사이', x: 70, y: 70, reveal: 'page' }] },
      { key: 'book', type: 'red', title: '사자의 서', art: '📕', text: '147쪽이 찢겨 나갔다. 페이지가 빠진 채로는 봉인할 수 없다.' },
      { key: 'page', type: 'blue', title: '찢긴 147쪽', art: '📄', text: '' },
      { key: 'gramophone', type: 'machine', title: '축음기', art: '🎼', text: '건반 같은 버튼 다섯 개가 달린 이상한 축음기.', buttons: ['도', '레', '미', '파', '솔'], solution: ['도', '미', '솔', '도'], result: 'cellar', hint: ['촛불을 켜면 노래가 들려요.', '도 → 미 → 솔 → 도'] },
      { key: 'restored', type: 'item', from: ['book', 'page'], discard: ['book', 'page'], title: '완성된 사자의 서', art: '📖', text: '페이지를 끼우자 글자가 빛난다: “봉인하려면 지하 제단에서, 깨운 주문의 쪽수를 거꾸로 외워라.”' },
      { key: 'cellar', type: 'place', title: '지하실', art: '⛓️🕯️👧🪦', text: '축음기 노래가 끝나자 벽이 열렸다. 창백한 소녀 유령 에밀리가 제단 앞에 서 있다. 제단에 숫자 다이얼 세 개.', shows: ['altar'] },
      { key: 'altar', type: 'code', title: '봉인 제단', art: '🪦', text: '숫자 3자리.', code: '741', result: 'out', hint: ['아이들이 읽은 쪽수를, 완성된 책이 말한 대로.', '147을 거꾸로 → 741'] },
      { key: 'trap1', type: 'trap', from: ['book', 'matches'], title: '안 돼!', text: '책에 불을 붙이려 하자 유령이 비명을 지르며 촛불을 모두 꺼 버렸다. 다시 켜느라 시간이 흘렀다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '평온한 밤', art: '🌙🏡', text: '책이 스르르 닫히고 에밀리가 미소 지으며 사라진다. 언덕 위의 집에 처음으로 고요가 찾아왔다.' },
    ],
  },
  {
    id: 'nautilus', box: B, title: '노틸러스호의 함정', orig: "The Nautilus' Traps", diff: 3, theme: '#2a6ab8',
    intro: '심해 다이빙 중 거대한 바다 괴물에게 쫓기다, 해저에 묻힌 낡은 해치를 열고 몸을 숨겼다. 그곳은 전설의 잠수함 노틸러스호! 산소가 떨어지기 전에 수면으로 올라갈 방법을 찾아라.',
    cards: [
      { key: 'seabed', type: 'place', start: true, title: '심해', art: '🌊🦑🫧🪸', text: '거대한 촉수가 어둠 속에서 다가온다! 산호 사이로 반쯤 묻힌 둥근 해치.',
        shows: ['hatch', 'oxygen'], spots: [{ label: '산호 틈', x: 20, y: 72, reveal: 'wheel' }] },
      { key: 'oxygen', type: 'item', title: '산소 게이지', art: '🫧', text: '잔량이 빠르게 줄어든다. 서둘러야 한다!' },
      { key: 'hatch', type: 'red', title: '낡은 해치', art: '⭕', text: '손잡이가 떨어져 나갔다.' },
      { key: 'wheel', type: 'blue', title: '해치 핸들', art: '☸️', text: '' },
      { key: 'airlock', type: 'place', from: ['hatch', 'wheel'], discard: ['hatch', 'wheel'], shows: ['pump', 'gauge'], title: '기밀실', art: '🚪💧🔧', text: '해치를 닫고 들어왔다. 물이 가슴까지 차 있다. 배수 레버 세 개와 낡은 안내판.' },
      { key: 'gauge', type: 'item', title: '배수 안내판', art: '📋', text: '“배수는 가장 낮은 탱크부터. 탱크 높이 — 1번: 중간, 2번: 가장 높음, 3번: 가장 낮음.”' },
      { key: 'pump', type: 'machine', title: '배수 레버', art: '🎚️', text: '레버를 순서대로 당기자.', buttons: ['레버 1', '레버 2', '레버 3'], solution: ['레버 3', '레버 1', '레버 2'], result: 'corridor', hint: ['안내판: 낮은 탱크부터.', '3 → 1 → 2'] },
      { key: 'corridor', type: 'place', title: '노틸러스호 복도', art: '⚓🎹📖🐙', text: '물이 빠지자 화려한 복도가 드러났다. 선장의 항해일지, 파이프오르간이 있는 방, 잠긴 도서실.',
        shows: ['logbook', 'organ', 'libdoor'], spots: [{ label: '둥근 창 테두리', x: 80, y: 28, reveal: 'libkey' }, { label: '벽의 문어 표본', emoji: '🐙', x: 30, y: 30, text: '표본 아래 명패: “다리 8개 — 하지만 오르간은 4음만 기억한다.”' }] },
      { key: 'logbook', type: 'item', title: '네모 선장의 항해일지', art: '📖', text: '“나, 네모. 탈출정은 격납고에 있다. 격납고는 내 이름을 오르간으로 연주하면 열린다. 탈출정의 항로는 도서실 해도에, 시동 코드는 이 배를 띄운 해에.”' },
      { key: 'organ', type: 'machine', title: '파이프오르간', art: '🎹', text: '건반마다 글자가 새겨져 있다.', buttons: ['A', 'E', 'M', 'N', 'O', 'S'], solution: ['N', 'E', 'M', 'O'], result: 'hangar', hint: ['항해일지: 선장의 이름.', 'N → E → M → O'] },
      { key: 'libdoor', type: 'red', title: '도서실 문', art: '🚪', text: '작은 자물쇠.' },
      { key: 'libkey', type: 'blue', title: '놋쇠 열쇠', art: '🗝️', text: '' },
      { key: 'library', type: 'place', from: ['libdoor', 'libkey'], discard: ['libdoor', 'libkey'], shows: ['chart', 'plaque'], title: '도서실', art: '📚🗺️🕯️', text: '천장까지 닿는 책장. 펼쳐진 해도, 벽에 걸린 동판.',
        spots: [{ label: '책장 맨 아래 칸', x: 24, y: 80, reveal: 'crank' }] },
      { key: 'chart', type: 'item', title: '해도', art: '🗺️', text: '빨간 선으로 그린 비상 부상 항로: 동 → 북 → 북 → 서' },
      { key: 'plaque', type: 'item', title: '동판', art: '🏷️', text: '“노틸러스호 — 18□□년 진수. 빈칸: 복도 창밖 물고기 떼의 마릿수를 두 번.”' },
      { key: 'crank', type: 'blue', title: '시동 크랭크', art: '🔧', text: '' },
      { key: 'hangar', type: 'place', title: '격납고', art: '🚤🫧⚙️', text: '작은 탈출정! 그런데 시동 크랭크 구멍이 비어 있다. 창밖으로 거대한 눈이 번뜩인다 — 괴물이 배를 감싸고 있다!',
        shows: ['pod'], spots: [{ label: '격납고 창', emoji: '🪟', x: 70, y: 30, text: '물고기 떼가 7마리씩 무리 지어 도망친다.' }] },
      { key: 'pod', type: 'red', title: '탈출정', art: '🚤', text: '크랭크를 끼우는 구멍이 있다.' },
      { key: 'podready', type: 'machine', from: ['pod', 'crank'], discard: ['crank'], title: '탈출정 조종간', art: '🕹️', text: '크랭크를 돌리자 계기판이 켜졌다. 항로를 입력하세요.', buttons: ['북', '동', '남', '서'], solution: ['동', '북', '북', '서'], result: 'launch', hint: ['도서실의 해도.', '동 → 북 → 북 → 서'] },
      { key: 'launch', type: 'code', title: '시동 장치', art: '🔢', text: '“항로 입력 완료. 시동 코드 4자리를 입력하세요.”', code: '1877', result: 'out', hint: ['도서실 동판, 그리고 격납고 창밖의 물고기 떼.', '18 + 7 + 7 → 1877'] },
      { key: 'trap1', type: 'trap', from: ['pod', 'libkey'], title: '열쇠가 부러졌다', text: '열쇠를 크랭크 구멍에 쑤셔 넣었다가 끝이 부러졌다. 꺼내느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['hatch', 'crank'], title: '괴물의 촉수!', text: '해치를 억지로 비틀자 틈으로 촉수가 들어왔다! 간신히 밀어냈다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '수면 위로!', art: '🌊☀️', text: '탈출정이 괴물의 촉수를 빠져나와 햇빛이 쏟아지는 수면으로 솟구친다. 노틸러스호는 다시 심해로 가라앉았다.' },
    ],
  },
  {
    id: 'tonipal', box: B, title: '토니팔의 보물', orig: "The Tonipal's Treasure", diff: 2, theme: '#c8a030',
    intro: '전설의 해적 스미스 선장이 토니팔 섬에 보물을 숨겼다. 수평선 너머 경쟁 보물 사냥꾼의 배가 다가온다. 세 개의 열쇠를 모아 그들보다 먼저 보물을 파내라!',
    cards: [
      { key: 'shore', type: 'place', start: true, title: '토니팔 섬 해안', art: '🏝️⛵🦜🏴‍☠️', text: '수평선에 검은 돛! 해안에는 잠긴 오두막과 모래에 꽂힌 선장의 일기장.',
        shows: ['diary', 'hut'], spots: [{ label: '앵무새 횃대', x: 30, y: 30, reveal: 'hutkey' }, { label: '검은 돛', emoji: '⛵', x: 80, y: 22, text: '망원경으로 보니 경쟁자 “외눈 잭”의 배다. 한 시간이면 도착하겠다.' }] },
      { key: 'diary', type: 'item', title: '스미스 선장의 일기', art: '📔', text: '“보물은 세 열쇠가 모여야 열린다 — 앵무새의 열쇠, 해골의 열쇠, 나침반의 열쇠. 오두막의 작은 함은 내 배 ‘바다제비’의 이름 글자 수와 선원 수(12명)로 잠갔다.”' },
      { key: 'hut', type: 'red', title: '잠긴 오두막', art: '🛖', text: '' },
      { key: 'hutkey', type: 'blue', title: '녹슨 열쇠', art: '🗝️', text: '앵무새가 물고 있던 열쇠.' },
      { key: 'cabin', type: 'place', from: ['hut', 'hutkey'], discard: ['hut', 'hutkey'], shows: ['map', 'smallchest'], title: '선장의 오두막', art: '🛖🗺️🕯️🧭', text: '해먹, 바다 지도, 작은 함. 벽에 글귀: “걸음을 세는 자가 보물을 찾는다.”',
        spots: [{ label: '해먹 아래', x: 70, y: 76, reveal: 'lens' }] },
      { key: 'smallchest', type: 'code', title: '작은 함', art: '📦', text: '숫자 3자리 자물쇠.', code: '412', result: 'parrotkey', hint: ['일기장: 배 이름 글자 수 + 선원 수.', '바다제비 4글자, 선원 12 → 412'] },
      { key: 'parrotkey', type: 'red', title: '앵무새의 열쇠', art: '🔑🦜', text: '첫 번째 열쇠!' },
      { key: 'map', type: 'red', title: '빛바랜 지도', art: '🗺️', text: '글씨가 너무 작아 읽을 수 없다.' },
      { key: 'lens', type: 'blue', title: '돋보기', art: '🔍', text: '' },
      { key: 'mapread', type: 'item', from: ['map', 'lens'], discard: ['map', 'lens'], shows: ['cave'], title: '지도의 비밀', art: '🗺️🔍', text: '“해골 동굴 앞 야자수에서 북쪽 3걸음, 동쪽 5걸음, 남쪽 1걸음, 서쪽 2걸음. 그곳을 파라. 나침반은 걸음의 방향을 기억한다.”' },
      { key: 'cave', type: 'place', title: '해골 동굴', art: '💀🕳️🦇🧭', text: '입구 위에 거대한 해골 바위. 안쪽 벽에 나침반 모양 장치가 박혀 있다.',
        shows: ['skull', 'compass'], spots: [{ label: '박쥐 둥지', x: 80, y: 24, reveal: 'dagger' }] },
      { key: 'skull', type: 'red', title: '해골 바위의 눈구멍', art: '💀', text: '눈구멍 안쪽에 무언가가 끼어 있다. 손이 닿지 않는다.' },
      { key: 'dagger', type: 'blue', title: '해적의 단검', art: '🗡️', text: '' },
      { key: 'skullkey', type: 'blue', from: ['skull', 'dagger'], discard: ['skull', 'dagger'], title: '해골의 열쇠', art: '🔑💀', text: '단검으로 눈구멍 속 열쇠를 빼냈다. 두 번째 열쇠!' },
      { key: 'compass', type: 'machine', title: '나침반 장치', art: '🧭', text: '방향 버튼 네 개.', buttons: ['북', '동', '남', '서'], solution: ['북', '동', '남', '서'], result: 'compasskey', hint: ['지도에 적힌 걸음의 방향 순서.', '북 → 동 → 남 → 서'] },
      { key: 'compasskey', type: 'blue', title: '나침반의 열쇠', art: '🔑🧭', text: '장치가 열리며 세 번째 열쇠가 나왔다!' },
      { key: 'twokeys', type: 'red', from: ['parrotkey', 'skullkey'], title: '두 개의 열쇠 고리', art: '🔑🔑', text: '두 열쇠를 고리에 꿰자 딸깍 맞물렸다. 하나만 더!' },
      { key: 'dig', type: 'place', from: ['twokeys', 'compasskey'], discard: ['twokeys', 'compasskey'], shows: ['treasure'], title: '야자수 아래', art: '🌴⛏️💰', text: '세 열쇠가 하나의 큰 열쇠로 합쳐졌다! 지도를 따라 걸어 땅을 팠다. 쇠 상자가 나왔다. 해안에서 외눈 잭의 고함 소리가 들린다!' },
      { key: 'treasure', type: 'code', title: '보물 상자', art: '🧰', text: '큰 열쇠를 꽂자 숫자 4자리 다이얼이 나타났다. “걸음을 세는 자가 보물을 찾는다.”', code: '3512', result: 'out', hint: ['지도의 걸음 수를 차례로.', '3 · 5 · 1 · 2 → 3512'] },
      { key: 'trap1', type: 'trap', from: ['map', 'dagger'], title: '지도가 찢어질 뻔', text: '단검으로 지도를 긁어 봤지만 아무것도 없었다. 오히려 일부가 지워질 뻔했다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '토니팔의 보물!', art: '💰👑', text: '금화와 보석이 넘친다! 외눈 잭이 해안에 닿았을 때, 당신의 배는 이미 수평선 너머로 사라지고 있었다.' },
    ],
  },
];
