'use strict';
// 언락! — 미스터리 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '미스터리 어드벤처';
module.exports = [
  {
    id: 'househill', box: B, title: '언덕 위의 집', orig: 'The House on the Hill', diff: 1, theme: '#6a3a8a',
    intro: '마을 아이들이 언덕 위 빈집에서 “사자의 서” 한 구절을 소리 내어 읽은 뒤로, 그 집에서 이상한 일들이 벌어진다. 초자연 현상 조사대가 되어 원인을 밝히고 책을 봉인하자.',
    cards: [
      { key: 'foyer', type: 'place', start: true, title: '빈집 현관', art: '🏚️🕯️🖼️👻', text: '먼지 쌓인 현관. 가족 초상화, 꺼진 촛대, 아이들이 떨어뜨리고 간 쪽지. 2층 계단은 가운데 판자가 부서졌다. 응접실 문은 숫자 자물쇠로 잠겨 있다.',
        shows: ['kidsnote', 'portrait', 'parlordoor', 'candles', 'stairs'], spots: [{ label: '현관 매트 밑', x: 46, y: 86, reveal: 'matches' }, { label: '거울', emoji: '🪞', x: 82, y: 30, text: '거울에 입김으로 쓴 글씨가 떠오른다: “내 생일에 문을 열어 줘…”' }] },
      { key: 'kidsnote', type: 'item', title: '아이들의 쪽지', art: '📝', text: '“우리 셋이 그 이상한 책 147쪽을 같이 읽었어. 그 뒤로 노래 소리가 들리고, 책 페이지가 바람에 찢겨 날아갔어…”' },
      { key: 'portrait', type: 'item', title: '가족 초상화', art: '🖼️', text: '아버지(1820년생), 어머니(1825년생), 딸 에밀리(1851년생), 아들 토마스(1853년생). 에밀리의 눈만 이쪽을 따라온다.' },
      { key: 'parlordoor', type: 'code', title: '응접실 문', art: '🚪', text: '숫자 4자리.', code: '1851', result: 'parlor', hint: ['거울의 글씨: “내 생일”. 누가 이쪽을 보고 있죠?', '에밀리의 출생 연도 1851'] },
      { key: 'candles', type: 'red', title: '꺼진 촛대', art: '🕯️', text: '' },
      { key: 'matches', type: 'blue', title: '성냥갑', art: '🔥', text: '' },
      { key: 'lit', type: 'item', from: ['candles', 'matches'], discard: ['candles'], title: '흔들리는 촛불', art: '🕯️✨', text: '촛불이 켜지자 어디선가 아이 목소리가 노래한다. “도… 미… 솔… 도…”' },
      { key: 'stairs', type: 'red', title: '부서진 계단', art: '🪜', text: '가운데 판자가 없어 올라갈 수 없다.' },
      { key: 'parlor', type: 'place', title: '응접실', art: '📕🎼🛋️🔥', text: '탁자 위에 펼쳐진 낡은 책 — “사자의 서”. 147쪽이 찢겨 나갔다. 오래된 축음기, 재가 쌓인 벽난로. 부엌으로 통하는 문이 열려 있다.',
        shows: ['book', 'gramophone', 'fireplace', 'kitchen'], spots: [{ label: '소파 쿠션 사이', x: 70, y: 70, reveal: 'poker' }] },
      { key: 'book', type: 'red', title: '사자의 서', art: '📕', text: '페이지가 빠진 채로는 봉인할 수 없다.' },
      { key: 'gramophone', type: 'machine', title: '축음기', art: '🎼', text: '건반 같은 버튼 다섯 개가 달린 이상한 축음기.', buttons: ['도', '레', '미', '파', '솔'], solution: ['도', '미', '솔', '도'], result: 'cellar', hint: ['촛불을 켜면 노래가 들려요. 다락방 일기도 보세요.', '도 → 미 → 솔 → 도'] },
      { key: 'fireplace', type: 'red', title: '재가 쌓인 벽난로', art: '🔥', text: '재 속에 종이 조각이 반짝인다. 손으로는 너무 뜨겁다.' },
      { key: 'poker', type: 'blue', title: '부지깽이', art: '🪝', text: '' },
      { key: 'pageTop', type: 'red', from: ['fireplace', 'poker'], discard: ['fireplace', 'poker'], title: '147쪽 윗부분', art: '📄', text: '그을린 페이지의 윗부분. 아래 절반이 없다.' },
      { key: 'kitchen', type: 'place', title: '부엌', art: '🍳🕰️🪵🥄', text: '녹슨 냄비들. 벽시계는 3시 33분에 멈춰 있다. 장작더미 옆에 쓸 만한 판자.',
        spots: [{ label: '장작더미', x: 76, y: 70, reveal: 'plank' }, { label: '찬장', emoji: '🥫', x: 26, y: 34, text: '찬장 문 안쪽에 아이 글씨: “다락방 비밀번호는 부엌 시계가 알아.”' }] },
      { key: 'plank', type: 'blue', title: '튼튼한 판자', art: '🪵', text: '' },
      { key: 'hallway', type: 'place', from: ['stairs', 'plank'], discard: ['stairs', 'plank'], shows: ['atticdoor'], title: '2층 복도', art: '🚪🕯️👣', text: '판자를 걸치고 2층으로 올라왔다. 복도 끝 다락방 문에 숫자 다이얼 셋. 작은 발자국이 다락으로 이어진다.',
        spots: [{ label: '발자국 끝', x: 70, y: 76, reveal: 'trunkkey' }] },
      { key: 'atticdoor', type: 'code', title: '다락방 문', art: '🔢', text: '숫자 3자리.', code: '333', result: 'attic', hint: ['찬장의 글씨: 부엌 시계가 안다.', '3시 33분 → 333'] },
      { key: 'attic', type: 'place', title: '다락방', art: '🧸🕸️📦', text: '낡은 인형들, 먼지 쌓인 여행 트렁크. 소녀의 일기장이 바닥에 펼쳐져 있다.', shows: ['trunk', 'emilydiary'] },
      { key: 'emilydiary', type: 'item', title: '에밀리의 일기', art: '📔', text: '“지하실 문은 내 노래를 들어야 열린다. 도-미-솔-도. 오빠 토마스는 늘 거꾸로 불러서 문이 안 열렸지. 내가 아끼는 건 다 트렁크에 넣어 뒀어.”' },
      { key: 'trunk', type: 'red', title: '에밀리의 트렁크', art: '🧳', text: '작은 자물쇠.' },
      { key: 'trunkkey', type: 'blue', title: '작은 놋쇠 열쇠', art: '🗝️', text: '' },
      { key: 'pageBottom', type: 'blue', from: ['trunk', 'trunkkey'], discard: ['trunk', 'trunkkey'], title: '147쪽 아랫부분', art: '📄', text: '트렁크 속 인형이 쥐고 있던 페이지 조각.' },
      { key: 'page', type: 'blue', from: ['pageTop', 'pageBottom'], discard: ['pageTop', 'pageBottom'], title: '이어 붙인 147쪽', art: '📃', text: '두 조각이 꼭 맞는다!' },
      { key: 'restored', type: 'item', from: ['book', 'page'], discard: ['book', 'page'], title: '완성된 사자의 서', art: '📖', text: '페이지를 끼우자 글자가 빛난다: “봉인하려면 지하 제단에서, 깨운 주문의 쪽수를 거꾸로 외워라.”' },
      { key: 'cellar', type: 'place', title: '지하실', art: '⛓️🕯️👧🪦', text: '축음기 노래가 끝나자 벽이 열렸다. 창백한 소녀 유령 에밀리가 제단 앞에 서 있다. “책을… 다시 잠재워 줘…”', shows: ['altar'] },
      { key: 'altar', type: 'code', title: '봉인 제단', art: '🪦', text: '제단에 숫자 다이얼 셋.', code: '741', result: 'out', hint: ['아이들이 읽은 쪽수를, 완성된 책이 말한 대로.', '147을 거꾸로 → 741'] },
      { key: 'trap1', type: 'trap', from: ['book', 'matches'], title: '안 돼!', text: '책에 불을 붙이려 하자 유령이 비명을 지르며 촛불을 모두 꺼 버렸다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['fireplace', 'matches'], title: '재가 날렸다', text: '벽난로에 불을 붙이자 재가 날아올라 종이 조각이 탈 뻔했다!', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['trunk', 'poker'], title: '손목이 삐끗', text: '부지깽이로 트렁크를 부수려다 손목만 삐었다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '평온한 밤', art: '🌙🏡', text: '책이 스르르 닫히고 에밀리가 미소 지으며 사라진다. 언덕 위의 집에 처음으로 고요가 찾아왔다.' },
    ],
  },
  {
    id: 'nautilus', box: B, title: '노틸러스호의 함정', orig: "The Nautilus' Traps", diff: 3, theme: '#2a6ab8',
    intro: '심해 다이빙 중 거대한 바다 괴물에게 쫓기다, 해저에 묻힌 낡은 해치를 열고 몸을 숨겼다. 그곳은 전설의 잠수함 노틸러스호! 산소가 떨어지기 전에 수면으로 올라갈 방법을 찾아라.',
    cards: [
      { key: 'seabed', type: 'place', start: true, title: '심해', art: '🌊🦑🫧🪸', text: '거대한 촉수가 어둠 속에서 다가온다! 산호 사이로 반쯤 묻힌 둥근 해치.',
        shows: ['hatch', 'oxygen'], spots: [{ label: '산호 틈', x: 20, y: 72, reveal: 'wheel' }] },
      { key: 'oxygen', type: 'item', title: '산소 게이지', art: '🫧', text: '잔량이 빠르게 줄어든다. 서둘러야 한다!' },
      { key: 'hatch', type: 'red', title: '낡은 해치', art: '⭕', text: '손잡이가 떨어져 나갔다.' },
      { key: 'wheel', type: 'blue', title: '해치 핸들', art: '☸️', text: '' },
      { key: 'airlock', type: 'place', from: ['hatch', 'wheel'], discard: ['hatch', 'wheel'], shows: ['pump', 'gauge'], title: '기밀실', art: '🚪💧🔧', text: '해치를 닫고 들어왔다. 물이 가슴까지 차 있다. 배수 레버 세 개와 낡은 안내판.',
        spots: [{ label: '물에 잠긴 공구 상자', x: 78, y: 78, reveal: 'wrench' }] },
      { key: 'gauge', type: 'item', title: '배수 안내판', art: '📋', text: '“배수는 가장 낮은 탱크부터. 탱크 높이 — 1번: 중간, 2번: 가장 높음, 3번: 가장 낮음.”' },
      { key: 'pump', type: 'machine', title: '배수 레버', art: '🎚️', text: '레버를 순서대로 당기자.', buttons: ['레버 1', '레버 2', '레버 3'], solution: ['레버 3', '레버 1', '레버 2'], result: 'corridor', hint: ['안내판: 낮은 탱크부터.', '3 → 1 → 2'] },
      { key: 'wrench', type: 'blue', title: '대형 렌치', art: '🔧', text: '' },
      { key: 'corridor', type: 'place', title: '노틸러스호 복도', art: '⚓🚪📚🐙', text: '물이 빠지자 화려한 복도가 드러났다. 잠긴 도서실, 볼트로 조인 기관실 해치, 숫자 자물쇠가 달린 선장실. 전기가 나가 어둡다.',
        shows: ['libdoor', 'hatch2', 'cabindoor'], spots: [{ label: '둥근 창 테두리', x: 80, y: 28, reveal: 'libkey' }, { label: '문어 표본', emoji: '🐙', x: 30, y: 30, text: '표본 아래 명패: “다리 8개 — 하지만 오르간은 4음만 기억한다.”' }] },
      { key: 'libdoor', type: 'red', title: '도서실 문', art: '🚪', text: '작은 자물쇠.' },
      { key: 'libkey', type: 'blue', title: '놋쇠 열쇠', art: '🗝️', text: '' },
      { key: 'library', type: 'place', from: ['libdoor', 'libkey'], discard: ['libdoor', 'libkey'], shows: ['chart', 'plaque'], title: '도서실', art: '📚🗺️🕯️', text: '천장까지 닿는 책장. 펼쳐진 해도, 벽에 걸린 동판.',
        spots: [{ label: '책장 맨 아래 칸', x: 24, y: 80, reveal: 'crank' }] },
      { key: 'chart', type: 'item', title: '해도', art: '🗺️', text: '빨간 선으로 그린 비상 부상 항로: 동 → 북 → 북 → 서' },
      { key: 'plaque', type: 'item', title: '동판', art: '🏷️', text: '“노틸러스호 — 길이 70미터. 18□□년 진수. 빈칸: 격납고 창밖 물고기 떼의 마릿수를 두 번.”' },
      { key: 'crank', type: 'blue', title: '시동 크랭크', art: '🔧', text: '' },
      { key: 'hatch2', type: 'red', title: '기관실 해치', art: '🔩', text: '커다란 볼트로 조여 있다.' },
      { key: 'engine', type: 'place', from: ['hatch2', 'wrench'], discard: ['hatch2', 'wrench'], shows: ['generator'], title: '기관실', art: '⚙️🔋💡', text: '거대한 발전기가 멈춰 있다. 이게 돌아가야 배 전체에 불이 들어온다.',
        spots: [{ label: '연료 탱크 뒤', x: 76, y: 66, reveal: 'fuel' }] },
      { key: 'generator', type: 'red', title: '멈춘 발전기', art: '⚙️', text: '연료가 바닥났다.' },
      { key: 'fuel', type: 'blue', title: '나트륨 연료통', art: '🛢️', text: '네모 선장이 바닷물에서 뽑아낸 연료.' },
      { key: 'powered', type: 'item', from: ['generator', 'fuel'], discard: ['generator', 'fuel'], shows: ['organ'], title: '전기가 들어왔다', art: '💡⚡', text: '웅— 배 전체에 불이 켜졌다! 복도 끝 살롱에서 파이프오르간이 빛난다.' },
      { key: 'cabindoor', type: 'code', title: '선장실 문', art: '🔢', text: '문패: “선장실 — 내 배의 길이(미터)를 아는 자만.” 숫자 2자리.', code: '70', result: 'cabin', hint: ['도서실 동판에 배의 길이가 있어요.', '70'] },
      { key: 'cabin', type: 'place', title: '네모 선장의 방', art: '🛏️📖🦪', text: '침대 옆 탁자에 항해일지, 진열장에 거대한 진주.', shows: ['logbook', 'pearl'] },
      { key: 'logbook', type: 'item', title: '네모 선장의 항해일지', art: '📖', text: '“나, 네모. 탈출정은 격납고에 있다. 격납고는 내 이름을 오르간으로 연주하면 열린다. 항로는 도서실 해도에, 시동 코드는 이 배를 띄운 해에. 괴물은 빛을 싫어한다 — 조명, 충격, 추진의 순서를 잊지 마라.”' },
      { key: 'pearl', type: 'item', title: '거대한 진주', art: '🦪', text: '주먹만 한 진주. 아름답지만 지금은 쓸모가 없다.' },
      { key: 'organ', type: 'machine', title: '파이프오르간', art: '🎹', text: '건반마다 글자가 새겨져 있다.', buttons: ['A', 'E', 'M', 'N', 'O', 'S'], solution: ['N', 'E', 'M', 'O'], result: 'hangar', hint: ['항해일지: 선장의 이름.', 'N → E → M → O'] },
      { key: 'hangar', type: 'place', title: '격납고', art: '🚤🫧⚙️', text: '작은 탈출정! 시동 크랭크 구멍이 비어 있다. 창밖으로 거대한 눈이 번뜩인다 — 괴물이 배를 감싸고 있다!',
        shows: ['pod'], spots: [{ label: '격납고 창', emoji: '🪟', x: 70, y: 30, text: '물고기 떼가 7마리씩 무리 지어 도망친다.' }] },
      { key: 'pod', type: 'red', title: '탈출정', art: '🚤', text: '크랭크를 끼우는 구멍이 있다.' },
      { key: 'podready', type: 'machine', from: ['pod', 'crank'], discard: ['crank'], title: '탈출정 조종간', art: '🕹️', text: '크랭크를 돌리자 계기판이 켜졌다. 항로를 입력하세요.', buttons: ['북', '동', '남', '서'], solution: ['동', '북', '북', '서'], result: 'launch', hint: ['도서실의 해도.', '동 → 북 → 북 → 서'] },
      { key: 'launch', type: 'code', title: '시동 장치', art: '🔢', text: '“항로 입력 완료. 시동 코드 4자리를 입력하세요.”', code: '1877', result: 'squid', hint: ['도서실 동판, 그리고 격납고 창밖의 물고기 떼.', '18 + 7 + 7 → 1877'] },
      { key: 'squid', type: 'item', title: '괴물의 습격!', art: '🦑🚤', shows: ['shock'], text: '탈출정이 배를 빠져나오자마자 거대한 촉수가 휘감았다! 계기판에 비상 버튼 셋: 조명, 충격, 추진.' },
      { key: 'shock', type: 'machine', title: '비상 버튼', art: '⚡', text: '순서를 틀리면 끝장이다!', buttons: ['🚀 추진', '⚡ 충격', '💡 조명'], solution: ['💡 조명', '⚡ 충격', '🚀 추진'], result: 'out', hint: ['선장의 항해일지 마지막 문장.', '조명 → 충격 → 추진'] },
      { key: 'trap1', type: 'trap', from: ['pod', 'libkey'], title: '열쇠가 부러졌다', text: '열쇠를 크랭크 구멍에 쑤셔 넣었다가 끝이 부러졌다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['hatch', 'crank'], title: '괴물의 촉수!', text: '해치를 억지로 비틀자 틈으로 촉수가 들어왔다! 간신히 밀어냈다.', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['generator', 'wrench'], title: '스파크!', text: '렌치로 발전기를 두드리자 불꽃이 튀었다!', penalty: 1 },
      { key: 'trap4', type: 'trap', from: ['pod', 'fuel'], title: '미끌미끌', text: '연료를 탈출정에 부었다가 넘쳐서 바닥이 미끄러워졌다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '수면 위로!', art: '🌊☀️', text: '눈부신 빛과 전기 충격에 괴물이 촉수를 풀고 달아났다! 탈출정이 햇빛이 쏟아지는 수면으로 솟구친다.' },
    ].map((c) => (c.key === 'wrench' ? c : c)),
  },
  {
    id: 'tonipal', box: B, title: '토니팔의 보물', orig: "The Tonipal's Treasure", diff: 2, theme: '#c8a030',
    intro: '전설의 해적 스미스 선장이 토니팔 섬에 보물을 숨겼다. 수평선 너머 경쟁 보물 사냥꾼 “외눈 잭”의 배가 다가온다. 세 개의 열쇠를 모아 그들보다 먼저 보물을 파내라!',
    cards: [
      { key: 'shore', type: 'place', start: true, title: '토니팔 섬 해안', art: '🏝️⛵🦜🏴‍☠️', text: '수평선에 검은 돛! 해안에는 잠긴 오두막, 모래에 꽂힌 선장의 일기장, 나무에 앉은 늙은 앵무새, 뒤집힌 작은 보트.',
        shows: ['diary', 'hut', 'parrot', 'rowboat'], spots: [{ label: '앵무새 횃대', x: 30, y: 30, reveal: 'hutkey' }, { label: '검은 돛', emoji: '⛵', x: 80, y: 22, text: '망원경으로 보니 외눈 잭의 배다. 한 시간이면 도착하겠다.' }] },
      { key: 'diary', type: 'item', title: '스미스 선장의 일기', art: '📔', text: '“보물은 세 열쇠가 모여야 열린다 — 앵무새의 열쇠, 해골의 열쇠, 나침반의 열쇠. 오두막의 작은 함은 내 배 ‘바다제비’의 이름 글자 수와 선원 수(12명)로 잠갔다. 난파한 바다제비의 선장실 함은 그 배가 처음 바다에 나간 날(3월 12일)로.”' },
      { key: 'parrot', type: 'item', title: '늙은 앵무새 피트', art: '🦜', text: '“열쇠! 열쇠! 노래하면 줄게! 꽥!” 노래를 아는 사람이 없다.' },
      { key: 'hut', type: 'red', title: '잠긴 오두막', art: '🛖', text: '' },
      { key: 'hutkey', type: 'blue', title: '녹슨 열쇠', art: '🗝️', text: '앵무새 횃대에 걸려 있었다.' },
      { key: 'cabin', type: 'place', from: ['hut', 'hutkey'], discard: ['hut', 'hutkey'], shows: ['map', 'smallchest'], title: '선장의 오두막', art: '🛖🗺️🕯️🧭', text: '해먹, 바다 지도, 작은 함. 벽에 글귀: “걸음을 세는 자가 보물을 찾는다.”',
        spots: [{ label: '해먹 아래', x: 70, y: 76, reveal: 'lens' }] },
      { key: 'smallchest', type: 'code', title: '작은 함', art: '📦', text: '숫자 3자리 자물쇠.', code: '412', result: 'oars', hint: ['일기장: 배 이름 글자 수 + 선원 수.', '바다제비 4글자, 선원 12 → 412'] },
      { key: 'oars', type: 'blue', title: '노 한 쌍', art: '🛶', text: '작은 함 속에 접이식 노가 들어 있었다.' },
      { key: 'rowboat', type: 'red', title: '뒤집힌 작은 보트', art: '🚣', text: '노가 없다.' },
      { key: 'wreck', type: 'place', from: ['rowboat', 'oars'], discard: ['rowboat', 'oars'], shows: ['cchest'], title: '바다제비호 난파선', art: '⚓🚢🐠', text: '노를 저어 암초의 난파선에 닿았다. 기울어진 선장실에 쇠 함이 있다.', spots: [{ label: '뱃머리 조각상', emoji: '🧜', x: 80, y: 30, text: '인어 조각상의 목걸이에 음표 셋이 새겨져 있다 — 피트가 좋아하던 노래?' }] },
      { key: 'cchest', type: 'code', title: '선장실 쇠 함', art: '🧰', text: '숫자 4자리.', code: '0312', result: 'oldlog', hint: ['일기장: 바다제비가 처음 바다에 나간 날.', '3월 12일 → 0312'] },
      { key: 'oldlog', type: 'item', title: '바다제비호 항해일지', art: '📜', shows: ['parrotsong'], text: '“피트에게 열쇠를 맡겼다. 피트는 내 노래만 들으면 열쇠를 내놓지 — 도, 솔, 미. 셋만 기억하면 된다.”' },
      { key: 'parrotsong', type: 'machine', title: '피트에게 노래하기', art: '🎵🦜', text: '피트가 고개를 갸웃거린다.', buttons: ['도', '레', '미', '파', '솔'], solution: ['도', '솔', '미'], result: 'parrotkey', hint: ['난파선의 항해일지.', '도 → 솔 → 미'] },
      { key: 'parrotkey', type: 'red', title: '앵무새의 열쇠', art: '🔑🦜', text: '“꽥! 잘했어!” 첫 번째 열쇠!' },
      { key: 'map', type: 'red', title: '빛바랜 지도', art: '🗺️', text: '글씨가 너무 작아 읽을 수 없다.' },
      { key: 'lens', type: 'blue', title: '돋보기', art: '🔍', text: '' },
      { key: 'mapread', type: 'item', from: ['map', 'lens'], discard: ['map', 'lens'], shows: ['jpath'], title: '지도의 비밀', art: '🗺️🔍', text: '“정글 길 끝 해골 동굴. 동굴 앞 야자수에서 북쪽 3걸음, 동쪽 5걸음, 남쪽 1걸음, 서쪽 2걸음. 그곳을 파라. 나침반은 걸음의 방향을 기억한다.”' },
      { key: 'jpath', type: 'place', title: '정글 오솔길', art: '🌴🐍🌺', text: '오솔길 한가운데 커다란 뱀이 똬리를 틀고 있다!', shows: ['snake'], spots: [{ label: '모닥불 자국', x: 24, y: 74, reveal: 'torch' }] },
      { key: 'snake', type: 'red', title: '똬리 튼 큰 뱀', art: '🐍', text: '불을 무서워할지도.' },
      { key: 'torch', type: 'blue', title: '타다 남은 횃불', art: '🔥', text: '' },
      { key: 'cave', type: 'place', from: ['snake', 'torch'], discard: ['snake'], shows: ['skull', 'compass'], title: '해골 동굴', art: '💀🕳️🦇🧭', text: '횃불에 뱀이 달아났다. 입구 위에 거대한 해골 바위, 안쪽 벽에 나침반 모양 장치.',
        spots: [{ label: '박쥐 둥지', x: 80, y: 24, reveal: 'dagger' }] },
      { key: 'skull', type: 'red', title: '해골 바위의 눈구멍', art: '💀', text: '눈구멍 안쪽에 무언가가 끼어 있다. 손이 닿지 않는다.' },
      { key: 'dagger', type: 'blue', title: '해적의 단검', art: '🗡️', text: '' },
      { key: 'skullkey', type: 'blue', from: ['skull', 'dagger'], discard: ['skull', 'dagger'], title: '해골의 열쇠', art: '🔑💀', text: '단검으로 눈구멍 속 열쇠를 빼냈다. 두 번째 열쇠!' },
      { key: 'compass', type: 'machine', title: '나침반 장치', art: '🧭', text: '방향 버튼 네 개.', buttons: ['북', '동', '남', '서'], solution: ['북', '동', '남', '서'], result: 'compasskey', hint: ['지도에 적힌 걸음의 방향 순서.', '북 → 동 → 남 → 서'] },
      { key: 'compasskey', type: 'blue', title: '나침반의 열쇠', art: '🔑🧭', text: '장치가 열리며 세 번째 열쇠가 나왔다!' },
      { key: 'twokeys', type: 'red', from: ['parrotkey', 'skullkey'], title: '두 개의 열쇠 고리', art: '🔑🔑', text: '두 열쇠를 고리에 꿰자 딸깍 맞물렸다. 하나만 더!' },
      { key: 'dig', type: 'place', from: ['twokeys', 'compasskey'], discard: ['twokeys', 'compasskey'], shows: ['treasure'], title: '야자수 아래', art: '🌴⛏️💰', text: '세 열쇠가 하나의 큰 열쇠로 합쳐졌다! 지도를 따라 걸어 땅을 팠다. 쇠 상자가 나왔다. 해안에서 외눈 잭의 고함 소리가 들린다!' },
      { key: 'treasure', type: 'code', title: '보물 상자', art: '🧰', text: '큰 열쇠를 꽂자 숫자 4자리 다이얼이 나타났다. “걸음을 세는 자가 보물을 찾는다.”', code: '3512', result: 'out', hint: ['지도의 걸음 수를 차례로.', '3 · 5 · 1 · 2 → 3512'] },
      { key: 'trap1', type: 'trap', from: ['map', 'dagger'], title: '지도가 찢어질 뻔', text: '단검으로 지도를 긁어 봤지만 아무것도 없었다. 오히려 일부가 지워질 뻔했다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['snake', 'dagger'], title: '쉬익!', text: '단검을 휘두르자 뱀이 덤벼들었다! 간신히 피했다.', penalty: 1 },
      { key: 'trap3', type: 'trap', from: ['hut', 'oars'], title: '노가 부러졌다', text: '노로 오두막 문을 두드리다 노 한쪽에 금이 갔다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '토니팔의 보물!', art: '💰👑', text: '금화와 보석이 넘친다! 외눈 잭이 해안에 닿았을 때, 당신의 배는 이미 수평선 너머로 사라지고 있었다.' },
    ],
  },
];
