'use strict';
// 언락! — 미식 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '미식 어드벤처';
module.exports = [
  {
    id: 'hades', box: B, title: '하데스의 손아귀에서', orig: 'In the Clutches of Hades', diff: 1, theme: '#4a2a6a',
    intro: '고대 그리스. 당신은 젊고 영리한 노예 알릭스. 주인 데메트리오스가 갑자기 사라졌다. 자유를 얻으려면 신들의 도움을 받아 그의 행방을 찾아야 한다.',
    cards: [
      { key: 'house', type: 'place', start: true, title: '데메트리오스의 저택', art: '🏛️🏺🕯️📜', text: '텅 빈 서재. 책상 위 편지, 마당의 신들의 제단. 올리브 나무가 바람에 흔들린다.',
        shows: ['letter', 'altar'], spots: [{ label: '올리브 나무', x: 80, y: 40, reveal: 'olive' }] },
      { key: 'letter', type: 'item', title: '주인의 편지', art: '📜', text: '“하데스께 진 빚을 갚으러 저승에 간다. 돌아오지 못하면 알릭스를 자유민으로 하라 — 해방 증서는 내가 지니고 간다. — 데메트리오스”' },
      { key: 'altar', type: 'red', title: '신들의 제단', art: '🔥🏛️', text: '“평화의 제물을 바치는 자에게 신이 응답하리라.”' },
      { key: 'olive', type: 'blue', title: '올리브 가지', art: '🫒', text: '평화와 아테나의 상징.' },
      { key: 'hermes', type: 'item', from: ['altar', 'olive'], discard: ['olive'], shows: ['styx'], title: '헤르메스의 강림', art: '🪽👟', text: '날개 달린 신발의 헤르메스가 내려왔다. “저승 입구까지는 데려다주지. 뱃사공에게 줄 은화는 직접 구하렴.”' },
      { key: 'styx', type: 'place', title: '스틱스 강가', art: '🌊⛵💀🌫️', text: '뱃사공 카론이 뼈만 남은 손을 내민다. “뱃삯.” 안개 속에서 머리 셋 달린 개가 짖는다.',
        shows: ['charon'], spots: [{ label: '강가 자갈', x: 26, y: 78, reveal: 'obol' }] },
      { key: 'charon', type: 'red', title: '뱃사공 카론', art: '🛶', text: '' },
      { key: 'obol', type: 'blue', title: '오볼로스 은화', art: '🪙', text: '' },
      { key: 'gate', type: 'place', from: ['charon', 'obol'], discard: ['charon', 'obol'], shows: ['lyre'], title: '하데스의 궁전 문', art: '🐕🐕🐕🏛️', text: '케르베로스가 문을 지킨다. 각 머리의 목걸이에 음표 하나씩 — 첫째 머리 솔, 둘째 미, 셋째 도. 바닥에 오르페우스가 두고 간 리라.' },
      { key: 'lyre', type: 'machine', title: '오르페우스의 리라', art: '🎼', text: '“케르베로스는 첫째 머리부터 노래를 들려주면 잠든다.”', buttons: ['도', '미', '솔'], solution: ['솔', '미', '도'], result: 'throne', hint: ['목걸이의 음표를 첫째 머리부터.', '솔 → 미 → 도'] },
      { key: 'throne', type: 'place', title: '하데스의 옥좌', art: '👑💀🍎', text: '하데스 곁에 데메트리오스가 묶여 있다! 하데스: “내 수수께끼를 맞히면 둘 다 보내 주마 — 페르세포네가 석류 씨를 몇 알 먹었지?” 페르세포네가 몰래 손가락을 펴 보인다.',
        shows: ['riddle'], spots: [{ label: '페르세포네의 손', emoji: '🖐️', x: 70, y: 62, text: '한 손은 다 펴고, 다른 손은 손가락 하나만 펴고 있다.' }] },
      { key: 'riddle', type: 'code', title: '하데스의 수수께끼', art: '❓', text: '숫자 1자리.', code: '6', result: 'out', hint: ['페르세포네의 손가락을 세어 보세요.', '5 + 1 = 6'] },
      { key: 'trap1', type: 'trap', from: ['altar', 'obol'], title: '신들의 분노', text: '제단에 은화를 바치자 제우스의 번개가 떨어질 뻔했다. 뇌물은 싫다고!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '자유!', art: '☀️🕊️', text: '하데스가 길을 열었다. 지상으로 돌아오자 데메트리오스가 해방 증서를 건넨다. “고맙다, 알릭스. 너는 이제 자유다.”' },
    ],
  },
  {
    id: 'animalomatic', box: B, title: '노사이드 교수의 애니멀-오-매틱', orig: "Professor Noside's Animal-O-Matic", diff: 2, theme: '#4ab878',
    intro: '노사이드 교수가 동물을 합체시키는 기계 “애니멀-오-매틱”을 동물원에서 시험했다! 사자 머리 펭귄, 기린 목 코끼리… 기계를 되돌려 동물들을 구하자.',
    cards: [
      { key: 'zoo', type: 'place', start: true, title: '난장판 동물원', art: '🦁🐘🦒🐧', text: '뒤죽박죽 동물들이 뛰어다닌다. 한가운데 거대한 기계, 옆에 동물원 안내판과 사육사 오두막.',
        shows: ['machine', 'sign', 'hut'], spots: [{ label: '먹이 통', x: 22, y: 74, reveal: 'wrench' }] },
      { key: 'sign', type: 'item', title: '동물원 안내판', art: '🪧', text: '우리 번호: 🦁 사자 1 · 🐧 펭귄 3 · 🐘 코끼리 5 · 🦒 기린 7.' },
      { key: 'hut', type: 'red', title: '사육사 오두막', art: '🛖', text: '사육사가 문을 잠그고 숨었다. “열쇠는 바나나 나무 원숭이가 가져갔어요!”' },
      { key: 'machine', type: 'red', title: '애니멀-오-매틱', art: '🏭', text: '제어 패널 나사가 꽉 조여 있다.' },
      { key: 'wrench', type: 'blue', title: '스패너', art: '🔧', text: '' },
      { key: 'panel', type: 'item', from: ['machine', 'wrench'], discard: ['wrench'], shows: ['reverse', 'monkeytree'], title: '열린 제어 패널', art: '🎛️', text: '노사이드의 메모: “되돌리기 코드 = 합체된 동물 쌍의 우리 번호를 이어서 (사자+펭귄, 코끼리+기린). 코드를 넣은 뒤 레버는 사육사 설명서대로.”' },
      { key: 'monkeytree', type: 'place', title: '바나나 나무', art: '🐒🍌🌴', text: '열쇠를 쥔 원숭이(인데 꼬리는 공작새)가 나무 꼭대기에서 약 올린다.', shows: ['monkey'], spots: [{ label: '나무 아래 바구니', x: 30, y: 78, reveal: 'banana' }] },
      { key: 'monkey', type: 'red', title: '공작 꼬리 원숭이', art: '🐒', text: '“끽끽!” 열쇠를 흔들어 보인다.' },
      { key: 'banana', type: 'blue', title: '잘 익은 바나나', art: '🍌', text: '' },
      { key: 'hutkey', type: 'blue', from: ['monkey', 'banana'], discard: ['monkey', 'banana'], title: '오두막 열쇠', art: '🗝️', text: '바나나와 열쇠를 바꿨다!' },
      { key: 'keeper', type: 'item', from: ['hut', 'hutkey'], discard: ['hut', 'hutkey'], title: '사육사의 설명서', art: '📘', text: '사육사: “살았다! 기계 설명서예요 — 코드 입력 뒤 레버: 빨강 → 파랑 → 빨강. 마지막으로 교수가 도망 못 가게 우리 문을 닫아야 해요!”' },
      { key: 'reverse', type: 'code', title: '되돌리기 키패드', art: '🔢', text: '숫자 4자리.', code: '1357', result: 'lever', hint: ['안내판의 우리 번호를 쌍 순서대로.', '사자1 펭귄3 코끼리5 기린7 → 1357'] },
      { key: 'lever', type: 'machine', title: '레버 두 개', art: '🕹️', text: '빨간 레버와 파란 레버.', buttons: ['🔴 빨강', '🔵 파랑'], solution: ['🔴 빨강', '🔵 파랑', '🔴 빨강'], result: 'restored', hint: ['사육사 설명서.', '빨강 → 파랑 → 빨강'] },
      { key: 'restored', type: 'item', title: '원래대로!', art: '🦁🐧🐘🦒', shows: ['cage'], text: '펑! 동물들이 제 모습으로! 그런데 노사이드 교수가 기계 위로 뛰어올라 도망치려 한다. 빈 사자 우리 문이 활짝 열려 있다.' },
      { key: 'cage', type: 'machine', title: '사자 우리 문', art: '🦁🚪', text: '교수를 우리 쪽으로 몰아넣자! 동물들에게 차례로 신호를: 가장 작은 동물부터 큰 동물 순서로 포위망을 좁혀라.', buttons: ['🐘 코끼리', '🐧 펭귄', '🦁 사자', '🦒 기린'], solution: ['🐧 펭귄', '🦁 사자', '🦒 기린', '🐘 코끼리'], result: 'out', hint: ['몸집: 펭귄 < 사자 < 기린 < 코끼리.', '🐧 → 🦁 → 🦒 → 🐘'] },
      { key: 'trap1', type: 'trap', from: ['machine', 'banana'], title: '바나나 합체?!', text: '기계에 바나나를 넣자 “바나나 펭귄”이 튀어나왔다. 급히 되돌렸다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '교수 체포!', art: '🐧🦁🔒', text: '동물들이 교수를 사자 우리로 몰아넣었다. 철컥! 노사이드: “이 동물들, 나보다 똑똑하잖아!”' },
    ],
  },
  {
    id: 'eighty', box: B, title: '80분간의 세계 일주', orig: 'Around the World in 80 Minutes', diff: 3, theme: '#3a7ab8',
    intro: '필리어스 포그처럼 리폼 클럽에서 내기를 걸었다 — 80분 만에 세계 일주! 런던을 떠나 수에즈, 봄베이, 홍콩, 요코하마, 샌프란시스코, 뉴욕을 지나 다시 런던으로.',
    cards: [
      { key: 'london', type: 'place', start: true, title: '런던 리폼 클럽', art: '🎩🕰️🗺️☕', text: '빅벤이 20시 45분을 가리킨다. 신사들이 내기 장부에 서명한다. 탁자 위 세계 지도와 잠긴 여행 가방.',
        shows: ['map', 'suitcase'], spots: [{ label: '신문 사이', x: 26, y: 64, reveal: 'key' }] },
      { key: 'map', type: 'item', title: '세계 지도', art: '🗺️', text: '경로: 런던 → 수에즈 → 봄베이 → 홍콩 → 요코하마 → 샌프란시스코 → 뉴욕 → 런던. 핀 색: 수에즈 🟢, 봄베이 🟡, 홍콩 🔴, 요코하마 ⚪.' },
      { key: 'suitcase', type: 'red', title: '잠긴 여행 가방', art: '🧳', text: '' },
      { key: 'key', type: 'blue', title: '가방 열쇠', art: '🔑', text: '' },
      { key: 'passport', type: 'item', from: ['suitcase', 'key'], discard: ['suitcase', 'key'], shows: ['suez'], title: '여권과 여비', art: '🛂💷', text: '여권, 지폐 뭉치, 하인 파스파르투의 메모: “아시아 구간은 지도의 핀 색깔 순서대로 기차를 갈아타셔야 합니다, 주인님!”' },
      { key: 'suez', type: 'place', title: '수에즈 항구', art: '🐫🚢🏜️', text: '형사 픽스가 당신을 은행 강도로 오해하고 미행한다! 봄베이행 배는 출항 직전. 승선권 검사원이 서 있다.',
        shows: ['inspector'], spots: [{ label: '낙타 안장', x: 22, y: 60, reveal: 'ticket' }] },
      { key: 'inspector', type: 'red', title: '승선권 검사원', art: '👮', text: '“표 없이는 못 탑니다.”' },
      { key: 'ticket', type: 'blue', title: '봄베이행 승선권', art: '🎫', text: '' },
      { key: 'bombay', type: 'place', from: ['inspector', 'ticket'], discard: ['inspector', 'ticket'], shows: ['train'], title: '봄베이 기차역', art: '🚂🐘🌴', text: '대륙 횡단 철도가 끊겼다! 코끼리를 타고 숲을 지나 다음 역으로. 역장실에 아시아 횡단 신호기.' },
      { key: 'train', type: 'machine', title: '아시아 횡단 신호기', art: '🚥', text: '색깔 신호 버튼.', buttons: ['🔴', '🟡', '🟢', '⚪'], solution: ['🟢', '🟡', '🔴', '⚪'], result: 'yokohama', hint: ['파스파르투의 메모와 지도의 핀.', '수에즈🟢 봄베이🟡 홍콩🔴 요코하마⚪'] },
      { key: 'yokohama', type: 'place', title: '요코하마 서커스', art: '🎪🤸🗾', text: '홍콩에서 길을 잃은 파스파르투가 서커스단에서 곡예를 하고 있다! 샌프란시스코행 배표는 그가 갖고 있다. 서커스 단장: “인간 피라미드 공연이 끝나야 내보내 주지.”',
        shows: ['pyramid'], spots: [{ label: '포스터', emoji: '📜', x: 76, y: 30, text: '“인간 피라미드: 아래부터 4명, 3명, 2명, 1명!”' }] },
      { key: 'pyramid', type: 'code', title: '피라미드 공연 무대', art: '🤸', text: '단장: “맨 위에서부터 사람 수를 외쳐라!” 숫자 4자리.', code: '1234', result: 'sf', hint: ['포스터는 아래부터 4, 3, 2, 1명이라고 해요. 위에서부터라면?', '1 · 2 · 3 · 4 → 1234'] },
      { key: 'sf', type: 'place', title: '샌프란시스코 → 뉴욕 대륙 철도', art: '🚂🦬🏜️', text: '파스파르투와 함께 열차를 탔다. 그런데 들소 떼가 선로를 막았다! 기관사: “석탄을 더 넣고 속도를 올려야 해!”',
        shows: ['furnace'], spots: [{ label: '석탄 칸', x: 70, y: 70, reveal: 'shovel' }] },
      { key: 'furnace', type: 'red', title: '기관차 화실', art: '🔥', text: '' },
      { key: 'shovel', type: 'blue', title: '석탄 삽', art: '⛏️', text: '' },
      { key: 'ny', type: 'place', from: ['furnace', 'shovel'], discard: ['furnace', 'shovel'], shows: ['deck'], title: '뉴욕 → 대서양 증기선', art: '🗽🚢🌊', text: '전속력으로 뉴욕 도착! 리버풀행 증기선에 올랐지만 석탄이 바닥났다. 선장: “갑판 나무라도 태워야 하오!”',
        spots: [{ label: '구명보트', x: 74, y: 60, reveal: 'axe' }] },
      { key: 'deck', type: 'red', title: '나무 갑판', art: '🪵', text: '' },
      { key: 'axe', type: 'blue', title: '소방 도끼', art: '🪓', text: '' },
      { key: 'liverpool', type: 'item', from: ['deck', 'axe'], discard: ['deck', 'axe'], shows: ['bigben'], title: '리버풀 상륙', art: '⚓', text: '갑판을 태워 리버풀에 닿았다! 형사 픽스가 수갑을 채우려다 진범이 잡혔다는 전보를 받는다. 런던행 특급열차를 타고 클럽으로! 그런데… 날짜 변경선을 넘으며 하루를 벌었다는 걸 깨달았다. 빅벤 시계를 맞추자.' },
      { key: 'bigben', type: 'code', title: '빅벤 시계탑', art: '🕰️', text: '“출발한 시각에서 정확히 80분 뒤로 시계를 맞춰라 (24시간제 4자리).”', code: '2205', result: 'out', hint: ['출발 시각은 20시 45분.', '20:45 + 1:20 = 22:05 → 2205'] },
      { key: 'trap1', type: 'trap', from: ['inspector', 'key'], title: '뇌물 혐의', text: '검사원에게 가방 열쇠를 내밀었다가 뇌물로 오해받았다. 해명하느라 시간이 흘렀다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['furnace', 'axe'], title: '불똥!', text: '도끼로 화실을 쑤시다 불똥이 튀었다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '내기에서 이겼다!', art: '🎩🏆', text: '마지막 종이 울리는 순간 클럽 문을 열었다. “신사 여러분, 제가 돌아왔습니다.” 80분간의 세계 일주 — 성공!' },
    ],
  },
];
