'use strict';
// 언락! — 시크릿 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '시크릿 어드벤처';
module.exports = [
  {
    id: 'nosidestory', box: B, title: '노사이드 스토리', orig: 'A Noside Story', diff: 1, theme: '#c84a8a',
    intro: '노사이드 교수가 국립 과학관에서 시간 기계를 훔쳐 갔다! 교수가 그 기계로 역사를 뒤집기 전에 아지트에 숨어들어 되찾아라.',
    cards: [
      { key: 'den', type: 'place', start: true, title: '노사이드의 아지트', art: '🧔🕰️🐈📚', text: '시계가 잔뜩 걸린 벽, 거대한 책장, 소파 위에서 자는 고양이. 시간 기계는 보이지 않는다.',
        shows: ['clocks', 'cat', 'bookcase'], spots: [{ label: '부엌 찬장', x: 84, y: 64, reveal: 'tuna' }, { label: '책장 위 칸', x: 62, y: 20, reveal: 'leverbook' }] },
      { key: 'clocks', type: 'item', title: '시계 벽', art: '🕐🕒🕕🕘', text: '시계 네 개가 왼쪽부터 1시, 3시, 6시, 9시에 멈춰 있다. 아래 쪽지: “유리 덮개는 시계를 왼쪽부터 읽은 수.”' },
      { key: 'cat', type: 'red', title: '교수의 고양이', art: '🐈', text: '목걸이에 무언가 반짝인다. 건드리면 할퀼 것 같다.' },
      { key: 'tuna', type: 'blue', title: '참치 캔', art: '🥫', text: '' },
      { key: 'collar', type: 'item', from: ['cat', 'tuna'], discard: ['tuna'], shows: ['pin'], title: '고양이 목걸이', art: '📿', text: '고양이가 참치에 정신 팔린 사이 목걸이를 살폈다. 작은 핀 모양 열쇠 “T-KEY”가 달려 있다.' },
      { key: 'pin', type: 'blue', title: 'T-KEY 핀', art: '📍', text: '' },
      { key: 'bookcase', type: 'red', title: '거대한 책장', art: '📚', text: '한 칸에 책 한 권이 빠진 자리가 있다.' },
      { key: 'leverbook', type: 'blue', title: '「시간의 역사」', art: '📘', text: '책등에 작은 손잡이가 달렸다.' },
      { key: 'lab', type: 'place', from: ['bookcase', 'leverbook'], discard: ['bookcase', 'leverbook'], shows: ['cover'], title: '비밀 실험실', art: '⏳🧪⚡', text: '책을 꽂자 책장이 돌아가며 비밀 실험실이 나타났다. 유리 덮개 속에서 시간 기계가 웅웅거린다.' },
      { key: 'cover', type: 'code', title: '유리 덮개', art: '🔐', text: '숫자 4자리.', code: '1369', result: 'machine', hint: ['시계 벽을 왼쪽부터.', '1 · 3 · 6 · 9 → 1369'] },
      { key: 'machine', type: 'red', title: '시간 기계', art: '⏳', text: '핀 모양 열쇠 구멍이 있다.' },
      { key: 'controls', type: 'machine', from: ['machine', 'pin'], discard: ['pin'], title: '기계 제어판', art: '🎛️', text: '“과거 → 현재 → 미래 순서로 누르면 원래 자리로 돌아갑니다.” 교수가 계단을 뛰어 내려온다!', buttons: ['미래', '현재', '과거'], solution: ['과거', '현재', '미래'], result: 'out', hint: ['적힌 순서 그대로.', '과거 → 현재 → 미래'] },
      { key: 'trap1', type: 'trap', from: ['cat', 'leverbook'], title: '할퀴었다!', text: '책으로 고양이를 밀어 보려다 손등을 할퀴었다. 응급 처치하느라 시간이 흘렀다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '되찾았다!', art: '✨', text: '시간 기계가 반짝이며 과학관으로 되돌아갔다. 노사이드 교수: “으아악, 또 실패야!”' },
    ],
  },
  {
    id: 'tombstone', box: B, title: '툼스톤 익스프레스', orig: 'Tombstone Express', diff: 2, theme: '#a86a3a',
    intro: '1870년 서부. 툼스톤행 급행열차의 우편 금고에서 금괴가 사라지고 기관사가 기절했다. 열차가 툼스톤에 닿기 전에 범인을 밝히고 열차를 세워라!',
    cards: [
      { key: 'car', type: 'place', start: true, title: '객차 3호', art: '🚃🤠🃏🎤', text: '승객들이 웅성댄다. 앞 칸 우편 차량 문은 안에서 잠겼다. 수상한 승객 셋.',
        shows: ['suspects', 'door'], spots: [{ label: '짐칸 가방', x: 74, y: 22, reveal: 'hook' }, { label: '보안관 배지', emoji: '⭐', x: 26, y: 70, text: '기절한 보안관의 배지. 그의 수첩: “오후 4시 30분 툼스톤 도착 예정”' }] },
      { key: 'suspects', type: 'item', title: '수상한 승객 셋', art: '🃏✝️🎤', text: '도박사 빌(언제나 검은 장갑) · 에이브러햄 목사(손목시계를 7분 빠르게 맞춰 둠) · 가수 릴리(빨간 비단 장갑).' },
      { key: 'door', type: 'red', title: '잠긴 연결 문', art: '🚪', text: '창문 너머로 안쪽 걸쇠가 보인다.' },
      { key: 'hook', type: 'blue', title: '갈고리 지팡이', art: '🦯', text: '' },
      { key: 'mail', type: 'place', from: ['door', 'hook'], discard: ['door', 'hook'], shows: ['emptysafe', 'mailbag', 'dynamite'], title: '우편 차량', art: '✉️🗄️🧨', text: '텅 빈 금고, 우편 자루, 그리고… 다이너마이트 한 묶음!',
        spots: [{ label: '금고 아래', x: 30, y: 80, reveal: 'handle' }, { label: '우편 자루 옆', x: 70, y: 70, reveal: 'knife' }] },
      { key: 'emptysafe', type: 'item', title: '빈 금고', art: '🗄️', text: '다이얼에 빨간 비단 실 한 올이 걸려 있다. 문 안쪽에 분필로: “석탄”.' },
      { key: 'mailbag', type: 'red', title: '꿰맨 우편 자루', art: '💼', text: '이상하게 무겁다. 입구가 실로 꿰매져 있다.' },
      { key: 'knife', type: 'blue', title: '접이식 칼', art: '🔪', text: '' },
      { key: 'ticket', type: 'item', from: ['mailbag', 'knife'], discard: ['mailbag'], shows: ['cabdoor'], title: '자루 속 물건', art: '🎫🧤', text: '빨간 비단 장갑 한 짝과 기관실 열쇠 쪽지: “기관실 문 = 툼스톤 도착 시각(24시간제 4자리). — L.”' },
      { key: 'dynamite', type: 'red', title: '다이너마이트', art: '🧨', text: '절대 불이나 충격을 주면 안 된다.' },
      { key: 'handle', type: 'blue', title: '브레이크 손잡이', art: '🔧', text: '누군가 일부러 뽑아 숨겨 두었다.' },
      { key: 'cabdoor', type: 'code', title: '기관실 문', art: '🔢', text: '숫자 4자리.', code: '1630', result: 'engine', hint: ['보안관 수첩에 도착 시각이 있어요.', '오후 4시 30분 → 1630'] },
      { key: 'engine', type: 'place', title: '기관차', art: '🚂🔥⛏️', text: '석탄이 활활. 기절했던 기관사가 깨어나 외친다. “브레이크 손잡이가 없어! 손잡이를 끼우고 기적 → 증기 → 브레이크 순서로!”',
        shows: ['coal', 'brake'], spots: [{ label: '공구 걸이', x: 80, y: 40, reveal: 'shovel' }] },
      { key: 'coal', type: 'red', title: '석탄 더미', art: '⬛', text: '분필 글씨 “석탄”이 떠오른다.' },
      { key: 'shovel', type: 'blue', title: '석탄 삽', art: '⛏️', text: '' },
      { key: 'gold', type: 'item', from: ['coal', 'shovel'], discard: ['coal', 'shovel'], title: '숨겨진 금괴', art: '🪙🪙', text: '석탄 아래에서 금괴가 나왔다! 금괴를 싼 천에서 장미 향수 냄새가 난다.' },
      { key: 'brake', type: 'red', title: '빠진 제동 레버', art: '🕹️', text: '' },
      { key: 'stopping', type: 'machine', from: ['brake', 'handle'], discard: ['handle'], title: '제동 장치', art: '⚙️', text: '레버를 끼웠다. 기관사의 말대로!', buttons: ['브레이크', '증기', '기적'], solution: ['기적', '증기', '브레이크'], result: 'stopped', hint: ['기관사가 순서를 외쳤어요.', '기적 → 증기 → 브레이크'] },
      { key: 'stopped', type: 'item', title: '열차 정지', art: '🚂💨', shows: ['accuse'], text: '끼이익— 열차가 툼스톤 직전에서 멈췄다. 이제 보안관에게 범인을 지목하자!' },
      { key: 'accuse', type: 'machine', title: '범인 지목', art: '👉', text: '깨어난 보안관: “증거를 대 봐. 누가 금괴를 숨겼지?”', buttons: ['도박사 빌', '에이브러햄 목사', '가수 릴리'], solution: ['가수 릴리'], result: 'out', hint: ['금고 다이얼의 빨간 비단 실, 자루 속 장갑과 쪽지의 서명 L.', '가수 릴리'] },
      { key: 'trap1', type: 'trap', from: ['dynamite', 'handle'], title: '쾅…?', text: '손잡이로 다이너마이트를 건드렸다! 다행히 불발. 심장이 멎는 줄 알았다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['dynamite', 'shovel'], title: '석탄 불똥', text: '삽에 묻은 석탄 불똥이 도화선에 튈 뻔했다! 급히 털어 냈다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '사건 해결', art: '⭐🤠', text: '릴리는 공범들과 툼스톤에서 금괴를 빼돌리려 했다고 자백했다. 승객들의 박수가 쏟아진다.' },
    ],
  },
  {
    id: 'oz', box: B, title: '오즈의 모험가들', orig: 'The Adventurers of Oz', diff: 3, theme: '#3ab858', limit: 90,
    intro: '회오리바람에 날려 오즈의 나라에 떨어졌다. 집으로 돌아가려면 노란 벽돌 길을 따라 에메랄드 시티의 마법사를 찾아가야 한다. (원작처럼 90분!)',
    cards: [
      { key: 'road', type: 'place', start: true, title: '노란 벽돌 길', art: '🌪️🏡🟨🌽', text: '무너진 집, 끝없이 이어진 노란 길. 옥수수밭 장대에 허수아비가 매달려 있다. 이정표가 서 있다.',
        shows: ['scarecrow', 'sign', 'shoes'], spots: [{ label: '옥수수밭', x: 80, y: 66, reveal: 'ladder' }] },
      { key: 'sign', type: 'item', title: '이정표', art: '🪧', text: '“에메랄드 시티 → 어두운 숲을 지나 → 양귀비 들판 너머. 성문은 동행한 친구들이 알려 주는 숫자로 열린다.”' },
      { key: 'shoes', type: 'item', title: '은 구두', art: '👠', text: '무너진 집 아래 마녀가 신고 있던 구두. 안쪽에 새겨진 글: “집만 한 곳은 없다 — 뒤꿈치를 세 번.”' },
      { key: 'scarecrow', type: 'red', title: '장대에 걸린 허수아비', art: '🧑‍🌾', text: '“나 좀 내려 줘! 손이 안 닿아!”' },
      { key: 'ladder', type: 'blue', title: '농부의 사다리', art: '🪜', text: '' },
      { key: 'scareFree', type: 'item', from: ['scarecrow', 'ladder'], discard: ['scarecrow', 'ladder'], shows: ['forest'], title: '허수아비', art: '🧑‍🌾😊', text: '“고마워! 나는 뇌가 없지만 숫자 하나는 알아 — 내 몸을 받치던 장대는 1개! 첫 번째 숫자야.”' },
      { key: 'forest', type: 'place', title: '어두운 숲', art: '🌲🌲🤖🦁', text: '녹슬어 굳은 양철 나무꾼, 덤불 뒤에서 덜덜 떠는 사자.',
        shows: ['tinman', 'lion'], spots: [{ label: '나무 그루터기', x: 24, y: 74, reveal: 'oil' }, { label: '버려진 오두막', x: 78, y: 40, reveal: 'lantern' }] },
      { key: 'tinman', type: 'red', title: '녹슨 양철 나무꾼', art: '🤖', text: '삐걱… 말을 할 수가 없다.' },
      { key: 'oil', type: 'blue', title: '기름통', art: '🛢️', text: '' },
      { key: 'tinFree', type: 'item', from: ['tinman', 'oil'], discard: ['tinman', 'oil'], title: '양철 나무꾼', art: '🤖❤️', text: '“아, 살 것 같다! 두 번째 숫자는 내 도끼의 날 수, 2야.”' },
      { key: 'lion', type: 'red', title: '겁쟁이 사자', art: '🦁', text: '“어, 어두운 건 무서워…!”' },
      { key: 'lantern', type: 'blue', title: '등불', art: '🏮', text: '' },
      { key: 'lionFree', type: 'item', from: ['lion', 'lantern'], discard: ['lion'], shows: ['poppy'], title: '용기 낸 사자', art: '🦁✨', text: '“밝으니까 하나도 안 무서워! 세 번째 숫자는 내 다리 수 4. 네 번째는… 우리 일행이 모두 몇 명인지 세어 봐!” (허수아비, 양철 나무꾼, 사자, 그리고 당신)' },
      { key: 'poppy', type: 'place', title: '양귀비 들판', art: '🌺🌺😴', text: '붉은 꽃향기에 일행이 하나둘 쓰러져 잠든다! 들판 끝 언덕 너머로 에메랄드빛 성이 보인다.',
        shows: ['poppies'], spots: [{ label: '시냇가', x: 70, y: 76, reveal: 'water' }] },
      { key: 'poppies', type: 'red', title: '잠든 일행', art: '😴', text: '흔들어도 일어나지 않는다.' },
      { key: 'water', type: 'blue', title: '차가운 시냇물', art: '💧', text: '' },
      { key: 'awake', type: 'item', from: ['poppies', 'water'], discard: ['poppies'], shows: ['citygate'], title: '정신 차린 일행', art: '😳💦', text: '찬물을 끼얹자 모두 벌떡! 서둘러 들판을 벗어나 에메랄드 성문 앞에 섰다.' },
      { key: 'citygate', type: 'code', title: '에메랄드 시티 성문', art: '🏰', text: '숫자 4자리. “친구들이 알려 줄 것이다.”', code: '1244', result: 'city', hint: ['허수아비 1, 양철 나무꾼 2, 사자 4, 그리고 일행 수.', '1 · 2 · 4 · 4 → 1244'] },
      { key: 'city', type: 'place', title: '에메랄드 시티', art: '💚🏰🎈', text: '거대한 얼굴의 마법사가 연기 속에서 말한다. “서쪽 마녀의 빗자루를 가져오면 소원을 들어주마.” 궁전 서재에 낡은 주문서가 꽂혀 있다.',
        shows: ['wizard'], spots: [{ label: '서재 책꽂이', x: 20, y: 60, reveal: 'spellbook' }] },
      { key: 'wizard', type: 'red', title: '위대한 마법사', art: '🎭', text: '커튼 뒤에서 무언가 움직인다…' },
      { key: 'spellbook', type: 'item', title: '날개 원숭이 주문서', art: '📜', shows: ['castlegate'], text: '“황금 모자를 쓰고 외쳐라 — 에피-페피-카키! 날개 원숭이들이 서쪽 성까지 데려다주리라.”' },
      { key: 'castlegate', type: 'machine', title: '황금 모자의 주문', art: '🐒🪽', text: '주문 단어 버튼.', buttons: ['지지', '에피', '카키', '페피', '힐로'], solution: ['에피', '페피', '카키'], result: 'castle', hint: ['주문서에 적힌 그대로.', '에피 → 페피 → 카키'] },
      { key: 'castle', type: 'place', title: '서쪽 마녀의 성', art: '🧙‍♀️🏯🧹', text: '초록 피부의 마녀가 깔깔 웃는다. “빗자루는 절대 못 준다!” 성 안뜰에 물 양동이가 놓여 있다.',
        shows: ['witch'], spots: [{ label: '우물가', x: 30, y: 78, reveal: 'bucket' }] },
      { key: 'witch', type: 'red', title: '서쪽 마녀', art: '🧙‍♀️', text: '물을 끔찍이 싫어한다고 한다.' },
      { key: 'bucket', type: 'blue', title: '물 양동이', art: '🪣', text: '' },
      { key: 'broom', type: 'blue', from: ['witch', 'bucket'], discard: ['witch', 'bucket'], title: '마녀의 빗자루', art: '🧹', text: '물을 끼얹자 마녀가 “녹는다아—!” 하며 사라졌다. 빗자루를 손에 넣었다!' },
      { key: 'reveal', type: 'item', from: ['wizard', 'broom'], discard: ['wizard', 'broom'], shows: ['heels'], title: '마법사의 정체', art: '👴🎈', text: '빗자루를 내밀자 커튼 뒤에서 평범한 노인이 나왔다. “미안하구나, 나는 마법사가 아니란다. 하지만 너는 처음부터 돌아갈 힘을 갖고 있었지 — 그 구두 말이야.”' },
      { key: 'heels', type: 'machine', title: '은 구두', art: '👠✨', text: '“집만 한 곳은 없다”를 외치며…', buttons: ['👠 뒤꿈치 딱', '🙏 기도', '🏃 달리기'], solution: ['👠 뒤꿈치 딱', '👠 뒤꿈치 딱', '👠 뒤꿈치 딱'], result: 'out', hint: ['구두 안쪽에 적힌 대로.', '👠 뒤꿈치 딱 × 3'] },
      { key: 'trap1', type: 'trap', from: ['scarecrow', 'oil'], title: '미끌미끌', text: '허수아비에게 기름을 붓자 짚이 엉망이 됐다. 말리느라 한참 걸렸다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['poppies', 'lantern'], title: '불이야!', text: '등불을 흔들자 마른 양귀비에 불이 옮겨붙을 뻔했다. 급히 밟아 껐다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '집만 한 곳은 없어', art: '🏡💫', text: '눈을 떠 보니 캔자스의 우리 집 침대. 꿈이었을까? 침대 밑에 은 구두가 반짝인다.' },
    ],
  },
];
