'use strict';
// 언락! — 쇼트 어드벤처 10편 (원작 줄거리를 따른 오리지널 수수께끼, 30~45분 분량)

const B = '쇼트 어드벤처';
module.exports = [
  {
    id: 'recipes', box: B, title: '옛날 옛적 비밀 레시피', orig: 'Secret Recipes of Yore', diff: 1, theme: '#d88a4a', limit: 30,
    intro: '괴짜 셰프 그랑구지에가 “영혼이 깃든 요리”를 만들어 오라는 시험을 냈다. 오래된 부엌의 비밀 레시피를 되살려 셰프를 감동시키자!',
    cards: [
      { key: 'kitchen', type: 'place', start: true, title: '셰프의 낡은 부엌', art: '🍳🧄🕰️📕', text: '구리 냄비, 마늘 다발, 잠긴 레시피 책. 셰프: “내 할머니의 사과 파이를 재현해 봐. 맛이 다르면 탈락!”',
        shows: ['recipebook', 'oven'], spots: [{ label: '사과 바구니', emoji: '🧺', x: 22, y: 66, text: '사과를 세어 보니 6개.' }, { label: '향신료 선반', x: 74, y: 30, reveal: 'cinnamon' }] },
      { key: 'recipebook', type: 'code', title: '잠긴 레시피 책', art: '📕', text: '자물쇠에 새겨진 글: “사과 수와 굽는 온도.” 오븐 다이얼에 연필 자국이 있다. 숫자 4자리.', code: '6180', result: 'recipe', hint: ['사과 바구니, 그리고 오븐 다이얼의 자국(180).', '6 · 180 → 6180'] },
      { key: 'oven', type: 'item', title: '오븐', art: '🔥', text: '다이얼에 연필 자국: 180' },
      { key: 'recipe', type: 'item', title: '할머니의 레시피', art: '📜', shows: ['dough'], text: '“반죽에 비밀의 향신료를 넣고, 사과를 얹고, 설탕을 뿌리고, 굽는다. 순서를 지킬 것!”' },
      { key: 'dough', type: 'red', title: '파이 반죽', art: '🥧', text: '' },
      { key: 'cinnamon', type: 'blue', title: '비밀의 향신료: 시나몬', art: '🌿', text: '' },
      { key: 'bake', type: 'machine', from: ['dough', 'cinnamon'], discard: ['dough', 'cinnamon'], title: '파이 만들기', art: '🥧', text: '향신료를 넣은 반죽 완성! 다음 순서는?', buttons: ['🔥 굽기', '🍎 사과 얹기', '🍬 설탕 뿌리기'], solution: ['🍎 사과 얹기', '🍬 설탕 뿌리기', '🔥 굽기'], result: 'out', hint: ['레시피의 순서.', '사과 → 설탕 → 굽기'] },
      { key: 'out', type: 'item', end: true, title: '셰프가 울었다', art: '🥧😭', text: '한 입 먹은 셰프가 눈물을 흘린다. “할머니의 맛이야…!” 합격!' },
    ],
  },
  {
    id: 'mummy', box: B, title: '미라의 각성', orig: 'The Awakening of the Mummy', diff: 2, theme: '#c8a85a', limit: 45,
    intro: '함정이 가득한 미로를 지나 저주받은 석관까지 가야 한다. 파라오의 미라가 완전히 깨어나기 전에!',
    cards: [
      { key: 'gate', type: 'place', start: true, title: '피라미드 미로 입구', art: '🔺🐍🕯️🗿', text: '갈림길이 세 개. 벽의 상형 문자가 경고한다: “뱀의 길은 죽음, 매의 길은 바람, 풍뎅이의 길이 진실.”',
        shows: ['paths'], spots: [{ label: '모래 바닥', x: 30, y: 80, reveal: 'torch' }] },
      { key: 'paths', type: 'machine', title: '세 갈래 길', art: '🛤️', text: '어느 길로 갈까?', buttons: ['🐍 뱀의 길', '🦅 매의 길', '🪲 풍뎅이의 길'], solution: ['🪲 풍뎅이의 길'], result: 'corridor', hint: ['상형 문자: 진실의 길.', '🪲 풍뎅이의 길'] },
      { key: 'corridor', type: 'place', title: '어두운 함정 복도', art: '⬛🕳️🗡️', text: '칠흑 같은 복도. 바닥 어딘가에 함정이 있다.', shows: ['dark'] },
      { key: 'dark', type: 'red', title: '어둠 속 복도', art: '⬛', text: '' },
      { key: 'torch', type: 'blue', title: '횃불', art: '🔥', text: '' },
      { key: 'lit', type: 'item', from: ['dark', 'torch'], discard: ['dark', 'torch'], shows: ['tomb'], title: '드러난 함정', art: '🔥🕳️', text: '횃불에 바닥의 함정 타일이 보인다! 무사히 지나 묘실에 도착했다.' },
      { key: 'tomb', type: 'place', title: '파라오의 묘실', art: '⚱️🧟🔺', text: '석관에서 붕대 감긴 손이 꿈틀댄다. 카노푸스 단지 넷. 벽의 글: “단지의 신들을 동-서-남-북 순으로 깨우면 봉인이 열린다: 동쪽 매, 서쪽 자칼, 남쪽 원숭이, 북쪽 사람.”',
        shows: ['jars'], spots: [{ label: '석관 아래', x: 30, y: 72, reveal: 'scarab' }] },
      { key: 'jars', type: 'machine', title: '카노푸스 단지', art: '🏺🏺🏺🏺', text: '단지 뚜껑을 차례로 돌리자.', buttons: ['🧑', '🐒', '🐺', '🦅'], solution: ['🦅', '🐺', '🐒', '🧑'], result: 'seal', hint: ['벽의 글.', '🦅 → 🐺 → 🐒 → 🧑'] },
      { key: 'seal', type: 'red', title: '열린 봉인 구멍', art: '🕳️', text: '풍뎅이 모양 홈.' },
      { key: 'scarab', type: 'blue', title: '황금 풍뎅이', art: '🪲', text: '' },
      { key: 'out', type: 'item', from: ['seal', 'scarab'], end: true, title: '다시 잠든 미라', art: '🧟💤', text: '풍뎅이를 끼우자 미라가 스르르 석관으로 돌아눕는다. 묘실에 다시 정적이 흐른다.' },
      { key: 'trap1', type: 'trap', from: ['seal', 'torch'], title: '저주의 연기', text: '봉인 구멍에 횃불을 넣자 검은 연기가 피어올랐다! 콜록콜록.', penalty: 1 },
    ],
  },
  {
    id: 'angelflight', box: B, title: '천사의 비행', orig: 'The Flight of the Angel', diff: 2, theme: '#a8b8e8', limit: 45,
    intro: '베네치아 카니발에 잠입해 비밀 임무를 완수하라! 산 마르코 광장의 “천사의 비행” 공연 중, 종탑에서 내려오는 천사가 비밀 문서를 건네받기로 되어 있다.',
    cards: [
      { key: 'plaza', type: 'place', start: true, title: '산 마르코 광장', art: '🎭🏛️🕊️🔔', text: '가면 쓴 군중. 종탑 꼭대기에서 천사 곡예사가 밧줄을 타고 내려올 준비를 한다. 연락책이 가면 상점에서 기다린다고 했다.',
        shows: ['shop'], spots: [{ label: '곤돌라', x: 22, y: 76, reveal: 'coin' }, { label: '비둘기 떼', emoji: '🕊️', x: 76, y: 30, text: '비둘기가 종탑 시계 주위를 돈다. 시계는 11시 45분.' }] },
      { key: 'shop', type: 'red', title: '가면 상점 주인', art: '🎭', text: '“가면은 금화 한 닢이오.”' },
      { key: 'coin', type: 'blue', title: '베네치아 금화', art: '🪙', text: '' },
      { key: 'mask', type: 'item', from: ['shop', 'coin'], discard: ['shop', 'coin'], shows: ['bell'], title: '흰 가면과 쪽지', art: '🎭📜', text: '가면 안쪽 쪽지: “종탑 문은 천사가 내려오는 시각(정오) 직전의 시계 시각. 천사에게 신호를 보내려면 종을 높은음-낮은음-높은음.”' },
      { key: 'bell', type: 'code', title: '종탑 문', art: '🚪', text: '숫자 4자리.', code: '1145', result: 'tower', hint: ['광장의 종탑 시계.', '11시 45분 → 1145'] },
      { key: 'tower', type: 'place', title: '종탑 꼭대기', art: '🔔🪽🌇', text: '천사 곡예사가 밧줄에 매달려 출발을 기다린다. 커다란 종 두 개 — 높은음 종과 낮은음 종.', shows: ['signal'] },
      { key: 'signal', type: 'machine', title: '종 신호', art: '🔔', text: '신호를 보내자.', buttons: ['🔔 높은음', '🛎️ 낮은음'], solution: ['🔔 높은음', '🛎️ 낮은음', '🔔 높은음'], result: 'out', hint: ['가면 속 쪽지.', '높은음 → 낮은음 → 높은음'] },
      { key: 'out', type: 'item', end: true, title: '임무 완수', art: '🪽📜', text: '천사가 광장으로 내려오며 군중에게 꽃잎을 뿌린다. 그 사이 당신의 손에 비밀 문서가 쥐어졌다.' },
    ],
  },
  {
    id: 'cabrakan', box: B, title: '카브라칸을 쫓아서', orig: 'In Pursuit of Cabrakan', diff: 2, theme: '#8a6a3a', limit: 45,
    intro: '마야 신화의 지진 거인 카브라칸이 깨어나 정글을 흔든다. 고대 신전의 의식으로 그를 다시 잠재우자.',
    cards: [
      { key: 'jungle', type: 'place', start: true, title: '정글 신전 앞', art: '🛕🌿🐍🌋', text: '땅이 흔들린다! 신전 계단에 그림 문자 넷. 계단 위 빈 제단.',
        shows: ['glyphs', 'altar'], spots: [{ label: '덩굴 아래', x: 24, y: 66, reveal: 'jade' }] },
      { key: 'glyphs', type: 'item', title: '계단의 그림 문자', art: '🐆🦅🐍🌽', text: '계단 아래부터: 옥수수, 뱀, 재규어, 독수리. “땅에서 하늘로 오르라.”' },
      { key: 'altar', type: 'red', title: '빈 제단', art: '🪨', text: '옥 구슬 모양 홈.' },
      { key: 'jade', type: 'blue', title: '옥 구슬', art: '🟢', text: '' },
      { key: 'ritual', type: 'machine', from: ['altar', 'jade'], discard: ['altar', 'jade'], title: '의식의 돌판', art: '🗿', text: '그림 문자 버튼.', buttons: ['🦅', '🐆', '🌽', '🐍'], solution: ['🌽', '🐍', '🐆', '🦅'], result: 'out', hint: ['계단 아래부터 위로.', '🌽 → 🐍 → 🐆 → 🦅'] },
      { key: 'out', type: 'item', end: true, title: '거인이 잠들다', art: '🌋💤', text: '땅의 울림이 멎는다. 카브라칸은 다시 깊은 잠에 빠졌다.' },
    ],
  },
  {
    id: 'birmingham', box: B, title: '버밍엄 살인 사건', orig: 'The Birmingham Murder', diff: 3, theme: '#4a4a5a', limit: 45,
    intro: '1920년 버밍엄. 위험한 갱단의 일원이 되어, 조직의 회계사를 죽인 범인을 찾아내라. 경찰보다 먼저!',
    cards: [
      { key: 'pub', type: 'place', start: true, title: '개리슨 펍', art: '🍺🎩🚬🃏', text: '갱단의 아지트. 보스 토마스: “회계사 그레이가 사무실에서 죽었다. 범인을 찾아와.” 사무실 열쇠를 던져 준다.',
        shows: ['boss', 'officedoor'], spots: [{ label: '당구대', x: 74, y: 70, reveal: 'officekey' }] },
      { key: 'boss', type: 'item', title: '보스 토마스', art: '🎩', text: '“용의자는 셋: 라이벌 갱 사빈(왼손잡이), 경찰 캠벨(시계를 늘 10분 빠르게), 바텐더 그레이스(빨간 립스틱). 그레이는 장부를 지키다 죽었다.”' },
      { key: 'officedoor', type: 'red', title: '회계 사무실 문', art: '🚪', text: '' },
      { key: 'officekey', type: 'blue', title: '사무실 열쇠', art: '🔑', text: '' },
      { key: 'office', type: 'place', from: ['officedoor', 'officekey'], discard: ['officedoor', 'officekey'], shows: ['clock', 'ledger'], title: '회계 사무실', art: '🗄️🩸🕰️', text: '그레이가 쓰러져 있다. 깨진 탁상시계는 9시 40분에 멈췄다. 장부는 찢겨 있고, 찻잔에 빨간 립스틱 자국.',
        spots: [{ label: '벽난로', x: 24, y: 64, reveal: 'letter' }] },
      { key: 'clock', type: 'item', title: '깨진 탁상시계', art: '🕰️', text: '9시 40분에 멈춤. 그런데 이 시계는 그레이가 늘 정확히 맞춰 두던 시계다.' },
      { key: 'ledger', type: 'item', title: '찢긴 장부', art: '📒', text: '마지막 페이지: “그레이스에게 50파운드 — 입막음 비용?” 아래에 사빈의 서명 위조 흔적.' },
      { key: 'letter', type: 'item', title: '타다 남은 편지', art: '✉️', text: '“9시 30분에 사무실로 와. 장부 문제로 할 얘기가 있어. — G”' },
      { key: 'alibis', type: 'item', title: '알리바이', art: '📋', text: '사빈: 9시~10시 경마장(증인 20명). 캠벨: “9시 50분까지 순찰” (그의 시계 기준). 그레이스: 9시 20분~9시 50분 “휴식”.' },
      { key: 'accuse', type: 'machine', title: '보스에게 보고', art: '👉', text: '“범인은 누구지?”', buttons: ['사빈', '캠벨', '그레이스'], solution: ['그레이스'], result: 'out', hint: ['9시 40분에 알리바이가 없는 사람, 립스틱 자국, 편지의 G.', '그레이스'] },
      { key: 'out', type: 'item', end: true, title: '사건 해결', art: '🎩🔍', text: '그레이스는 장부의 비밀을 들킨 뒤 범행을 털어놓았다. 보스가 모자를 고쳐 쓴다. “좋아, 넌 쓸모가 있군.”' },
    ].map((c) => (c.key === 'letter' ? { ...c, shows: ['alibis', 'accuse'] } : c)),
  },
  {
    id: 'schrodinger', box: B, title: '슈뢰딩거의 고양이', orig: "Schrödinger's Cat", diff: 3, theme: '#3a6a5a', limit: 45,
    intro: '슈뢰딩거의 고양이가 미친 양자 우주에서 길을 잃었다! 살아 있으면서 동시에 죽어 있는 고양이를 찾아, 상자를 열어 확실히 구해 내자.',
    cards: [
      { key: 'lab', type: 'place', start: true, title: '양자 실험실', art: '📦🐈⚛️🧪', text: '빈 상자, 방사능 계수기, 칠판 가득한 수식. 상자 속 고양이는 다른 우주로 새어 나갔다!',
        shows: ['board', 'portal'], spots: [{ label: '계수기', emoji: '📟', x: 22, y: 60, text: '계수기 숫자가 깜빡인다: 1-0-1-1' }, { label: '서랍', x: 76, y: 70, reveal: 'shield' }] },
      { key: 'board', type: 'item', title: '칠판', art: '🧮', text: '“이진수 1011 = ?” 아래: “양자 문 코드 = 계수기가 보여 주는 이진수를 십진수로.”' },
      { key: 'portal', type: 'code', title: '양자 문', art: '🌀', text: '숫자 2자리.', code: '11', result: 'multiverse', hint: ['1011(2) = 8 + 0 + 2 + 1.', '11'] },
      { key: 'multiverse', type: 'place', title: '뒤죽박죽 다중 우주', art: '🌀🐈🐈‍⬛🌌', text: '고양이가 동시에 여러 마리! 흰 고양이, 검은 고양이, 투명한 고양이. 진짜는 관측해야만 하나로 정해진다.', shows: ['box'], spots: [{ label: '공중에 뜬 상자', x: 70, y: 40, reveal: 'lens' }] },
      { key: 'box', type: 'red', title: '관측 상자', art: '📦', text: '열면 독약 장치가 작동할지도. 납 차폐막이 필요하다.' },
      { key: 'shield', type: 'blue', title: '납 차폐막', art: '🛡️', text: '' },
      { key: 'lens', type: 'item', title: '관측 렌즈', art: '🔍', text: '렌즈로 보니 고양이 꼬리 색이 바뀐다: 흰 → 검정 → 흰 → 흰. “관측 순서를 기억하라.”' },
      { key: 'opened', type: 'machine', from: ['box', 'shield'], discard: ['box', 'shield'], title: '관측하기', art: '👁️📦', text: '차폐막을 대고 상자를 열 준비! 고양이를 관측한 순서대로 버튼을 누르면 진짜 우주가 확정된다.', buttons: ['⚪ 흰 고양이', '⚫ 검은 고양이', '🫥 투명 고양이'], solution: ['⚪ 흰 고양이', '⚫ 검은 고양이', '⚪ 흰 고양이', '⚪ 흰 고양이'], result: 'out', hint: ['관측 렌즈의 꼬리 색 순서.', '흰 → 검정 → 흰 → 흰'] },
      { key: 'out', type: 'item', end: true, title: '야옹!', art: '🐈😺', text: '파동 함수가 붕괴하고, 상자 속에서 고양이가 하품을 한다. 확실히 살아 있다!' },
    ],
  },
  {
    id: 'octopus', box: B, title: '문어의 비밀', orig: 'The Secrets of the Octopus', diff: 1, theme: '#c85a8a', limit: 30,
    intro: '수족관의 천재 문어 “오토”가 탈출했다! 문어가 남긴 수수께끼 같은 흔적을 따라가 보자.',
    cards: [
      { key: 'tank', type: 'place', start: true, title: '빈 수조', art: '🐙🐠🫧🪣', text: '수조 뚜껑이 열려 있고, 바닥에 젖은 빨판 자국이 직원실 쪽으로 이어진다. 조개 껍데기에 그림이 있다.',
        shows: ['trail'], spots: [{ label: '수조 속 조개', emoji: '🐚', x: 30, y: 72, text: '조개 껍데기에 다리 그림 8개.' }, { label: '먹이 통', x: 76, y: 40, reveal: 'crab' }] },
      { key: 'trail', type: 'code', title: '직원실 문', art: '🚪', text: '빨판 자국이 문 밑으로 사라졌다. 숫자 1자리 자물쇠. 문에 문어 낙서.', code: '8', result: 'staff', hint: ['문어 다리는 몇 개?', '8'] },
      { key: 'staff', type: 'place', title: '직원실', art: '🍪🗄️🐙', text: '과자 통 뚜껑이 들썩인다! 오토가 과자 통 안에 숨었다. 꽉 붙잡고 놓지 않는다.', shows: ['jar'] },
      { key: 'jar', type: 'red', title: '오토가 숨은 과자 통', art: '🫙', text: '' },
      { key: 'crab', type: 'blue', title: '살아 있는 꽃게', art: '🦀', text: '문어가 제일 좋아하는 간식.' },
      { key: 'out', type: 'item', from: ['jar', 'crab'], end: true, title: '찾았다!', art: '🐙🦀', text: '꽃게를 보자 오토가 쏙 나왔다. 무사히 수조로 돌아간 오토가 다리 하나로 손(?)을 흔든다.' },
    ],
  },
  {
    id: 'dooarann', box: B, title: '두아란의 던전', orig: "Doo-Arann's Dungeon", diff: 1, theme: '#6a5a3a', limit: 30,
    intro: '사악한 마법사 두아란의 던전에 갇혔다. 횃불 하나에 의지해 탈출구를 찾자.',
    cards: [
      { key: 'cell', type: 'place', start: true, title: '지하 감옥', art: '⛓️🕯️💀🚪', text: '쇠창살 문, 벽의 횃불, 해골 하나. 해골이 무언가를 꽉 쥐고 있다.',
        shows: ['door'], spots: [{ label: '해골의 손', x: 40, y: 66, reveal: 'key' }, { label: '벽의 낙서', emoji: '✍️', x: 76, y: 30, text: '이전 죄수의 낙서: “출구는 왼쪽, 왼쪽, 오른쪽.”' }] },
      { key: 'door', type: 'red', title: '쇠창살 문', art: '🚪', text: '' },
      { key: 'key', type: 'blue', title: '녹슨 열쇠', art: '🗝️', text: '' },
      { key: 'maze', type: 'machine', from: ['door', 'key'], discard: ['door', 'key'], title: '갈림길 미로', art: '🧭', text: '문을 나서자 갈림길이 계속된다.', buttons: ['⬅️ 왼쪽', '➡️ 오른쪽'], solution: ['⬅️ 왼쪽', '⬅️ 왼쪽', '➡️ 오른쪽'], result: 'out', hint: ['벽의 낙서.', '왼쪽 → 왼쪽 → 오른쪽'] },
      { key: 'out', type: 'item', end: true, title: '바깥 공기!', art: '🌄', text: '마지막 계단을 오르자 별빛이 쏟아진다. 두아란의 분노한 외침이 멀어진다.' },
    ],
  },
  {
    id: 'seaspray', box: B, title: '물보라의 노래', orig: 'The Song of the Sea Spray', diff: 2, theme: '#2a8ab8', limit: 45,
    intro: '정반대인 두 동물의 사랑 이야기. 하늘을 나는 갈매기 마린과 땅속에 사는 두더지 테오가 서로에게 시를 남긴다. 시 속 수수께끼를 풀어 둘을 등대 아래에서 만나게 해 주자.',
    cards: [
      { key: 'cliff', type: 'place', start: true, title: '바닷가 절벽', art: '🌊🐦🕳️🗼', text: '갈매기 마린의 둥지와 두더지 테오의 굴 입구. 둘 사이엔 깊은 바다 동굴. 등대가 저 멀리 서 있다.',
        shows: ['poem1', 'burrow'], spots: [{ label: '갈매기 둥지', x: 70, y: 24, reveal: 'shell' }] },
      { key: 'poem1', type: 'item', title: '마린의 시', art: '📜', text: '“파도가 세 번 오고, 바람이 한 번 불면 / 나는 등대 꼭대기에서 기다릴게.” 시 뒷면에 등대 문 그림과 물결 세 개, 바람 하나.' },
      { key: 'burrow', type: 'red', title: '테오의 굴 입구', art: '🕳️', text: '조개 모양 문패가 비어 있다.' },
      { key: 'shell', type: 'blue', title: '소라 껍데기', art: '🐚', text: '귀에 대면 파도 소리가 난다.' },
      { key: 'den', type: 'item', from: ['burrow', 'shell'], discard: ['burrow', 'shell'], shows: ['lighthouse'], title: '테오의 답장', art: '✉️', text: '소라를 문패에 끼우자 굴이 열리고 테오의 답장이 나왔다: “땅속 길로 등대 아래까지 갈게. 등대 문은 너의 시가 열어 줄 거야.”' },
      { key: 'lighthouse', type: 'machine', title: '등대 문', art: '🗼🚪', text: '물결과 바람 버튼.', buttons: ['🌊 물결', '🌬️ 바람'], solution: ['🌊 물결', '🌊 물결', '🌊 물결', '🌬️ 바람'], result: 'out', hint: ['마린의 시: 파도 세 번, 바람 한 번.', '🌊 🌊 🌊 🌬️'] },
      { key: 'out', type: 'item', end: true, title: '등대 아래에서', art: '🐦💕🦔', text: '등대 문이 열리고, 땅속에서 올라온 테오와 하늘에서 내려온 마린이 마주한다. 물보라가 노래처럼 흩어진다.' },
    ],
  },
  {
    id: 'sherlockmind', box: B, title: '셜록 홈즈의 머릿속', orig: 'Inside the Mind of Sherlock Holmes', diff: 2, theme: '#5a3a2a', limit: 45,
    intro: '홈즈가 “기억의 궁전” 속에서 길을 잃었다. 그의 머릿속 방들을 지나 결정적 단서를 되찾게 돕자.',
    cards: [
      { key: 'palace', type: 'place', start: true, title: '기억의 궁전 현관', art: '🏛️🧠🎻🔍', text: '방문 셋: 바이올린의 방, 화학의 방, 사건의 방. 사건의 방만 잠겨 있다.',
        shows: ['casedoor'], spots: [{ label: '바이올린의 방', x: 20, y: 50, reveal: 'bow' }, { label: '화학의 방', emoji: '⚗️', x: 50, y: 50, text: '시험관 넷: 2, 2, 1, B 라벨 — “베이커가 221B”' }] },
      { key: 'casedoor', type: 'red', title: '사건의 방 문', art: '🚪🎼', text: '문에 오선지가 그려져 있다. 연주해야 열릴 듯.' },
      { key: 'bow', type: 'blue', title: '바이올린 활', art: '🎻', text: '' },
      { key: 'caseroom', type: 'place', from: ['casedoor', 'bow'], discard: ['casedoor', 'bow'], shows: ['memory'], title: '사건의 방', art: '🗂️🕯️', text: '홈즈의 목소리: “결정적 단서는… 내가 사는 곳의 번지수가 열쇠였지.”' },
      { key: 'memory', type: 'code', title: '기억의 서랍', art: '🗄️', text: '숫자 3자리.', code: '221', result: 'out', hint: ['화학의 방 시험관 라벨.', '221(B) → 221'] },
      { key: 'out', type: 'item', end: true, title: '기억이 돌아오다', art: '🎩💡', text: '“그래, 범인은 그 사람이었어!” 홈즈가 눈을 번쩍 뜬다.' },
    ],
  },
];
