'use strict';
// 언락! — 스타워즈 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '스타워즈';
module.exports = [
  {
    id: 'sw-delay', box: B, title: '예상치 못한 지연', orig: 'An Unforeseen Delay', diff: 1, theme: '#3a3a5a',
    intro: '아우터 림의 밀수업자. 자바의 값비싼 화물을 운반하던 중 제국 스타 디스트로이어에 붙잡혀 격납고에 끌려왔다! 검문을 피하고 우주선을 고쳐 탈출하라.',
    cards: [
      { key: 'hold', type: 'place', start: true, title: '우주선 화물칸', art: '📦🛸⭐🤖', text: '바닥 아래 비밀 화물칸에 자바의 화물. 밖에서 스톰트루퍼들이 검문을 준비한다. 정비 드로이드가 삐빅거린다.',
        shows: ['droid', 'hatch'], spots: [{ label: '공구 서랍', x: 76, y: 70, reveal: 'panel' }] },
      { key: 'droid', type: 'item', title: '정비 드로이드', art: '🤖', text: '“삐빅! 하이퍼드라이브 동력 코일 고장. 예비 코일은 격납고 정비실에. 재가동 순서: 냉각 → 충전 → 점프!”' },
      { key: 'hatch', type: 'red', title: '비밀 화물칸 덮개', art: '⬛', text: '검문 전에 완벽히 위장해야 한다.' },
      { key: 'panel', type: 'blue', title: '위장 바닥판', art: '🟫', text: '' },
      { key: 'hidden', type: 'item', from: ['hatch', 'panel'], discard: ['hatch', 'panel'], shows: ['hangar'], title: '검문 통과', art: '🪖✅', text: '스톰트루퍼: “이상 없음.” 휴, 화물을 숨겼다. 그들이 떠난 틈에 격납고로 몰래 나간다.' },
      { key: 'hangar', type: 'place', title: '스타 디스트로이어 격납고', art: '🚀🪖🔧', text: '거대한 격납고. 정비실 문은 제국 코드 키패드. 벽의 근무표에 “정비실 비밀번호 = 오늘 근무 교대조 번호 TK-421의 숫자”.', shows: ['maint'], spots: [{ label: '근무표', emoji: '📋', x: 30, y: 30, text: '교대조: TK-421, TK-422. 오늘은 TK-421.' }] },
      { key: 'maint', type: 'code', title: '정비실 키패드', art: '🔢', text: '숫자 3자리.', code: '421', result: 'coilroom', hint: ['근무표의 오늘 교대조.', 'TK-421 → 421'] },
      { key: 'coilroom', type: 'item', title: '정비실', art: '🌀', shows: ['coil', 'drive'], text: '예비 동력 코일 확보! 서둘러 우주선으로.' },
      { key: 'drive', type: 'red', title: '하이퍼드라이브', art: '⚙️', text: '타 버린 코일 자리.' },
      { key: 'coil', type: 'blue', title: '예비 동력 코일', art: '🌀', text: '' },
      { key: 'fixed', type: 'machine', from: ['drive', 'coil'], discard: ['drive', 'coil'], title: '하이퍼드라이브 제어판', art: '🎛️', text: '견인 광선이 해제된 순간을 노려라!', buttons: ['🚀 점프', '❄️ 냉각', '⚡ 충전'], solution: ['❄️ 냉각', '⚡ 충전', '🚀 점프'], result: 'out', hint: ['드로이드의 말.', '냉각 → 충전 → 점프'] },
      { key: 'trap1', type: 'trap', from: ['hatch', 'coil'], title: '스파크!', text: '코일로 덮개를 누르다 스파크가 튀었다. 스톰트루퍼가 돌아볼 뻔했다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '광속 점프!', art: '✨🚀', text: '별빛이 선으로 늘어나며 우주선이 하이퍼스페이스로 사라진다. 자바에게 늦었다고 혼나겠지만… 살아남았다!' },
    ],
  },
  {
    id: 'sw-hoth', box: B, title: '호스 탈출', orig: 'Escape From Hoth', diff: 2, theme: '#a8c8e8',
    intro: '얼음 행성 호스의 에코 기지 소속 반란군. 톤톤을 타고 정찰하던 중 기지와 통신이 끊겼다! 정찰을 계속하며 행성을 탐사하고 에코 기지와 연락해 탈출하라.',
    cards: [
      { key: 'plain', type: 'place', start: true, title: '얼음 평원', art: '❄️🦌🌨️📡', text: '눈보라. 톤톤이 추위에 떤다. 통신기는 잡음뿐. 멀리 추락한 제국 탐사 드로이드가 연기를 뿜는다.',
        shows: ['comm', 'probe'], spots: [{ label: '눈 더미', x: 22, y: 76, reveal: 'antenna' }] },
      { key: 'comm', type: 'red', title: '고장 난 통신기', art: '📻', text: '안테나가 부러졌다.' },
      { key: 'antenna', type: 'blue', title: '휴대용 안테나', art: '📡', text: '' },
      { key: 'radio', type: 'item', from: ['comm', 'antenna'], discard: ['comm', 'antenna'], shows: ['cave'], title: '잡음 섞인 교신', art: '📻💬', text: '“…여기 에코 기지… 제국 보행 병기 접근 중… 방어막 코드는 레이더에… 북쪽 얼음 동굴로 피신하라…”' },
      { key: 'probe', type: 'item', title: '추락한 탐사 드로이드', art: '🤖', text: '화면에 남은 기록: “반란군 기지 발견. 보행 병기 5기, 2시 방향에서 진격 개시.”' },
      { key: 'cave', type: 'place', title: '얼음 동굴', art: '🧊🕳️👹', text: '눈보라를 피해 들어온 동굴. 거대한 설인 왐파가 잠들어 있다! 동굴 벽에 반란군 보급 상자.',
        shows: ['wampa', 'crate'], spots: [{ label: '고드름 사이', x: 74, y: 28, reveal: 'saber' }] },
      { key: 'wampa', type: 'item', title: '잠든 왐파', art: '👹💤', text: '깨우면 큰일 난다.' },
      { key: 'crate', type: 'red', title: '얼어붙은 보급 상자', art: '📦🧊', text: '' },
      { key: 'saber', type: 'blue', title: '라이트세이버', art: '🗡️', text: '누군가 떨어뜨리고 간 광선검.' },
      { key: 'supplies', type: 'item', from: ['crate', 'saber'], discard: ['crate'], shows: ['base'], title: '보급품', art: '🎒', text: '광선검으로 얼음을 녹여 상자를 열었다. 열 감지 망토와 기지 출입 카드. 기지로 서두르자!' },
      { key: 'base', type: 'place', title: '에코 기지 지휘실', art: '🛰️🚨🧊', text: '경보! 방어막 발생기가 꺼졌다. 격납고 문은 얼어붙었다. 사령관: “방어막을 다시 켜고 마지막 수송선을 띄워라!”', shows: ['shield', 'hangardoor'], spots: [{ label: '난방 장치', x: 24, y: 72, reveal: 'heater' }] },
      { key: 'shield', type: 'code', title: '방어막 발생기', art: '🛡️', text: '“재가동 코드 = 접근 중인 적 병기 수와 방향 시각.”', code: '52', result: 'shieldon', hint: ['추락한 탐사 드로이드의 기록.', '5기, 2시 → 52'] },
      { key: 'shieldon', type: 'item', title: '방어막 가동', art: '🛡️✨', text: '포격이 방어막에 막힌다! 시간을 벌었다.' },
      { key: 'hangardoor', type: 'red', title: '얼어붙은 격납고 문', art: '🧊🚪', text: '' },
      { key: 'heater', type: 'blue', title: '휴대용 히터', art: '♨️', text: '' },
      { key: 'hangar', type: 'place', from: ['hangardoor', 'heater'], discard: ['hangardoor', 'heater'], shows: ['transport'], title: '격납고', art: '🚀❄️', text: '문이 녹아 열렸다! 마지막 수송선. 조종사: “발사 순서는 엔진 → 방어막 → 이륙!”' },
      { key: 'transport', type: 'machine', title: '수송선 발사 패널', art: '🕹️', text: '세 버튼.', buttons: ['🛫 이륙', '🔥 엔진', '🛡️ 방어막'], solution: ['🔥 엔진', '🛡️ 방어막', '🛫 이륙'], result: 'out', hint: ['조종사의 말.', '엔진 → 방어막 → 이륙'] },
      { key: 'trap1', type: 'trap', from: ['crate', 'antenna'], title: '왐파가 깼다!', text: '안테나로 상자를 두드리다 왐파가 눈을 떴다! 숨죽이고 기다렸다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '탈출 성공', art: '🚀🌌', text: '수송선이 얼음 행성을 벗어난다. 반란군은 다음 기지에서 다시 모일 것이다.' },
    ],
  },
  {
    id: 'sw-jedha', box: B, title: '제다의 비밀 임무', orig: 'Secret Mission on Jedha', diff: 3, theme: '#c8a878',
    intro: '당신은 성지 도시 제다에 잠입한 제국 첩보원. 값비싼 카이버 크리스털 상자를 싣던 화물 셔틀이 도시 외곽에 추락했다. 반란 세력 소우 게레라의 패거리에게 들키지 않고 상자를 회수하라.',
    cards: [
      { key: 'market', type: 'place', start: true, title: '성지 도시 시장', art: '🏜️🛕🛒👁️', text: '반란군 패거리가 거리를 누빈다. 눈먼 수도승이 사원 앞에서 기도문을 외운다. 셔틀 추락 지점은 사원 지하 수로를 지나야 한다.',
        shows: ['monk', 'temple'], spots: [{ label: '과일 가게', x: 22, y: 66, reveal: 'robe' }, { label: '패거리', emoji: '🪖', x: 76, y: 44, text: '패거리 둘이 투덜거린다: “사원 수로 문 번호가 기도문 줄 수랑 글자 수래.”' }] },
      { key: 'monk', type: 'item', title: '눈먼 수도승', art: '🧘', text: '“나는 포스와 하나, 포스는 나와 함께.” 같은 기도문을 네 줄로 반복한다. 그의 염주 구슬 색: 초록, 파랑, 초록, 보라.' },
      { key: 'temple', type: 'red', title: '사원 입구', art: '🛕', text: '경비병: “순례자만 들어갈 수 있다.”' },
      { key: 'robe', type: 'blue', title: '순례자 망토', art: '🧥', text: '' },
      { key: 'inside', type: 'place', from: ['temple', 'robe'], discard: ['temple', 'robe'], shows: ['crystals', 'canaldoor'], title: '사원 내부', art: '💎🕯️📜', text: '빛나는 크리스털이 박힌 제단, 그리고 지하 수로로 내려가는 문.' },
      { key: 'crystals', type: 'machine', title: '크리스털 제단', art: '💎', text: '크리스털을 순서대로 만지면 제단이 열린다.', buttons: ['🟢', '🔵', '🟣', '🔴'], solution: ['🟢', '🔵', '🟢', '🟣'], result: 'holo', hint: ['수도승의 염주 구슬 색.', '🟢 🔵 🟢 🟣'] },
      { key: 'holo', type: 'item', title: '제단 속 홀로그램', art: '📽️', text: '홀로그램: “추락한 셔틀의 화물 상자는 조종사의 생체 인식 장갑으로만 열린다.” 그리고 셔틀 위치 좌표.' },
      { key: 'canaldoor', type: 'code', title: '지하 수로 문', art: '🔐', text: '숫자 3자리. “기도문의 줄 수, 그리고 첫 줄의 글자 수(띄어쓰기 빼고).”', code: '414', result: 'canal', hint: ['기도문은 4줄. “나는포스와하나포스는나와함께”는 몇 글자?', '4 · 14 → 414'] },
      { key: 'canal', type: 'place', title: '지하 수로', art: '💧🕳️🔦', text: '물이 무릎까지 찬 수로. 출구의 철창 너머로 사막 빛이 보인다. 철창 자물쇠가 녹슬었다.', shows: ['grate'], spots: [{ label: '물속 반짝임', x: 30, y: 78, reveal: 'oil' }] },
      { key: 'grate', type: 'red', title: '녹슨 철창', art: '⛓️', text: '' },
      { key: 'oil', type: 'blue', title: '윤활유 깡통', art: '🛢️', text: '' },
      { key: 'crash', type: 'place', from: ['grate', 'oil'], discard: ['grate', 'oil'], shows: ['crate', 'pilot'], title: '셔틀 추락 지점', art: '🛸🔥🏜️', text: '연기 나는 셔틀 잔해. 화물 상자가 모래에 반쯤 묻혀 있다. 기절한 제국 조종사. 멀리서 소우 게레라 패거리의 스피더 소리!' },
      { key: 'pilot', type: 'item', title: '기절한 조종사', art: '👨‍🚀', text: '“…장갑… 상자는… 장갑으로…” 장갑 한 짝이 셔틀 조종석에 끼어 있다.', spots: [{ label: '조종석', x: 60, y: 40, reveal: 'glove' }] },
      { key: 'crate', type: 'red', title: '카이버 크리스털 상자', art: '📦💎', text: '생체 인식 잠금.' },
      { key: 'glove', type: 'blue', title: '조종사의 생체 인식 장갑', art: '🧤', text: '' },
      { key: 'out', type: 'item', from: ['crate', 'glove'], end: true, title: '임무 완수', art: '💎🛸', text: '상자를 열자 카이버 크리스털이 푸르게 빛난다. 패거리가 도착하기 전 제국 셔틀이 당신을 태우고 떠난다.' },
      { key: 'trap1', type: 'trap', from: ['crate', 'oil'], title: '경보!', text: '상자에 기름을 붓자 보안 경보가 울렸다! 급히 꺼뜨렸다.', penalty: 1 },
    ],
  },
];
