'use strict';
// 언락! — 타임리스 어드벤처 (원작 줄거리·분량을 따른 오리지널 수수께끼)

const B = '타임리스 어드벤처';
module.exports = [
  {
    id: 'nosideshow', box: B, title: '노사이드 쇼', orig: 'The Noside Show', diff: 1, theme: '#d84a4a',
    intro: '디오센 서커스가 마을에 왔다! 그런데 노사이드 교수가 공연을 망칠 대형 사보타주를 준비했다. 막이 오르기 전에 교수의 장치들을 찾아 멈추자.',
    cards: [
      { key: 'tent', type: 'place', start: true, title: '서커스 천막', art: '🎪🤡🦁🎈', text: '광대, 사자 우리, 공중그네. 무대 아래에서 째깍째깍 소리. 단장이 발을 동동 구른다. “공연까지 얼마 안 남았어!”',
        shows: ['stage', 'ringmaster'], spots: [{ label: '광대 모자', x: 26, y: 30, reveal: 'crowbar' }, { label: '풍선 다발', emoji: '🎈', x: 76, y: 28, text: '풍선 색: 빨강 2개, 노랑 5개, 파랑 3개.' }] },
      { key: 'ringmaster', type: 'item', title: '서커스 단장', art: '🎩', text: '“사자 우리 열쇠가 없어졌어! 노사이드가 사자 우리에 뭔가 숨겼을지도 몰라.”' },
      { key: 'stage', type: 'red', title: '무대 바닥판', art: '🪵', text: '못으로 단단히 박혀 있다.' },
      { key: 'crowbar', type: 'blue', title: '쇠지렛대', art: '🔧', text: '' },
      { key: 'device', type: 'code', from: ['stage', 'crowbar'], discard: ['stage'], title: '방해 장치 1: 풍선 폭탄', art: '💣🎈', text: '“해제 코드 = 풍선 색깔별 개수, 빨-노-파 순서.” 이 교수는 왜 늘 힌트를 남길까?', code: '253', result: 'cage', hint: ['천막의 풍선 다발.', '빨강 2 · 노랑 5 · 파랑 3 → 253'] },
      { key: 'cage', type: 'place', title: '사자 우리 뒤편', art: '🦁🔒⚙️', text: '첫 장치를 해제하자 쪽지가 나왔다: “두 번째 선물은 사자 우리에! — N.” 사자가 우리 안에서 서성인다. 우리 안쪽 기둥에 톱니 장치가 붙어 있다.',
        shows: ['lion'], spots: [{ label: '건초 더미', x: 72, y: 74, reveal: 'steak' }] },
      { key: 'lion', type: 'red', title: '배고픈 사자', art: '🦁', text: '장치 앞에서 버티고 있다.' },
      { key: 'steak', type: 'blue', title: '스테이크', art: '🥩', text: '' },
      { key: 'gear', type: 'machine', from: ['lion', 'steak'], discard: ['steak'], title: '방해 장치 2: 톱니 기계', art: '⚙️', text: '사자가 고기를 먹는 사이 장치에 다가갔다. 레버 셋. 장치에 새겨진 글: “공중그네는 왼쪽부터 3, 1, 2번 순서로 떨어진다.” 반대로 당겨야 막을 수 있을 것 같다.', buttons: ['1번 레버', '2번 레버', '3번 레버'], solution: ['2번 레버', '1번 레버', '3번 레버'], result: 'out', hint: ['3 → 1 → 2 의 반대 순서.', '2 → 1 → 3'] },
      { key: 'trap1', type: 'trap', from: ['lion', 'crowbar'], title: '어흥!', text: '쇠지렛대로 사자를 밀자 사자가 포효했다. 단장이 달려와 겨우 진정시켰다.', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '쇼는 계속된다!', art: '🎪✨', text: '장치들이 멈추고 막이 오른다. 관객석 맨 뒤에서 노사이드 교수가 팝콘을 집어 던지며 투덜댄다.' },
    ],
  },
  {
    id: 'lupin', box: B, title: '아르센 뤼팽과 거대한 흰 다이아몬드', orig: 'Arsène Lupin and the Great White Diamond', diff: 2, theme: '#2a2a4a',
    intro: '1910년 파리. 괴도 아르센 뤼팽이 “오늘 밤 자정, 흰 다이아몬드를 가져가겠다”는 예고장을 보냈다. 파리를 가로지르는 보석 쟁탈전 — 뤼팽보다 먼저 다이아몬드를 찾아라!',
    cards: [
      { key: 'museum', type: 'place', start: true, title: '루브르 특별 전시실', art: '🏛️💎🎩🕯️', text: '진열장 속 다이아몬드는 이미 가짜로 바뀌어 있다! 바닥에 뤼팽의 카드. 경비원이 졸고 있다.',
        shows: ['card', 'fake'], spots: [{ label: '경비원 의자', x: 24, y: 70, reveal: 'uv' }, { label: '창문', emoji: '🪟', x: 78, y: 24, text: '창밖으로 센 강과 노트르담 성당의 두 탑이 보인다.' }] },
      { key: 'fake', type: 'item', title: '가짜 다이아몬드', art: '💎', text: '유리다. 받침에 작은 글씨: “진짜는 내가 먼저 찾을 것이다. 단서는 공평하게 남겨 두지. — A.L.”' },
      { key: 'card', type: 'red', title: '뤼팽의 카드', art: '🃏', text: '“A.L.” 서명뿐. 보이지 않는 잉크로 무언가 쓰인 듯하다.' },
      { key: 'uv', type: 'blue', title: '자외선 등', art: '🔦', text: '' },
      { key: 'msg', type: 'item', from: ['card', 'uv'], discard: ['card'], shows: ['bookshop'], title: '보이지 않는 글씨', art: '🃏✨', text: '“다이아몬드는 센 강변 고서점에. 금고는 노트르담의 탑 수와 종 수(10)를 이어서.”' },
      { key: 'bookshop', type: 'place', title: '센 강변 고서점', art: '📚🕰️🐈‍⬛', text: '서점 주인은 사라졌고 검은 고양이만 있다. 금고와 지도책, 벽에 걸린 에트르타 해안 그림.', shows: ['safe', 'atlas'], spots: [{ label: '그림 액자 뒤', x: 80, y: 34, reveal: 'diary' }] },
      { key: 'safe', type: 'code', title: '서점 금고', art: '🔐', text: '숫자 3자리.', code: '210', result: 'box', hint: ['노트르담의 탑 수 + 종 수.', '2와 10 → 210'] },
      { key: 'atlas', type: 'item', title: '지도책', art: '🗺️', text: '책갈피에 “에트르타의 바늘바위 — 나의 은신처.” 지도 위 화살표: 북 → 서 → 북 → 동.' },
      { key: 'diary', type: 'item', title: '서점 주인의 일기', art: '📔', text: '“뤼팽이 상자를 맡기고 갔다. 상자를 열면 그가 어디로 갔는지 알 수 있다고.”' },
      { key: 'box', type: 'machine', title: '비밀 상자', art: '📦', text: '금고 속 상자. 나침반 다이얼이 달렸다.', buttons: ['북', '동', '남', '서'], solution: ['북', '서', '북', '동'], result: 'etretat', hint: ['지도책의 화살표.', '북 → 서 → 북 → 동'] },
      { key: 'etretat', type: 'place', title: '에트르타 바늘바위', art: '🪨🌊🌅', text: '상자 속 기차표를 따라 노르망디 해안으로! 바늘바위 안쪽 동굴에 뤼팽의 은신처. 쇠문에 조각된 그림: 다이아몬드 하나와 열쇠 구멍.', shows: ['ironDoor'], spots: [{ label: '조개껍데기 더미', x: 26, y: 78, reveal: 'shellkey' }] },
      { key: 'ironDoor', type: 'red', title: '은신처 쇠문', art: '🚪', text: '' },
      { key: 'shellkey', type: 'blue', title: '조개 모양 열쇠', art: '🐚', text: '' },
      { key: 'out', type: 'item', from: ['ironDoor', 'shellkey'], end: true, title: '흰 다이아몬드', art: '💎🎩', text: '은신처 금고 속에 진짜 흰 다이아몬드와 쪽지: “축하하오. 이번엔 당신이 이겼소. 다음엔 내가 이기겠지. — A.L.”' },
      { key: 'trap1', type: 'trap', from: ['ironDoor', 'uv'], title: '함정!', text: '자외선을 비추자 문에서 연막이 터졌다! 콜록거리며 물러났다.', penalty: 1 },
    ],
  },
  {
    id: 'timewarp', box: B, title: '시간의 틈에 갇히다!', orig: 'Lost in the ChronoWarp', diff: 3, theme: '#3a6ad8',
    intro: '알키비아데스 템푸스 교수의 시간 기계가 제멋대로 작동해 역사가 뒤죽박죽! 공룡이 로마에, 기사가 우주선에… 흩어진 부품을 모아 시간선을 원래대로 돌려놓자.',
    cards: [
      { key: 'lab', type: 'place', start: true, title: '템푸스 교수의 연구실', art: '⏳🌀🦖🏛️', text: '시간 기계가 불꽃을 튀긴다. 교수는 시간의 틈에 반쯤 걸려 있다! “부품 셋이 다른 시대로 날아갔어! 시간 순서대로 되찾아야 해!”',
        shows: ['board', 'timemachine'], spots: [{ label: '공구함', x: 22, y: 72, reveal: 'magnet' }] },
      { key: 'board', type: 'item', title: '시대 표지판', art: '📅', text: '시간 기계의 시대 버튼: 🦖 백악기 · 🏛️ 고대 로마 · 🏰 중세 · 🚀 미래.' },
      { key: 'timemachine', type: 'machine', title: '시간 기계 행선지', art: '🌀', text: '시대 버튼을 시간 순서대로 눌러 여행을 떠나자.', buttons: ['🚀', '🏰', '🏛️', '🦖'], solution: ['🦖', '🏛️', '🏰', '🚀'], result: 'cretaceous', discardSelf: false, hint: ['교수: 시간 순서대로!', '🦖 → 🏛️ → 🏰 → 🚀'] },
      { key: 'cretaceous', type: 'place', title: '백악기', art: '🦖🌋🌿', text: '티라노가 무언가 반짝이는 쇠붙이를 둥지에 깔고 앉아 있다. 시간 기계 부품, 톱니바퀴다!',
        shows: ['nest'], spots: [{ label: '고사리 덤불', x: 76, y: 70, reveal: 'rock' }] },
      { key: 'nest', type: 'red', title: '티라노의 둥지', art: '🪺🦖', text: '꿈쩍도 하지 않는다.' },
      { key: 'rock', type: 'blue', title: '알 모양 돌', art: '🪨', text: '공룡 알과 똑같이 생겼다.' },
      { key: 'gear', type: 'red', from: ['nest', 'rock'], discard: ['nest', 'rock'], title: '시간 톱니바퀴', art: '⚙️', text: '돌을 알인 척 굴리자 티라노가 쫓아갔다. 톱니 확보! 자석으로 기계에 붙여야 한다.' },
      { key: 'gearok', type: 'item', from: ['gear', 'magnet'], discard: ['gear', 'magnet'], shows: ['rome'], title: '톱니 장착', art: '⚙️✅', text: '톱니가 철컥! 기계가 다음 시대로 튕겨 보낸다.' },
      { key: 'magnet', type: 'blue', title: '강력 자석', art: '🧲', text: '' },
      { key: 'rome', type: 'place', title: '고대 로마 콜로세움', art: '🏟️⚔️🐘', text: '검투사가 방패 대신 부품, 시간 렌즈를 들고 싸운다! 관중석의 황제가 엄지를 든다. 검투사 방패에 로마 숫자 XII.',
        shows: ['emperor'], spots: [{ label: '황제석 쿠션', x: 70, y: 30, reveal: 'laurel' }] },
      { key: 'emperor', type: 'red', title: '황제', art: '👑', text: '“월계관을 바치는 자에게 상을 내리리라!”' },
      { key: 'laurel', type: 'blue', title: '황금 월계관', art: '🌿', text: '' },
      { key: 'lens', type: 'item', from: ['emperor', 'laurel'], discard: ['emperor', 'laurel'], shows: ['castle'], title: '시간 렌즈', art: '🔍⏳', text: '황제가 검투사에게서 렌즈를 빼앗아 상으로 주었다! 기계에 끼우자 다음 시대로 휙.' },
      { key: 'castle', type: 'place', title: '중세의 성', art: '🏰🐉🛡️', text: '탑 꼭대기 공주 대신 시간 크리스털이 갇혀 있다. 탑 문에 문장 버튼: 사자, 독수리, 용, 백합. 문 위 문구: “용은 하늘의 왕 다음, 백합은 언제나 처음, 사자는 마지막.”', shows: ['towerdoor'] },
      { key: 'towerdoor', type: 'machine', title: '탑의 문장 문', art: '🛡️', text: '문장 버튼.', buttons: ['🦁 사자', '🦅 독수리', '🐉 용', '⚜️ 백합'], solution: ['⚜️ 백합', '🦅 독수리', '🐉 용', '🦁 사자'], result: 'crystal', hint: ['백합 처음, 사자 마지막, 용은 하늘의 왕(독수리) 다음.', '⚜️ → 🦅 → 🐉 → 🦁'] },
      { key: 'crystal', type: 'item', title: '시간 크리스털', art: '🔮', shows: ['future'], text: '크리스털을 기계에 장착! 마지막 시대로.' },
      { key: 'future', type: 'place', title: '미래 우주 정거장', art: '🚀🛰️🤖', text: '로봇이 안내한다: “시간 좌표 확인. 원래 시대로 돌아가려면 좌표를 입력하세요 — 지금 연도의 앞 두 자리(20) 뒤에, 콜로세움 검투사 방패의 숫자를 아라비아 숫자로.”', shows: ['final'] },
      { key: 'final', type: 'code', title: '시간 좌표 입력', art: '⌨️', text: '숫자 4자리.', code: '2012', result: 'out', hint: ['콜로세움의 방패: XII = 12.', '20 + 12 → 2012'] },
      { key: 'trap1', type: 'trap', from: ['emperor', 'rock'], title: '사자 우리로!', text: '황제에게 돌을 바치자 화가 나서 사자 우리에 던져 넣으려 했다! 간신히 빠져나왔다.', penalty: 1 },
      { key: 'trap2', type: 'trap', from: ['nest', 'magnet'], title: '티라노의 분노', text: '자석으로 둥지를 휘젓다 티라노를 깨웠다!', penalty: 1 },
      { key: 'out', type: 'item', end: true, title: '시간선 복구!', art: '⏳✨', text: '번쩍! 공룡은 백악기로, 검투사는 로마로, 기사는 중세로. 교수가 틈에서 빠져나와 안경을 고쳐 쓴다. “자, 차 한잔할까? …몇 년도의 차로?”' },
    ],
  },
];
